### ISSUE TITLE
Can not connect to Astart EVM

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1001]

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.7.9-1675420421123.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/216865642-a25d8f71-3218-4916-93ce-415c3556df57.png)
