### ISSUE TITLE
Upgrade UI - Screen Phishing Page

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1004]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1112%3A46496&t=i34VRSl9C0ltrIwf-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678083121116.zip

- [ ] Missing the "I trust this website" button
![image](https://user-images.githubusercontent.com/102292476/223323213-6d4aa4e5-09df-43bf-a30c-f327893c2c03.png)

- [ ] Do not show the phishing page when the user does not open the extension yet

**Comment by sokol142** [comment]
@saltict @Quangdm-cdm please check Chain Patrol's API phishing detection (MetaMask & Coinbase integrated): https://github.com/Koniverse/SubWallet-Extension/pull/1080

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1679632511811.zip

Validation passed.
![1004_Validation](https://user-images.githubusercontent.com/102292476/227681746-1f008d56-add4-48d1-b774-90b6cfc109eb.gif)
