### ISSUE TITLE
Upgrade UI - Screen Home / NFT

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1006]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1088%3A59632&t=lSq6WfQhrzPdUsuL-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip
Please check:

- [ ] Incorrect extension's size when switch to NFTs tab
- Actual: 394px x 600px
- Expected: 390px x 600px
![image](https://user-images.githubusercontent.com/102292476/220511102-bc58cc71-12f7-4382-b965-401f56e98b2b.png)

- [ ] Still show scroll bar in case have no NFT
- Expected: Do not show scroll bar 
![image](https://user-images.githubusercontent.com/102292476/220511278-afe41240-d956-4294-8652-32a93aac4bd8.png)

- [ ] Incorrect break character on the popup NFT Description 
![image](https://user-images.githubusercontent.com/102292476/220512882-c80b8e63-cf37-4d1c-bb3a-d457ee184f8b.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679287685306.zip

- [ ] Re-check bug show scroll bar in case empty list: @S2kael

**Comment by sokol142** [comment]
Version test:

- [ ] UI bug when the owner address is long
![image](https://user-images.githubusercontent.com/102292476/226793097-929f22a1-c235-47da-a971-7ae32cb71272.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1679666144073.zip

- [ ] Review duplicate NFT item issue: https://github.com/Koniverse/SubWallet-Extension/issues/729
- [ ] Add the link to source NFT (if yes)
- [ ] Do not show Karura, Pioneer NFT
   - Check Karura NFT with address: 5GBw5o91TwwLwpj24ucJimWZhpg9bc5W9mBTMERjiaYYsENd
   - Check Pioneer NFT with address: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc
- [ ] Do not show imported NFT if the user standing on SubWallet expand mode

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.1-1680265510089.zip

- [ ] Incorrect validation for the "Send to account" when the user sends NFT from the "All accounts" mode
- Actual: Show error message although address is valid
![image](https://user-images.githubusercontent.com/102292476/229398744-21c14b38-be4d-4982-be9c-1e26442f77e6.png)

**Comment by sokol142** [comment]
- [ ] Still shows NFT when turning off the network
![1006_bugShowNFT](https://user-images.githubusercontent.com/102292476/229499827-5dc1ef94-a05f-43bd-b23f-4fce5eaf9e16.gif)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1128-merge-build-1.0.1-1680685230797.zip

- [ ] Still shows NFT sent on the "All accounts"
![image](https://user-images.githubusercontent.com/102292476/230036371-c797319e-cf37-4f30-a806-51a7dfd49140.png)

**Comment by ThaoNguyen998** [comment]
- [ ] Do not show the tooltip when importing NFT incase existed NFT

![Image](https://user-images.githubusercontent.com/117999489/230715654-eab840ba-9e94-4d51-b44a-5befd0af71c8.png)
