### ISSUE TITLE
Upgrade UI - Screen Home / Staking

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1007]
- UI
- [x] Get data for Staking list
- [x] UI for Staking List
- [x] UI for filter
- [x] UI for Staking Detail
- [x] UI for Staking More Action

**Comment by saltict** [comment]
@NamPhamc99 Update new staking logic from the background

**Comment by sokol142** [comment]
- [ ] An error occurs when switching accounts after viewing Staking Detail
![1007_bug](https://user-images.githubusercontent.com/102292476/227942542-e52b3b8a-dc9e-4e18-993b-76431ec64420.gif)

**Comment by sokol142** [comment]
- [ ] Re-check the case turning on the token to stake
   - Do not show estimated earnings, Minimum active, or network info after turning on the token
   - Show duplicate message turn on token successful
   - Show incorrect Available balance of the selected token
![1007_bugNominate_turnOnToken](https://user-images.githubusercontent.com/102292476/228802572-07cdd768-0461-478e-9958-1f1b4c7f7f42.gif)

**Comment by sokol142** [comment]
- [ ] Some bug related to unstke action
   - Do not update unstake balance, active stake balance on the Detail screen after unstake successful
   - Do not unstake for another collator if unstake record existed
![1007_bugNominate_Unstake](https://user-images.githubusercontent.com/102292476/228811637-4bcdf28c-1291-46a8-9f5e-f590557b5fc7.gif)

**Comment by sokol142** [comment]
- [ ] Some bugs related to withdrawal:
   - Do not update unstake request after withdrawing successfully
   - After withdrawal successfully, Redirect the user to the incorrect screen
      - Actual: Redirect to the Action popup
      - Expect: Redirect to the Transaction Result screen
![1007_bugNominate_withdraw](https://user-images.githubusercontent.com/102292476/228812764-94fa4386-d630-4cb4-addb-ff1dc8a33594.gif)

**Comment by sokol142** [comment]
- [ ] Do not cancel unstake request with EVM chain
![1007_bugNominate_cancelUnstake](https://user-images.githubusercontent.com/102292476/228813561-2ce0961f-bd69-4e7d-b41c-94ce07c4197e.gif)

**Comment by sokol142** [comment]
- [ ] Some bug related to Claim reward action:
- Update the message on the Confirmation when Checkbox "Bond reward" = OFF
   - If "Bond reward" = OFF -> Show message "Withdrawing rewards will immediately transfer them to your account as free balance"
   - If "Bond reward" = ON -> Show message "Your rewards will be bonded back into the pool"
- Do not show the "Reward claiming" value on the pooled record
- Do not update balance after claimed successful

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1128-merge-build-1.0.1-1680685616400.zip

- [ ] Can't close popup when click on any action with read-only account
![1007_bugCrash](https://user-images.githubusercontent.com/102292476/230051551-a403d109-9b08-40b6-80ee-4784bbe408ea.gif)

**Comment by NamPhamc99** [comment]
Done
