### ISSUE TITLE
Upgrade UI - Screen Home / Crowdloan

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1008]
- UI
- [x] Get data Crowdloan list
- [x] UI for Crowdloan List
- [x] UI for filter

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678083121116.zip

Please check:

- [ ] Update font-size for the tag follow by design

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679055190508.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/226086028-c5b5b06c-986d-4567-bd8f-fd4ab67f84c7.png)
