### ISSUE TITLE
Upgrade UI - Screen Home / Histories

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1009]
UI:
- Component:
  - [x] History item 
- Layout:
  - [x] List screen
  - Detail screen:
    - [x] transfer
    - [x] staking
    - [x] NFT
    - [x] crowdloan
    - [x] claim reward

**Comment by saltict** [comment]
- [ ] Link history detail with  subscan
- [ ] Link transaction done with history

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678525608021.zip
Please check issues:

- [ ] Update the history's icon follow by design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1309%3A289363&t=ZcBZrBz9xyFfzWms-4
- [ ] Add the filter action
- [ ] Update style of the history's status
- [ ] Other issue
![image](https://user-images.githubusercontent.com/102292476/224599953-8dd5942f-53e5-4ddf-85de-9d4f67e4aa06.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679119100958.zip

Please check:

- [ ] Still enable button "View on explorer" in case the chain is not support explorer (Rococo)
- [ ] Do not recipient address on the stake history
   - Expect: Show address of the validator
![image](https://user-images.githubusercontent.com/102292476/226093061-2b8e5c84-8cea-4ae5-b037-d6e3cdd0f0a9.png)

**Comment by sokol142** [comment]
Version test: 
Please check the issues:

- [ ] Still showing the history of removed accounts when viewing history in All Accounts mode
![image](https://user-images.githubusercontent.com/102292476/227697940-cea78bfb-f667-420e-b0bb-a3755df8f5ef.png)

- [ ] Re-check the sorting of the history list
![image](https://user-images.githubusercontent.com/102292476/227698076-c2d22a32-c517-4450-8331-565c4c7582ba.png)

**Comment by sokol142** [comment]
- [ ] Show incorrect History status
   - Actual: The transaction success but the history show failed
![image](https://user-images.githubusercontent.com/102292476/227886910-188e4e7e-2687-451b-9a0c-67b7fe6321ea.png)

**Comment by sokol142** [comment]
- [ ] Do not show Send NFT history when standing the specific account, but it's shown on All accounts mode
![image](https://user-images.githubusercontent.com/102292476/228131214-a964ea42-5ab7-4f2c-b7d7-d49289a37689.png)

**Comment by sokol142** [comment]
- [ ] Add the Amount on the History Detail screen
- [ ] Update Amount for NFT's history

**Comment by sokol142** [comment]
- [ ] Update UI for the XCM transfer history
![image](https://user-images.githubusercontent.com/102292476/229025721-6e6fe65e-9714-4341-9233-5165301e8326.png)

**Comment by sokol142** [comment]
- [ ] Still history of the type = EVm Execute in case forget account

![image](https://user-images.githubusercontent.com/102292476/229080737-ca037178-33f6-4fd0-833f-51a250213a4b.png)
