### ISSUE TITLE
Upgrade UI - Screen Confirmations

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1010]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1365-132089&t=NrJav8Bnxa3JrSBN-4

- [x] Authorize
- [x] Update metadata
- [x] Add network
- [x] Add token
- [x] Sign message
- [x] Send transaction from dApp
- [x] Send transaction from Extension
  - [x] Send token
  - [x] Send NFT
  - [x] Staking
    - [x] Stake
    - [x] UnStake
    - [x] Withdraw
    - [x] Compound
    - [x] Claim

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1044-merge-build-0.8.1-1676868246779.zip

Please check:

- [ ] Incorrect padding
![image](https://user-images.githubusercontent.com/102292476/220330433-6bff9fcb-50a1-4911-8681-3983e2b4bcd0.png)
![image](https://user-images.githubusercontent.com/102292476/220330719-e15b3de7-b031-460c-9ba7-f3f41e0fcab3.png)


- [ ] Disable button Connect if not select account
![image](https://user-images.githubusercontent.com/102292476/220330574-582ecefa-ca6e-4ca6-a924-49ee02e2bf54.png)

- [ ] Incorrect logo's size
![image](https://user-images.githubusercontent.com/102292476/220330675-563a896c-80bb-416b-a6e9-d270764a7eec.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1677556157305.zip

![image](https://user-images.githubusercontent.com/102292476/221760731-952b34e7-d625-4b53-8a17-b6c88def2245.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1087-merge-build-0.8.1-1678951713211.zip

- [ ] Do not show the add network screen when add from dApp
![1010_Bug_AddNetwork](https://user-images.githubusercontent.com/102292476/225626153-f6234b29-f13f-4575-81ef-387a228c737a.gif)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679287685306.zip

Please check:

- [ ] Add the "View detail" button & add the View detail screen
- [ ] Add the Back button on the Screen Confirmation
![image](https://user-images.githubusercontent.com/102292476/226276134-fa73e543-89a4-4eb0-a80d-f1f7e7f05f8a.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1092-merge-build-0.8.1-1679311924409.zip

- [ ] Update UI in case Signature request in case account is not supported
   - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1331-155628&t=5WDOgvTuWg59SDI2-4
