### ISSUE TITLE
Upgrade UI - Screen Settings / Networks

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1013]
Design:    https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=934%3A32107&t=SgUdY9La2CB4fHMX-4

**Comment by NamPhamc99** [comment]
- [ ] Manage network UI
- [ ] Filter networks
- [ ] Configure network screen (read-only)
- [ ] Add network
- [ ] Provider config (1 vs many)
- [ ] Delete network
- [ ] Add provider

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1055-merge-build-0.8.1-1677656812660.zip

Please check issues:

- [ ] Bug UI in case Turn on/ Turn off network _(after the first time)_ 
![1013_bugUI](https://user-images.githubusercontent.com/102292476/222093307-537672e7-3117-4004-9754-c52d7465bc5f.gif)

- [ ] Show incorrect Total balance on the "All accounts" when turn on Acala, Moonbeam network
![image](https://user-images.githubusercontent.com/102292476/222125960-b14e3b2c-2ab3-4c59-837a-a5caf78a25ca.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679119100958.zip

- [ ] Add the connection status on the network list
- [ ] Update icon Configure network follow by design
- [ ] UI bug in case search/filter empty
   - link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1052-61815&t=VPmTk9fxh5AG52AZ-4
![image](https://user-images.githubusercontent.com/102292476/226094680-de144d1a-97f5-4faf-a3cd-73e480dff35b.png)

**Comment by sokol142** [comment]
**_Note for tester: Handle case upgrade version_**
Expected:
     - Update Network configure 
          - Change provider/ add new provider -> Keep the change
          - Update other information -> Reset to the default value
     - Update custom network to pre-defined network
          - Has 1 record network -> Keep the configuration (re-check: display network, token, balance)
          - Have 2 record networks (EVM + Substrate) -> Discuss more

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1679550205800.zip

- [ ] Re-check the connection status of the network
   - Actual:
      - The connection status is delayed.
      - Still show connected status when turned off the network
![1013_Connection Status](https://user-images.githubusercontent.com/102292476/227133197-a4ea04ed-9aff-4de4-be30-450889bbf40a.gif)

**Comment by sokol142** [comment]
- [ ] UI on the add provider
![image](https://user-images.githubusercontent.com/102292476/228139261-6415fc47-7e3a-4679-9675-b4e08981ba2e.png)
