### ISSUE TITLE
Upgrade UI - Screen Settings List

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1015]

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1047-merge-build-0.8.1-1677006965970.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/221074571-e9ce0b48-a0bc-4769-9c39-2d4977543be2.png)
![image](https://user-images.githubusercontent.com/102292476/221074604-430f320c-d072-40a3-986d-3d1e2393a587.png)
