### ISSUE TITLE
Upgrade UI - Screen Token List

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1016]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1214%3A29804&t=i34VRSl9C0ltrIwf-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678083121116.zip

- [ ] Update UI follow by design
- [ ] Ui bug
![image](https://user-images.githubusercontent.com/102292476/223367864-beb716f4-7921-4058-92d4-e06b98d1deaa.png)

- [ ] Can not add new token
![image](https://user-images.githubusercontent.com/102292476/223367490-e79590cc-0a29-49c9-805c-9cbe8f9f46ce.png)

Test later:
- Import token
- Remove token

**Comment by sokol142** [comment]
Version test: https://drive.google.com/file/d/1zNXM57x7tr1BE9LMY_yam-TdzLMoyI7J/view?usp=share_link
Please check:

- [ ] Update the Add token screen follow the design
![image](https://user-images.githubusercontent.com/102292476/223682911-eed6b7a2-91ac-4530-93fa-9e416bcb6b41.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678525608021.zip

- [ ] The phenomenon of blinking view when on/off token
![1016_bugReload](https://user-images.githubusercontent.com/102292476/224926111-f01dfdf7-edf1-4dd3-89f7-f2f3dbe896a2.gif)

**Comment by sokol142** [comment]
Version test:
- [ ] Add the custom/ testnet tag for the token

**Comment by sokol142** [comment]
Version test:

- [ ] Do not automatically turn on the token in cases:
   - Import network from dApp (expect: automatically native token of this network)
   - Import token from dApp (expect: automatically turn on token and turn on the network of this token)

**Comment by sokol142** [comment]
**Improvement**
- [ ] Add the custom/ testnet tag for the token
- [ ] Incorrect logo's style, logo's size
- [ ] UI bug in case search/filter empty
![image](https://user-images.githubusercontent.com/102292476/226099731-16d268da-f3c7-417f-8164-d78e650fa5a3.png)

**Comment by sokol142** [comment]
- [ ] Do not show $ balance of the custom token
- Address account: 0xA41712B4f2cF4429E2F6e2E4e3c5e9C9A025Fb07
- Contract address: 0x03065E84748a9e4a1AEbef15AC89da1Cdf18B202 (Astar-EVM)
![image](https://user-images.githubusercontent.com/102292476/226101088-dfb0d40b-6a6f-48c0-bf32-47fbe937d9dd.png)
