### ISSUE TITLE
Upgrade UI - Screen Account / Export

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1019]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=864%3A33156&t=ENjVxCJpOxJvG5Co-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1055-merge-build-0.8.1-1677562303221.zip

Please check issues:

- [ ] Do not scan account address
- Actual: Do not scan account address
- Expected: add the errorLevel to component
![image](https://user-images.githubusercontent.com/102292476/221848010-d64113b8-4553-4726-9e26-728cb763c454.png)

- [ ] Show loading icon in case go to the Account Detail on the first time visit
![image](https://user-images.githubusercontent.com/102292476/221848301-4219fe74-5b39-4a88-b819-4599cbabd1c3.png)

**Comment by saltict** [comment]
- [ ] Hide export option if password is empty

**Comment by sokol142** [comment]
- [ ] Require field when input Account Name is all space

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679042310117.zip

Validation passed for case:
- GUI
- Scan QR code
- Copy address
- Edit name
- Derive account
- Export account
- Remove account
