### ISSUE TITLE
Upgrade UI - Screen Transactions

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1024]
## Update Background
- [x] Handle Transaction Queue
- [x] Handle Confirmation Queue
- [x] Handle Signature
- [x] Upgrade message for transaction
```mermaid
sequenceDiagram
    UI->>+TransactionHandler: Create Transaction
    TransactionHandler->>+RequestHandler: Create Request
    RequestHandler->>-UI: Require Confirm
    UI->>+Keyring: Sign Transaction
    Keyring->>-UI: Signature
    UI->>+TransactionHandler: Send (Signature + Transaction)
    TransactionHandler->>-TransactionHandler: Do Transaction + Update RS
    TransactionHandler->>+UI: Notify RS
```

## Implement API
- [x] Transaction Screens
  - [x] Transfer + XCM
  - [x] Send NFT
  - [x] Transaction
  - [x] Stake
  - [x] Unstake
  - [x] Withdraw
  - [x] Claim Reward

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1090-merge-build-0.8.1-1679287685306.zip

Please check issues:
- [ ] Still showing error message when user click on back button
![1010_bugUI](https://user-images.githubusercontent.com/102292476/226278667-ffbabd55-78f9-4a07-872a-69a1cacfa0b7.gif)

- [ ] Handle case don't get transaction's fee
- Actual: Do not send token
- Expected: Allow send token with estimated fee = 0

- [ ] Handle case check validate of the form
![image](https://user-images.githubusercontent.com/102292476/226279123-71502730-cc9b-4442-a679-1e0938ee557c.png)

**Comment by sokol142** [comment]
Version test: https://drive.google.com/file/d/1cmBsZ4Iy2bs4O-YxlkAphe9jKmQMZG8p/view?usp=share_link

- [ ] Do not showing transaction history in case:
   - Send token with substrate account
   - Send token with EVM account (same wallet): do not showing history of the recipient
![1024_DonotShowHistory](https://user-images.githubusercontent.com/102292476/226295844-d2b1f7cd-1abf-43dc-a8d5-ca8919b7d8b6.gif)

- [ ] Recheck action go to back the Transfer screen when submitting

**Comment by sokol142** [comment]
Version test:
**NFT Transaction**

- [ ] Still show incorrectly Transferable balance when standing on All accounts
![image](https://user-images.githubusercontent.com/102292476/227142007-878a9961-ecf4-4bee-a481-30798830c0ee.png)

- [ ] Hide the Send button with read-only account

**Comment by sokol142** [comment]
- [ ] UI bug
![image](https://user-images.githubusercontent.com/102292476/227848689-ca969173-03a4-4dc2-bc2d-9dbe615a7829.png)

**Comment by sokol142** [comment]
- [ ] Do not send custom token
- Reproduce with MFG (Moonbase Alpha) has contract address: 0xb161b2da48de283ec22bafbc36e5551c892629a2
![image](https://user-images.githubusercontent.com/102292476/227849031-468b93df-0c83-4f35-aca3-f5791c624a10.png)

**Comment by sokol142** [comment]
- [ ] Validate incorrect List account when the user sends a token from the Token Detail screen with All accounts mode
   - Actual: 
      - Show list account incorrect
      - Do not show token default if have only 1 token on the Token detail view
   - Expect: View detail in BA Document: https://www.notion.so/subwallet/Feature_Manage-token-6bcf46a6bd004d64b52a0ce964c94929?pvs=4#be8fc93a8eda4447906bf2dce344a2e6
![1024_Sendtoken_ValidateAccount](https://user-images.githubusercontent.com/102292476/227179216-441833b9-852f-4e00-90c0-83392563e818.gif)

**Comment by sokol142** [comment]
- [ ] An error occurred when the user click on the Back button on the "Transaction Result" screen after Send NFT successful
![1024_errorPage_BackfromResult](https://user-images.githubusercontent.com/102292476/227849342-686cbe1e-8576-444d-8d99-6306e69410d4.gif)

**Comment by sokol142** [comment]
- [ ] Show incorrect balance or do not show balance
- Show incorrect EQ balance
   - Check with address: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc
![image](https://user-images.githubusercontent.com/102292476/227850110-837b0272-82da-4181-ae8c-59d87e16a814.png)

- Do not show GENS balance
   - Check with address: 5GdyPmQ8trkyeWRXaq6zjUJfB7mFzAz8Qc5e55sFkHXwUaHJ
![image](https://user-images.githubusercontent.com/102292476/227850226-7481caea-8000-478d-8ad6-d1b4c59996a9.png)

**Comment by sokol142** [comment]
- [ ] Show require message when clicking on the Max button
   - Steps:
      - Do not enter Amount
      - Out focus -> Show require message
      - Click Max
   - Actual: Still show require message
![1024_bugUI](https://user-images.githubusercontent.com/102292476/228134188-97790323-52be-4469-94f1-6892fdfdc8ac.gif)

   - Expect: Do not show a message

**Comment by sokol142** [comment]
- [ ] Re-check the MAX function
   - Actual: Max = Max balance
   - Expect: Max = Max balance - Estimated fee

**Comment by sokol142** [comment]
- [ ] Show incorrect token list
   - Actual: Show ERC-721 (custom NFT)
![image](https://user-images.githubusercontent.com/102292476/229051699-4f9f03fc-64c5-49be-acbb-fe1abbbd27ef.png)

**Comment by sokol142** [comment]
- [ ] Do not send local tokens on the EVM account 
   - Reproduce the behavior with xcACA (Moonbeam)
![1024_SendLocalToken](https://user-images.githubusercontent.com/102292476/229055451-ae72df17-e710-4454-a996-f14cb72d0eaa.gif)

**Comment by sokol142** [comment]
- [ ] Re-check balance of the local token on the "Crab-EVM" chain

**Comment by sokol142** [comment]
Version test: 

- [ ] Some issues related to XCM feature
     - [ ] Show duplicate Destination chain
        - Moonbeam --> Interlay (xcINTR)
        ![image](https://user-images.githubusercontent.com/102292476/229674684-e2a3f96a-6b71-456c-bdf3-fd9d3fc24c7a.png)
     - [ ] Show incorrect Destination Chain
        - xcAUSD: only supported Moonbeam --> Acala, Moonriver --> Karura
        ![image](https://user-images.githubusercontent.com/102292476/229675199-7d8b8472-057f-4887-bb3c-47bb343abd0c.png)
       ![image](https://user-images.githubusercontent.com/102292476/229675732-eab295a4-5dcd-43eb-98a7-e45b745d342c.png)

     - [ ]

**Comment by sokol142** [comment]
Version test: 

- [ ] Re-check Transferable when 
![image](https://user-images.githubusercontent.com/102292476/230043945-8d46da32-7c41-48ab-82ed-2399fb5f8165.png)
