### ISSUE TITLE
Unable to load Staking in Brave Browser (waiting Subsquid API)

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#103]
**Describe the bug**
Unable to load Staking in Brave Browser

**To Reproduce**
1. Open SubWallet with Brave
2. Open the Staking screen
3. Observe the display screen

Actual: Unable to load, only shows the loading icon (try reloading the extension, it still doesn't work)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Brave

**Comment by NamPhamc99** [comment]
It seems to be working fine on the wallet.
Subsquid team reported some bugs on their side, so this task will be checked again later
@hieudd
