### ISSUE TITLE
Can't cancel staking compound task

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1034]
**Description of the bug**

Don't cancel the task when staking the Turing network

Steps:

1. Open the application
2. Go to the Staking tab
3. Go to the Staking details Turing network
4. Compound staking successfully with the Turing network
5. Cancel task Actual: Don't cancel the task with the Turing network![Image](https://user-images.githubusercontent.com/117999489/217702882-4ebaea36-23a9-413d-874c-2b534cc4df0c.png)
![Image](https://user-images.githubusercontent.com/117999489/217987741-c8ba63f2-b4a4-4775-af71-09d2982499c2.png)

**Comment by Sokol142196** [comment]
Do not support on the new UI version
