### ISSUE TITLE
Upgrade UI - DApps Connection Status

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1040]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1327%3A172805&t=i34VRSl9C0ltrIwf-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1677556157305.zip
Please check:

- [ ] Show incorrect dApp status
- Show incorrect dApp connection dApps
- Do not show tooltip when hover over button

![image](https://user-images.githubusercontent.com/102292476/221761008-21d62c07-62b9-4f38-9242-dd84964ebd3d.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678083121116.zip

Please check issues:

- [ ] Update UI in case have no account to connect wallet
- Follow this design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1331%3A128046&t=i34VRSl9C0ltrIwf-4

Please check:

- [ ] Incorrect padding
![image](https://user-images.githubusercontent.com/102292476/220330433-6bff9fcb-50a1-4911-8681-3983e2b4bcd0.png)
![image](https://user-images.githubusercontent.com/102292476/220330719-e15b3de7-b031-460c-9ba7-f3f41e0fcab3.png)


- [ ] Disable button Connect if not select account
![image](https://user-images.githubusercontent.com/102292476/220330574-582ecefa-ca6e-4ca6-a924-49ee02e2bf54.png)

- [ ] Incorrect logo's size
![image](https://user-images.githubusercontent.com/102292476/220330675-563a896c-80bb-416b-a6e9-d270764a7eec.png)

**Comment by S2kael** [comment]
- [ ] Incorrect logo's style (hard to control)
