### ISSUE TITLE
Make Polkadot.js App like in a white list to support EVM Accounts

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1046]
Support EVM Account on some specify DApp like Polkadot{.js} App only for some network support EVM Account like Moonbeam, Moonriver

**Comment by sokol142** [comment]
@saltict please update description for this task

**Comment by saltict** [comment]
@sokol142: I've updated issue's description

**Comment by Sokol142196** [comment]
Resolved on the current extension version (v1.2.28) -> Close this issue
