### ISSUE TITLE
Upgrade UI - Screen Signing Data

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1050]
- [x] EVM
  - [x] Sign with Keyring
  - [x] Sign with QR
  - [x] Sign with Ledger (Not available)
  - [x] Decode Sign Payload
- [x] Substrate
  - [x] Sign with Keyring
  - [x] Sign with QR
  - [x] Sign with Ledger
  - [x] Decode Sign Payload

**Comment by sokol142** [comment]
- [ ] Add sign request in case not support transaction (QR-signer account, Ledger account)

**Comment by sokol142** [comment]
- [ ] Show incorrect Amount of the transaction
![image](https://user-images.githubusercontent.com/102292476/228136881-0036ffe7-bd84-456a-9a04-b31a84feea91.png)
