### ISSUE TITLE
Upgrade UI - Add Components for Transaction Screens

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1067]
- [x] Screen Tab (use in Stake screen) (Quang)
- [x] Value Input (output ra số full) (Quang)
- [x] Data Tables (LW )
  - [x] 		Confirmation
  - [x] 		Staking Screen
  - [x] 		Sign Screen
- [x] Staking Network details (LW)
- [x] Select Pool Input (Quang)
- [x] Select Nominator Input (Quang)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678083121116.zip
- [ ] Do not show background in case below
Steps:
1. Open the any dApp (ex: connect.subwallet.app)
2. When the connect wallet popup displayed, the user closes this popup
3. Re-open the SubWallet extension
4. Click on Cancel/Connect/Block button to close the connect request
5. Go to the any select modal then observe the background displayed

Actual: Do not show background
![1067_bugBackground](https://user-images.githubusercontent.com/102292476/223413143-a3e75d91-543f-4909-9591-75352763734b.gif)
Expected: Show background
