### ISSUE TITLE
Support XCM for some chains

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1094]
**Description the task**
Support XCM for some chains:

- [x] Kusama -> Statemine
- [x] Polkadot -> Statemint
- Recheck xcm on Kintsugi chain: https://github.com/Koniverse/SubWallet-Extension/issues/1085. => Update later

**Comment by NamPhamc99** [comment]
Kintsugi xcm will be updated later

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1107-merge-build-0.8.2-1680063463658.zip

Validation passed!
![1094_validation_kusama_statemine](https://user-images.githubusercontent.com/102292476/228428448-5d7e2ce7-51cd-4200-a146-8f2bb6c47f77.gif)
![1094_validation_polkadot_statemint](https://user-images.githubusercontent.com/102292476/228428482-4770ecb2-d58e-436d-8e9d-92ba75f670bc.gif)
