### ISSUE TITLE
Equilibrium logo update

### ISSUE THREAD

**Issue by emily-subwalletapp** [Koniverse/SubWallet-Extension#1098]
The logos of EQ, EQD tokens & Equilibrium parachain are outdated. Please help replace them with the latest ones. 

EQ token: https://drive.google.com/file/d/1ugIA5H9ECV29PPIm6pSUt-hFxX_2fJOV/view?usp=sharing
EQD token: https://drive.google.com/file/d/1yRjdI3qy6RFFMTSIybVcYxLFADp7BzMf/view?usp=sharing
Equilibrium parachain: https://drive.google.com/file/d/1ugIA5H9ECV29PPIm6pSUt-hFxX_2fJOV/view?usp=sharing
 
Thanks a lot!

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1105-merge-build-0.8.2-1680002085136.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/228409491-81961d13-c128-42b3-b86e-49ab9e98f341.png)
