### ISSUE TITLE
Upgrade UI - Grammar Verification

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1125]
Description of the task
- Grammar Verification

**Comment by GeneGlsn** [comment]
Upgrade UX for action:transfer in SubWallet extension
Change title of the following screen from "Select chain" to "Select destination chain"
<img width="287" alt="Screenshot 2023-04-04 161744" src="https://user-images.githubusercontent.com/119558200/229750750-9c151e9b-3703-4f9d-8fc5-e1386375beb2.png">

**Comment by GeneGlsn** [comment]
Fix typo in action: import by seedphrase
Change into "Polkadot"
<img width="282" alt="Screenshot 2023-04-04 164136" src="https://user-images.githubusercontent.com/119558200/229753473-423f62ee-bc0b-4def-8c71-eb9693ce30b2.png">

**Comment by GeneGlsn** [comment]
Change field name in screen: Staking details - pooled staking
<img width="283" alt="Screenshot 2023-04-11 115635" src="https://user-images.githubusercontent.com/119558200/231060726-d5141370-8050-444f-ae27-09de6636f306.png">

Follow this comment in design file
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep?node-id=2482:61739#404419315

**Comment by GeneGlsn** [comment]
Change field name in screen: Staking details - pooled staking
<img width="288" alt="Screenshot 2023-04-11 115536" src="https://user-images.githubusercontent.com/119558200/231061050-e0cbd3f7-7838-4d67-9253-124d1ed7d27e.png">

Change "Nomination" into "Pooled status"
Follow design here:
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=2091-55571&t=ASK2YKJYGOOvH8vr-0

**Comment by GeneGlsn** [comment]
Change field name in screen: Staking details - pooled staking
Major differences between current product
<img width="287" alt="Screenshot 2023-04-11 120942" src="https://user-images.githubusercontent.com/119558200/231062099-5f1b1e6b-94c8-4b99-8384-575ab007990f.png">

And design:
<img width="200" alt="Screenshot 2023-04-11 121005" src="https://user-images.githubusercontent.com/119558200/231062197-acbe73ed-f117-4720-a120-db544221e663.png">

Field names such as "Staked", "Active staked" are not user-friendly (what's the difference between the two?). Please change field name accordingly following the design:
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=2091-55571&t=ASK2YKJYGOOvH8vr-0

**Comment by GeneGlsn** [comment]
Change field name in screen: Staking details - nomination staking
Major differences between current product
<img width="281" alt="Screenshot 2023-04-11 122029" src="https://user-images.githubusercontent.com/119558200/231063384-8648b433-ef00-40db-9c11-735a6906e3ca.png">

And design:
<img width="203" alt="Screenshot 2023-04-11 121832" src="https://user-images.githubusercontent.com/119558200/231063443-ca3a41b1-8a64-4673-ae1c-bdd7311af8e2.png">

Field names such as "Staked", "Active staked" are not user-friendly (what's the difference between the two?). 
Incorrect screen name
Incorrect name for field: nomination status

Please change field name accordingly following the design:
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=2091-55571&t=ASK2YKJYGOOvH8vr-0

**Comment by sokol142** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/1280
