### ISSUE TITLE
Re-test with other browser and other OS

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1126]
Description of the task

- [x] Retest with another browser:
   - [x] Chrome: NhungPTT
   - [x] Brave: : NhungPTT
   - [x] Firefox
   - [x] Microsoft Edge
   - [x] Opera
   - Safari: Re-test later

- [x] Retest with another OS
   - [x] MAC: : NhungPTT
   - [x] Window
   - [x] Linux

**Comment by ThaoNguyen998** [comment]
- [ ] Recheck the size of the password field

![Image](https://user-images.githubusercontent.com/117999489/230031498-343b5dd4-bfb5-459a-8222-ae6448a02b8b.png)
