### ISSUE TITLE
An error occurs when send WASM NFT

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1132]
**Description of the bug**
An error occurs when sending WASM NFT

Actual: When the user sends AzeroPunk NFT with address: 5CUV3wU3FU7BcdmKNi6f5WikcH9iKJFWDDoE6VLvGsiaqcz9 then an error occurs

![Image](https://user-images.githubusercontent.com/102292476/230278861-9eee211a-5373-4b32-a2e4-95f7b9730e45.png)

![Image](https://user-images.githubusercontent.com/102292476/230278897-b3e26a66-2fda-4be8-908c-822d7d3acdc0.png)

**Comment by Sokol142196** [comment]
Do not reproduce this bug on v1.0.11 => Closed this issue and keep follow-up
