### ISSUE TITLE
Upgrade UI - Bugs related to the send tokens feature

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1140]
**Description of the task**
Bugs related to the send tokens feature:
_Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.1-1680525001131.zip_

- [x] Re-check the MAX function
   - Actual: Max = Max balance
   - Expect: Max = Max balance - Estimated fee

- [x] Re-check case validate amount when changing token
![image](https://user-images.githubusercontent.com/102292476/230043945-8d46da32-7c41-48ab-82ed-2399fb5f8165.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-2023-04-12T18-57-04UTC.zip

- [ ] Re-check case validate amount when changing token KSM to ACA

![Image](https://user-images.githubusercontent.com/117999489/231691115-6c848672-b3dc-4cc6-9a1e-0ab6787d5ad1.png)
