### ISSUE TITLE
Upgrade UI - Handling the case where the user chooses the bet action when no account is supported

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1149]
**Describe the issue**
Handling the case where the user chooses the bet action when no account is supported

Steps:
1. Install SubWallet
2. Attach read-only account
3. Go to the Staking tab
4. Perform staking actions then observe the screen displayed

**Actual:** 
- When stake/stake more/unstake/ claim -> Open the screen but do not have an account to select to perform action

![Image](https://user-images.githubusercontent.com/102292476/230709680-3c13a4d4-41dc-4bc6-a9a1-ebc466132767.png)
- When claiming a reward on the dApp -> Show message lỗi

![Image](https://user-images.githubusercontent.com/102292476/230709724-2fc449f5-d637-4793-9ea8-a56dd07487de.png)

**Expect**: Show message "" when click on button action 

**Solution: Temporality redirect user to the action screen without account**

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-2023-04-12T18-57-04UTC.zip
Validation passed in case claiming a reward on the dApp

![Image](https://user-images.githubusercontent.com/117999489/231643744-fb7c8efa-87a8-43f9-a6a4-488cbad41fa3.gif)
