### ISSUE TITLE
Upgrade UI - Implement Withdraw feature for the "All accounts" mode

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1150]
**Describe the task**
Implement Withdraw feature for the "All accounts" mode

**Expect**: When user standing on "All accounts" mode, click on "Withdraw" button -> Redirect user to the Withdraw screen with Select account field (refer claim reward)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-1681181326431.zip

Validation passed.

![Image](https://user-images.githubusercontent.com/117999489/231109211-7ca5bd7b-2738-469b-96c0-6024fb170d8a.gif)
