### ISSUE TITLE
Upgrade UI - Keep the address inputted by the user

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1155]
**Describe the task**
Keep the address inputted by the user

Actual: On the transfer screens (send token, send NFT) -> the address inputted by the user automatically convert to Substrate address -> confuses 
Expected: 
- Keep the address and show more "network address"

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-1681181326431.zip
Validation passed.

![Image](https://user-images.githubusercontent.com/117999489/231406692-7e835f47-b77c-4225-a96b-0d9ba8e55ea3.png)
