### ISSUE TITLE
Upgrade UI - Update UI confirmation screen follow by design

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1157]
**Describe the task**
Update UI confirmation screen follow by the design
- Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1365-132089&t=J9UOYor2hqfwX2MM-4

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-1681181326431.zip
Validation passed.


![Image](https://user-images.githubusercontent.com/117999489/231385435-3973d7e8-6cca-41e2-8c53-0698c982fe97.png)
