### ISSUE TITLE
Decrease time and avoid error while changing master password

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1184]

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1186-build-1.0.2-1-2023-04-12T10-23-13UTC.zip

Validation passed!
- Note: Change password successfully with >30 accounts in the wallet
