### ISSUE TITLE
Upgrade UI - Do not show the Successful screen after migrated password successfully

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#1193]
**Describe the bug**
Do not show the Successful screen after migrated account successfully

**Actual**: After migrating password successfully then redirect the user to the Homepage screen
**Expect**: Redirect the user to the Apply success screen

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1195-build-1.0.2-1-2023-04-13T07-43-12UTC.zip

Validation passed.

![Image](https://user-images.githubusercontent.com/117999489/231712310-8997b4a4-de71-4b6a-8fe1-52757f29d5ae.png)
