### ISSUE TITLE
Block export Private key with Substrate due to not supporting import

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#1207]
Since we and other wallets have not yet allowed importing the private key for the Substrate account, this export in the Substrate account can be temporarily hidden for users to avoid confusion.

![image](https://user-images.githubusercontent.com/2582652/231927428-1ce28d64-2944-4630-8fb5-649be59cd6d9.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1212-build-1.0.2-1-2023-04-18T05-17-47UTC.zip
Validation passed!
![image](https://user-images.githubusercontent.com/130966515/232699872-4f4a6f63-c31f-4986-a8e5-590fca9d1ac5.png)
