### ISSUE TITLE
Fix search input errors logs of some modal with seach input

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1209]
Error logs is created with some modal with search input inside like this.

![Image](https://user-images.githubusercontent.com/11567273/231930487-707d97e5-845e-46ab-abca-8f8af32bfece.png)

The reason is because SWModal use deprecated props.
- Need update @subwallet/react-ui
- Upgrade @subwallet/react-ui inside extension
- Replace with new props

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-2023-04-17T08-06-05UTC.zip

Validation passed.
