### ISSUE TITLE
Upgrade UI - Re-check validate amount must be equals when transfer

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1215]
Describe the bug
Re-check validate amount must be equals when transfer

Actual: 

![Image](https://user-images.githubusercontent.com/117999489/232023788-a8212987-0d20-48ab-a170-4107b62d788b.png)

**Comment by ThaoNguyen998** [comment]
- [ ] Re-check with staking 

![Image](https://user-images.githubusercontent.com/117999489/232463717-4544b885-7fd5-4eea-b5cc-28c0e39b58b6.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1214-build-1.0.2-1-2023-04-17T11-47-37UTC.zip

- [ ] @S2kael please check the value when the user changes the token on the Staking screen

Steps:
1. Go to the Add to bond screen
2. Select DOT and input the amount
3. Change the token to WND then observe the error message on the Amount field

Actual: Show incorrect balance 
![image](https://user-images.githubusercontent.com/130966515/233022467-67012b51-1f21-499e-8614-7137cfe2adc7.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1214-build-1.0.2-1-2023-04-19T09-52-32UTC.zip

Validation passed!
