### ISSUE TITLE
Review and improve send max in transaction screens

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1220]
**Describe the task**
- Update UX when the user transfer max

![Image](https://user-images.githubusercontent.com/130966515/233777931-33519f93-4047-42cb-99fe-b8290cee616d.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1288-build-1.0.2-1-2023-04-24T07-37-12UTC.zip

Please check:

- [ ] Show incorrect amount in case of the user input Amount: [Available balance - Amount - Fee] < ED
   - Actual: Change to "Transfer Max" but Amount is not max
![image](https://user-images.githubusercontent.com/130966515/233946309-b6327c76-586c-4c92-94d9-0538e14664fc.png)

   - Expect: Automatically change Amount to Max

- [ ] Show incorrect Amount when transferring BNC (Bifrost Kusama) token
![image](https://user-images.githubusercontent.com/130966515/233950818-ed26e3c6-36a6-45c7-be0d-466c840ecfe7.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1288-build-1.0.2-1-2023-04-27T02-41-06UTC.zip

- [ ] Improve: Do not change Amount when change token in case [Avalable balance - Amount] < ED

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1288-build-1.0.2-1-2023-04-27T09-20-17UTC.zip

Validation passed!
_Notes: In case user input Max then change token (change from token A to token B), when select token A again then Amount will invalid.
Reason: every time user exchange tokens back and forth
then it has to recalculate the max transfer, which each time calculates a different gas fee._
