### ISSUE TITLE
Detect phishing with chainpatrol

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1226]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=5587-152780&t=YPPkMFV6LwCk79XI-4

**Comment by Sokol142196** [comment]
- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/30464692-9311-4bfc-8d25-c2c7d336a07e)
