### ISSUE TITLE
Update manage message and notification in extension

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1227]
The notification that implementing in the extension is not good. I lack of many thing because not not delivery with antd did. 
Need recheck and optimize it in the right way
- [x] Add close button

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1613-build-1.1.1-2023-07-06T12-49-23UTC.zip

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b05db69e-b21b-4b14-91b7-3569fb9e681b)
