### ISSUE TITLE
Resolve problems with expand view

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1229]
Update UI by design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=7606-168290&mode=design&t=Y0CejLLZw95wNqNc-4

**Comment by Sokol142196** [comment]
Resolve in https://github.com/Koniverse/SubWallet-Extension/pull/1562
