### ISSUE TITLE
The list of accounts that can withdraw is incorrect when viewing in All accounts mode

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1230]
**Describe the bug**
The list of accounts that can withdraw is incorrect when viewing in All accounts mode

**Pre-condition:** Account A have Active staked balance = 0 and can withdraw all

**Steps:**
  1. Go to Staking tab on the All Accounts mode
  2. Click on "Withdraw" action and perform withdraw successfully with Account A
  3. Until withdraw all, continuing to click on Withdraw action
  4. Then observe the account list displayed.

**Actual**: Still show account A on list

[Withdraw_All.gif.zip](https://github.com/Koniverse/SubWallet-Extension/files/11247351/Withdraw_All.gif.zip)

**Comment by Sokol142196** [comment]
Do not reproduce this issue on v1.0.12
=> Closed issue
