### ISSUE TITLE
An error occurs when send some token (DOT (Genshiro), xcUNIT (Moonbase))

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1232]
**Description of the bug**

- [x] An error occurs when sending DOT (Genshiro)

**To reproduce the bug**
Steps: 
  1. Go to the Transfer screen
  2. Input token = DOT (Genshiro)
  3. Input valid data for the remain fileds
  4. Click button Transfer

Actual: 

![Image](https://user-images.githubusercontent.com/117999489/232415779-4c1f55d1-5ec7-4dc5-b808-b9520644ca58.png)

- [x] Re-check when send token xcUNIT

![Image](https://user-images.githubusercontent.com/117999489/232459667-852014c3-2729-4bbb-923c-bd3e757b9b0f.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1257-build-1.0.2-1-2023-04-20T09-24-07UTC.zip

Validation passed with DOT (Genshiro)
- xcUNIT (Moonbase Alpha) has been removed!
