### ISSUE TITLE
Update error message in some of the following cases

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1233]
- #1270
   - Expect: Show incorrect file box (refer: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base-1.0.0?node-id=1543-10136&t=32tm1P2YXaGovZwk-4)

![Image](https://user-images.githubusercontent.com/117999489/232433086-592cff91-66d8-4e56-a8cb-8c17d0896593.png)

- [x] Update message when staking

![Image](https://user-images.githubusercontent.com/117999489/232433386-0558f051-2ac8-4d6c-8ab1-86e87b502b06.png)

- [x] Update message in case unstake with Remain amount < Minimum stake
   - Change to "Invalid. If you unstake this amount your staking would fall below minimum stake required"
![image](https://user-images.githubusercontent.com/130966515/232674821-83fcea41-b808-486d-953f-6f2bd66673b7.png)

- [x] Update placeholder on searchbox
![image](https://user-images.githubusercontent.com/130966515/232757893-4469987b-3629-421a-88c4-5155d2c9672d.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1257-build-1.0.2-1-2023-04-20T09-24-07UTC.zip

I still get this behavior, please check
![image](https://user-images.githubusercontent.com/130966515/233341288-64ca0662-1e3e-4898-a53a-485ebf00df09.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1257-build-1.0.2-1-2023-04-21T03-28-48UTC.zip

Validation passed!
