### ISSUE TITLE
Show the alternate title name of Dapp in the Manage website access screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1234]
Description of the bug
Show the alternate title name of Dapp in the Manage website access screen

To reproduce the bug
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-2023-04-17T08-06-05UTC.zip

Actual: Do not show title Dapp (check with dotinsights.subwallet.app)

![Image](https://user-images.githubusercontent.com/117999489/232443647-6eff2b2a-dcfa-4e90-b432-6c2aaf5026af.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1341-build-1.0.3-2023-05-11T05-16-49UTC.zip

Validation passed!


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5e87b11e-f73a-42cd-8f6a-5b7802c467b6)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c7cd8bb7-b261-4c07-8c54-3f0fd42cf602)
