### ISSUE TITLE
Still showing sent NFT when using 2 different browser

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1235]
**Description of the bug**
Still showing sent NFT when using 2 different browser

**To reproduce the bug**

Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-2023-04-17T07-59-29UTC.zip

Pre-condition: Open 2 different browsers A & B and use the same account

Steps:

1. In browser A, send NFT successfully
2. In browser B, observe the information displayed

Actual: Still showing sent NFT

Expect: Do not show sent NFT

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1271-build-1.0.2-1-2023-04-21T12-01-24UTC.zip

Validation passed!
![1235_Validation](https://user-images.githubusercontent.com/130966515/233637204-b6dcd36b-721e-493e-918e-6099874dfd4c.gif)
