### ISSUE TITLE
Display multi window in case multi request

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1238]
Description of the bug
Display multi-window in case multi request

To reproduce the bug

Actual: Display multi-window in case multi request

![Image](https://user-images.githubusercontent.com/117999489/232480558-f0a794ca-311d-4524-b09f-db14720333f2.gif)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1252-build-1.0.2-1-2023-04-20T04-16-33UTC.zip

Validation passed
