### ISSUE TITLE
Check extension sleeping and wake up

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1239]
Check sleep - wake up date some new service:
- Price
- History

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1292-build-1.0.2-1-2023-04-24T11-46-25UTC.zip

Please re-check issue Send transaction from dApp
- Actual: Do not send 
![image](https://user-images.githubusercontent.com/130966515/236195395-4a3d823f-326c-4f02-a80c-b9dedce2bbc8.png)


Note for tester
- Re-check case improperly shutting down the browser

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1292-build-1.0.2-2023-05-05T07-47-27UTC.zip

Validation passed!
- Transaction history displays correctly
- Token price updated according to configuration
- Other information displayed correctly
