### ISSUE TITLE
Do not display the add network screen in case the network already exists

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1241]
**Describe the bug**
Do not display the add network screen in case the network already exists when user add network from dApp

**Steps:**
1. Go to chainlist.org
2. Connect wallet successfully
3. On the Chainlist page, click on "Add to wallet" button
4. Perform add a network to SubWallet successfully
5. Back to Chainlist page, click on "Add to wallet" button again
6. Observe the screen displayed

**Actual:** Do not show add network screen

![Image](https://user-images.githubusercontent.com/130966515/232720152-a05083bd-9e99-4b2b-9eb9-42fd37eedbf0.gif)

**Expect:** Show the add network screen with message "The network already exists"

**Comment by xavier238** [comment]
Hi @ I suggest you contact Chainlist UI developers on their web3chain website [CHAINLIST SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by ThaoNguyen998** [comment]
@saltict Please re-check: Still do not display the add network screen in case the network already exits

Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1259-build-1.0.2-1-2023-04-20T11-25-52UTC.zip

![Image](https://user-images.githubusercontent.com/117999489/233536309-ab4f4dda-048f-4380-b5f7-a961ebccf877.gif)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1259-build-1.0.2-1-2023-04-21T04-20-10UTC.zip

Validation passed.


![Image](https://user-images.githubusercontent.com/117999489/233575580-b2a2c2b4-02a5-4bd9-aed8-11496f3d0568.png)
