### ISSUE TITLE
Can't add token from dApp

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1242]
**Describe the bug**
Can't add token from dApp

**Steps:**
1. Go to any dApp (ex: https://portal.astar.network/astar/assets)
2. Connect to wallet successfully
3. On the Astar Portal, click on "Add token to wallet"
4. Observe the screen displayed

**Actual:** Do not show add token screen

![Image](https://user-images.githubusercontent.com/130966515/232726057-5e230308-0944-47c9-b21e-0cb8aab29bd0.gif)

![Image](https://user-images.githubusercontent.com/130966515/232724757-b25345ca-7370-41f5-b6db-d66190e34e80.png)

**Expect**: Redirect user to the "add token" screen then add token successfully

**Comment by xavier238** [comment]
Hi @Sokol142196  I had the same issue as well till i was told to contact a dapp UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. I suggest you do the same. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by ThaoNguyen998** [comment]
@saltict Please re-check still can't add token from dApp
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1259-build-1.0.2-1-2023-04-20T09-36-56UTC.zip


![Image](https://user-images.githubusercontent.com/117999489/233352059-119fe58d-6b89-4382-98c4-047b131ab74f.png)

**Comment by ThaoNguyen998** [comment]
- [ ] Do not display the add token screen in case the token already exists when user add token from dApp
Actual: Do not show add network screen
Expect: Show the add token screen with message "The token already exists"

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1259-build-1.0.2-1-2023-04-21T04-20-10UTC.zip

Validation passed.


![Image](https://user-images.githubusercontent.com/117999489/233574966-ed3792f9-7861-450c-96f9-0b2affe26b52.png)
