### ISSUE TITLE
Don't show NFT, staking details on the first time accessing

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1246]
**Describe the bug**
Don't show NFT, staking details on the first time accessing

**Steps:**
1. Install the SubWallet extension successfully
2. Create a master password
3. Import account successfully
4. Observe the assets (balance, NFT, crowdloan, staking) displayed 

**Actual:** Do not show NFT and can not view Staking detail
- Users have to close pop-up and then reopen it to see them

**Comment by NamPhamc99** [comment]
Due to not adding eventHandler when there's no account on the wallet

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1257-build-1.0.2-1-2023-04-20T09-24-07UTC.zip

Validation passed!
![1246_Validation](https://user-images.githubusercontent.com/130966515/233334455-cb15acd9-cb62-4db4-aad8-cf019337daeb.gif)
