### ISSUE TITLE
Re-check the feature of automatically turning on the network according to the existing balance

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1247]
**Describe the task**
Re-check the feature of automatically turning on the network according to the existing balance

**Actual:** Turn on some networks with Balance = 0 (check with address: 5CqUd153pVTUe3K12TJnpFzkpXGBhU3Z9SqqH5u2ifZ6u1x2)
- RING (Darwinia)
- EDG (Edgeware)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1259-build-1.0.2-1-2023-04-21T04-20-10UTC.zip

Validation passed.

**Comment by Sokol142196** [comment]
Re-open the issue to verify with EVM account in case create a new account.
