### ISSUE TITLE
Incorrect balance display of some tokens

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1248]
**Describe the bug**
Incorrect balance display of some tokens:

- [x] RING

![Image](https://user-images.githubusercontent.com/130966515/232965736-65c28f82-cb4f-4ee7-90af-ac347b0301d9.png)

- [x] KSM (Shiden)

![Image](https://user-images.githubusercontent.com/130966515/232965596-f4c0c4b1-6236-4387-8613-e898e1730c19.png)

**Comment by NamPhamc99** [comment]
RING is about to be hard forked

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1257-build-1.0.2-1-2023-04-20T09-24-07UTC.zip

Validation passed for KSM (Shiden)
![image](https://user-images.githubusercontent.com/130966515/233338860-af30409b-e8f9-48c3-b3f9-eec6ffa30111.png)

About the RING (Darwinia) test later update the new chain
