### ISSUE TITLE
Feedback from partners

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#1250]
**Describe the bug**

I've collected some feedback (and attached some screenshots about it as well):

- still, my main issue is that if i have a default page zoom set in Chrome/brave settings (e.g. 110%) the extension is somehow broken / incorrectly scaled => Resole later (https://github.com/Koniverse/SubWallet-Extension/issues/1286)

- [x] 2. very high balances like 5,235,637.12 TZERO get somehow inaccurately rounded (→ 5M in this case) which holds not have enough information IMO: https://github.com/Koniverse/SubWallet-Extension/issues/1272

- [x] 3. "Manage Chains" is not capitalized like the rest in your settings

- 4. wallet addresses after the account name in the top bar should be truncated in the middle (currently it only shows the end of the address for me) => Do not fix

<img width="502" alt="wrong scaling when 110% zoom 2" src="https://user-images.githubusercontent.com/2582652/232998112-78e0dfc1-c973-436b-8de8-e52091b84d65.png">
<img width="456" alt="wrong scaling when 110% zoom 1" src="https://user-images.githubusercontent.com/2582652/232998216-1633f1f9-4d6b-428a-a02d-9a4c8d38efb1.png">
<img width="698" alt="warning in brave after install" src="https://user-images.githubusercontent.com/2582652/232998245-9118fc01-a244-4f5e-a252-00209ed8b88c.png">
<img width="430" alt="the_wallet_address_should_be_truncated_in_between_and_not_only_show" src="https://user-images.githubusercontent.com/2582652/232998259-5c65f635-d590-44ec-a0cb-516bff9055ae.png">
<img width="411" alt="inconsistens capitalization in settings" src="https://user-images.githubusercontent.com/2582652/232998267-d2ec9401-c474-4ea8-b1c5-63d8c3c97832.png">
<img width="408" alt="5M is too shortly abbreviated" src="https://user-images.githubusercontent.com/2582652/232998277-fde99273-0f17-48d7-bc4e-2b18328e5a94.png">

**Comment by NamPhamc99** [comment]
- [ ] Show number of tokens/chains on token/chain selector
