### ISSUE TITLE
Incorrect transaction fee display

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1251]
**Describe the bug**
Incorrect transaction fee display

**Actual:** To reproduce the behavior with address: 0x25B12Fe4D6D7ACca1B4035b26b18B4602cA8b10F
- Extrinsic: https://moonbeam.subscan.io/extrinsic/0xd22425d6c9c8c6d488bf27015e4363ee4a6e85fe6d197486291b1f018af6b30c

![Image](https://user-images.githubusercontent.com/130966515/233059443-52422100-8663-4f61-819a-b83a4523a1e3.png)

**Comment by S2kael** [comment]
Since data from the DataIndexer is missing, the fee calculation is incorrect.
The issue will be further resolved after updating the DataIndexer side.

**Comment by S2kael** [comment]
Currently use data in transaction to calculate gas fee.

However, evm network have 2 way to set max gas fee for transaction:
  - Simple: `gasPrice` and `gasLimit`
  - EIP 1559: `gasLimit`, `maxPriorityFeePerGas` and `maxFeePerGas`

At the moment, we are using the formula: `gasFee = gasPrice * gasLimit`.
So in case transaction use EIP 1559 protocol, we cannot calculate `gasFee`.

The above methods all use information from the transaction submitted to calculate the fee. This way of getting the fee is not correct, the information should be taken directly from the block.

**Comment by Sokol142196** [comment]
Unable to reproduce the issue on the current extension (v1.2.28) => Close this issue
