### ISSUE TITLE
Improve Transaction UX

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1254]
**Describe the task**
Improve Transaction UX

**Expect:** Show the transaction done immediately after approve the transaction

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1296-build-1.0.2-1-2023-04-27T12-31-14UTC.zip

Please check:

- [ ] Update "Sending" status to "Submitting" status
- [ ] Please kindly check issue: Do not update the history status of the XCM transaction 
   - I sometimes have this situation, can't reproduce correctly
![image](https://user-images.githubusercontent.com/130966515/236119918-f40add2c-948f-48d3-8343-38a426964953.png)
