### ISSUE TITLE
Add Gemini3d - Subspace testnet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#1255]
**Is your feature request related to a problem? Please describe.**
Please add Gemini3d - New testnet of Subspace
- [wss://eu-0.gemini-3d.subspace.network/ws
](url)
- [wss://eu-1.gemini-3d.subspace.network/ws
](url)

**Comment by NamPhamc99** [comment]
added to chain list

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-2023-04-22T11-46-48UTC.zip

Validation passed!
![image](https://user-images.githubusercontent.com/130966515/233924836-21c43e5b-c632-42a6-9781-47c5eb7dfe9c.png)
