### ISSUE TITLE
INW token logo update

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-Extension#1260]
On Subwallet, the logo for the INW token is the same as AZERO. Please help change it to the correct INW logo.

INW token logo (36x36): https://drive.google.com/file/d/1LtNH6eCqXiAabTyaJOG0vceqqFDqr3or/view?usp=sharing

Thank you!

**Comment by Sokol142196** [comment]
Close the issue on this repository, move to "SubWallet-Chain" (https://github.com/Koniverse/SubWallet-Chain/issues/3)
