### ISSUE TITLE
Update fetching staking info with middleware service

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1263]

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1287-build-1.0.2-1-2023-04-24T09-20-35UTC.zip

@saltict @NamPhamc99 

- [ ] Please also check the error of not showing the validator list in case of the first time turning on the network when staking.
   - Actual: Do not show the validator list to stake, the user must change token or change the account... then list validator is displayed
![Staking_turnOn_firsttime](https://user-images.githubusercontent.com/130966515/236179936-0c50b5fc-ded9-44f8-b39e-a7a48e2e2b75.gif)

**Comment by saltict** [comment]
The above problem is because network is disconnected. We will improve with #1318
