### ISSUE TITLE
Re-check border

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1275]
**Describe the task**
Re-check the border of the extension

**Expect:** border = 1px

**Comment by ThaoNguyen998** [comment]
- [ ] UI bug when open extension in case expand view
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1278-build-1.0.2-1-2023-04-22T07-39-34UTC.zip


![Image](https://user-images.githubusercontent.com/117999489/233772016-06e8e6a5-73c7-4dff-ba57-4795b8ac5a06.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1278-build-1.0.2-1-2023-04-22T12-24-11UTC.zip

Validation passed.
