### ISSUE TITLE
Spelling update (round 1)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1280]
**Describe the task**
Spelling update
- Documents: https://www.notion.so/subwallet/Chu-n-h-a-ng-n-ng-cho-extension-13b83fa6f95e49b9923b0b4ec11f7072?pvs=4

**Comment by ThaoNguyen998** [comment]
- [ ] Update message when import from metamask

![Image](https://user-images.githubusercontent.com/117999489/233901824-577d33ca-063f-4744-ad5a-7f58ccf670f0.png)
