### ISSUE TITLE
Update some new logos

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1282]
- Update new logo from:
https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/Polkadot-Project-Logo?t=fcSs0FwjORtTFMW3-0
- Update SubWallet default logo

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1283-build-1.0.2-1-2023-04-24T02-44-50UTC.zip

Validation passed.
