### ISSUE TITLE
Can not send EVM Transaction from DApps

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1294]
## Reproduce
- Create EVM transaction from connect.subwallet.app or any DApps like astar portal
- Sign / Send transaction
- Extension and DApp show failed

![Image](https://user-images.githubusercontent.com/130966515/234250192-e69ca12a-530d-41ad-80de-346082b519f2.png)

![Image](https://user-images.githubusercontent.com/130966515/234276713-9e18d4a6-107a-4c0a-a962-b5e538aa5b53.png)

- Some time extension and show error 

=> Exprect: Send transaction or throw clearly wrong reason for the failed

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1296-build-1.0.2-1-2023-04-26T08-53-41UTC.zip

Validation passed!
Send successfully with extrinsic below:
- https://astar.subscan.io/tx/0x9d4c4e0d63b838cd2a67540df7260010bd0c884963174f06c8d45f45453d33c1
- https://moonbase.subscan.io/extrinsic/0x61237cec3fa4a8e9e5895bfe6a2511b926c22ec7ed99104176d4118903f2f9d5
- https://moonbeam.moonscan.io/tx/0x2e52277eb2d60b80c0f7e69c2ad254b6224fb29744c773f2f65bec8573172cd3
![image](https://user-images.githubusercontent.com/130966515/234564229-f464a997-1a3d-4f30-9f1b-e734e2fb6dc4.png)
