### ISSUE TITLE
Update Welcome and Login Logo & Background

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1298]
![Image](https://user-images.githubusercontent.com/11567273/234763442-314526bc-2f85-48b7-851e-e3a3bb63ceee.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1299-build-1.0.2-1-2023-04-27T09-48-16UTC.zip

Validation passed!


![Image](https://user-images.githubusercontent.com/130966515/234848791-027cfd87-1fb2-4feb-9859-d7820a41df85.png)



![Image](https://user-images.githubusercontent.com/130966515/234853321-1c847cfb-3dcb-4492-8c3c-e08e21b3c4c8.png)
