### ISSUE TITLE
Bug when URL NFT collection fails

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1300]
Description the bug
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1299-build-1.0.2-1-2023-04-27T09-48-16UTC.zip

Steps:
1. Go to the NFT conllection
2. Click on detail NFT collection screen
3. Observe the screen displayed

Actual: Display error

![Image](https://user-images.githubusercontent.com/117999489/235055808-9d29d6ce-f669-42e6-b5e8-78786772c143.gif)

Expect: Display detail NFT collection screen

**Comment by saltict** [comment]
@NamPhamc99 please recheck with cf-ipfs.com

**Comment by Sokol142196** [comment]
Do not reproduce the behavior on current version (v1.2.28) => Close issue
