### ISSUE TITLE
Do not automatically switch the network according to the dApp in case of version upgrade

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1301]
**Describe the bug**
Do not automatically switch the network according to the dApp in case of version upgrade

**To reproduce the behavior**
Steps:
1. Installed SubWallet v0.8.4 then turn on Moonbeam and Etherium
2. Connect to StellaSwap -> Cannot connect, Show "Wrong network"
3. Upgrade to v1.0.2 
4. Go to the StellaSwap to re-connect

**Actual**: Still cannot connect though turn on only Moonbeam
- User must be forget site to connect

![Image](https://user-images.githubusercontent.com/130966515/235142860-4f670042-561d-4a3b-96cd-8600b08436f6.gif)

**Expect**: Automatically switch the network and connect to dApp successfully

**Comment by saltict** [comment]
Auto re apply new DApps for existed DApp in the known list in the case update extension

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1338-build-1.0.3-2023-05-10T04-56-41UTC.zip

Validation passed!
![1301_Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/708a2497-e6c9-4528-bf3c-8c92ee4f0248)
