### ISSUE TITLE
Bump dev outdate libs

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1306]
- [x] Update apollo client
- [x] Update @subwallet/chain-list with newest @gh-page version
- [x] Update web3

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1312-build-1.0.2-2023-05-05T14-46-25UTC.zip

Validation passed!
