### ISSUE TITLE
A pending transaction frenzy can lead to duplicate transactions being created within the same session.

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1308]
When users submit a transaction, the wallet stores it in memory with the state pending.
If the rpc or user's networking experiences have any issues, the pending transaction freezes in memory, preventing the user from sending any new transactions during the session.

Solution: **Add some timeout for this transaction, after timeout transaction auto change to failed**

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1324-build-1.0.2-2023-05-06T10-29-45UTC.zip

Please check the issue:

- [ ] Handling the case of showing "Completed" while there is no "Extrinsic hash"
Steps:
1. Go to the transfer screen
2. Input valid data for all field
3. Click on the Transfer button
4. Click on the Approve transaction and view history
5. Immediately after approving the transaction, the user turns off the network
6. Waiting for the 30s (< timeout setting) then turn on the network
7. Observe the history displayed

Actual: The history show:
- Status = Completed
- Extrinsic hash = ... (there is no "Extrinsic hash")
![image](https://user-images.githubusercontent.com/130966515/237001927-c0c3f31e-f0b2-4b4f-bc2d-68ab02a02c1c.png)


Expect: Show Status = Failed
