### ISSUE TITLE
Support Unstake Max

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1311]
**Describe the task**
Support Stake and Unstake Max

**Actual:** Do not have Max when unstake -> It is difficult for users to determine the maximum amount that can be unstake in case of receiving rewards (with odd numbers)

![Image](https://user-images.githubusercontent.com/130966515/236162432-0e9f8662-fc1e-402b-801f-e5adf248ff81.png)

**Expect:**

- [x] In case: Unstake Max

   - Max = Active bonded
   - If user input Amount: Active staked < min stake then auto-detect Unstake Max

- In case stake:
   - Max = Available - Fee - ED

**Comment by S2kael** [comment]
### Stake max

- To estimate fees, it needs to know the number of validators.
- When the number of validators is changed, the fee will change so the maximum value must change. Too complicated to calculate the maximum value.
- Repetitive calculations can lead to a slow user experience, especially on mobile

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1431-build-1.0.7-0-2023-05-31T08-15-14UTC.zip

Please check:

- [ ] Validate of the Amount is incorrect in case user change account, change collator

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b5be77f2-de9f-4e23-9501-88e5b891c685)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1431-build-1.0.7-1-2023-06-01T05-43-43UTC.zip

Validation passed unstake max for cases:
- Pooled
- Nominated relaychain
- Nominated parachain
- Nominated dApp
