### ISSUE TITLE
Support Subspace Gemini 3d on version 0.8.x

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1315]

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.8.4-1683260999135.zip
Validation passed!



![Image](https://user-images.githubusercontent.com/130966515/236401933-918d17c1-96be-4db6-9aaa-db6e2cf8e101.png)
