### ISSUE TITLE
Add support for $NEER on Transak

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#1317]
**Is your feature request related to a problem? Please describe.**
Transak has added support for $NEER. Please integrate $NEER fiat on-ramp on SubWallet to allow users to buy $NEER with fiat currencies.
- https://docs.transak.com/

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1325-build-1.0.2-2023-05-08T07-27-03UTC.zip

Validation passed!
![1317_Validation](https://user-images.githubusercontent.com/130966515/236982590-b80a5c0c-1130-4134-9bd9-27803d0dea2b.gif)
