### ISSUE TITLE
Auto-update online from chain list (step 2)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1319]
Step 2: Implement basic level of auto update chain list
- [x] Auto update chain-data
  - [x] Update token info
  - [x] Update chain info
  - [x] Auto update logo map

**Comment by NamPhamc99** [comment]
Prioritize data from chain-list over stored data on the app. If the asset/chain is custom, then just save the setting from user

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1342-build-1.0.3-2023-05-11T07-56-50UTC.zip

Validation passed for cases:
- Update chain: 
   - Subspace Gemini 3d: logo and URL explorer
   - Tinkernet: Update network name
- Add new network:
   - Vara network
   - Snow-EVM network
