### ISSUE TITLE
Can't pool after withdraw all

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1323]
**Describe the bug**
Can't pool after withdraw all

**To reproduce the behavior**
_Pre-condition: A record exists that can withdraw all (active stake = 0)_

**Steps:**
1. Go to the detail screen of the record above
2. Click on Withdraw button
3. Perform withdrawal successfully
4. Observe the Staking list displayed
5. Click on the + button to stake for another pool
6. Observe the screen displayed

**Actual:**
- In step 4: Staking list displayed without record above
- In step 6:
   - Still show the old pool
   - When a user enters data and clicks on the Stake button then shows the message "Exist unstaking request"

_Notes: Reproduce the bug with address: 5CqUd153pVTUe3K12TJnpFzkpXGBhU3Z9SqqH5u2ifZ6u1x2 on WND_ 

![Image](https://user-images.githubusercontent.com/130966515/236612567-6f131fc0-aa30-4d62-9803-8e735802e75c.gif)

**Expect:** Stake for another pool successfully

**Comment by NamPhamc99** [comment]
Need to check:

- [ ] Staking after withdrawing all
- [ ] Stake with a new account
- [ ] Stake more

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1331-build-1.0.3-2023-05-09T04-34-36UTC.zip

Validation passed!
![1323_Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f8e1e001-9950-4b95-afb0-26195cb456bf)
