### ISSUE TITLE
Integrate Land/Estate NFT on Pioneer's metaverses

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1335]
Related issues:
#622 

- Each metaverse has a collection for Land and a collection for Estate (different collectionId for each metaverses)
- Estate is a group of multiple Land
- Metaverse is a record on blockchain

Check with address: 5GxmyqFWk9WGrJYxDf5aSEiDG655ZUxfCnD63FW3WZ6hsQQ2

**Comment by Sokol142196** [comment]
Waiting Pioneer's updated

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1339-build-1.1.1-2023-07-10T08-53-30UTC.zip

Validation passed
