### ISSUE TITLE
UI bug when scroll wallet

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#1336]
**Describe the bug**
UI bug when scrolling the wallet

**To Reproduce**
1. Go to the Home screen
3. Scroll down
4. See error: Have a small gap between the header and the balance display

**Expected behavior**
Rework the UI code to fix this problem

**Screenshots**

![Screenshot 2023-05-10 at 10 51 40 AM](https://github.com/Koniverse/SubWallet-Extension/assets/2582652/cebe92ca-1ef7-44ac-b76e-7c1de053ca42)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0 (22A380)
 - Browser Chrome
 - Version 1.0.3

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1337-build-1.0.3-2023-05-10T04-12-37UTC.zip

I reproduce this issue on device: 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4e104905-e31f-4b4e-be45-7e5d713df3d1)

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2f4a5811-b5c4-4024-94e3-e576a0231368)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1337-build-1.0.3-2023-05-12T03-56-24UTC.zip
Validation passed on my device (device information on the comment above)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8be668ca-fa8b-4004-ba41-4c1e0a8ee30e)

@hieudd please review this bug on your device

**Comment by hieudd** [comment]
Lgtm!
