### ISSUE TITLE
Bug address validator auto detect to top 5

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1346]
Describe the bug
Bug address validator auto detects to top 5

Reproduce the behavior

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/dd9c4952-c170-45fb-8363-5e87e518d67a)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1347-build-1.0.3-2023-05-11T12-05-03UTC.zip

Please check issue:

- [ ] Do not reset selected validator when change token
   - Reproduce the bug with new account
![1346_bug](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9ec8f2b1-bcbe-4d07-b69d-a3e126dc40dc)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1347-build-1.0.3-2023-05-15T03-30-10UTC.zip
Validation passed!

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e21a1b44-26c5-4fc5-aff9-4aafabfc981e)
