### ISSUE TITLE
Upadte Parity Signer logo & name

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#1351]
**Is your feature request related to a problem? Please describe.**
Parity Signer (https://signer.parity.io/) has been changed to Polkadot Vault. Please update it

- Name: Polkadot Vault
- Logo: https://github.com/paritytech/parity-signer/blob/master/ios/PolkadotVault/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.png

<img width="384" alt="3b70422b-2b56-43a3-8d48-bbbed6bee490" src="https://github.com/Koniverse/SubWallet-Extension/assets/102496727/0b17c657-df7d-4942-813e-755654be0929">
<img width="386" alt="61cb797d-290e-428f-acde-e9c3facaa1b3" src="https://github.com/Koniverse/SubWallet-Extension/assets/102496727/49485417-c4df-4aad-b19b-93d7da7c6069">

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1384-build-1.0.5-2-2023-05-19T07-59-32UTC.zip

Validation passed!
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/aae8ad10-61c8-469b-8418-4c98f77c5133)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3ac1fd16-903c-4fab-8fa0-df740774c1e4)
