### ISSUE TITLE
No policy for a master password

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1369]
**Describe the task**
The Subwallet should require users to create a strong password when they create a new account or change their password. This will help prevent weak passwords that are easy to guess or crack, and increase the overall security of the platform.

**Comment by hieudd** [comment]
Some policies we should follow:

- [x] Passwords should be at least 8 characters in length. (require)
- [ ] Including letters and numbers (require)
- [ ] Including special characters (warning)
- [ ] Including uppercase (warning)

**Comment by GeneGlsn** [comment]
Update message:
Password must be at least 8 characters long with at least 1 uppercase letter, 1 number, and 1 special character

**Comment by GeneGlsn** [comment]
Update message:
Password must be at least 8 characters long. There should be at least 1 uppercase letter, 1 number, and 1 special character

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1377-build-1.0.5-1-2023-05-18T05-36-27UTC.zip

Validation passed!
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b1771771-8051-4795-ae14-3feef1fbe2b1)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/274fcd7a-3128-4429-a601-2d0e5475bc54)
