### ISSUE TITLE
Handler transaction last status when stop extension and transaction in submiting phase

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1370]

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1371-build-1.0.5-1-2023-05-17T14-31-45UTC.zip

Validation passed for cases:
- Close extension
- Lost of the internet
- Close browser

_Notes:_
- Submitting transaction -> Unknown
- Processing transaction -> The last status
- Time out -> Failed transaction
