### ISSUE TITLE
Add support "view transaction explorer" for the some chain

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1381]
**Describe the task**
Add support "view transaction explorer" for the some chain

![Image](https://user-images.githubusercontent.com/130966515/239184562-c92d8617-d88c-4454-a4be-4a8c4ed2f11a.png)

**Comment by S2kael** [comment]
Update for chain:

- Rococo
- Shibuya EVM
- Aventus Polkadot
- Aventus Testnet
- Bobabase

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1390-build-1.0.5-2-2023-05-20T03-26-53UTC.zip

Validation passed!
