### ISSUE TITLE
Do not get transaction history in case the wallet have multi-account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1411]
**Describe the bug**
Do not get transaction history in case the wallet has multi-account

**Actual:** History shows very little for later added accounts.

**Comment by saltict** [comment]
Solution: Get history for single account when it is added (imported, add watch-only...)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1425-build-1.0.5-2023-05-22T11-45-23UTC.zip

- [ ] Do not show history 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b2c25436-07c6-4806-902b-bd1a6145cfdb)

**Comment by Sokol142196** [comment]
Version test:
Please re-check the issues:

- [ ] Do not show Sender on history record
   - Check with address: 5HMkyzwXxVtFa4VGid3DuDtuWxZcGqt57wq9WiZPP8YrSt6d

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4857d135-bd41-4c7b-9e3a-d547ee55c4bc)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1425-build-1.0.8-2023-06-08T05-28-03UTC.zip

Validation passed show history for cases:
- Create/Import account
- Restore account by JSON file (single account, multiple accounts)
- Attach Ledger, QR signer, watch-only account
- Remove account
