### ISSUE TITLE
Recheck DApp UX

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1413]
dApp request:
- Sign request
- Send request
- Connect request
- Add network request
- Add token request

=> After checking, I summarize according to the file below
- Discuss more to improve the highlight box

@saltict please review for me

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a2c72183-6ae5-4fd4-9e09-588b60de5fb9)

**Comment by Sokol142196** [comment]
Resolved on v1.2.28
