### ISSUE TITLE
Recheck RMRK API

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1414]
**Describe the task**
Recheck RMRK API

**Actual:** Do not show Kusama's NFT

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8794efcb-8316-4700-85f0-414ba7253dfd)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1442-build-1.0.5-2023-05-25T09-30-28UTC.zip

Validation passed for cases:
- Show NFTs
- Send NFT

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ed0224fb-09d7-4faa-941c-d6373d6574b4)
