### ISSUE TITLE
Support auto-select validator/collator/dApp when click on "auto-select" validator to nominate

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1417]
**Describe the task**
Support auto-select validator/collator/dApp when click on "auto-select" validator to nominate

**Actual:** Do not auto-select when user click on "auto-select" validator to nominate
**Expect:** @GeneGlsn please confirm the algorithm auto-select

**Comment by GeneGlsn** [comment]
There is no reasonable rationales for wallet to suggest a particular validator. Users should do their own research while choosing a validator. If they don't, they should stake via a pool. => Auto-select validator as a feature is NOT advised.

More on best practices for choosing validators: https://support.polkadot.network/support/solutions/articles/65000150130-how-do-i-know-which-validators-to-choose-
