### ISSUE TITLE
Do not detect Phishing Page with ChainPatrol on the Firefox browser

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1422]
**Describe the bug**
Do not detect Phishing Page with ChainPatrol on the Firefox browser

**To reproduce the behavior**
Steps:
1. Open SubWallet on Firefox browser
2. Go to Settings > Security Setting > Turn on "Advance phishing detection" option
3. Access to phishing page (on Chain Patrol):   trustpad-sui.cloud, 4exchange.lidonft.info...
4. Observe the screen displayed

**Actual:** Do not detect phishing page, still access page

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/928c93cb-9fe1-4a06-ace1-6aba9cd82a7e)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/094f0da2-24f0-4088-81c5-674984aae2f7)

**Expect:** Show phishing page screen

**Comment by S2kael** [comment]
Waiting for the answer from ChainPatrol
