### ISSUE TITLE
Implement Send fund UI with new Send Fund API

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#143]
### Check list:

**Components**
  - [X] InputAddress: 
    - Use messages to get data from background instead of using API directly via the background global object
      - message to get all addresses, recent entered addresses 
      - ...
    - Convert to Function component (current is class component)
    - Options Dropdown: use React Dropdown instead of SUIDropdown 
  - [X] InputBalance: 
    - The unit dropdown now only has options as token names (the unit options like mili, pico, kilo, ... will be remove) 
    - Options Dropdown: use React Dropdown instead of SUIDropdown
  - [X] Available: 
    - Use messages to get data from background instead of using API directly via the background global object
  - [X] Password
    - Use messages to get data from background instead of using API directly via the background global object
  - Fee display
    - [X] Use messages to get data from background instead of using API directly via the background global object
    - [x] Get fee with correct token. For example, if sub token is sent, main token may be used as fee 
    
**Screens**
  - [X] SendFund: 
    - Support transferring for EVM accounts
    - Support transferring for non native tokens
    - Use messages to get data from background instead of using API directly via the background global object
  - [X] AuthTransaction: 
    - Use messages to get data and perform action from background instead of using API directly via the background global object
      - Sign and Send
      - Validate 
      - Get transaction Result
      - ...
  - [X] Donate: Same as SendFund
  - [X] SendFundResult: 
    - Use messages to get the transaction result instead of using API directly
  - Transaction History:
    - Data get from Chrome storage:
      - [X] Acala, Karura, Acala Testnet
      - [X] Interlay, Kintsugi, Kintsugi testnet
      - [x] EVM networks    
  
**Other**
  - [x] Update UI (if has new design)
  - #233 
  - Change method to display Send fund result from screen to extension notification (?)
  - Check issue #154

**Comment by hieudd** [comment]
Some UI need improve
<img width="1345" alt="Screen Shot 2022-05-05 at 10 18 48 AM" src="https://user-images.githubusercontent.com/2582652/166859378-59058423-18f6-476e-984f-cced6be1714a.png">
