### ISSUE TITLE
Re-check sign transaction request from dApp with Extrinsic on the Chrome browser

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1433]
In Google Chrome, the transaction doesn't display the details that are shown in the Brave browser

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1190af52-319d-45c9-b0ea-03692e3fed13)

**Comment by saltict** [comment]
This issue because need update newest metadata

**Comment by Sokol142196** [comment]
Resolve this issue in https://github.com/Koniverse/SubWallet-Extension/issues/588
