### ISSUE TITLE
Missing balance validation on pool bonding

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1447]
Check free balance against ED and amount in case pool bonding

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1448-build-1.0.6-0-2023-05-26T08-36-04UTC.zip

Validation passed!
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6fa2e3ff-7586-45db-bd5d-62e162f895c5)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/605e8636-4ec2-4a63-831e-fdb65aa7998f)


Recheck validate when nominate
