### ISSUE TITLE
Error page when send token of the custom network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1451]
**Describe the bug**
Error page when send token of the custom network

**To reproduce the behavior**
Steps:
1. Perform add network successfully (Ex: https://kcc-rpc.com)
2. After imported successfully, go to the Send fund screen
3. Perform send token of the network above

**Actual:** Show error page

![Image](https://user-images.githubusercontent.com/130966515/241111256-55fe396f-904a-4878-b0d2-cb8d1c42a5f6.gif)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1467-build-1.0.6-2023-05-30T11-29-08UTC.zip
Validation passed.
