### ISSUE TITLE
Re-check case "Get balance error"

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1459]
**Describe the task**

- [x] Re-check case "Get balance error"
   - Actual:Show "Can not get balance" although network is active & connected

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8ba7860c-6218-4917-bf9c-f76de21c0596)

- [x] Re-check casse "Connection not open on send()

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/40f211cf-16ed-4489-a795-d767eb48797f)

**Comment by saltict** [comment]
Hot fix: Update error message for clearly, @Sokol142196 please give message for these cases.
Full solution:
- Reconnect feature is wrong => need update this
- Suggest user reconnect network after few time failed

**Comment by Sokol142196** [comment]
@saltict The message to hotfix: "Can't connect to this network. Please reconnect the network and try again"

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/1469
