### ISSUE TITLE
Script test send fund and fix bug when send fund for some tokens

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1460]
Describe the task

- [x] Script test send fund
   - Connect to all connectable network
   - Create extrinsic (success or not?)

- [x] Fix bug send token for some token:
   - [x] tKSM (Karura)
   - [x] BNB (Etherium)
   - [x] THETA (Etherium)

   - Zero value:
     - SMS (Shiden-EVM)
     - SRISE (Shiden-EVM)
     - FEGS (Shiden-EVM)
   - Owner only:
     - KZY (Astar-EVM)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1466-build-1.0.6-2023-05-30T10-24-30UTC.zip
Validation passed.
