### ISSUE TITLE
Review and optimize staking performance

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1461]
Describe the task
Re-check staking-related issues

Staking metadata is incorect on Astar
Staking information cannot be obtained on mobile

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1465-build-1.0.7-0-2023-05-31T10-41-08UTC.zip

Validation passed for cases:
- Show informations: Chain staking metadata, unclaim reward, staking detail
- Regression test all staking actions for:
   - Pooled
   - Nominated relaychain
   - Nominated parachain
   - Nominated dApp
