### ISSUE TITLE
The account should disconnect/connect in the Manage Website Access screen when user click on the disconnect/connect icon in the Homepage screen

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#147]
**Is your feature request related to a problem? Please describe.**
The account should disconnect in the Manage Website Access screen when user click on the disconnect icon in the Homepage screen

**Describe the solution you'd like**
- When user click on the disconnect/connect icon in the Homepage -> This account automatically disconnect/connect in the Manage Website Access
- When user choose disconnect/connect account in the Manage Website Access -> This account automatically disconnect/connect in the Homepage

Notes: In case add account (create acc, import acc, restore acc) -> Default: Connected

**Comment by hieudd** [comment]
Already described in the issue #207
