### ISSUE TITLE
Re-check case stake more for pool in case have unstake request

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1470]
**Describe the bug**
Do not stake more for pool in case have unstake request

To reproduce the behavior
Steps: 
1. Perform unstake a part pooled
2. After unstaked successfully
3. Perform stake more

**Actual:** Do not stake more show error "exists unstake request"

![Image](https://user-images.githubusercontent.com/130966515/242141004-fd8b8fae-ecf9-472d-b292-4abcb9f7a98c.png)

**Comment by NamPhamc99** [comment]
Allow staking more in case has unstaking in nomination pool

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1465-build-1.0.7-0-2023-05-31T10-41-08UTC.zip

Validation passed for cases:
- stake more
- stake more in case unstake
- stake more in case unstake all

Check with TZERO & DOT token
