### ISSUE TITLE
Optimize decode contract in transaction

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1474]
This resolution in #1472 is just hot fix version, please implement full resolution to optimize EVM contract decode

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1485-build-1.0.8-2023-06-08T05-16-51UTC.zip

Validation passed for cases:
- Send token
- Send NFT
- Staking
- Connect dApp
- Sign request from dApp
- Add network, add token from dApp
