### ISSUE TITLE
Optimize require enable token in Transaction Screen

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1482]
- Only required enable network in transaction screen
- Auto enable token when get balance from transaction screen
- Update required enable token message

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1484-build-1.0.7-1-2023-06-01T10-44-44UTC.zip

Validation passed
