### ISSUE TITLE
Do not show validator on the Select validator screen in case turn on network when stake

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1496]
Show the validators list after turn on network

- Link figma: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=9138-171425&mode=design&t=XoMHlSJWHKNy3RU5-4

**Comment by saltict** [comment]
Apply logic get validators when network status changes on UI

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1727-build-1.1.5-2023-08-03T08-32-39UTC.zip

Validation passed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/09380c91-8b12-40fb-8562-3e4f69154307)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/be2925bc-b612-4430-bc30-e37210c1e4fd)
