### ISSUE TITLE
Integrate Wallet Connect

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1497]
@S2kael Please describe your plan here:
- Work with @Sokol142196 to clarify this task requirement
- What you need to implement
  - From SubConnect
  - From Wallet 
    - Core feature for Wallet Connect
    - Extension setting for Wallet Connect: Manage session ...
    - What design do you need?

**Comment by S2kael** [comment]
Having some problems with `eth_sign`, `eth_signTypedData`. Therefore, these methods are not currently supported

**Comment by S2kael** [comment]
Sign message:
  - Substrate: 
    - polkadot_signTransaction
  - Evm: 
    - eth_signTransaction
    - eth_sendTransaction

Core hasn't supported `eth_signTransaction`. Therefore, these methods are not currently supported.

**Comment by Sokol142196** [comment]
Version test:
Please check isssues:

- [ ] UI
   - [ ] Add validate for URI field
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ded3a7e9-33fe-462f-8803-fea391327968)

- [ ] Add error message in case pairing already existed.
   - Actual: Show "failed to add connection"
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d07e7abe-a9f6-4654-b284-f908e6464aaa)

   - Expect: Change to message ""

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1581-build-1.0.12-2023-07-03T11-24-46UTC.zip

- [ ] Update UI:
   - Icon connect on the Connect screen
   - UI bug when scrolling on the List connection
   

- [ ] Error page when go to the List connection after connected https://paritytech.github.io/polkadot-onboard successfully

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1581-build-1.0.12-2023-07-04T11-41-49UTC.zip

Validation passed for cases:
- Create connection
- Disconnect
- Sign request

Follow-up case auto-disconnect
