### ISSUE TITLE
Double check the self-activation of tokens based on account balance

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1500]
**Describe the task**
Double check the self-activation of tokens based on account balance

**To reproduce the behavior**
Actual:
Example: Attach address: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc
-> Don't turn on USDT (Statemint) but USDT (Astar) is shown?

**Comment by S2kael** [comment]
- Reason: Way to compare token to active is out of date:
  - Way to create token slug from indexer: `${chain}-${category === 'native' ? 'NATIVE' : 'LOCAL'}-${symbol.toUpperCase()}` 
  - But in some cases, token symbols are not all uppercase

- Resolution: Convert slugs to lowercase and compare. Use the slug that exists in the chains list as the token slug for the activity token

**Comment by ThaoNguyen998** [comment]
Version test: 
- WebApp: https://90785549.subwallet-webapp.pages.dev/

Validation passed in case:
- USDT(Statemint)
- aUSD (Astar)
- kBTC(Kinsugi)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d4a4490d-fb78-42df-85dc-5b6480b5a317)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4df4c731-c1c1-43af-b415-759883d0894d)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d6c31fc3-4561-4985-9e75-162070fd1dd2)

**Comment by ThaoNguyen998** [comment]
Version test extension: http://14.224.158.246:8900/s/ZbGwqQeccgoQdsm

- [ ] Do not turn on  USDT (Bifrost)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/3b1b0662-0f7d-42a8-965c-4c6b2fae0f2a)

**Comment by S2kael** [comment]
> Version test extension: http://14.224.158.246:8900/s/ZbGwqQeccgoQdsm
> 
> * [x]  Do not turn on  USDT (Bifrost)
> 
> ![Image](https://user-images.githubusercontent.com/117999489/283994640-3b1b0662-0f7d-42a8-965c-4c6b2fae0f2a.png)

Update chain map between wallet and Subscan:
`
  polymesh: 'polymesh',
  bifrost_dot: 'bifrost-p',
  vara_network: 'vara',
  bifrost: 'bifrost',
  creditcoin: 'creditcoin',
  joystream: 'joystream'
`

**Comment by ThaoNguyen998** [comment]
Version test: 
- Extension: http://14.224.158.246:8900/s/6jCsC8PoRAaLP9f
- WebApp: https://5a6d02bb.subwallet-webapp.pages.dev/

Validation passed in case show balance
- USDT(Statemint)
- USDT(Bifrost)
- aUSD (Astar)
- kBTC(Kinsugi)
- JOY
- CTC
