### ISSUE TITLE
Fix bug detecting on-chain attributes for WASM NFTs

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1508]
Result from the smart contract can return an object containing error

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1511-build-1.0.8-2023-06-08T04-32-54UTC.zip

Validation passed for cases:
- Import NFT
- Show NFT
- Send NFT
- Regression test with ERC 721
