### ISSUE TITLE
Update send-fund screen

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1509]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=6621-157128&t=exT8ppaI3h2PXt8i-4

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1513-build-1.0.8-2023-06-08T10-15-13UTC.zip
Please check:

- [ ] Update message on the send fund screen
   - Change to message: "You are performing a transfer of a fungible token"
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0828d000-3f75-4b8f-9d9d-f558ef48982d)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1513-build-1.0.8-2023-06-09T09-21-48UTC.zip

Validation passed
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1b1f38d5-a7db-4956-8ce4-2f900f2e090b)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/39929d2c-20c5-4fe0-9e0e-f97139509fd6)

Notes: Re-check passed for validated cases
