### ISSUE TITLE
Re-check all transaction on Westend

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1512]
**Describe the task**
Re-check all transaction on Westend

**Actual:** Transaction is failed.

![Image](https://user-images.githubusercontent.com/130966515/244274776-f2bb3f0b-45ee-4021-aa48-7b00ef36b193.png)

**Comment by S2kael** [comment]
Westend network has no new block from 8/6/2023

**Comment by Sokol142196** [comment]
Now (17/06/2023) I check again, the transaction is done successfully.
Extrinsic example: https://westend.subscan.io/extrinsic/0x285277eb4606424c91f07c1d6aae2869403dbd5f86e96bc6fc67118d9917d2f2 
=> Closed issue
