### ISSUE TITLE
Show incorrect address book type

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1524]
**Describe the bug**
Show incorrect address book type

**To reproduce the behavior**
**Steps:**
1. Go to the send fund screen
2. Input new address on the "Send to" field
3. Input valid data for remain fields
4. Click on Transfer button
5. Go to the Manage address book screen
6. Observe the address book above

**Actual:** Show address on the "Saved contact" type

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b3b5a7f7-736c-429d-a185-c71153e6e872)

**Expect:** Show address on the "Recent" type

**Comment by S2kael** [comment]
If use address to create transaction, this address move from recent to save contact type

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1540-build-1.0.9-2023-06-14T04-45-57UTC.zip

Validation passed.
