### ISSUE TITLE
Support viewing zkAssets on Manta

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1525]
https://github.com/Koniverse/SubWallet-ChainList/issues/7

- [x] Write classes to interact with WASM bindgen
- [x] Manage zkAddresses (store, generate, getter)
- [x] Optimize syncing mechanism for UTXO
- [x] Showing zkAssets on UI

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1584-build-1.0.12-2023-07-04T11-40-19UTC.zip

Validation passed for cases:
- Enable/Disable ZK mode
- Show ZK Assets
- Show warning when send Zk assets
- Get address
- Apply zk mode for multi-account in wallet
- Handling sudden sync stop (reload page, close browser, reload extension)
- Do not auto-lock while syncing
