### ISSUE TITLE
Do not sign transaction with EVM QR-signer account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1528]
**Describe the bug**
Do not sign transaction with EVM QR-signer account

**Actual:** Show error message when sign transaction with EVM Signer account

![Image](https://user-images.githubusercontent.com/130966515/245401329-b00cc091-146e-443d-bfe6-33d367961472.png)

**Comment by saltict** [comment]
Need update in mobile app when implementing as signer

**Comment by Sokol142196** [comment]
Actual: Do not support performing any transaction with EVM QR-signer account
=> Close this issue
