### ISSUE TITLE
Re-check nominated record of the Calamari network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1536]
**Describe the bug**
Re-check nominated record of the Calamari network

**Actual:** Show incorrect data on the staking detail

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7f80e073-1b30-46cc-97e9-470309a07078)

- Check with address: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc

**Comment by sokol142** [comment]
Same as https://github.com/Koniverse/SubWallet-Extension/issues/1536
