### ISSUE TITLE
Error fetching nominator data for Calamari

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1538]
Unable to see nominator data due to an error parsing identity pallet

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1539-build-1.0.9-2023-06-14T03-20-59UTC.zip

Validation passed for cases:
- Show balance
- Show staking data
- Perform stake actions
- Re-check send token

Notes: Currently Calamari has a delay of information after each action is performed.
- Reason: API's from the Calamri network is delayed.
- Solution: Implement reload button to get data (#1545)
