### ISSUE TITLE
PHA token transfer successfully but the extension infinity loading

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#154]
**Describe the bug**
PHA token transfer successfully but the extension does not turn off automatically

**To Reproduce**
See the video below:

https://drive.google.com/file/d/1m0mYt-GXSyVttosOk48T-6JKevcZfJLJ/view?usp=sharing

**Expected behavior**
When I finished transferring the token, it should show that Transfer success, and there should be a link for me to click and check on Subscan.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - SubWallet extension: Version 0.3.3

**Additional context**
Please fix it. Thanks a lot. 
Keep up the good work, guys.

Ryan.

**Comment by hieudd** [comment]
Implement in #143
