### ISSUE TITLE
Update chain-list

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#1541]
### Related

- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/43
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/70
   - Support show balance

- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/72

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1544-build-1.0.9-2023-06-15T04-01-52UTC.zip

Validation passed.
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9f902379-aede-414a-978c-6add64f433eb)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a9bda18f-d43c-4b01-ae8f-c5dd13f23958)
