### ISSUE TITLE
Improve connection status

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1554]
- Update chain status:
    - Disconnected
    - Connecting
    - Connected
    - Error (after 3 times reconnect failed)
- Update chain interaction
    - Auto re-connect
        - 1st: 3s after disconnect
        - 2nd, 3rd, 4th, 5th, 6th: interval with each 20s
        - If all of above failed => network change to unstable
        - Auto re-connect after wake up from sleep. This recover status will be reset
    - Manual re-connect
        - Update with button from balance info
        - Update from chain-manager
        - Update from chain-customization popup
- Update UI:
    - Balance Info:
        - Chain is connected: Connect with chain and fetch balance
            - Can not get balance : Show can not get balance, with button try to re-connect
        - Chain is connecting: Show connecting status
        - Chain is error:
            - Chain connection is error with button re-connect
        - Chain is disconnected: Show button enable chain
    - Update chain status icon
      - Connecting
      - Error

**Comment by saltict** [comment]
Check consisten between current design and https://github.com/Koniverse/SubWallet-Mobile/issues/786

**Comment by saltict** [comment]
Todo:
- [ ] Update connection status
- [ ] Add re-connect feature
- [ ] Update balance view for network interaction

**Comment by saltict** [comment]
All new UI exclude chain status will be move into #1597 because we need more discussion with design in this task. I will rollback these UI.
We just need test again network status in this task.

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1607-build-1.0.12-2023-07-05T18-43-14UTC.zip

Please check issues:

- [ ] Has not been automatically reconnected and changed status in the event of a mid-life loss (reproduce with Bajun network)
- [ ] Error showing network activation status in case Send fund/Staking screen is open and enable network from customize asset display screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0156309d-f099-4620-83ad-94129ce776d0)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1607-build-1.1.5-2023-08-03T05-08-19UTC.zip

Please check the issue:

- [ ] Show incorrect network on the turn-on message
  Steps:
  1. Go to the Send fund screen
  2. Select any token that is disabled
  3. Then turn on the network of the token above
  4. Open customize your assets display screen, turn on any network
  5. Observe the message displayed

  Actual: Show incorrect network on the turn-on message

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ea340ace-4885-4388-8383-905411d35603)
