### ISSUE TITLE
Show previous screen when reopening extension

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1555]
Describe the task
User feedback: 
"It was totally unusable. Copy/paste was necessary, but impossible because the extension popup was closed when switching to another window"

=> First, implement on screens:

- [x] Transaction confirmation
- [x] Send token

**Comment by saltict** [comment]
Think should implement the feature for the views containing form and QR or export result.

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1811-build-1.1.8-2023-08-17T08-32-09UTC.zip

Please check:

- [ ] UI bugs in case re-open popup after transaction successful

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/69c2346a-52b2-44eb-855f-495e341b764a)

- [ ] Still show information after approved transaction in case open both expand mode and popup mode

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/349f61cb-5c75-4c6e-8e09-5594e113e2fd)

- [ ] The Next button still disable

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7df5921b-6bde-4cd6-bb62-adf5822f4128)

- [ ] Do not save the sender, recipient?

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5a04dfd1-6a7b-41db-953f-15f1b3440e7a)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/488ae640-e8ec-45e4-9800-9b99d310cefd)

- [ ] Ui bug related to stake actions

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/cd9205bf-7f09-484a-9293-76cb967dd42d)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8d401c44-5da3-407f-aac2-534fd0c12433)


@S2kael Please double check before uploading

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1811-build-1.1.8-2023-08-18T09-37-59UTC.zip

Please check the issue

- [ ] Show the Error page
  **Steps:**
  1. Open the both expand and popup mode
  2. On the expand view: Go to the send fund screen and input valid data for the all fields
  3. Open the popup mode: Go to the send fund screen and observe the information displayed then approve the transaction
  5. Back to expand mode, perform transaction

  **Actual:** Show the error page screen
![1555_Bug](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ef95bec3-9836-4693-abef-fe3fde195d85)
  **Expect**: On the expand mode: After submit transaction (click on button Approve transaction) successful then Back to Homepage

- [ ] Do not save the state of the withdraw, cancel unstake request, claim transaction

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1811-build-1.1.8-2023-08-21T05-25-31UTC.zip

@S2kael please check this issue:

- [ ] Do not show available balance to claim the reward on pools with single account mode
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d66956af-c44d-49f0-874b-f0085d399a2c)

- [ ] Show incorrect information in case switch to expand view when standing on transaction screen
  - Expect: need to discuss more
![1555_Bug](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b0d7dc08-956b-4e92-8a36-59b4211efe87)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1811-build-1.1.8-2023-08-22T08-34-40UTC.zip

Validation passed cases:
- Transfer token transaction
- Transfer NFT
- Staking actions
