### ISSUE TITLE
Bugs related to address book

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1559]
Describe the bug

- [x] Do not move the address from Recent to Saved in case the address is address network

To reproduc the behavior: 
Steps: 
1. Go to the Manage Address book screen
2. Perform Save the Address on the Recent list and then observe the displayed screen
Actual: Duplicate Address on the list

![Image](https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/18bc1f78-e4b7-47b2-ad1e-7fb36d0cb94f)

Expect: Address move Recent to Saved

------

- [x] Show recent duplicate addresses when pasting the network address of the same account to "send to" field

   Steps:
   1. Go to the Send token screen
   2. Paste the Polkadot's address on the "Send to" field
   3. Clear address on step 2, Paste Kusama's address (2 address of the same account)
   4. Open the address book then observe the Recent list

Actual: Show duplicate

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b43ef965-9ba3-43f2-8905-f0af16f60ddf)

Expect: Show only 1 address

-----

- [x] Show the Contact Name when attach a watch-only account when address to attach same as the saved contact
   - Actual:  Show the Contact Name on account address field, but after attached successfully then show the default account name

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/49fd1db5-bc50-4c5e-9753-64a51e9ef1da)

   - Expect: Show address entered (do not show contact name)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1586-build-1.0.12-2023-06-29T09-30-36UTC.zip

Validation passed for cases 1 and 2.
@S2kael please fix the case 3 (I just added)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1586-build-1.0.12-2023-07-01T07-22-17UTC.zip

Validation passed
