### ISSUE TITLE
[Ledger] Add Aleph Zero network

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#1565]
**Is your feature request related to a problem? Please describe.**
Add Aleph Zero network

**Comment by ledgerLC** [comment]
[S2kael](https://github.com/S2kael) 

Please see the link below to our dedicated support line:

Support :( https://discord.com/invite/dBvqrrgP )

**Comment by S2kael** [comment]
At the moment, support transfer AZERO token only

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1566-build-1.0.11-2023-06-27T10-34-45UTC.zip

Validation passed for cases:
- Connect account
- Show balance
- Send fund with native token: https://alephzero.subscan.io/extrinsic/0x82f3998737d86bf0ceaae286117305ddd12729348dd7dafb898838a289b9d32d
- Send fund with PSP token, Staking, Send NFT
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6a68ce2e-6d8e-44c9-aa40-af2452a0e96d)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2f7ad24d-d197-4507-ad58-d3e18368bc5e)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0cba3e33-66a7-4a4c-b953-ba3333e7d732)

- Connect and approve request from dApp
