### ISSUE TITLE
Check the Flags attribute in the balance of Polkadot Collectives, Kusama Bridge Hub

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1567]
**Describe the task**
Check the Flags attribute in the balance of Polkadot Collectives, Kusama Bridge Hub
- What is this?
- Does it count toward the balance?
![Image](https://user-images.githubusercontent.com/130966515/248245903-6c3d31f0-ea06-41ae-94da-aaa3fb387365.png)

**Comment by saltict** [comment]
It is not related to account fungible token balance. It just a flag to mark somehing.
