### ISSUE TITLE
Leverage phishing website & addresses database to protect users

### ISSUE THREAD

**Issue by Tbaut** [Koniverse/SubWallet-Extension#157]
**Is your feature request related to a problem? Please describe.**
When a user visits a phishing website, Subwallet should redirect them and inform them, the way polkadot-js extension does

**Describe the solution you'd like**
There's a community driven repo https://polkadot.js.org/phishing/ with a list of phishing website and known scammer accounts. Talisman should leverage this database to inform users about phishing website and before sending any token to known phishing addresses.

**Comment by saltict** [comment]
Hi @Tbaut,

SubWallet for fork from polkadot-js extension and use same way detecting phishing websites with info from `@polkadot/phishing` package .

Thanks for your reminder! We will update dependencies regularly to make extension more safety.

**Comment by Tbaut** [comment]
Awesome, I did a search but somehow missed it. Thanks!
