### ISSUE TITLE
Improve UX the Ledger connection

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1573]
**Describe the task**
Improve UX the Ledger connection

**Actual:** 
- Users often encounter error "Failed to connect" when approving the transaction although still connected to Ledger

**Expect:**
- Reduce this situation => Solution: Disconnect Ledger when close connect Ledger device screen
- Update message in cases:
   - Open multi-tab: "Failed to connect, click to retry" to "Failed to connect. Please check your cable and make sure that you are connecting Ledger with only 1 browser tab."
   - Txn version not support
   - Navigate to Blind mode

**Comment by saltict** [comment]
I guess that the reason of this issue is becuase SubWallet is using the same domain index.html for expend and popup view. The solution is separate they into another view

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1575-build-1.0.12-2023-06-30T12-00-18UTC.zip

Please check: 

- [ ] Show incorrect message in case reject a transaction/ Txn version not support

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e6a7ba9f-e558-4328-bd42-8065b186252c)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1575-build-1.0.12-2023-07-05T09-57-45UTC.zip

Validation passed
