### ISSUE TITLE
Add Staking Support For Pendulum

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-Extension#1595]
**Is your feature request related to a problem? Please describe.**
Please add in-app staking support for Pendulum. Pendulum uses the same staking pallet as Amplitude (https://twitter.com/amplitude_chain)

- Pendulum docs: https://pendulum.gitbook.io/pendulum-docs/learn/readme

Let me know if you need any other information! Thank you!

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1604-build-1.1.1-2023-07-07T10-30-03UTC.zip

Validation passed (Approve step)
