### ISSUE TITLE
Import EVM tokens

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#160]
**Is your feature request related to a problem? Please describe.**
EVM networks like Moonbeam, Moonriver, Astar, Shiden have many tokens. We need some way to import them into SubWallet for display balance, transfer, swap.

**Describe the solution you'd like**
Quick upate:
- Add some common tokens into predefined network list:
  Eg: SOLAR, FLARE (Solarbeam); GLINT, SHARE(Beamswap), MFAM (Moonwell), BEANS (Moonbeans), STELLA, xStella (Stellaswap)

Longterm update:
We need to develope the feature that help user can define their token like metamask do.
This features update for EVM network and ERC20 tokens only.
Each token need to fill these info:
- isMainToken: false
- symbol
- ERC20Address
- decimals

These custom data need to be stored in chrome storage and mixed with predefined tokens => final tokens in each network.

**Comment by RyanDinh8** [comment]
Plz add xcAUSD.

https://twitter.com/MoonriverNW/status/1516149231064600583

**Comment by hieudd** [comment]
pls auto-fill Symbol và Decimal when the user fill contract address and chain information

**Comment by sokol142** [comment]
Please add "Shiden" Chain
![image](https://user-images.githubusercontent.com/102292476/167588580-6a5a0152-ca55-43db-b452-3b4b66edf6f6.png)

**Comment by sokol142** [comment]
Not show Configure EVM Token Information when re-open extension
Steps:
1. Open popup extension
2. Go to Setting > Manage EVM Tokens screen
3. Click on any token to navigate to Configure EVM Token screen
4. Turn-off popup extension
5. Reopen extension
Actual: All Information of the Configure EVM Token screen is empty
![bug_160](https://user-images.githubusercontent.com/102292476/167775349-e8caeca9-02a5-4fe1-a690-e5f1b8e471e3.gif)

**Comment by sokol142** [comment]
Bug UI
![image](https://user-images.githubusercontent.com/102292476/167776386-16ba38a4-44c6-438c-a0e5-92c0fad4a5cc.png)
![image](https://user-images.githubusercontent.com/102292476/167778049-92901a46-e325-42c0-ac05-78708d558c1c.png)

**Comment by sokol142** [comment]
Not update balance of the new tokens after transfer successfully
![Screenshot at May 11 15-04-51](https://user-images.githubusercontent.com/102292476/167800877-12fabd12-5304-4a67-9164-3cdba02506bc.png)
