### ISSUE TITLE
Improve ZK mode

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#1608]
- [ ] Metadata necessary is too heavy, it increases the size of extension by 3 times
- [ ] Heavily branched logic, need to refactor code
- [x] Causes extension to initiate incorrectly, chrome.runtime.onInstalled doesn't fire correctly

**Comment by Sokol142196** [comment]
- [ ] Show QR code for ZKAssets

**Comment by Sokol142196** [comment]
Currently does not support features related to ZK assets => Close this issue
