### ISSUE TITLE
Still showing NFTs that have been sent

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1615]
if one sends NFTs from another device, then the wallet still show those NFTs as owned

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1616-build-1.1.1-2023-07-10T05-00-38UTC.zip

I reproduce this issue when transferring NFT with Aleph Zero Testnet
=> Please re-check
