### ISSUE TITLE
Optimize ZK - Not implement in some evironement like WebApp and Mobile

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1628]
Describe the task
Optimize ZK - Not implement in some evironement like WebApp and Mobile

Expect: web-runner not include and use logic of zkAssets
- [ ] web-runner not include and use logic of zkAssets
- [ ] not show zkAssets in token list

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1637-build-1.1.1-2023-07-12T04-23-08UTC.zip

Result of rechecking ZK mode function on extension: Normal
