### ISSUE TITLE
Fix Video NFT size

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#1651]
All video are fixed with size 124: Need update to 100% view width

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1652-build-1.1.2-2023-07-17T11-42-27UTC.zip

Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0af53288-89bf-473f-a32e-74ce94401154)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a314c099-2c02-4d04-b9f1-d20b39835591)
