### ISSUE TITLE
Can not load colllection and another nft when one in collection failed to display

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1672]
Address get this problem:
- 5Hdmob81pfjKUfb3wChbTFB5GYmZ2yaVJJfphNoAcjn7rJAb

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.1.3-2023-07-24T05-30-56UTC.zip

Validation passed
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c125fe26-2029-47b0-a705-68f01d0e16cd)
