### ISSUE TITLE
WebApp - Portforlio % show incorrect

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1675]
**Describe the bug**
Portforlio % show incorrect

**To Reproduce**
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/3f1fe6a2-9f6f-4703-b093-563f10965ebf)

Expect: Confirm later

**Comment by ThaoNguyen998** [comment]
Validation passed.
 Portfolio % = $balance của token/ Total balance

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9a5e6b2b-fa7e-44c9-94e0-85ff9d1bf5de)
