### ISSUE TITLE
WebApp - Show incorrect locked balance of the account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1680]
**Describe the bug**
Show incorrect locked balance of the account

**To reproduce the behavior**
**Steps:**
1. Import/Attach an account that has balance
2. After imported successfully, observe the balance displayed

**Actual:** Show Locked balance = Transferable balance = Total balance
- Check with address: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/891dc857-5bf3-420c-9e05-4e4a02725f8d)

**Expected:** Show correct locked balance
- Total balance = Transferable balacne + Locked balance

**Comment by Sokol142196** [comment]
Version test:

**Comment by ThaoNguyen998** [comment]
Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e65035f4-d2bd-46c6-b7e9-c95468995a51)
