### ISSUE TITLE
WebApp - Re-check apply master password feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1681]
**Describe the bug**
Re-check apply the master password feature

- [x] Update UI: @roman0211 
- [x] Re-check logic: tester

Actual: Some UI bugs
![Pasted Graphic 10](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/9082fa84-c5c9-4aad-8ff8-7b8a6e29e84d)

**Comment by ThaoNguyen998** [comment]
- [ ] Update UI when apply master password

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/51908de0-a9c9-4238-84a7-fffdc24ef235)
