### ISSUE TITLE
WebApp - Show incorrect the current account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1682]
**Describe the bug**
Show incorrect the current account

**Actual:** Show incorrect "All accounts" mode and Specific account mode
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/7e6468ce-74d1-415f-a2be-ad1243450e9c)

**Expect:**

- [x] Update select box: Select network, Select account
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/12d607bb-2bb3-4b99-ba00-3c1ecf50541d)

- [x] Show correct account mode (include 2 mode):
  - [x]  All accounts: 
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/dc37b0f3-62ae-49fd-a8f5-3441fdf7a265)

  - [x] Specific account: Show 1 avatar of the account

**Comment by ThaoNguyen998** [comment]
Validation passed.
