### ISSUE TITLE
WebApp - Bugs related Manage NFT feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1683]
**Describe the bug**
Bugs related Manage NFT feature

- [x] Still, enable button Remove Collectible on the Pre-defined NFT
   - Expect: 
     - If NFT is a pre-defined NFT -> Disable button Remove Collectible
     - If NFT is a custom NFT -> Enable button Remove collectible

- [x] Error page when send NFT
![Bug_SendNFT](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/25a67775-7170-4d51-9c9b-8a89db097cf3)

- [x] Update UI for the Import NFT screens follow by design
- [x] Do not close the Import NFT screen after imported NFT successfully
   - Actual: after imported NFT successfully, do not close the Import NFT screen
![20_Bug](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/966c4f47-ddfb-48bd-afef-5e7a62237f3a)

   - Expect: Close the Import NFT screen
- [x] Still show entered data when re-open the Import NFT screen
   - Steps:
      1. Go to the Import NFT screen
      2. Input data
      3. Click on X button to close Import NFT screen
      4. Click button Import collectible to re-open the Import NFT screen
      5. Observe the screen displayed

   - Actual: Still show entered data when re-open the Import NFT screen
![20_Bug_2](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/e05aa890-3451-4d68-97d6-aa8dd6f3b6f1)

   - Expect: Reset previously entered data

- [x] Do not show Properties of the NFT
   - Check with address 0x0a7826A5ba9E119F6D2406d1d7c284F1b2fe8969

- [x] Do not show EVM custom NFT 
   - Check with address 0x40a207109cf531024B55010A1e760199Df0d3a13
   - NFT address contract: 0x5ca22CcE3aEf2caCBb4054503c503a1106050C8C

**Comment by ThaoNguyen998** [comment]
Validation passed.
