### ISSUE TITLE
Extension - Improve lock UX

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1684]
**Describe the bug**
Automatically lock the app every reload

**To Reproduce**
1. Go to the Web-app
2. Unlock app
3. Reload app
4. Observe the screen displayed

**Actual:** Automatically lock the app every reload
![9_Bug](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/aa31209a-319c-4725-afba-55b22f8ec961)

**Expect:** Do not require unlock wallet when reload page

**Solution**: Implement options on Security settings:
- Option 1: Unlock on start
- Option 2: Unlock when required (perform transaction, export account)
  - Lock button is lock both keyring and screen
    - No need to display the lock keyring status
    - When the user performs any action that requires the keyring, the enter password screen will be displayed to unlock the keyring
  - When unlock is unlock both keyring and screen

**Comment by saltict** [comment]
Can not perform as mentioned above.

Suggesstion solution:
- Unlock with popup for some view that require unlock like create password, confirmation...

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1808-build-1.1.8-2023-08-16T11-16-35UTC.zip

Please check case "when required": 

- [ ] Do not show enter password popup in cases:
  - Derive account from account detail screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1bcd6b7d-6b21-4df8-a091-bb40782ba647)

  - Import account by JSON file
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/344e5ae2-d052-422c-b781-bc0f4cd24c9a)

- [ ] Do not show err message when entering the wrong password
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/bc5e8c90-77a0-43cd-8d9d-319abeb40d1f)

- [ ] Still showing the entered password in case of closing then reopening pop-up

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1808-build-1.1.8-2023-08-17T11-40-16UTC.zip

Please check more issues:

- [ ] Do not show the select account screen to derive in case below
  **Steps:**
  1. Go to the Create a new account
  2. Select derive from an existing account option
  3. Select an account
  4. Do not enter password, click on x button to close the enter password popup
  5. Re-select the derive from an existing account option and observe the screen displaying

  **Actual:** Do not show the Select account screen to derive
![1684_Bug_2](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f9b90166-fdec-492b-90e5-166d7c5bee3d)

  **Expect:** Show the Select account screen to derive account

- [ ] Do not show enter password popup in case import account by QR code
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b0c074a2-f9ef-4fe7-ab60-b825b7ee63e2)


- [ ] Still show submitting when user closes the enter password popup
  - Expect: Enable button to click to re-open the enter password popup
![1684_Bug_3](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/aafa273d-90a3-465b-9d94-1e9f080a8061)

**Comment by saltict** [comment]
@Sokol142196, I fixed these issues. Please check it one more time

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1808-build-1.1.8-2023-08-18T09-17-34UTC.zip

Authentication passed for the above issues

Notes: Re-test after implement issue #1763

**Comment by Sokol142196** [comment]
@saltict please re-check case unlock to login in case wallet unlock type = "when need"
- Actual: Still unlock wallet when user enter wrong password

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1808-build-1.1.8-2023-08-23T11-36-35UTC.zip

Validation passed

Waiting update icon and label option
