### ISSUE TITLE
WebApp - UI bugs on the Welcome screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1685]
**Describe the bug**
UI bugs on the Welcome screen
- [x] Incorrect logo
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/92499846/34a5a3e3-813c-4803-9dba-c7292c6d4165)

- [x] Incorrect icon on the Watch any wallet!
[image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/b99fd8db-bddc-4179-a115-68ff4fbcc1f7)

- [x] Re-check focus style
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/9a18e441-099b-43a9-9a6e-28791eab0716)

**Comment by Sokol142196** [comment]
@lw-cdm please update Welcome screen follow by design after updated and confirmed:
- Login screen: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3389-204283&mode=design&t=oGVYblv0Q2PLi3wL-4
- Welcome screen: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3389-202134&mode=design&t=oGVYblv0Q2PLi3wL-4

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.7-0
Validation passed.
