### ISSUE TITLE
 WebApp - Do not attach watch any wallet from Welcome screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1686]
**Describe the bug**
Do not attach watch any wallet from Welcome screen
**To Reproduce**
1. Go to the https://web-demo.subwallet.app/welcome
2. Scroll to Watch any wallet
3. Input a valid address on the Address field
4. Click on the "Add watch-only wallet" button

**Actual:** Do not attach the watch-only wallet
![10_Bug](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/d0a1a1a4-2c43-47a9-a791-ac8bc29bea8e)

**Expect:** Attach watch-only wallet successfully
- Case 1: Created master password -> Attached successfully then switch to attached account
- Case 2: Haven't created a master password yet -> When click the "Attach" button then navigate to the Create master password; After created master password successfully, then Attached successfully then switch to attached account

**Comment by ThaoNguyen998** [comment]
Validation passed.
