### ISSUE TITLE
WebApp - UI bugs related to Add/Import/Attach account features

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1688]
**Describe the bug**
UI bugs related to Add/Import/Attach account features
- [x] Temporarily hide the option "Import multiple accounts from this seed phrase"
   - Reason: Do not implement this feature
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/f3ef7679-8658-4d3f-bcd2-29547a3db7c2)

- [x] Update Successull screen follow by design
   - Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3389-167211&t=pjzjbGc1DWroLrkK-4
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/4aef0cc5-ef0e-4414-8530-f670c9b2a268)

- [x] Bugs on Import acc by JSON 
   - [x] Update title, label
      - Change to :Import from JSON" to "Import account"
      - Change label "What is a JSON" on section 2 to "How to export your JSON backup file?"
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/e2d99b1d-77db-4770-bb7b-ad57eb6486fd)
   - [x] Update the default screen: follow the design with Import account button is disable
      - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3311-272182&t=pjzjbGc1DWroLrkK-4
   - [x] UI bug on the Import list screen   
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/eeb85360-734d-4339-9e55-cc50b7bb5093)

- [x] Do not trimspace private key
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/33a545f0-90e3-4f16-8371-292b4e73b560)

- [x] UI bug on the Scan QR code
   - Follow-up by design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3311-278775&t=pjzjbGc1DWroLrkK-4
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/ffea88e5-3d1d-4ff4-afb3-b4ed89c546cc)

- [x] Do not show logo of the Polkadot Vault 
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/37c3c0f4-b136-424b-9a1f-d49bca85544a)

- [x] Update "read-only" to "watch-only"
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/76f5af5d-bf1a-4a86-a088-422120a3f21d)

- [x] UI bug on Connect Ledger device
   - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3311-329036&t=BSHNBrofyKyBU1IL-4
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/1966f6ca-7726-4607-a2d5-09d0ae45eb27)

**Comment by ThaoNguyen998** [comment]
- [ ] Bug when removing the account in case the wallet has 1 account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/61f92f63-a77c-4e6c-ac10-78ca7cb9d8b3)

**Comment by Sokol142196** [comment]
Validation passed for the cases above.
