### ISSUE TITLE
WebApp - Bugs related to Manage network feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1696]
**Describe the bug**
Bugs related to Manage network

**To Reproduce**

- [x] Do not navigate to the Manage network when click on Manage networks button on the Customize network screen 
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/f81cb483-b455-4585-83af-e81266b0f1f0)

- [x] Chain screen title from "Manage chain" to "Manage networks"
- Update UI follow by design (move to other issue , set priority to 3): 
   - Add the Edit button
   - Manage by tab: Substrate, EVM -> move issue: https://github.com/Koniverse/SubWallet-Extension/issues/1735
   - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3460-109254&t=BSHNBrofyKyBU1IL-4

- [x] UI bug on the Manage networks screen
![image](https://github.com/Koniverse/SubWallet-WebApp/assets/130966515/ca54ec71-ec7e-4b9f-bb08-a5daf6f69230)

**Comment by Sokol142196** [comment]
Version test: v1.1.5

Please check:

- [ ] Add the Edit button
- [ ] Re-check margin
- [ ] UI bug on the add networks screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4582f2be-74ce-4f2c-b905-cf3a6e5ad035)

Notes for tester: Re-check Update, remove network after fixed the issues above

**Comment by ThaoNguyen998** [comment]
- [ ] Do no reset criteria when search network after re-open

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/44732233-c45a-44d7-a520-4624df2b8141)

**Comment by ThaoNguyen998** [comment]
- [ ] Do not delete custom network

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/b5eb435e-66f5-4fbb-8283-1849be9b5e16)

**Comment by ThaoNguyen998** [comment]
Version test:  v 1.1.6-2
Validation passed.
