### ISSUE TITLE
Import EVM Inject Object

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1710]
- [x] Auto enable if DApp is connected before
- [x] Add SubWallet to Wagmi predefined list (#1719)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1734-build-1.1.5-2023-08-02T12-46-03UTC.zip

Validation passed for cases:
- Connect dApp
- Sign request
