### ISSUE TITLE
Allow substrate Dapp subscribe allow access accounts List

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1712]
Can test this feature on: https://h9fhp8.csb.app/

**Comment by Sokol142196** [comment]
@saltict Please fix the bug:

- [ ] Do not disconnect watch-only account when the user performs disconnect all from the manage website access screen

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1713-build-1.1.4-2023-07-29T07-37-25UTC.zip

Validation passed.
