### ISSUE TITLE
Update chain-list (w31)

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1715]
**Describe the task**
Update chainlist:
- https://github.com/Koniverse/SubWallet-ChainList/issues/93
- https://github.com/Koniverse/SubWallet-ChainList/issues/83
- https://github.com/Koniverse/SubWallet-ChainList/issues/89
- https://github.com/Koniverse/SubWallet-ChainList/issues/13
- https://github.com/Koniverse/SubWallet-ChainList/issues/95

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1720-build-1.1.5-2023-08-01T08-03-40UTC.zip

Validation passed
