### ISSUE TITLE
WebApp - Can not back to the previous screen when cancel transaction

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1725]
Describe the bug
Can not back to the previous screen when cancel transaction

To reproduce the behavior
Steps:
1. Go to the NFT detail, Token detail screen
2. Input valid data for the all fields
3. Click on Transfer/Send button
4. On the confirmation screen, click on Cancel

**Comment by ThaoNguyen998** [comment]
Validation passed.
