### ISSUE TITLE
WebApp - Update UI some screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1739]
- [x] Add new provider screen

![Image](https://user-images.githubusercontent.com/117999489/258078132-7e6d277b-4ec0-4172-939f-e4e28fcc9ca4.png)

- [x] Size image NFT

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/dffa154f-5af1-4e88-ad95-9d03003c4bd0)

**Comment by Sokol142196** [comment]
Version test: https://e5887c02.subwallet-webapp.pages.dev/

Validation passed
