### ISSUE TITLE
Can not back to Welcome screen when click back on Create master password screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1740]
**Describe the bug**
Can not back to Welcome screen when click back on Create master password screen

**To reproduce the behavior**
Steps:
1. Enter address to attach watch-only account from Welcome screen
2. Click on "Create master password"
3. On the Create master password, click on Back button

**Actual:** Show the popup require create master password, can not back to Welcome screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ea47c8c8-4daa-4cd5-9619-366a9decaa6e)

**Expect:** Remove the Back button, do not allow user back

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.7-0
Validation passed.
