### ISSUE TITLE
WebApp - Error page in case Import by Json on firefox

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1741]
Describe the bug
Error page in case import from Polkadot.{js}

To reproduce the bug
Steps: 
1. Go to Welcome to Subwallet screen
2. Click on Import a account
3. Select Import from Polkadot.{js} and observe the displayed screen

Actual:

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/42d91d4f-63ca-40fc-880f-5080b541ab62)

**Comment by Sokol142196** [comment]
Do not reproduce this issue => Close issue
