### ISSUE TITLE
WebApp - Do not generate new seed phrase

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1743]
**Describe the bug**
Do not generate new seed phrase

**To reproduce the behavior**
**Steps:**
1. Go to the create new account by seed phrase
2. Observe the seed phrase
3. Add account successfully
4. After added, go to the create new account by seed phrase screen again
5. Observe the seed phrase displayed

**Actual:** 
- In Step 4: Redirect incorrect screen
- In Step 5: Do not generate new seed phrase

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4062b4ec-a045-4a3c-88eb-d69f15cb74bb)

**Expect:**
- In Step 4: 
  - If have account in wallet -> After added account then redirect to the Homepage of the account
  - If the account is the first account -> After added account then redirect to the Successful screen

- In Step 5: Generate new seed phrase to add new account

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.7-0
@lw-cdm Please re-check issue: 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/32cd4178-04bf-482f-af5c-11fa48fa690e)

**Comment by Sokol142196** [comment]
@lw-cdm @saltict I recommend creating a new seed phrase when reopening create a new account

To reproduce the behavior
Steps:
1. Choose option "Create a new account" then select "Create with new seed phrase"
2. Select account type then clcik on Continue to next step
3. Observe the seed phrase generated
4. Click on Back to step 2
5. Select account type then click Continue again
6. Observe the seed phrase generated

Actual: Do not generate new seed phrase
Expect: Generate new seed phrase (like UX in the extension)

**Comment by saltict** [comment]
@Sokol142196 I think you should create new issue with low prority for this recommendation.

**Comment by Sokol142196** [comment]
> @Sokol142196 I think you should create new issue with low prority for this recommendation.

Ok sir, i raised other issue: https://github.com/Koniverse/SubWallet-Extension/issues/1761
And close this issue
