### ISSUE TITLE
WebApp - Bug related to Staking feature

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1745]
- Do not show APY (Nampc will investigate this in #1726)
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8d2df27b-0c69-4090-9b79-4ac4d8802fc6)
- [x] UI bug when scrolling

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/372dbb25-5ca0-4515-a349-308160e765d5)

**Comment by Sokol142196** [comment]
Version test: v1.1.7-0
Please fix UI bugs more

- [ ] Ui bug when searching

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1aea7530-2682-418f-a9f3-8b3f47ff0b95)
