### ISSUE TITLE
Update Astar NFT: Astar Pass & Astar Cats

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#175]
**Is your feature request related to a problem? Please describe.**

Update Astar NFT: Astar Pass & Astar Cats
- [x] Astar Pass - Astarnaut: https://tofunft.com/vi/collection/astarnaut/items
- [x] Astar Cats: https://tofunft.com/vi/collection/astarcats/items

**Comment by NamPhamc99** [comment]
Resolved in pull request #171
