### ISSUE TITLE
Support account domain name

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1750]
Describe the task
Support account domain name
- Related issue https://github.com/Koniverse/SubWallet-ChainList/issues/40

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1768-build-1.1.7-0-2023-08-09T12-05-05UTC.zip

Validation pass for cases:
- Send fund with domain name: input domain name & input address
- Send NFT with domain name: input domain name & input address

Waiting partner feedback for case: Enter another address of the account that has registered the domain name
