### ISSUE TITLE
WebApp - UI bug header

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1751]
- [x] Bug header Account detail screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/548b60ea-1133-4326-8e17-37191b3f4c48)

- [x] Bug UI import by seed phrase  screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/04991236-e0d1-4b84-acd2-8739ff2f60c2)

- [x] Duplicate header in case access camera setting

To reproduce the behavior
Pre-condition: Do not access camera permission yet

Steps:
1. Standing on the Welcome screen (the wallet have no account)
2. Go to the import account by QR code screen or Attach Signer account screen
3. Click on Scan button
4. On the popup cannot scan, click on Go to Setting button
5. Observe the screen displayed

Actual: Show duplicate header

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/42478a30-5fef-45bd-a3c6-eafa201f19df)

- [x] Do not show title screen of the History screen in case below

To reproduce the behavior
Steps:
1. Go to the Send fund screen
2. Performed any transaction successfully
3. On the Result screen, click on "View transaction history" to go to the history screen
4. On the History screen, perform filter
5. Then switch account and obserse the screen displayed

Actual: Do not show title screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/bc91bca1-73c8-4627-bffb-f90f3c067818)

**Comment by Sokol142196** [comment]
Version test: https://e5887c02.subwallet-webapp.pages.dev/

Validation passed for 4 cases above
