### ISSUE TITLE
WebApp - Show incorrect the menu is active

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1754]
**Describe the bug**

- [x] Show incorrect the menu is active when opening the successful screen

**To reproduce the behavior**
Steps:
1. Perform send any token successfully
2. Observe the menu activing 

**Actual:** Active "Staking" menu although standing on Portfolio menu

![Image](https://user-images.githubusercontent.com/130966515/258745033-846e4897-e373-4bb6-a176-2caf3bde4690.png)

- [x] Show incorrect the menu is active when opening the account detail screen
  - Actual: Active setting menu

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2b2b9586-6536-4155-a8a4-4726d404d937)

  - Expect: Active the menu active before

- [x] Show incorrect the menu is active when import multi-account successfuly

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9d23e4c6-c4c0-4a92-b653-68cb31972cdf)

Expect: Active menu Portfolio

**Comment by ThaoNguyen998** [comment]
Version test: https://0481b418.subwallet-webapp.pages.dev/
Validation passed.
