### ISSUE TITLE
Webapp - Can not buy token from Banxa

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1760]
The main reason of this issue is Banxa block CORS access from unwanted domain

**Comment by S2kael** [comment]
Wait to merge with web app

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1786-build-1.1.7-0-2023-08-10T12-59-00UTC.zip

I did not receive the code from Banxa via email to create an order -> please re-check

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1786-build-1.1.7-0-2023-08-12T03-39-57UTC.zip

Please re-check this issue:

- [ ] Show code "something went wrong" when buy token (From the 2nd time onwards)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ffc25e5d-b036-4455-b964-8d64830cf879)

**Comment by S2kael** [comment]
> Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1786-build-1.1.7-0-2023-08-12T03-39-57UTC.zip
> 
> Please re-check this issue:
> 
> * [x]  Show code "something went wrong" when buy token (From the 2nd time onwards)
> 
> ![Image](https://user-images.githubusercontent.com/130966515/260347348-ffc25e5d-b036-4455-b964-8d64830cf879.png)


Can create 2 orders within 1 min

**Comment by Sokol142196** [comment]
> > Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1786-build-1.1.7-0-2023-08-12T03-39-57UTC.zip
> > Please re-check this issue:
> > 
> > * [x]   Show code "something went wrong" when buy token (From the 2nd time onwards)
> > 
> > ![Image](https://user-images.githubusercontent.com/130966515/260347348-ffc25e5d-b036-4455-b964-8d64830cf879.png)
> 
> Can create only 2 orders within 1 min

Thanks for feedback
