### ISSUE TITLE
Improve auto-lock feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1763]
**Describe the task**
Improve auto-lock feature

**Expect**: Add the options:
- Always require password
- Require when login

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f6af932f-3ce9-409f-af89-5c53e10d4852)

_Notes: Update to implement Master password for mobile (do not implement UI on the extension)_

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1770-build-1.1.7-0-2023-08-09T09-30-51UTC.zip

@S2kael please re-check: With option "always require" then: 
- require password when click transfer and approve transaction?
- require password after change auto-lock setting?
- do not require password in case sign transaction, sign message... from dApp

**Comment by Sokol142196** [comment]
@S2kael please list for me the locking and unlocking operations you have performed

Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1770-build-1.1.8-2023-08-12T12-38-06UTC.zip

Need to confirm:
- Lock/Unlock when show/hide balance?
- Lock/Unlock when changing the setting "show zero balance"?
- Is it possible to ask for a password when:
   - deleting an account?

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1770-build-1.1.10-2023-08-31T04-37-10UTC.zip

@S2kael Please re-check always require with sign EVM account

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1770-build-1.1.10-2023-09-05T08-42-49UTC.zip

Validation passed.
