### ISSUE TITLE
WebApp - Recheck connection status when turn on/turn off network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1769]
**Describe the task**
Recheck connection status when turn on/turn off network

**To reproduce the behavior**
**Steps:**
1. Unlock webapp
2. Go to the Network screen
3. Turn on/ turn off the network on the list and observe the connection status of the network

**Actual:** Show incorrect connection status

![Image](https://user-images.githubusercontent.com/130966515/259353107-a60c7e2b-f513-4b01-b14c-30b139aee8b5.gif)

**Comment by saltict** [comment]
Fix after change from popover display to popup display

**Comment by Sokol142196** [comment]
Version test: https://webapp-dev.subwallet-webapp.pages.dev (07092023)

This situation is almost never encountered with normal on/off cases.
However, sometimes it still happens that multiple networks are turned on continuously
Because this case rarely happens, temporarily close the task and continue monitoring.
