### ISSUE TITLE
WebApp - Re-check screen navigation

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1776]
**Describe the task**
Re-check screen navigation

**Actual:**
- Screen flickering (navigate to another screen before navigating to the correct one)
Example:
  - Navigate via URL
  - Open the import account in case do not create master password yet

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0d58add8-5175-4de8-97c0-6eff13d6a38a)

**Comment by saltict** [comment]
The problems is fixed
Another problem:
- [ ]  Can not navigate to static link with current hosting. It auto add "?" between domain and path and navigate to default link

**Comment by Sokol142196** [comment]
Version test: https://webapp-dev.subwallet-webapp.pages.dev (07092023)

Validation passed
