### ISSUE TITLE
Bug on getAddressTokens of quartz_nft

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#178]
**Describe the bug**
Quartz have update their unique API. SubWallet sill use old API and this will show error on `getAddressTokens` in folder `quartz_nft`

**Solution**
Update `getAddressTokens` use new api interface of `api.rpc.unique.accountTokens`

**To Reproduce**
1. Go to background page of extension
2. Show console
3. See error
  ![image](https://user-images.githubusercontent.com/11567273/163672610-71cca748-02a4-48f4-8238-8e15980dcd7d.png)

**Comment by hieudd** [comment]
This error is due to Unique changing their API, will reassemble after they complete the new API
