### ISSUE TITLE
WebApp - Do not show Select Import an account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1780]
**Describe the bug**
Do not show Select Import an account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/c778bd6c-8852-4003-bdd6-51a1f5b3526b)

**Comment by Sokol142196** [comment]
@ThaoNguyen998 please add the step to reproduce this bug

**Comment by ThaoNguyen998** [comment]
Version test: https://585a4183.subwallet-webapp.pages.dev/home/tokens

- [ ] Error page when create and import account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/2bc49e64-a89c-473f-b91a-3e2f95b0b517)

**Comment by Sokol142196** [comment]
> Version test: https://585a4183.subwallet-webapp.pages.dev/home/tokens Browser: Brave
> 
> * [ ]  Error page when create and import account
> 
> ![Image](https://user-images.githubusercontent.com/117999489/260357617-2bc49e64-a89c-473f-b91a-3e2f95b0b517.gif)

@ThaoNguyen998 try to reproduce this bug.
If you do not reproduce this error, please close it

**Comment by ThaoNguyen998** [comment]
Version test: https://web.subwallet.app/home/tokens
Do not reproduce this bug -> Close issue
