### ISSUE TITLE
The "All Accounts" option is not showing first in the list of accounts in Firefox browser

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1781]
**Describe the bug**
The "All Accounts" option is not showing first in the list of accounts in Firefox

Expect:
- "All accounts" always the fisrt option in list of account
- Check the sort function again

**Comment by dungnguyen-art** [comment]
In the Firefox browser:
- I observed that 'All accounts' still occupies the top position in the account list. 
- Simultaneously, I added the selected account immediately following 'All accounts' at Issue #2318  
- The current order is as follows: 'All accounts' --> 'selected account' --> and the remaining accounts are arranged in alphabetical order.
![image](https://github.com/Koniverse/SubWallet-Extension/assets/59666831/dc256083-5690-440b-8943-a21afd5214ab)
