### ISSUE TITLE
WebApp - Update basic Metadata for WebApp (for sharing, SEO...)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1783]
- Update title
- Update description
- Update preview images

**Comment by djhatrang** [comment]
- **Title**: Comprehensive Polkadot, Substrate & Ethereum wallet
- **Description**: Empower blockchain usage with a one-stop-shop for the multichain. SubWallet helps you manage your assets with full control.

**Comment by djhatrang** [comment]
Link preview image: https://www.figma.com/file/imsv2UTTYDyFhgC3OR8d7v/02.-Social-Poster-2(Dara)?type=design&node-id=5224-73159&mode=design&t=dih7Qme7iHTB69TB-4
