### ISSUE TITLE
WebApp - Bugs related to WalletConnect feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1789]
**Describe the bug**
Bugs related to WalletConnect feature

_Version test: https://dac6fba6.subwallet-webapp.pages.dev_

- [x] Do not show popup connect confirmation 
   - Actual: User inputs valid URI but do not show popup connect confirmation 
   - Expect: Show popup connect confirmation

Notes for tester: continue to test the feature after this fix

- [ ] Update UI: require design

**Comment by ThaoNguyen998** [comment]
Version test: https://456d45f6.subwallet-webapp.pages.dev/

- [ ] Still show popup when click on Create one

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e3dd84ac-7b4f-4724-9ea0-261831f5be63)

**Comment by ThaoNguyen998** [comment]
Version test: https://0481b418.subwallet-webapp.pages.dev/wallet-connect/connect

- [ ] Do not show the message in case scan QR invalid

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/0a42d603-fe73-4fe6-b0fb-fd1edd50ca70)

**Comment by ThaoNguyen998** [comment]
Version test: https://web.subwallet.app/wallet-connect/connect
Do not reproduce this bug -> Close the issue
