### ISSUE TITLE
WebApp - Bugs related to responsive UI

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1790]
Describe the bug

- [x] Welcome screen

![Image](https://user-images.githubusercontent.com/130966515/260197881-23b68001-12bf-43a0-8d4d-831de3b1730f.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://a2a4346f.subwallet-webapp.pages.dev/
Validation passed.
