### ISSUE TITLE
WebApp- Improve performance

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1794]
- [ ] Re-check performance 
  Example: Standing on History screen then filtering and switching account
  Actual: The web app is laggy
- [ ] Show incorrect filter result 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/635c94f7-0a9b-4f2b-be35-2dfec3050da9)

**Comment by saltict** [comment]
Fixed after resolve load on scroll problem and add key for filtered list

**Comment by ThaoNguyen998** [comment]
Version test: https://webapp-dev.subwallet-webapp.pages.dev/home/tokens

Validation passed.
