### ISSUE TITLE
WebApp - Implement connect with SubWallet

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1795]

**Comment by Sokol142196** [comment]
Version test: https://7786e79b.subwallet-webapp.pages.dev/

Please check:

- [ ] Do not show a popup connect wallet when clicking "Use SubWallet extension" after canceling confirmation
  Steps: 
  1. Open the webapp 
  2. Click on the Use SubWallet extension button
  3. On the popup connect wallet, click on Cancel
  4. Click on the Use SubWallet extension button again
  5. Observe the screen displayed

  Actual: Do not show popup connect wallet, user must reload page to connect

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e8a7b217-9368-4e3a-b7ec-4f32cad56c50)

**Comment by Sokol142196** [comment]
Version test: https://webapp-dev.subwallet-webapp.pages.dev (31082023)

Please check issue

- [ ] Shows the disconnect button in case the connection is canceled

**Steps:**
1. Open webapp
2. Perform connect wallet
3. Click on Cancel button in the Connect extension confirmation
4. Observe the button connect extension

**Actual:** Show disconnect wallet button although it is not connect yet

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ad8c8e8f-e297-4005-9dc3-895ed6979c5c)

Expect: Show the Disconnect button only when the extension is successfully connected

**Comment by saltict** [comment]
Cannot connect to extension in the first time open browser and open web-app immediately

**Comment by Sokol142196** [comment]
Version test: https://8f4510e3.subwallet-webapp.pages.dev/

Please check

- [ ] Show incorrect connection status when closing the connect wallet popup
- [ ] Disable the derive account option in case of only accounts connected from the extension
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1d13e7d1-336c-4d6c-b03d-408339eed23a)

**Comment by Sokol142196** [comment]
Version test: https://f5e59e75.subwallet-webapp.pages.dev/
- Version extension: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1836-build-1.1.10-2023-09-07T12-22-53UTC.zip

Please check:

- [ ] Still do not delete the connection when reset wallet

**Comment by Sokol142196** [comment]
Continue working on this issue on #1907 
=> Closed this issue
