### ISSUE TITLE
WebApp - Wrong portfolio balance UI

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#1802]
- Actual:

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/5c9977d2-d637-4e46-a2c6-46e18a64181e)

- Expect:

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/dea95c8b-0c3c-4127-b996-b9bd1ae0a58d)

**Comment by ThaoNguyen998** [comment]
Version test: https://5eb284e1.subwallet-webapp.pages.dev/home/tokens
Validation passed.
