### ISSUE TITLE
WebApp - UI bug on the Select account screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1803]
**Describe the bug**
Popup size changes when group button have 3 icons

**Actual:**
- Default: Popup size = 396 x 620

![Image](https://user-images.githubusercontent.com/130966515/260626604-56a83467-e3d8-4a3b-a4b2-ff67758dfbb7.png)

- When group button have 3 icons then popup size = 426 x 620

![Image](https://user-images.githubusercontent.com/130966515/260626562-28184c1e-0820-42d9-a4f7-f51ecd4b664e.png)

**Expect:** 390 x ...

**Comment by ThaoNguyen998** [comment]
Version test: https://a2a4346f.subwallet-webapp.pages.dev/
Validation passed.
