### ISSUE TITLE
WebApp - $value of token on History is incorrect

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1805]
**Describe the bug**
$value of token on History is incorrect:
- KMA
- NEER
- BNC
- Please re-check all tokens

![Image](https://user-images.githubusercontent.com/130966515/260657932-45624534-91af-4473-98f5-ad526f51c075.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://a2a4346f.subwallet-webapp.pages.dev/
Validation passed.
