### ISSUE TITLE
WebApp - UI bugs on the custom token detail

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1807]
**Describe the bug**
UI bugs on the custom token detail

To reproduce the behavior
1. Import custom token successfully
2. After imported successful, go to the detail screen of this token
3. Observe the screen displayed

Actual: Custom token case:
- Hide the primary delete token

![Image](https://user-images.githubusercontent.com/130966515/260666708-fb2c765b-0a76-4fb1-80e3-ce52c995564d.png)

**Comment by ThaoNguyen998** [comment]
Version test: https://0481b418.subwallet-webapp.pages.dev/
Validation passed.
