### ISSUE TITLE
[Ledger] Add support for Astar dApp Staking

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-Extension#1814]
Astar dApp Staking with Ledger is now available, please help add this support on SubWallet:
https://twitter.com/AstarNetwork/status/1691978189504172069?s=20

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1862-build-1.1.10-2023-08-29T10-10-57UTC.zip

Please check the issue:

- [ ] Expect: Disable the pool tab when clicking to start staking with Astar's Ledger account
  - Actual: Have no token to pool

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3ff0900f-0624-4938-914d-d40610423c45)


  - Expect: Disable the pool tab, navigate to the nominate tab to stake

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1862-build-1.1.10-2023-09-05T08-38-33UTC.zip

Validation passed.
The Ledger account with Astar network supported:
- View & Send token (single chain)
- View NFT
- View and stake
