### ISSUE TITLE
Fix a few minor bugs with NFT

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#1817]
- [x] Support ABI for PinkRobo
- [x] Fix bug parsing URL for some collections
- [x] Support Azero Domain NFT

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1818-build-1.1.8-2023-08-18T11-16-22UTC.zip

Validation passed
