### ISSUE TITLE
WebApp - Update collapsed mode for sidebar

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#1819]
Follow the design: 
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=9652%3A304399&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=9652%3A321197&mode=dev

**Comment by ThaoNguyen998** [comment]
Version test: https://d81f260c.subwallet-webapp.pages.dev/
Validation passed.

**Comment by Sokol142196** [comment]
@lw-cdm lw
Please update UX for sidebar: 

- [ ] Only show the icon collapsed icon when hover the sidebar

**Comment by ThaoNguyen998** [comment]
Version test: https://7fb81417.subwallet-webapp.pages.dev/
Validation passed.
