### ISSUE TITLE
WebApp - Update general modal UI

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#1820]
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3172%3A169940&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3172%3A186447&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3172%3A198046&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3196%3A97610&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3196%3A102587&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3172%3A164192&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3172%3A164596&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3311%3A436563&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3311%3A387677&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3311%3A437029&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3460%3A137666&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3267%3A82852&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3267%3A85075&mode=dev
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=3267%3A86206&mode=dev
- ....

**Comment by Sokol142196** [comment]
Version test: https://f3d1a4aa.subwallet-webapp.pages.dev/welcome

Please update more:

- [ ] Select camera modal
- [ ] Discuss more showing the toast when clicking the button in modal

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f0422eca-284b-4983-8630-aa86641228a8)

**Comment by ThaoNguyen998** [comment]
Version test: https://b2483e99.subwallet-webapp.pages.dev/

- [ ] Select camera

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/01976e3c-6e2f-4fa2-96aa-f3928a6ba3fa)

**Comment by ThaoNguyen998** [comment]
Version test: https://860b9b4f.subwallet-webapp.pages.dev/

Validation passed.
