### ISSUE TITLE
WebApp - Bug related to Authenticate with password feature in WebApp

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1826]
**Describe the bug**
Bug related to Authenticate with password feature in WebApp

_Version test: https://d81f260c.subwallet-webapp.pages.dev/_

- [x] Do not show enter password popup when creating a new account with new seed phrase

**Comment by Sokol142196** [comment]
@saltict please fix this issue early

**Comment by Sokol142196** [comment]
Version test: https://webapp-dev.subwallet-webapp.pages.dev (24082023)

Validation passed
