### ISSUE TITLE
WebApp - Add the tooltip for icon button without text

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1831]
**Describe the task**
Add the tooltip for icon button without text

- [x] Sidebar toggle button

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/1a1bd126-74eb-46dd-8f81-ce27698c1d3d)

 
- [x] Show/hide balance button

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/451753a8-f6ea-4ddb-8915-0adc7f20aaeb)

**Comment by ThaoNguyen998** [comment]
- [ ] Add a tooltip
  - [ ] Receive
  - [ ] Send
  - [ ] Buy
  - [ ] Show zero balance
- [ ]  Update Receive icon to Copy button
- [ ] Update text from "Receive" to "Address"

**Comment by ThaoNguyen998** [comment]
Version test: https://ffd4259e.subwallet-webapp.pages.dev/home/staking

Validation passed.
