### ISSUE TITLE
Integrate Coinbase Pay fiat on-ramp feature

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#1834]
**Describe the solution you'd like**

Please integrate Coinbase Pay fiat on-ramp solution:
- https://docs.cloud.coinbase.com/pay-sdk/docs/intro
- https://github.com/coinbase/cbpay-js#react-native-example

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1876-build-1.1.10-2023-09-06T08-24-56UTC.zip

Please check:

- [ ] Incorrect URL when click on Coinbase hyperlink in the Disclaimer screen
  - Actual: Redirect to Banxa homepage
  - Expect: Redirect to Coinbase homepage (https://www.coinbase.com)

- [ ] Update logo for Coinbase: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=1510%3A27&mode=design&t=AyZ6qfuUpW3OuCNJ-1

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1876-build-1.1.10-2023-09-07T08-29-25UTC.zip

Validation passed
