### ISSUE TITLE
WebApp - Add tabs for Crowdloans, Staking, History

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1840]
**Describe the task**
Add tabs for Crowdloans, Staking, History

- Crowdloans with All, Active and Winner tab
- Staking with All, Pooled and Nominated tab
- History with All, Tokens, NFT, Staking tab

**Comment by ThaoNguyen998** [comment]
Version test: https://860b9b4f.subwallet-webapp.pages.dev/home/crowdloans

Validation passed.
