### ISSUE TITLE
WebApp - Update token list (Hompage) by new design

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1845]
**Describe the task**
Update token list (Hompage) by new design
- [x] Update network count / name only (if there is only one network) below token name
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/b37cbb0a-e579-4f67-8b8f-8551a0d89c5b)
- Update logos with count and animation (when hovering)
  - [x] logos
  - [x] animation  (when hovering)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/c189fc72-121f-4f1f-9f9d-1059dae23a71)

**Comment by haiyenvu23** [comment]
Version test : https://55ca5d29.subwallet-webapp.pages.dev/home/tokens
Validation passed in case : 
- All account mode
- Specific account mode
![image](https://github.com/user-attachments/assets/195143b8-7423-460a-9cfb-86e67bc093fa)
![image](https://github.com/user-attachments/assets/6da0503a-c553-43b0-a5c8-6286f4453b65)
- Improve UI in case responsive => Related to issue #3424
