### ISSUE TITLE
Re-check the service to get the transaction history

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1846]
**Describe the task**
Re-check the service to get the transaction history

Actual: Do not get history from end of June
_- Notes: Check with BD account (5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc) on Polkadot_

# Solution:
- Update background logic: 
  - Get and save history from Subscan with input background & subscan keys
- Update UI:
  - Add button get history from subscan or "not found you history?"
  - Open popup fetch popup (address, network, fetch_buttons)

**Comment by saltict** [comment]
Wait for update new data explorer from subsquid

**Comment by saltict** [comment]
Resolve and update in 1846

**Comment by Sokol142196** [comment]
> Resolve and update in 1846

@saltict please kindly check cause this issue is 1846
