### ISSUE TITLE
Update list of tokens supported on fiat-onramp feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1848]
**Describe the task**
Update list of tokens supported on fiat-onramp feature

**Comment by S2kael** [comment]
[result.zip](https://github.com/Koniverse/SubWallet-Extension/files/12557230/result.zip)

List tokens update

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1887-build-1.1.10-2023-09-08T08-08-56UTC.zip

Please check:

- [ ] Incorrect token when buying a token with Transak
  - NEAR
  - XRP
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ae2c36ad-8b5f-48ab-b312-321483af0644)

  - Re-check BUSD (Binance smart chain)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/085e9e0d-3b2f-4ca3-8bf4-b257fb0a0efb)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1887-build-1.1.10-2023-09-09T05-14-00UTC.zip

Validation passed

**Comment by S2kael** [comment]
[compact.csv](https://github.com/Koniverse/SubWallet-Extension/files/12565347/compact.csv)

Final token list
