### ISSUE TITLE
UI bug on the Buy token screen on the Firefox browser

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1849]
**Describe** the bug
UI bug on the Buy token screen on the Firefox browser

![Image](https://user-images.githubusercontent.com/130966515/263576677-99ba85c6-acda-42da-8cbb-6543499e9d66.png)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/86iEAFn2YAjjAWY

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/702601e5-4329-4554-a220-a83f172ab523)
