### ISSUE TITLE
Integrate aUSD and USDT on Bifrost

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#185]
**Is your feature request related to a problem? Please describe.**
Bifrost has announced a bi-directional cross-chain of $USDT
[https://twitter.com/bifrost_finance/status/1514964495499620352](url)

**Describe the solution you'd like**
Please add USDT and aUSD cross-chain tokens on Bifrost to SubWallet.

**Comment by NamPhamc99** [comment]
Bifrost on Polkadot has not supported these tokens yet

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./543-merge-build-0.5.5-1660623430987.zip
![image](https://user-images.githubusercontent.com/102292476/184868758-4ce584f5-33b0-4b62-82f8-c5acf443c57c.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./543-merge-build-0.5.5-1660707692026.zip
Validation passed!

![Image](https://user-images.githubusercontent.com/102292476/185035348-bc5bcadb-659e-45a4-ac56-57738e774e94.png)
