### ISSUE TITLE
WebApp - Add sub-logo to staking list

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1855]
**Describe** the task
- [x] Add the sub-logo 

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3cec026e-4168-411c-b55e-d79fc5374dc5)

**Comment by ThaoNguyen998** [comment]
Version test: https://860b9b4f.subwallet-webapp.pages.dev/home/staking

Please re-check this issue: Do not add sub-logo

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/eee10a9a-97aa-47e0-98fc-e9c51d16c4cd)

**Comment by ThaoNguyen998** [comment]
Version test: https://airlyft.one/subwallet/claim-free-azeroid-domain-with-subwallet-1692956681969

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/1b2e93c6-989b-4a9e-b870-b677fa2c2ee8)
