### ISSUE TITLE
WebApp - Incorrect navigation when remove all accounts

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1858]
**Describe the bug**
Incorrect navigation when remove all accounts

_Version test: https://75a5d968.subwallet-webapp.pages.dev/_

**Steps:**
1. Perform remove all accounts
2. Observe the screen displayed

**Actual:** Do not navigate to the Welcome screen (naviate to https://75a5d968.subwallet-webapp.pages.dev/)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2551b78f-e238-4cf7-a9f1-17acba077605)

**Expect**: Navigate to the Welcome screen: https://75a5d968.subwallet-webapp.pages.dev/welcome

**Comment by ThaoNguyen998** [comment]
Version test: https://e134650e.subwallet-webapp.pages.dev/welcome

Validation passed.
