### ISSUE TITLE
Re-check status of the crowdloans item

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1860]
**Describe the bug**
Re-check status of the crowdloans item

**Actual:** Do not show status 
- Check with address 5HMkyzwXxVtFa4VGid3DuDtuWxZcGqt57wq9WiZPP8YrSt6d

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ff4d2fc3-3bb8-4fc8-9b47-46b7d41795bd)

**Comment by saltict** [comment]
Add acala to the winner with fixed value. Check paid status.

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/Nagmf77CiLAyHrQ

Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6dd77530-4e13-4656-855c-1ddad3c9e342)
