### ISSUE TITLE
WebApp - Some UI bug

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1863]
- [x] Show popup action on the confirmation screen (Solution: change from popover to modal)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/0dc7f281-a9df-4c6c-8874-8dd500bbb832)

- Do not turn off toast in case Import Token successfully (follow up)
Version test: https://860b9b4f.subwallet-webapp.pages.dev

- [x] Update max width for Select account Selectbox
  - Expect: max width = 208px
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d4a9f125-6e7d-47dd-bcfd-0a42eff42c6b)

**Comment by ThaoNguyen998** [comment]
Version test: https://e4c48712.subwallet-webapp.pages.dev/

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/7642fd83-1a6f-48a2-acbd-c067dc6b8ad7)

**Comment by ThaoNguyen998** [comment]
Version test: https://028fa0c2.subwallet-webapp.pages.dev/home/tokens

- [ ] Do not show the Account name in case have 1 account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/f8e9bf6a-c476-45e9-ba5a-699f851dc24a)

**Comment by Sokol142196** [comment]
Version test: https://f9802de6.subwallet-webapp.pages.dev/
Fix some UI bugs:

- [ ] Space on the button in case loading


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/88e8b665-3041-4aea-8b4b-0b9eac5857d0)

- [ ] Content position on empty screens

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e28029f8-f1ac-41b9-bfd3-c4b96016c0ff)

**Comment by lw-cdm** [comment]
- [X] Error happens when reloading NFT detail (both collection and item)

**Comment by Sokol142196** [comment]
Version test: https://fc5c507b.subwallet-webapp.pages.dev/

@lw-cdm please re-check font-size on the create new account screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b30f64b6-a44c-45c2-b404-38562ecde780)

**Comment by Sokol142196** [comment]
> Version test: https://e4c48712.subwallet-webapp.pages.dev/
> 
> * [ ]  Do not turn of toast
> 
> ![Image](https://user-images.githubusercontent.com/117999489/264542149-7642fd83-1a6f-48a2-acbd-c067dc6b8ad7.png)

@ThaoNguyen998 I can't reproduce this issue, please reproduce this issue on the newest version.

**Comment by ThaoNguyen998** [comment]
> > Version test: https://e4c48712.subwallet-webapp.pages.dev/
> > 
> > * [ ]   Do not turn of toast
> > 
> > ![Image](https://user-images.githubusercontent.com/117999489/264542149-7642fd83-1a6f-48a2-acbd-c067dc6b8ad7.png)
> 
> @ThaoNguyen998 I can't reproduce this issue, please reproduce this issue on the newest version.

I can't reproduce this issue on the newest version -> Close issue
