### ISSUE TITLE
WebApp - Do not derive account in case below

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1864]
**Describe the bug**
Do not derive account

**To reproduce the behavior**
Steps:
1. Open the web-app (keyring is locked)
2. Go to the account list, click create a new account then choose "Derive from an existing account"
3. Select account 
4. Do not enter password then choose "Derive from an existing account" again
5. Enter valid password then observe the screen displayed

**Actual:** Do not derive account
- User must choose parent account to derive again

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7a6facc4-1ffd-46b0-8beb-1698cc0cba4d)

**Expect:** After enter password successfully then derive account immediately

**Comment by ThaoNguyen998** [comment]
Version test: ttps://bf9af435.subwallet-webapp.pages.dev/

Validation passed.
