### ISSUE TITLE
Change appear of manage network and account selector from popover to modal

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#1865]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/26600344-ab9f-4855-bb45-0fc1f7569365)

**Comment by Sokol142196** [comment]
Version test: https://c6e67155.subwallet-webapp.pages.dev/

- [ ] Please check UI bug when search

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6f3e439b-e9b7-4632-8721-d576e033b71e)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c7a65ddb-9a84-41dc-a68c-3d634f3c0afa)

**Comment by ThaoNguyen998** [comment]
Version test: https://bf9af435.subwallet-webapp.pages.dev/

Validation passed.
