### ISSUE TITLE
Handle the case of signing transactions from dApp using a Ledger account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1874]
**Describe the task**
Handle the case of signing transactions from dApp using a Ledger account

**To reproduce the behavior**
Pre-condition: SubWallet extension has Ledger account

**Steps:**
1. Open SubWallet Webapp (https://webapp-dev.subwallet-webapp.pages.dev/home)
2. Connect to the SubWallet extension successfully
3. After connecting successfully, make a transaction with another token than the network that the account is supporting
4. Sign the transaction with SubWallet extension and observe the transaction result

**Actual:** Transaction failed
**Expect:** Show message do not support transaction

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1892-build-1.1.10-2023-09-08T10-57-08UTC.zip

Validation passed.
