### ISSUE TITLE
Keep update webapp with newest version of extension

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#1889]
Required test most of feature of webapp

**Comment by Sokol142196** [comment]
Version test: https://fb316069.subwallet-webapp.pages.dev/

Please check:

- [ ] Do not create new account
![Bug_create account](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/67e377a2-60aa-40cd-9f6b-5fd78c41f470)

- [ ] Change popover to Modal for select type in case of imported account by seed phrase
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/262b5f8a-de71-46d2-90e4-75ef98f2fbcd)
