### ISSUE TITLE
WebApp - The display is very slow when opened for the first time

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1902]
**Describe the task**

- The display is very slow when opened for the first time -> Will resolve in https://github.com/Koniverse/SubWallet-Extension/issues/3343

_Example with Account detail screen_

![Image](https://user-images.githubusercontent.com/130966515/267206278-b2a72c88-823f-43c2-aa81-1b450eba457a.gif)

- [x] Do not open the NFT detail in case NFT loading
- [x] Do not open Statistic tab when update web app version or opened on the first time

**Comment by Sokol142196** [comment]
Note for tester: Re-check:
- NFT collection list
- NFT list
- NFT details
- Search on NFT collection and NFT list
- Navigate

**Comment by haiyenvu23** [comment]
Version test : https://98fd360e.subwallet-webapp.pages.dev/home/tokens

- [ ] Can't open NFT details


![Image](https://github.com/user-attachments/assets/2fe0014a-a091-4578-bd62-4fbd68e583a0)

**Comment by haiyenvu23** [comment]
Version test: https://80d45a9c.subwallet-webapp.pages.dev/home/nfts/item-detail
Validation passed in case : 
- Test on Chrome, Firefox
- Responsive
- NFT collection list


![Image](https://github.com/user-attachments/assets/85d6e1f3-db0e-44e9-be29-6ff38c928d18)


- NFT list


![Image](https://github.com/user-attachments/assets/3821a460-fd7a-4098-82d0-bececd9fdfcb)


- NFT details


![Image](https://github.com/user-attachments/assets/659c013a-dde7-43a1-ae77-befab9799a5d)


- Search on NFT collection and NFT list
- Navigate
- Show static tab


![Image](https://github.com/user-attachments/assets/45be2b61-8844-4247-b93c-0839ab9995c1)
