### ISSUE TITLE
Improve Amount input field

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1905]
**Describe the task**
Improve the Amount of input field
- [x] Can not enter "0." 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/eb543e75-17f8-4d7f-9339-d16ba8243be0)

- [x] Can not input Amount < 1 when do not select account yet

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6ed6cf34-b640-4413-b59e-5d16ed8c236c)

**Comment by dungnguyen-art** [comment]
Handle case Can not enter "0." (task 1)
In case you haven't selected an account, because I can't get decimals, I disable the input amount form. (task 2)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/LDse9TJCGGtJraD

- [ ] Disable the input Amount in case do not select account yet when Transfer, Staking
Actual: Hide the input amount 
Expect: Disable the input Amount
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/443991af-0c54-4d97-9b14-e87ba0bc50da)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/Ja9DTxFkNMyW5KH

- [ ] Enter "0." : Passed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0c24cd1d-8483-47b7-9d1d-a06bb7c25ee9)



- [ ] Disable the input Amount in case do not select account yet when Transfer : Passed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e790e965-d9a2-41a5-bcfb-2dd4504c2472)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/HgKRRdpHJmXKgQg
Validation passed in case : 
- Install/Update version 
- Enter "0." on Transfer, Stake, Unstake screen 


![Image](https://github.com/user-attachments/assets/64e00ea6-929e-487c-9869-b8cbb3d4cd9b)

- Disable the input Amount in case do not select account yet




![Image](https://github.com/user-attachments/assets/61e6a617-2b42-4c73-a8f8-6e92f4d2994e)
