### ISSUE TITLE
Improve connect extension feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1907]
**Describe the task**
Improve connect extension feature

- [x] Do not close confirmation popup on WebApp when sign transaction with extension in case network is disconnected/ fee

- [x] Do not show confirmation popup when sign transaction with extension on WebApp -> https://github.com/Koniverse/SubWallet-Extension/issues/2501

- [x]   Sometimes the connection popup is not displayed when performing connection extension -> https://github.com/Koniverse/SubWallet-Extension/issues/2120

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2e9c171a-e0c1-49bb-b694-80e2904c80ac)

  https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a347d183-0916-4778-8aa9-d7419d1e4c86

--------
### WalletConnect

- [x] Handle case 0 networks connected
  - Actual: Still show connect but show error message

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7f35aa42-d9a4-4e72-8505-9ce9a859532f)
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/05769be0-3e65-4c83-ab55-3fa97dd3d080)

  - Expect: Update UI follow case Unsupported network https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=8205-353076&mode=design&t=CwnUFsfSaoYu4Na8-4 
  

- [x] [WebApp] Detect account name of the EVM accounts after connected successfully

--------
Improve later

- [x] [WebApp] Handle case forget site in extension

    - Actual: Still show connected status
  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6fbac03e-b50d-448a-9190-427ef3a38100)

    - Expect: Show disconnect status
   
- [x] [WebApp] Case: Do not have account in wallet (Talisman, Polkadot js)

    - Actual: Can not show wallet and do not show message to user
    - Expect: Show message to warn to user
      - Example: 

   ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5c559ca6-3a4d-4172-9aa3-63edabbbb150)

**Comment by haiyenvu23** [comment]
Version test : https://e2a0a2e7.subwallet-webapp.pages.dev/home/tokens

- [ ] Re-check list account connect with extension in case disconnect wifi

**Comment by haiyenvu23** [comment]
Version test : https://12c1113e.subwallet-webapp.pages.dev/home/tokens

- [ ] Re-check case connect with Talisman 


![Image](https://github.com/user-attachments/assets/99c6681b-e72d-45b7-8295-d3e4dccad753)

**Comment by haiyenvu23** [comment]
Version test : https://27ebe059.subwallet-webapp.pages.dev/home/tokens
Validation passed in case : 

-  In Case: Do not have account in wallet (Talisman, Polkadot js)


![Image](https://github.com/user-attachments/assets/eda24fd7-11ae-4e99-bc3b-f7600f7322ae)

- Do not close confirmation popup on WebApp when sign transaction with extension in case network is disconnected/ fee




![Image](https://github.com/user-attachments/assets/d7c720e9-16d8-4f9d-978e-db7e7f63e521)

- Detect account name of the EVM accounts after connected successfully


![Image](https://github.com/user-attachments/assets/6b09398c-c8a7-429a-a810-7db45d165ca6)

- Handle case forget site in extension


![Image](https://github.com/user-attachments/assets/d6946f35-8669-4096-bde1-e5505bb67980)
