### ISSUE TITLE
Handle the case of auto lock after import multi account

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1910]
**Describe the bug**
Handle the case of auto lock after import multi account

**To reproduce the bug**
Pre-conditon: Config Require unlock = Always
Steps: 
1. Go to Import account screen
2. Perform import multi account successfully

Actual: Do not auto lock master password

Expect: Auto lock master password after import account successfully

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/sPcE8KMo8jdwsgb

@S2kael please hide the Always require option on the extension before merging.
@ThaoNguyen998 re-check this feature after implementing for the mobile app

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/tS6DxYC3qMPtnMP

Validation passed
@S2kael please hide the "Always require" option on the extension before merging.
