### ISSUE TITLE
WebApp - Update UI for import account by seed phrase and import account by private key

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1914]
**Describe the task**

Update UI for import account by seed phrase and import account by private key
  - Import by seed phrase: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3290-90202&mode=design&t=yzsrmH0ixDiSI1xC-0
  - Import by private key: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3311-248577&mode=design&t=IjV2fwA36rnmLqi0-0

- [x] Other: Change popover to Modal for select type in case of imported account by seed phrase
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/262b5f8a-de71-46d2-90e4-75ef98f2fbcd)

**Comment by Sokol142196** [comment]
Version test: https://webapp-dev.subwallet-webapp.pages.dev/ (15/09/2023)

Please check:

- [ ] Still allow submit when do not select account type

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/004acf8c-eb91-40ef-a4dc-b1f9eaae1f5a)


  - Expect: Disable button import when do not select account type

**Comment by Sokol142196** [comment]
Version test: https://c2000a84.subwallet-webapp.pages.dev/

Validation passed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e0b2c752-91ff-4908-a455-506bce33e618)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/11e1dcf1-c58c-40b3-9310-01ee3c0496d9)
