### ISSUE TITLE
WebApp - Not show selected account on header when choose all account and list account have one account only

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#1919]

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/dnoy8ZpQxHdFzgK

Please check:

- [ ] Switch account incorrect after import account in case have no account in wallet
  - Actual: Switch to Substrate account
  - Expect: Switch to All accounts 
![1919_Bug](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1d901597-77c9-48ae-8c33-38e512a7b854)

**Comment by Sokol142196** [comment]
Version test: 
- Extension: http://14.224.158.246:8900/s/pjTs6waEmWETZrp
- Webapp: https://1a6409ed.subwallet-webapp.pages.dev/

Validation passed for this case
