### ISSUE TITLE
Extension error when entering Substrate's seed phrase but selecting EVM account

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#192]
**Describe the bug**
Extension error when entering Substrate's seed phrase but selecting EVM account

**To Reproduce**
1. Go to the extension
2. Click on Import account from Seed Phrase
3. Add seed phrase and choose EVM
4. See an error

**Expected behavior**

**Screenshots**

![275949068_744789120225918_3744247984074862296_n](https://user-images.githubusercontent.com/2582652/163850870-3a87d703-11ee-404d-aade-035d6cf6690d.png)
![277865742_557629982339011_836809212678724383_n](https://user-images.githubusercontent.com/2582652/163850875-5b5a7ed6-6980-448a-aa89-f941ff80902f.png)
![277682984_690111868903188_6963969606329143744_n](https://user-images.githubusercontent.com/2582652/163850877-fd14f810-6fda-416c-a88d-3c4b70b5fbfa.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Comment by saltict** [comment]
@daodinhhieu seed phase can use for both Subtrate's account and EVM account.
@Quangdm-cdm let check something wrong and fix it.
