### ISSUE TITLE
Update entered address on the transaction confirmation

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1923]
**Describe the task**
Show the entered address on the transaction confirmation

**Actual:** Detect to 5x address
Expect: Show network's address
- If user input recipient = Substrate address then show message "Recipient should be a valid [Network name] address"

- [x] Round 1: Apply for transfer token, transfer NFT feature (Input screen, Confirmation screen, History screen)

**Comment by haiyenvu23** [comment]
-  Show network address on NFT detail screen


![Image](https://github.com/user-attachments/assets/d394dd5b-149a-479f-ac5d-de2baa9b032a)
- Show substrate network when copy/paste on Address book

![image](https://github.com/user-attachments/assets/a69ae0f8-1ebf-417f-844c-d3f9919c30f7)

=> Related to issue #3573
