### ISSUE TITLE
Re-check the border on Window OS after updating to the latest browser version

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1928]
**Describe the task**
Re-check the border on Window OS after updating to the latest browser version

![Image](https://user-images.githubusercontent.com/130966515/268556349-daaf2202-6bba-4f87-9da5-f94bac8df5d8.png)

**Comment by S2kael** [comment]
This cannot be controlled. It is completely controlled by the browser
