### ISSUE TITLE
Collect NFT on Singular.app but it doesnt show on SubWallet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#194]
**Describe the bug**
Collect NFT on Singular.app but it doesnt show on SubWallet. I tried reload the extension many times but still cant see that NFT on SubWallet.

**To Reproduce**
Please see the video:
https://drive.google.com/file/d/13KeJ5MgJ3nembJWcFyQvYxmhawyw48Tc/view?usp=sharing

**Screenshots**
<img width="1279" alt="Screen Shot 2022-04-19 at 16 05 25" src="https://user-images.githubusercontent.com/102496727/163970051-8271fa1a-ef89-40ab-abb2-ec0772c358c1.png">

**Desktop (please complete the following information):**
 - Macbook
 - Browser: Brave and Chrome
 - Version: 0.3.5

**Comment by NamPhamc99** [comment]
Bug due to pinata server, consider building a dedicated pinata gateway
https://docs.pinata.cloud/gateways/dedicated-gateways
