### ISSUE TITLE
[Ledger] Support connect Ledger device for more chains

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1942]
**Describe the task**
Support connect Ledger device for more chains:

- [x] Karura (KAR): https://github.com/Zondax/ledger-karura
- [x] Edgeware (EDG): https://github.com/Zondax/ledger-edgeware
- [x] Shiden (SDN) - this is EVM
- [x] xx network (xx): https://docs.zondax.ch/ledger-apps/xxnetwork/supported_1.202.x
- [x] Polymesh (POLY): https://github.com/Zondax/ledger-polymesh
- Centrifuge: Currently, I see some applications that cannot be integrated => integrate later
- Darwinia (RING): No application found, only token information on ETH
- Energy Web Chain (EWT): integrate later

**Comment by djhatrang** [comment]
- [ ] Karura (KAR)
- [ ] Edgeware (EDG)
- [ ] Shiden (SDN) - this is EVM
- [ ] xx network (xx)
- [ ] Energy Web Chain (EWT)
- [ ] Polymesh (POLY)
- [ ] Darwinia (RING)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/RL5J3YZRKHkRXno

Please check:

- [ ] Re-check case transfer native token (KAR) of the Karura network
  - Actual: Show message "Method not supported" although transfer local token (NEER) successfully

Notes:
- Waiting for updated Edgware network to testing

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/fQACcSkkrL9ESfn

Validation passed in case: 

- Acala
  - Show balance
  - Send token: Transfer, Transfer all
