### ISSUE TITLE
Add "Token Name" to the Token Details and Import Token screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1946]
**Describe the task**
Add "Token Name" to the screens:

- [x] Token Details: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3312-238367&mode=design&t=M9dTXPQ5OHGlgkt5-4
- [x] Import Token: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1901-54480&mode=design&t=M9dTXPQ5OHGlgkt5-4
- [x] Select token: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1774-56639&mode=design&t=M9dTXPQ5OHGlgkt5-4

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/T7wS2etGd4bD2Sg

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/5a2fd029-6152-44cd-9862-0d7f778dfd34)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/22467ff0-a916-4bc1-8187-6126993018ad)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6be63826-d553-4319-b4db-6cd86edcaf4e)
