### ISSUE TITLE
Update token logo retrieval mechanism

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1947]
**Describe the task**
Update token logo retrieval mechanism

**Actual:** detect logo by symbol, but some tokens have the same symbol
**Solution:** Detect by slug

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/t67cwRGgqH6qamn

- [ ] Re-check the logo of the TAO (Bittensor) token

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/44b986d3-1778-404d-a898-5d8a0b0dd46f)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/6oScnRHFT7otWkJ

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a707e4d7-9911-43c2-a457-9173a63d0235)
