### ISSUE TITLE
WebApp - Navigate incorrect in case back to Import account

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1958]
Describe the bug
Version test: https://fcc535f4.subwallet-webapp.pages.dev/

To reproduce the bug
Steps: 
1. Go to Import account -> Import from seed phrase
2. Click on Back button
3. Observe the displayed screen

Actual: Back to Select account type screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9d2c4ccd-592a-498e-a69a-2f625e05d5d3)

Expect: Back to the previous screen
- In case of large screen (desktop, laptop): Back to the Import account (select import method screen)
- In case mobile screen (iPad, mobile): Back to the Select account type screen

**Comment by S2kael** [comment]
Currently, the logic is divided by UI (Extensions and WebApp).
On the Extended UI, use the state by selecting the type of method stored in storage.
On the WebApp UI, use the local state on the screen

**Comment by Sokol142196** [comment]
Version test: https://09a66e58.subwallet-webapp.pages.dev/

Validation passed in cases:
- Large screen: Back to select import account method
- Small screen (web mobile): Back to Select account type
![1958_Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/12248d90-278e-4f33-8ba9-5fe0bab41bd7)
