### ISSUE TITLE
WebApp - UI bug on DApps screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#1977]
- [x] Re-check the width of the textbox

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/45e2eb19-eafa-42ee-a1e3-20e2dedd135b)

- [x] Redirect to Homepage when switching acc
  - Expect: Still standing on dApp screen when the user switches account

- [x] UI bug on the small screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/45fb3b50-c97f-4eef-9cae-569e5c1f0bd2)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b1f47b5c-af20-4ad5-b4bc-6821b48ada6a)

**Comment by Sokol142196** [comment]
- [ ] @lw-cdm please update the scrolling area
  - Actual: Users must point their mouse in the middle of the content to scroll

**Comment by Sokol142196** [comment]
Version test: https://2b0b9d5a.subwallet-webapp.pages.dev/

Validation passed.


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/54765a8a-99ab-41f1-805b-cefcf2fd1e61)
