### ISSUE TITLE
Integrate Snowbridge bridge features: ERC20 <=> Polkadot token transfer

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#1984]
**Is your feature request related to a problem? Please describe.**

The Snowbridge team has successfully tested bidirectional ERC20 token transfers between Rococo and Goerli. They will enable testing for other parachains soon. Please do research and integrate their solutions

- https://forum.polkadot.network/t/update-on-snowbridge/3902
- https://docs.snowbridge.network/applications/token-transfers
- https://www.youtube.com/watch?v=wq8SAg2TjKY

**Comment by nampc1** [comment]
Added these tokens:
https://docs.google.com/spreadsheets/d/1D3sJWxHQZBipNhqjAZUDRlGrQCTPW8nS3r7ZNUsL904/edit?gid=1523240658#gid=1523240658

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/qfjfFR5RFRQ2iFA

Validation passed in cases:
- XCM WETH: Rococo Asset Hub <-> Ethereum Sepolia
- Re-check WETH, WBTC: PAH <-> Ethereum (Approve step)
- Re-check all validate on Send fund feature
