### ISSUE TITLE
WebApp - Need to switch to the account in case connect to extension with only 1 account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1988]
**Describe the task**
Need to switch to the account in case connect to extension with only 1 account

**Actual:** Switch to All account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5513edb2-a844-4743-afad-c108ed1efd90)

**Expect:** Switch to specific account

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/AmHC5rXeHPwzQqR

Validation passed.
