### ISSUE TITLE
Bug IPFS in Firefox browser

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1995]
**Describe the task**
Bug IPFS in Firefox browser

**Actual:** Do not show NFT of some NFT collection
_Example: Check with Sub0 NFT in the account 5DcW42REUeTLySnuhG3ob8H6SPoVYMk73uZ1unKfRTg8hJdB_
- Console log

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9f1d869f-176b-4576-9731-c80197e2a4ac)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/Jo2348KLmGntGc2

Validation passed.
