### ISSUE TITLE
Update the Token detail screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#1997]
**Describe the task**
Update the Token detail screen
- Design link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=11742-356846&mode=design&t=eXhEkcONDhlXK3mv-4
- Component link: https://www.figma.com/file/mfCcK60D4OWv42MlVvrJF4/SubWallet-UI-Base-1.0.1?type=design&node-id=3590-23741&mode=design&t=MhTv9PnES3XK9qc2-4

**Comment by S2kael** [comment]
`
  kintsugi: ['kintsugi', 'interlay', 'kintsugi_test', 'mangatax_para'],
  genshiro: ['genshiro_testnet', 'genshiro'],
  equilibrium_parachain: ['equilibrium_parachain'],
  bifrost: ['bifrost', 'acala', 'karura', 'acala_testnet', 'pioneer', 'bitcountry', 'bifrost_dot', 'hydradx_main', 'pendulum', 'amplitude'],
  statemine: ['statemine', 'astar', 'shiden', 'statemint', 'moonbeam', 'moonbase', 'moonriver', 'crabParachain', 'darwinia2', 'parallel', 'calamari'],
  kusama: ['kusama', 'kintsugi', 'kintsugi_test', 'interlay', 'acala', 'statemint', 'karura', 'bifrost'] // perhaps there are some runtime updates
`

Account pallet: ngoại trừ các group kintsugi, genshiro, equilibrium_parachain (pallet bao gồm logic tính locked balance từ nomination pool) (pallet chỉ tính được native token)
Token pallet: gồm các group bifrost và kintsugi (pallet sử dụng để tính local token là chủ yếu) ( với kintsugi, pallet này tính cả native token)
Asset pallet: gồm các group statemine (pallet chỉ sử dụng để tính local token)
EqBalances pallet: gồm các group genshiro (pallet sử dụng để tính local token và native token)
EQ System account pallet: gồm các group equilibrium_parachain (pallet sử dụng để tính local token và native token)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/cLK9YMHXfWFJRCq

Please check issues:

- [ ] Show Balance = NaN with cusom token in case Balance = 0
  - Check with PANX on Aleohe Zero Testnet _(contract address: 5DGHdeY4SXsZ2w8RZrgXXJwHXXe2Qg8LCnUoDTr3tnBnu2BC )_ 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b6d767ea-6bdb-422b-a2fb-3cbeb9fb1b1f)

- [ ] Still showing Ledger account in Token details screen of tokens not supported on Ledger account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4812cd22-72d7-47ad-96fb-7b79e8565e0c)

**Comment by Sokol142196** [comment]
Discuss more https://github.com/Koniverse/SubWallet-Extension/issues/1574

**Comment by Sokol142196** [comment]
Version test: 

- [ ] Update some UI
  - [ ] Fix the height of the Token details popup
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f1937e91-15d5-486b-a63a-f273224c889a)

  - [ ] Sticky tabbar 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/643a8427-3af1-49f6-9672-de746b8a3d5c)

- [ ] Show address by network
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7c938196-4df1-4ea8-94ba-a67aa15b2e86)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/SXiNKTgqAgWzmWy
- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4b83f87f-6545-4eb2-b113-7956d5cc9db3)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/AqrAtjSYcFwwM5s

@S2kael please check the issues:

- [ ] Sort accounts by balance in descending order

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/838aaeb0-e14e-435e-a684-f1a46babd104)


- [ ] Update token details pop up in case of specific account mode, follow the image below
  - Notes: "All accounts" mode should be left intact

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1049ac43-eff0-4be4-96f0-2ca71994fbf5)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/trWpaTgXFmHQQST

Validation passed all these case
