### ISSUE TITLE
Support QR code signer such as Stylo and Parity Signer

### ISSUE THREAD

**Issue by Tbaut** [Koniverse/SubWallet-Extension#2]
Hello,
I've seen a video of Subwallet, and it's impressive, you've done a great job.
As a user, one thing that I would like to request is to keep the integration with QR code signer, that are [Parity Signer](https://github.com/paritytech/parity-signer/) and [Stylo](https://github.com/stylo-app/stylo). These are among the most secure wallets to keep your seed-phrase in, and keeping the integration with them would be greatly appreciated.

**Comment by saltict** [comment]
Hello Tbaut,
Thanks for your suggestion, it's great. I will discuss with the team to include it in the product development roadmap.
Looking forward to hearing more from you!

**Comment by Tbaut** [comment]
Please don't let me create a bot to comment on this every 21 days :)

**Comment by saltict** [comment]
Hi Tbaut, sorry about that.

**Comment by hieudd** [comment]
Implement in #150
