### ISSUE TITLE
[Yield aggregator] Bugs related to the earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2005]
Describe the task

- [x] Update data:
- Earning pools screen:
  - [x] APY
  - [x] Total staked
- Staking information
  - [x] Unlock period
  - [x] Reward distribution
  - [x] Minimum active
- Manage earnings:
  - [x] Unclaimed rewards
  - [x] Token conversion rate to check Estimated receivables value

- [x] Handle cases where accounts do not support actions (Watch-only account, Ledger account)
  - Expect: 
    - Support Ledger account for nomination pool
    - Do not support Ledger account for the remain type; When click on stake actions then show error message
    - For Ledger account: Shows only networks that Ledger supports on the Staking information screen and Staking calculator screen
  - Notes: Handle case All accounts mode

- [x] Update UI of the Empty earning pools
  - Refer to other empty screens

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/04c7c86a-e2c5-4030-a8d0-0c8f920988a1)

- [x] Handle case subscribe when turn on/ turn off network
  - Actual: Do not Westend's earning item although turning on (It has to be shown many times to get it right)

- [x] Still allow stake more in case withdraw all with nomination pool
  - Actual: Still allow stake more then transaction failed
  - Expect: Show error message

- [x] Still show earning item on the list after withdrawing all

- [x] Filter incorrect on the Manage earning screen
  - Actual: Filter result always empty

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a53f091e-fb1f-499b-9841-09c73560b1d5)

- [x] An error occurs when earning (2 steps, all validate passed)
  - Input: Amount = 20, DOT (Parallel) = 88.06, DOT (Polkadot) = 9.064, PARA = 240667
  - Actual: An error occurs
![1955_errorpage](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/42570231-1579-471f-ac23-a90aef6d82e9)

- [x] Discuss more validation for XCM transfer
- [x] Improve: when reloading the page then redirect to the Earning
  - Actual: Redirect to the Portfolio screen
  - Expect: Redirect to the Earning screen

- [x] Check case get information retrieval after x (seconds) on the earn screen
![1955_BugReload](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/139d5f29-7d80-450e-9d8a-f0cac2f3c1f3)

- Showing incorrect earning pools in case of only EVM accounts in All accounts mode -> https://github.com/Koniverse/SubWallet-Extension/issues/2127
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/59a9097e-ccd3-4a4e-ad18-23aa00035734)

- [x] Re-check case withdraw: https://bifrost.subscan.io/extrinsic/0x789dc1fcd7d351a239d303eedf4f8fa85353f0687069a6e7f23bbf9e58266bd2
  - Actual: Transaction failed and UI bug on history screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b19a1e71-ded0-44d3-a661-989413651ba1)

- [x] The reward claim button is disabled even though there are unclaimed rewards

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5c437af6-cecf-434b-bc03-91a044b9a7ec)

- [x] Discuss more the showing of the earning value
  - Actual: Amount input = 1 DOT (Interlay), but the earning value displayed = 49.77 DOT after earning successfully
  - Extrinsic hash: https://interlay.subscan.io/extrinsic/0xd9c26562a2ecd95fd1765c6057541e23adf74d3d5e6ff541bddc72a0cd1a69b3 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/43d7aa67-305d-4f35-a108-0d648157c82a)

- [x] Decimal separator character

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c7727c96-f0b8-4f47-9df2-dda6beda0812)

- [x] Link to doc FAQs when click on Help button
  - Link doc: https://docs.subwallet.app/main/web-dashboard-user-guide/earning/faqs
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3b15f2ef-e907-4749-896b-ceb62e7ff0cb)

- [x] Fix content: https://www.notion.so/subwallet/Fix-content-for-Earning-page-5306cff08b1f48c48cc7ae27bc3a757a?pvs=4

**Comment by Sokol142196** [comment]
@S2kael please fix bug Claim reward when All accounts mode
- Actual: 
    - Do not show the account to select to claim rewards
    - Incorrect title screen
![2005_ClaimRewards](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1ea62436-2f6e-4ab9-a08f-83e6f799c194)

**Comment by NamPhamc99** [comment]
- [ ] Add unstaking period to Earning info modal
- [ ] Add min stake to Earn screen
- [ ] Add min unstake to Withdraw screen

**Comment by Sokol142196** [comment]
- [ ] Add the Estimated receivables on the History detail screen

**Comment by NamPhamc99** [comment]
- [ ] Show DOT (Polkadot) balance in Earning screen

**Comment by ThaoNguyen998** [comment]
- [ ] Error page in case turn off the network when opening Earn screen

https://github.com/Koniverse/SubWallet-Extension/assets/117999489/380f36e8-f98c-46e5-b82b-96663a5523d4

**Comment by NamPhamc99** [comment]
- [ ] Change disclaimer text in Earning screen
- [ ] Change step explanation text in Earning screen
- [ ] Update Error text
