### ISSUE TITLE
WebApp - Handle case responsive

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2014]
**Describe the task**
Handle case responsive:

- [x] Crowdloans page: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=11334%3A258545&mode=design&t=NxzchbvvSaVxvL5g-1
- [x] Earning page: 
  - Grid for list earning pools (refer Mission Pools)
  - Design responsive: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=12205-203953&mode=design&t=Er3krwW10JUUwxXD-4

- [x] Earning demo: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=12069-167479&mode=design&t=KA8PbMaDtRiE8rqw-4

- [x] Mission Pools: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=12121-442987&mode=design&t=nuK6ymfW6JXRxMOg-4
- [x] Add the dApps and Mission pool to menu
- [x] dApp: follow-up by mobile app

**Comment by ThaoNguyen998** [comment]
Follow up: https://konistudio-my.sharepoint.com/:w:/r/personal/nhungphung_koni_studio/_layouts/15/Doc.aspx?sourcedoc=%7B82DD2E97-52A3-42F4-B8ED-F990FC1F6CC7%7D&file=Responsive_WebApp.docx&action=default&mobileredirect=true

**Comment by ThaoNguyen998** [comment]
Version test: https://45ef0fc3.subwallet-webapp.pages.dev/home/tokens

- [ ] Duplicate banner

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/65a78ebb-7496-4495-8972-277883597862)

- [ ] UI bug on mobile 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/48ed5dcc-70e2-45a6-b958-79fdeb803d40)

**Comment by Sokol142196** [comment]
Version test: https://6df83167.subwallet-webapp.pages.dev/

Validation passed in these cases
