### ISSUE TITLE
WebApp - Bug related to Safari browser

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2015]
Describe the bug
Version test: Version 15.6.1 (17613.3.9.1.16)
Bug related to Safari browser

To reproduce the bug

- [x] Can't perform an action when Earning
Steps:
1. Open the Earning screen
2. Perform any action (Earning/ Withdraw/ Unstake)
3. Input valid data field
4. Click the Submit button and observe the displayed screen
Actual: Show message

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d64b820a-3228-4afd-9197-1a6531e100a1)

Note: Re-check in case Send fund 
- [x] UI bug

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/082056c4-e6f1-46ac-b904-efb277796e86)

- #2211
![2015](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/fc591cc8-9f45-48e2-909c-815bf4de712d)

**Comment by Sokol142196** [comment]
Version test: https://webapp-dev.subwallet-webapp.pages.dev
_- Safari version: Version 16.4 (18615.1.26.110.1)_

I can't reproduce the transfer error and UI error on Watch-Only Attachments account but there are other UI errors

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/07255486-6434-4cfc-b40a-107010fba717)

@ThaoNguyen998 Please check again for these errors and provide the version of Safari on your device

**Comment by ThaoNguyen998** [comment]
> Version test: https://webapp-dev.subwallet-webapp.pages.dev _- Safari version: Version 16.4 (18615.1.26.110.1)_
> 
> I can't reproduce the transfer error and UI error on Watch-Only Attachments account but there are other UI errors
> 
> ![Image](https://user-images.githubusercontent.com/130966515/278526892-07255486-6434-4cfc-b40a-107010fba717.png)
> 
> @ThaoNguyen998 Please check again for these errors and provide the version of Safari on your device

Safari version: 15.6.1 (17613.3.9.1.16)
Version test: https://webapp-dev.subwallet-webapp.pages.dev/home/tokens

Can't reproduce the bug when performing the transaction (Can't perform an action when Earning)

**Comment by Sokol142196** [comment]
Version test: https://22b51b57.subwallet-webapp.pages.dev
Safari version: Version 16.4 (18615.1.26.110.1)
Verify passed for these cases.
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0f71f6bc-e42d-4f17-9e53-0681afe37e42)

@ThaoNguyen998 please check more in your device with other Safari version

**Comment by ThaoNguyen998** [comment]
> Version test: https://22b51b57.subwallet-webapp.pages.dev Safari version: Version 16.4 (18615.1.26.110.1) Verify passed for these cases. ![image](https://user-images.githubusercontent.com/130966515/285094089-0f71f6bc-e42d-4f17-9e53-0681afe37e42.png)
> 
> @ThaoNguyen998 please check more in your device with other Safari version

Version test: https://22b51b57.subwallet-webapp.pages.dev/
Safari version: Version 15.6.1 (17613.3.9.1.16)

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d016e2f1-d543-4e65-b897-ace7b0fc65bf)
