### ISSUE TITLE
[Yield aggregator] Update Exclusive reward tag

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2018]
**Describe the task**
Update Exclusive reward tag
- Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=11337-265967&mode=design&t=L1ZeXgo8yIHhVDb2-4 
- Link component: https://www.figma.com/file/mfCcK60D4OWv42MlVvrJF4/SubWallet-UI-Base-1.0.1?type=design&node-id=2466-34989&mode=design&t=6CNrbfKiubxZwcZ4-4

When hover tag then show tooltip.
- Tooltip content: https://github.com/Koniverse/SubWallet-Extension/issues/2018#issuecomment-1761401346

**Comment by katehasw** [comment]
Tooltip content

16 Oct - 23 Oct: Exclusive rewards will be available from 24 Oct 2023, when #StakeDOT #EarnMany campaign gets started. Stay tuned!

From 24 Oct: 
Acala: Stake and share a reward pool of 80K ACA when stake from 24 to 31 Oct!
Bifrost: Stake and share a reward pool of 5K BNC when stake from 24 to 31 Oct!
Parallel (TBC): Stake and share a reward pool of 1M PARA when stake from 24 to 31 Oct!

**Comment by djhatrang** [comment]
Revised tooltip content

16 Oct - 23 Oct: Exclusive rewards will be available from 24 Oct 2023, stay tuned!

From 24 Oct:
Acala: 80K ACA reward pool available from Oct 24 to Nov 7! More details (hyperlink to FAQ)
Bifrost: 5K BNC reward pool available from Oct 24 to Nov 7!! More details (hyperlink to FAQ)
Parallel: 1M PARA reward pool available from Oct 24 to Nov 7! More details (hyperlink to FAQ)

Link FAQ: https://docs.subwallet.app/main/web-dashboard-user-guide/earning/faqs#exclusive-rewards

**Comment by Sokol142196** [comment]
Version test: https://yield.subwallet.app/

Validation passed
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2a77ae88-768b-4aae-8b41-e21a69363005)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/261dd2fe-d184-49a7-934d-b86731d70f43)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/94dd5641-b660-4b36-800d-1a59d856a5fe)
