### ISSUE TITLE
Hide the AutoSelect validator/collator/dApp button if this method is not supported

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2020]
**Describe the task**
Hide the AutoSelect validator/collator/dApp button if this method is not supported

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/240f3361-0563-4765-aaa5-2a5224b1e7f3)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/oGoGAWdiyGHEGY8

- [ ] Hide the AutoSelect validator/collator/dApp button with Nominate staking

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/3325fe71-a27a-4c7d-a966-e77b5074fcfa)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/qftqo6es8jfnK3F

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/b4f27dbc-8c59-4f55-b071-6cb9cd18c11d)
