### ISSUE TITLE
Don't load web app in the In-App Browser on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2022]
**Describe the task**
Don't load web app in the In-App Browser on mobile app

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/49781a23-80ef-4b60-a810-767c63503649)

**Comment by ThaoNguyen998** [comment]
Version test: https://webapp-dev.subwallet-webapp.pages.dev/home/tokens
Device test: Samsung S20 FE 5G

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/c9b3994a-10c1-481f-ba25-45df358cbdb4)
