### ISSUE TITLE
Sorting the token list to buy

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2025]
**Describe the task**
Sorting the token list to buy
- Sort by Network status and DOT in top for Substrate account
- Sort by Network status and ETH (Ethereum) in top for EVM account

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/FfzrDteJZbrDQrj

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8961a484-f637-473f-b79b-ceefaae8859c)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/edQAJArp4zc6Hcr

- [ ] Please re-check ordinal
  - Actual: Order incorrect (do not order by ordinal) 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2edbf3b9-136d-4554-8664-7335a1bc6a1a)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/gnqg2coGDJMDeEb

Validation passed
