### ISSUE TITLE
Updated list of tokens supported by Transak

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2026]
**Describe the task**

- [x] Updated list of tokens supported by Transak

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5ff66f34-49a7-49bc-906c-dde1073688b5)

- [x] Re-check Banxa and Coinbase Pay

**Comment by S2kael** [comment]
[compact.csv](https://github.com/Koniverse/SubWallet-Extension/files/12926207/compact.csv)
