### ISSUE TITLE
Update online token list for fiat-onramp feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2031]
**Describe the task**
Update online token list for fiat-onramp feature

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/FfzrDteJZbrDQrj

Validation passed./
@Sokol142196 Please help me re-check this issue

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/dyKCNNJKfL2XXWL

- [ ] Wrong network status detected
  - Actual: Network is inactived (not active yet) but extension show "The chain is disconnected"
  - Expect: Show popup turn on network

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/gnqg2coGDJMDeEb

Validation passed
