### ISSUE TITLE
WebApp - Support Connect More Wallet

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2032]
- Design https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=12148%3A83175&mode=design&t=sQcXWs0XmAYzB1RD-1
*** Add support SubWallet Mobile

**Comment by Sokol142196** [comment]
Version test: https://c5ff8660.subwallet-webapp.pages.dev/

Please check the issues:
- [ ] Still shows EVM account even though disconnected extension successfully in case have only connected account
  - Reproduce with Talisman extension

- [ ] Confirm UX
  - Case: Do not have account in wallet (Talisman, Polkadot js)
  - Case: Disconnect extension
  - icon to distinguish connected extensions
