### ISSUE TITLE
Extension - Update crowdloan data

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2035]
Update data for crowdloan on extension. UI with more info will be update later

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/5tgxzTFC4dsbq3B
- Check with address: 1CDTs83GrViMyHRnLnWon7SSvVwXfDxFmMMu6s1DHwKh2W9

Please check:
- [ ] Show incorrect data of the same chain
  - Do not show parachain
  - Do not show token

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/240e2629-4121-49bf-88c6-01d643da4c81)

- [ ] Do not show project of the Kusama parachain
- [ ] Show incorrect in case have multiple aution on the same network

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3a5d052d-d068-475b-8799-e4c7b9e82b39)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/ySE2gmYJiN84pze

Validation passed for crowdloan data
