### ISSUE TITLE
[Grab 100M DOT] Exclusive rewards calculation

### ISSUE THREAD

**Issue by katehasw** [Koniverse/SubWallet-Extension#2037]
**Context**
In Stake DOT Earn Many campaign, users who stake or supply to pools listed on SubWallet earning page from Oct 24, 2 AM UTC to Oct 31, 11:59 PM will have the chance to share a pool of exclusive rewards.

**Business requirement**
Calculate stake/supply amount to each protocol in 6 protocols (Polkadot nomination pool, Acala, Bifrost, Interlay, Parallel, Moonwell) from Oct 24, 2 AM UTC to Oct 31, 11:59 PM

Terms
- Users must be Polkadot Power Staker NFT owner (Which means they stake to these protocols on SubWallet earning page at least 1 time)
- Calculate independently on each protocol. 
For example, a user stakes for Acala, Bifrost, Parallel. We need to identify the amount this user stakes for each protocol from Oct 24, 2 AM UTC to Oct 31, 11:59 PM

**Timeline**
We need this information before Nov 7 to start distributing rewards to users from Nov 15

**Comment by Sokol142196** [comment]
Exported file
