### ISSUE TITLE
Improve notification/banner in app feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2038]
Please implement the tasks:
- [x] Handle case update and remove campaign
- [x] Still shows the popup even though the user has interacted with the popup

https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2ff53c8a-a258-4140-a03f-83e917bb1e7d

**Comment by S2kael** [comment]
- [x] Handle case update and remove campaign

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/acBREwQKjZbj3BQ

Validation passed in cases:
- Update banner campaign
- Delete campaign

on both mode: install and upgrade version
