### ISSUE TITLE
Update Crowdloan UI in home page

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#2041]
Refer this design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=11359-280034&mode=dev

**Comment by Sokol142196** [comment]
Version test: https://50f89b8e.subwallet-webapp.pages.dev/
- [ ] @lw-cdm update the filter of the crowdloan screen

- Expect: Filter by crowdloan status (In Aution, Won)
