### ISSUE TITLE
WebApp - Recheck logic calculate the Staking value on the Statistics

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2047]
**Describe the task**
Recheck logic calculate the Staking value on the Statistics

Actual: Calculate to "Other" value when have earning
Expect: Calculate to "Staking" value when have earning

**Comment by haiyenvu23** [comment]
Version test : https://c96bbb0e.subwallet-webapp.pages.dev/home/statistics

- [ ] Re-check on All account mode

**Comment by haiyenvu23** [comment]
Version test : 
Validation passed in case : 
- Responsive
- Show % on Porfolio allocation 


![Image](https://github.com/user-attachments/assets/f6492036-0885-4446-9a5b-ffeeb47e4a4f)



![Image](https://github.com/user-attachments/assets/186c0fda-9762-44a4-b1dc-36e3b43cb02e)

- Show transferable and other
Account : 5FbZsh8jpUDkdFespENFZcxgfRSBwYv2J4h6L1Ukjdic2vdN


![Image](https://github.com/user-attachments/assets/789c44de-e40e-49e8-98b4-77f5f3e38f74)

- Show staking
Account : 5FjsfciyUnuN7DRDsqWkbQeoTdVLeaotj4ZxWZ4eAC9uXdh9


![Image](https://github.com/user-attachments/assets/5536b7d2-fbd4-45d2-9826-02e622c2d52b)


- Show other
Account : 5FSZxR4XM2V6bpRYL93ayebnJ3G12xaHCb8LvS6h4RT9dzVJ


![Image](https://github.com/user-attachments/assets/ed19a346-d82f-4077-9281-667583b85ae1)



- Show transferable , staking, other
Account : 5CFh4qpiB5PxsQvPEs6dWAhzgAVLHZa8tZKxeE9XsHBg4n9t


![Image](https://github.com/user-attachments/assets/78ad3ef3-9f85-49c6-b3a1-662e1801404d)

- All account mode 


![Image](https://github.com/user-attachments/assets/7745cdc2-ae2b-47ca-bccc-e04aa1b9b517)
