### ISSUE TITLE
Handles the case of accessing specific features via URL

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2051]
**Describe the task**
Handles the case of accessing specific features via URL

- [x] Welcome screen: /welcome
  - Expect:
    - If have account -> Auto redirect to the Homepage screen
    - If have no account -> Redirect to the Welcome screen

- [x] Migrate master password: /keyring/migrate-password
  - Expect:
    - If have account need to apply master password -> Auto redirect to the Homepage screen
    - If have no account need to apply master password-> Redirect to the Welcome screen

**Comment by ThaoNguyen998** [comment]
Version test: https://375e5c29.subwallet-webapp.pages.dev/home/tokens

Validation passed on WebApp

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/1b259743-a253-450f-a45d-51b2c5b7e482)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/LzLLKcCA6222e4Z

Validation passed on Extension.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a4975c29-e96e-4389-8ef0-c02ed376fece)
