### ISSUE TITLE
Re-check for WalletConnect connection loss

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2052]
**Describe the task**
​Handle WalletConnect reconnection case

**Actual**: If the previous connection fails, subsequent connections will still fail
**Expect**: Allow reconnect successful

**Comment by S2kael** [comment]
Solution:
- Subscribe connection status of relayer, try to reconnect if connection stalled

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3275
