### ISSUE TITLE
WebApp - Show create master password screen when reset wallet

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2056]
**Describe the task**
Show create master password screen when resetting wallet in the case connected with extension

**Reproduce the behavior**
Steps:
1. Performing connected extension successfully
2. After connect successfully, perform reset the wallet
3. Observe the screen displayed

**Actual:** Show the create master password screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/cb92e9f2-3499-4d3b-910d-a30447fd51b6)

**Expect:** Show the Welcome screen

**Comment by ThaoNguyen998** [comment]
Version test: https://c23b2978.subwallet-webapp.pages.dev/welcome

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/78ec8606-e3dc-48d2-ac58-036f62c3e514)
