### ISSUE TITLE
Website access wrong logic

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#207]
**Describe the bug**
Website access wrong login 
*This bug should be resolve in #469*

**To Reproduce**
1. Go to SubWallet
2. Click on Setting
3. Go to Manage Website Access

**Note**

Check the case of Issue #147

**Expected behavior**
Display uniformity between the list of accounts that allow Dapp connection and the display status of the acc when accessing the Dapp website

**Screenshots**
<img width="1437" alt="Screen Shot 2022-04-24 at 10 39 35 PM" src="https://user-images.githubusercontent.com/2582652/164985417-a48542a7-0c73-4f7c-82ea-024af0c9da9c.png">
<img width="1438" alt="Screen Shot 2022-04-24 at 10 38 59 PM" src="https://user-images.githubusercontent.com/2582652/164985426-586184d8-c72f-456d-8746-f7fba2222152.png">

**Desktop (please complete the following information):**
 - OS: All OS
 - Browser: All browser

**Comment by saltict** [comment]
This bug should be resolve in https://github.com/Koniverse/SubWallet-Extension/issues/469
