### ISSUE TITLE
Redirect to Homepage when click on SubWallet icon on sidebar

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2071]
**Describe the task**
Redirect to Homepage when click on SubWallet icon on sidebar

![Image](https://user-images.githubusercontent.com/130966515/277556415-fd5bd6fc-6c43-4ead-a439-58b0a5f8a444.png)

![Image](https://user-images.githubusercontent.com/130966515/277556612-28e380d6-01fa-4060-92bf-c22e0e4c123a.png)

**Comment by ThaoNguyen998** [comment]
Version test: http://192.168.10.155:9000/home/tokens

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d3100abd-8d89-49f3-bef2-4fe7c483e510)
