### ISSUE TITLE
WebApp - Add support connect mobile wallet

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2073]
**Describe the task**
Add support connect mobile wallet

- [x] SubWallet mobile: auto inject
- [x] Nova wallet

**Comment by djhatrang** [comment]
Please also add support for Nova Mobile. 
Docs: https://docs.novawallet.io/nova-wallet-wiki/misc/developer-documentation/intergrate-nova-wallet

**Comment by ThaoNguyen998** [comment]
Version test: https://pr-2084.subwallet-webapp.pages.dev/welcome

- [ ] Don't navigate the app store when the device doesn't have the app

https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e51a168d-1517-4b65-8647-51873ca740d3

- [ ] Show modal create master password

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8827b1e9-0cbd-48b9-a5d5-cb75549cc58b)

- [ ] Change title Connect extension -> Connect wallet

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6fff7f63-3fc3-4f80-8b5a-ab6787b2a433)

**Comment by Sokol142196** [comment]
Version test: https://a7e5288a.subwallet-webapp.pages.dev/

Please check the issues:

- [ ] Do not create new account when connect wallet in case have only 1 type account

To reproduce the behavour:
Pre-condition: Mobile wallect has only Substrate account
Steps:
1. Open the mobile app
2. Open the browser tab then visit https://a7e5288a.subwallet-webapp.pages.dev/
3. Perform connect wallet

**Actual:** Can'r create one new EVM account when clicking on the Create one button on the popup
  - Record file: https://a7e5288a.subwallet-webapp.pages.dev/

**Expect:** Allow create on new EVM account on mobile app

**Comment by Sokol142196** [comment]
Bugs related to this feature https://github.com/Koniverse/SubWallet-Extension/issues/2103
