### ISSUE TITLE
Obtaining Ledger account addresses on incompatible networks is not allowed

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2075]
Describe the task
Obtaining Ledger account addresses on incompatible networks is not allowed

**Comment by ThaoNguyen998** [comment]
Version test: 
Extension: http://14.224.158.246:8900/s/QxqsxeAdYaqBxSk
Webapp: https://798c5fdf.subwallet-webapp.pages.dev/

Validation passed.
