### ISSUE TITLE
Improve import Private key feature

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#208]
**Is your feature request related to a problem? Please describe.**
Improve import Private key feature:

- [x]  Auto-add 0x to private key export from Metamask
- [x] Alert when user add Seed Phrase to Private key box

**Comment by sokol142** [comment]
Can't import private key, please check!
![Bug_208](https://user-images.githubusercontent.com/102292476/168419095-89b5098f-e750-4aaa-add8-f266799b44e4.gif)
