### ISSUE TITLE
WebApp - Improve UI for mobile

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2086]
- [x]  **1.** Remove auto-focus in NFT, History on mobile
- **2.** Fix modal height in mobile:
  - [x] Select Account
  - [x] Customize network
  - [x] All select modal
-   [x] **3.** Add enter trigger on screen create master password
- **4.** Data on the search box is being reset when expanding or shrinking the screen size 
  - Haven't had solution for this yet
- [X] **5.** Improve in case the screen has 1 banner (DApp)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a306f908-6d96-4b31-8801-410a62dc6acb)

- [x] **6.** UI bug in search hasn't data
![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8e5288c6-b43a-42f5-b984-4ea2950b78f0)

- [x] **7.** Hide tooltip on mobile
![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9bc9267d-4a46-4c06-aef4-b2937685127d)

-  **8.** UI bug when scrolling on the Homepage screen(Token Detail)
     - Will be fixed in #2104

**Comment by ThaoNguyen998** [comment]
Version test: https://59aabbab.subwallet-webapp.pages.dev/

- [ ] UI bug 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/7527d73a-aa4c-4e1c-bbb8-250dfeaf94fa)

**Comment by Sokol142196** [comment]
Version test: https://ecf25797.subwallet-webapp.pages.dev/home
Continue troubleshooting in https://github.com/Koniverse/SubWallet-Extension/issues/2141
