### ISSUE TITLE
An error occurred when transferring XCM USDT (Parallel --> Statemint)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2091]
**Describe the task**
An error occurred when transferring XCM USDT (Parallel --> Statemint)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0a7b15d0-ddf8-4618-8d71-37be9734a220)

Error: createType(Call):: Call: failed decoding xTokens.transfer:: Struct: failed on args: {"currency_id":"u32","amount":"u128","dest":"{\"_enum\":{\"__Unused0\":\"Null\",\"V2\":\"XcmV2MultiLocation\",\"__Unused2\":\"Null\",\"V3\":\"XcmV3MultiLocation\"}}","dest_weight_limit":"{\"_enum\":{\"Unlimited\":\"Null\",\"Limited\":\"SpWeightsWeightV2Weight\"}}"}:: Struct: failed on dest: {"_enum":{"__Unused0":"Null","V2":"XcmV2MultiLocation","__Unused2":"Null","V3":"XcmV3MultiLocation"}}:: Cannot map Enum JSON, unable to find 'V1' in __unused0, v2, __unused2, v3
    at Le (461.js:2:376064)
    at wa.createTypeUnsafe (461.js:2:426568)
    at o (461.js:2:600296)
    at Object.r [as transfer] (7941.js:2:581710)
    at background.js:1:104447
    at W (background.js:1:104869)
    at async we.makeCrossChainTransfer (background.js:1:130599)
    at async we.handle (background.js:1:172664)
(anonymous) @ background.js:1

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/CJGck8bbq4WSmnc

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ced818f1-2b86-4bf3-83e8-a2f68fd05dec)
