### ISSUE TITLE
WebApp - Occasionally an error occurs when accessing web app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2094]
**Describe the bug**
Occasionally an error occurs when accessing web app

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/883e13b4-c023-4db5-8c0a-84dedee5d0bd)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/56dfb40d-9dee-4353-b4c1-9b5ea3c6cf2c)

**Comment by lw-cdm** [comment]
Close. A similar issue is #2779
