### ISSUE TITLE
Separate environment for data on Strapi

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2097]
**Describe the task**
Separate environment for data on Strapi

- [x] Crowdloan check

  - Fund list
  - Chain

- [x] DApps

  - Categories
  - DApps List

- [x] Mission Pool

**Comment by saltict** [comment]
- Crowdloan check
  - Fund list
  - Chain
- DApps
- Mission Pool

**Comment by Sokol142196** [comment]
Version test: https://64f2b1e9.subwallet-webapp.pages.dev/

Validation passed for dApps and Mission pool
Re-check crowdloan when have new item
