### ISSUE TITLE
Bugs related to connect mobile wallet

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2103]
**Describe the task**
Bugs related to connect mobile wallet

- [x] Logo Subwallet

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/c6122d79-eca2-440a-b8d3-dcd667460d15)

- [x] Icon style on the Processing screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/71f90bb1-2c6e-4f0b-a341-58d5b2d56d26)

- [x] Still show Minting screen when visit app via recent link on browser in app

https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7beb1406-f090-4d4f-80a6-e16db2f8d66c

- [x] Update UI for the Minting success screen
  - Expect: Show icon button replace button

**Comment by Sokol142196** [comment]
**_Version test: https://03bd2929.subwallet-webapp.pages.dev_**

Validation passed in case Still show Minting screen when visit app via recent link on browser in app
- Expect: Automatically redirect to earning page

**Comment by ThaoNguyen998** [comment]
Version test: 
http://192.168.10.156:9000/
https://ae4fe5a0.subwallet-webapp.pages.dev/

Validation passed in case
- Update UI Earning screen
- Show icon button replace button
- Fix bug auto-redirect Portfolio screen when reloading (connect web app with extension)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/42e07221-65f7-469b-9e86-3f227a57b430)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/09320a6d-ba25-489d-a946-560c9ef61e85)
