### ISSUE TITLE
Do not delete NFT data when reset wallet

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2106]
**Describe the bug**
Do not delete NFT data when reset wallet

**To reproduce the bug**
Steps: 
1. Import successfully NFT collection
2. Perform reset wallet and observe the displayed screen
3. Perform import NFT in step 1

Expect: 
In step 3: Show message: Existed NFT
In step 4: Show NFT step 1 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/002915b5-0e5a-47a8-983a-09e0f094726f)

**Comment by Sokol142196** [comment]
Resolve later in https://github.com/Koniverse/SubWallet-Extension/issues/2374
