### ISSUE TITLE
WebApp - Disable Browser notification type setting

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2117]
**Describe the task**
Disable Browser notification type setting cause this feature do not supported on webapp

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0fae4db0-d7c2-404f-95ee-35da132e2a43)

**Comment by ThaoNguyen998** [comment]
Version test: https://375fa73e.subwallet-webapp.pages.dev/settings

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/2b2ccdbb-65c8-4888-a3aa-096a9eeb39e5)
