### ISSUE TITLE
Update transferable balance calculation formula

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2118]
**Describe the task**
Update transferable balance calculation formula

**Expect:** transferable = free - max(frozen - reserved, ED)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7c7032ec-7da1-42b3-bb36-a4fdb7331059)

**Comment by NamPhamc99** [comment]
https://github.com/paritytech/substrate/pull/12951
https://github.com/paritytech/polkadot-sdk/blob/3069b0af398e5a0374802c31201637e97f4a530a/substrate/frame/balances/src/impl_fungible.rs#L44

**Comment by NamPhamc99** [comment]
![image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/bc7b46be-5555-4e45-9582-895ce01885ae)

**Comment by S2kael** [comment]
https://github.com/paritytech/polkadot-sdk/issues/1833

**Comment by NamPhamc99** [comment]
https://github.com/paritytech/polkadot-sdk/issues/1833#issuecomment-1805764506

**Comment by nampc1** [comment]
- [ ] Update formula calculating transferable balance
- [ ] Update parsing system pallet
- [ ] Update transfer max formula
- [ ] Update validation logic when transfer token

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/k2JG8ArrHFW443f 

Please check issues:

- [ ] Re-check swap with HydraDX provider
- [ ] Update message in case not enough balance to stake with XCM
- [ ] Update some other message

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/PXR2eSmPW8JAKGb
- Validation passed for all logic: https://konistudio-my.sharepoint.com/:x:/r/personal/nhungphung_koni_studio/Documents/Balance%20Validation.xlsx?d=wf6a3319222fa4dcca0b7d0b1add85251&csf=1&web=1&e=ZvJ5ST 
- Some message will resolve in https://github.com/Koniverse/SubWallet-Extension/issues/3150
