### ISSUE TITLE
Update Wallet Connect namespace

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2119]
https://docs.walletconnect.com/advanced/multichain/polkadot/namespaces-guide

**Comment by S2kael** [comment]
Re-check some case with requiredNamespace is empty or undefined

**Comment by S2kael** [comment]
How to test:
- Re check connect WalletConnect

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/T8dsSfZNfe7jMDY

Validation passed. 
- Manage WalletConnect
- Sign transaction/ message
