### ISSUE TITLE
Recheck issue cannot connect extension because the embedded content.js file is blocked

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2120]
**Describe the task**
Recheck issue cannot connect extension because the embedded content.js file is blocked

**Comment by saltict** [comment]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/11567273/a9bff44e-5b2e-4ffb-bba8-b3a221aba933)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/RBNEyb85mQKs6Qq

- [ ] Show popup only once in 5s

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/4Mi7a7YHsNLxRAN
Validation passed in case : Show message only once in 5s


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a16f9b56-be63-431f-9221-9f4b87e29400)
