### ISSUE TITLE
WebApp - Handle the case of error page when opening the app with an invalid URL

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2150]
**Describe the bug**
Handle the case of error page when opening the app with an invalid URL

**To reproduce the bug**
**Actual:** Error page
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c72ebcd4-406d-4363-8cae-f1d313ea10e5)

**Expect:** Displays a message that the page does not exist

**Comment by saltict** [comment]
Fixed with 404 error pages
