### ISSUE TITLE
Handle error when get balance on transaction screen

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2156]
### Current state
- In some transaction screens, when the chain connects status is `DISCONNECTED` or `UNSTABLE`, the action to get some information to complete or validate the form will be errored. So cannot make transactions.
- Example: In the transfer screen, when the chain is disconnected, the action getMaxTransfer will error, max value will be set to 0. -> When input amount, the error message is `Amount must be equal or less than 0`. It confuses users.

### Solution
- Handle case network status is `DISCONNECTED` or `UNSTABLE`, show popup to update network or provider
- Handle error message in form when getting balance fail, make it clearer (split getting info error and validate error)

### Improve
- Re-handle checking to connect network status

**Comment by Sokol142196** [comment]
Related issue https://github.com/Koniverse/SubWallet-Extension/issues/1597

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Re-check case network trying to reconnect (`UNSTABLE`)

**Comment by Sokol142196** [comment]
@S2kael please update this message 
- [ ] Update message when connection to chain is lost
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b3f5784d-0446-47fb-a0e0-9e25b421d1fb)

- [ ] Improve UX after re-connect

**Comment by Sokol142196** [comment]
Will resolve in https://github.com/Koniverse/SubWallet-Extension/issues/2504
