### ISSUE TITLE
Re-check chainStakingMetadata

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2162]
**Describe the task**
Re-check chainStakingMetadata

**Actual:** Do not chainStakingMetadata on the Kusama network

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/113a5c65-359c-4b08-b8f8-2684d1ad532f)

**Expect:** Recheck all network and update function

**Comment by S2kael** [comment]
- Reason: Kusama update function to get max nominations

- Solution: Add fallback for this case

- Note:
  - Follow this update for this function on other chains
  - Explore why Kusama updated this

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/gZB3RMa3XPNMgZS 

Validation passed in cases:
- Stake
- Unstake
- Check point staking feature on other type: dApp, validator
