### ISSUE TITLE
WebApp - Update 404 not found page

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2165]
Update 404 UI on webapp from branch `koni/dev/issue-2164`
Figma Link: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=12891-212912&mode=design&t=WI1sWXNAsywKwoMX-0

**Comment by ThaoNguyen998** [comment]
Version test: https://3cef4dbe.subwallet-webapp.pages.dev/not-found
 @S2kael Update UI follow by design

**Comment by ThaoNguyen998** [comment]
Version test: https://4dd5e701.subwallet-webapp.pages.dev/not-found

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/db13b664-ae44-4166-bb11-7de55410c8a4)
