### ISSUE TITLE
Implement lightweight Dotsama connector

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#217]
## Overview of the problem
API called with `ApiPromise` of polkadot{.js} consume too much resources and time if we connect to many networks.
It consum so much resources because it need to load metadata and create type in registry and prepre for some other method.

## Solution
Instead of use full Dotsama API promise we can use connect to API endpoint directly with provider like `WsProvider`.
- After compare ram need to connect via on `WsProvider` and `ApiPromise` I have this result:
  - Connect with 4 endpoint: `WsProvider` only need ~71mb ram with `ApiPromise` it need to ~137mb ram
  - Connect with 20 endpoint: `WsProvider` only need ~72mb ram with `ApiPromise` it need to ~264mb ram
- Connect only with `WsProvider` we need to do more work
  - Need too know exactly what we call, we can found this by inspect WS call from polkadot-js apps with its endpoint
  - Need to hash data before call storage api and decode response data with registry
- This solution will have some limitation and we still to use `ApiPromise` for dervive methods and complex methods in `tx`.

**Additional content**
Need fix some case like #93

**Comment by hieudd** [comment]
Will implement when rebuilding architecture for Manifest V3 in #349
