### ISSUE TITLE
Assessing the feasibility and feedback for Oxalus x SubWallet cross-traffic enhancement

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2172]
**Describe the task**
Assessing the feasibility and feedback for Oxalus x SubWallet cross-traffic enhancement
- Doc: https://www.notion.so/subwallet/Oxalus-x-SubWallet-cross-traffic-boosting-Feature-request-d64ce14a3a784239a0ccf85f41236028?pvs=4

**Expect:**

- [x] Feedback about Assessing the feasibility
- [ ] Estimated timing

**Comment by saltict** [comment]
Updated technical information for @katehasw:
Which should detect: 
- Browser
- Language

Should not detect:
- User Location
