### ISSUE TITLE
WebApp | Extension - Missing Centrifuge Crowdloan Result

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2184]
Missing crowdloan result from default crowdloan screen:
Test Address: 14rjPBzYwNnb3dfVjCH8L6MR3djRwXEuuomDLeRKzXxyG9ZD

**Comment by Sokol142196** [comment]
Version test: https://07132caa.subwallet-webapp.pages.dev/

Please check the issues:

- [ ] Missing the crowdloan item with in-auction status
  
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7b82b3ab-9daa-4c4c-aa8a-8e5a349b7346)
  - Expect: Show correct the crowdloan item with in-auction status
- [ ] Recheck and fill in information for new crowdloan item on content manager
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b008b4e2-28a5-4da4-9565-b03963534215)

  - Expect: Recheck every week to update in content manange

**Comment by Sokol142196** [comment]
Version test: https://4d7a8de2.subwallet-webapp.pages.dev/

Please check the issues:

- [ ] Sorting by time on details column
- [ ] Missing Ajuna crowdloan result 
  - Check with address 5DRewsYzhJqZXU3SRaWy1FSt5iDr875ao91aw5fjrJmDG4Ap

**Comment by Sokol142196** [comment]
Version test: https://8745fa6c.subwallet-webapp.pages.dev/

Validation passed

@saltict please implement for extension

**Comment by Sokol142196** [comment]
> Version test: https://8745fa6c.subwallet-webapp.pages.dev/
> 
> Validation passed in webapp
> 
> @saltict please implement for extension

Extension will implement in https://github.com/Koniverse/SubWallet-Extension/issues/2199
