### ISSUE TITLE
Pooled assets are not included in locked balance

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2185]
**Describe the bug**
Pooled assets are not included in locked balance

**Actual:** Pooled assets are not included in locked balance
- Check with Aleph Zero Testnet
- Notes: DOT, KSM is normal 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/56260c5f-5733-4270-a660-f37a289c9eea)

**Comment by S2kael** [comment]
Reason:
- In code, only relay chains have that logic.
- Currently,  Aleph Zero Testnet is defined as a para chain.
--> Pooled balance is not added to the locked balance

Solution:
- Update correct chain info

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/jJHYGEzZXoEobnC
 
Do not update locked balance after the first pooled

**Comment by S2kael** [comment]
> Version test: http://14.224.158.246:8900/s/jJHYGEzZXoEobnC
> 
> Do not update locked balance after the first pooled

This will be resolved in issue #2194

**Comment by Sokol142196** [comment]
@S2kael This issue has the same PR as the issue #2181 -> This issue should be split into another pr to test and close the issue

**Comment by S2kael** [comment]
> @S2kael This issue has the same PR as the issue #2181 -> This issue should be split into another pr to test and close the issue

Moved to PR #2190

**Comment by Sokol142196** [comment]
> > @S2kael This issue has the same PR as the issue #2181 -> This issue should be split into another pr to test and close the issue
> 
> Moved to PR #2190

@ThaoNguyen998 Please help me test this issue again on v1.1.22 (official version will close this issue if it passes the test)

**Comment by Sokol142196** [comment]
Version test: V1.1.22 (Official version)

Validation passed
