### ISSUE TITLE
Add refresh button for balance screen

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2194]
#### Current state
In some cases, the account balance is not accurate (combine balance info with some other info: staking....)

#### Solution
Add a button to refresh service in the tokens screen to manually refresh

- Link design:
  - Extension: 
    - Token list: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=243-8468&mode=design&t=Io1fplEFdfSl7ppm-4
    - Token details: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1214-49096&mode=design&t=Io1fplEFdfSl7ppm-4
  - WebApp: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=2802-84976&mode=design&t=Io1fplEFdfSl7ppm-4

**Comment by Sokol142196** [comment]
Same as https://github.com/Koniverse/SubWallet-Extension/issues/2381
