### ISSUE TITLE
Update XCM for Astar

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2196]
### Current status
Error on XCM local tokens from Astar.

### Reason
Astar removed the old function used for XCM local tokens (`limitedReserveWithdrawAssets`)

### Solution
Update to use new function

**Comment by S2kael** [comment]
For test: 
- USDt: 5HjN9PXUc3Kywoz5GwrViypGKypBGs6Gtwp2ewKyRaXoLBJM
- DOT: 5Hedt4xqZ5gcPtbzEifnTvruXCbTEJhRG8vRkZMWVogLbSvu

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/DDiCtp7Jo7fc3zX

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4b4f504f-7f3d-41b2-8821-7aee0085bd12)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/44994b6b-7092-4571-9c7a-191ba4f4c860)
