### ISSUE TITLE
Build Chain-List

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2198]
**Describe the task**
Update chain-list:
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/153
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/156
- https://github.com/Koniverse/SubWallet-ChainList/issues/130 => Follow-up and integrate later

**Comment by S2kael** [comment]
## Update
- Add tokens:
  - `moonbeam-LOCAL-xcUSDC`
  - `interlay-LOCAL-USDC.wh`
  - `acala-LOCAL-USDCet`
  - `centrifuge-LOCAL-USDC`
 - Add price id for `krest_network-NATIVE-KREST`
 - Add logo for GOS network (custom network)

**Comment by Sokol142196** [comment]
Version test: 

- 156: Validation passed 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/118da011-6d05-4e22-bd92-5ab32943c487)

- 153: Validation passed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0e1ecb75-f41a-48e6-bf10-7010ff0db832)


- 130: Waiting token to test

**Comment by S2kael** [comment]
> ## Update
> * Add tokens:
>   
>   * `moonbeam-LOCAL-xcUSDC`
>   * `interlay-LOCAL-USDC.wh`
>   * `acala-LOCAL-USDCet`
>   * `centrifuge-LOCAL-USDC`
> * Add XCM channels:
>   
>   * `xcUSDC` from `Moonbeam` to `Statemint`
>   * `USDC` from `Statemint` to `Moonbeam`
> * Add price id for `krest_network-NATIVE-KREST`
> * Add logo for GOS network (custom network)

Removed 2 XCM channels

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/D5JEjieB67YpsFX

Validation passed in these case
