### ISSUE TITLE
[Extension] Apply online update mechanism and update missing crowdloan chains

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2199]
**Describe the task**

- [x] Apply online update mechanism with content manage
- [x] Update missing crowdloan chains

(refer issue https://github.com/Koniverse/SubWallet-Extension/issues/2184)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/Cp7bdiybEpDdpnW

Validation passed.
- Check on page Crowdloan: https://web.subwallet.app/crowdloan-unlock-campaign/contributions-result
- Menu Crowdloan on Extension
