### ISSUE TITLE
Implement offline tool to recover assets from Ledger

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2200]
**Description**
Ledger only allow one asset on each derivative account. Users will "lose" their assets if they transfer tokens into the wrong derivative account. Technically, the assets are still there but users will not be able to interact with them using Ledger. Therefore, we should have a tool to assist users in such cases

For reference:
https://github.com/TalismanSociety/ledger-substrate-recover

**Comment by S2kael** [comment]
The repo: [SubWallet-Ledger-Recover](https://github.com/Koniverse/SubWallet-Ledger-Recover)

#### Current state

- Implement base logic (Import seed phrase and export JSON)
- Use our lib for UI (@subwallet/chain-list)


### Need to improve
- Require new design and update
- Find a way to build an offline version (single HTML page)
  - Reference the repo of Talisman (use Vite - but missing font)

**Comment by ThaoNguyen998** [comment]
Version test: https://ledger-recovery.subwallet.app/

- [ ] Do not show popup when account doesn't exist

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ab4e266f-7a0c-4308-a1fc-a9deb29fe579)

- [ ] Show incorrect address when import by JSON file

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/26fa2426-ae1e-4a70-827e-bc1070b65bbc)

- [ ] Trimspace seed phrase

**Comment by haiyenvu23** [comment]
Version test : 
- https://github.com/Koniverse/SubWallet-Ledger-Recover/releases/tag/v0.1.3
- https://ledger-recovery.subwallet.app/
                      
Validation passed in case : 
- Show popup when account doesn't exist
- Show correct address when import by JSON file
- Trimspace seed phrase

- [ ] Update the network list according to this list :
- Kusama
- Polkadot
- Polymesh
- Dock
- Centrifuge
- Edgeware
- Equilibrium
- Genshiro
- Statemint
- Statemine
- Nodle
- Sora
- Polkadex
- Bifrost
- Karura
- Reef
- Acala
- XXNetwork
- Parallel
- Astar
- Composable
- Stafi
- AlephZero
- Interlay
- Unique
- BifrostKusama

- [ ] On Advanced mode, when selecting Sora, Bifrost, XXNetwork, Composable networks do not generate addresses in the Account address field

![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/91bb4545-5c6d-4782-be59-3f0034d4455b)

- [ ] Update file name when downloading "account.json" -> “Ledger account.json”

**Comment by Sokol142196** [comment]
Version test: https://github.com/Koniverse/SubWallet-Ledger-Recover/releases/tag/v0.1.5

- [ ] Re-check case re-import to SubWallet
  - Actual: Show EVM tokens on Substrate account.
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a5e50b39-32b2-4833-bb26-144dd864ed82)

**Comment by haiyenvu23** [comment]
Version test :
- https://github.com/Koniverse/SubWallet-Ledger-Recover/releases/tag/v0.1.6
- https://ledger-recovery.subwallet.app/
Validation passed
