### ISSUE TITLE
Handle the case of display large balance in Token detail screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2201]
**Describe the task**
Handle the case of display balance in Token detail screen
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4b83f87f-6545-4eb2-b113-7956d5cc9db3)

**Comment by ThaoNguyen998** [comment]
@dungnguyen-art Please fix UI bug
![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4cfe6449-02a4-46b4-be08-71048210d9ab)

**Comment by dungnguyen-art** [comment]
**[Unable to reproduce the reported error].**
I have checked the "Token details" on three browsers: Chrome, Firefox, and Microsoft Edge, but I could not reproduce the reported error.

**Comment by Sokol142196** [comment]
> **[Unable to reproduce the reported error].** I have checked the "Token details" on three browsers: Chrome, Firefox, and Microsoft Edge, but I could not reproduce the reported error.

You can reproduce this bug on Firefox browser with acc address 0xe7a9a370747aab5e7ff1C621a9C337Ca5b8dEbAd and MFG token
- Address contract to import token: 0xb161b2da48de283ec22bafbc36e5551c892629a2 (Moonbase Alpha)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/Bo8aSqjFTq4taEk
Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/598b7e27-1de1-4654-a622-18b8d0554ef1)
