### ISSUE TITLE
WebApp | Extension - Fix some UI bug (Round 1)

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2203]
**Describe the bug**
UI bug manage netwwork, select token

**To reproduce the bug**

- [x] WebApp: UI bug in case select token when receive
Browser test: Firefox

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a9d4cee0-be89-402b-8605-eb8bb35208ae)

- [x] Extension: UI bug manage network screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/f2ba5f93-2005-48d0-99c6-6e5c4447dbe4)

- [x] Subwallet -> SubWallet

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6477f41a-6af1-4477-8e06-9a924f9cb255)

**Comment by lw-cdm** [comment]
@ThaoNguyen998 , 
- For Web app issue, please check https://github.com/Koniverse/SubWallet-Extension/pull/2261
- For Extension issue, please check https://github.com/Koniverse/SubWallet-Extension/pull/2263

**Comment by ThaoNguyen998** [comment]
@dungnguyen-art Please help me fix UI bug on Crowdloan tab

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9c0f91d9-1235-410d-9243-d0d570c23a72)

Link Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1341-40968&mode=design&t=eAnxgrNLaQNh7WuU-4

**Comment by Sokol142196** [comment]
**Extension**
Version test: http://14.224.158.246:8900/s/dEo5SY89fQZ5pBi
Please check the issues:

- [ ] UI bug in the Manage network screen on Firefox browser
  - Expect: refer Chrome/Brave browser
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/61540400-7094-4ba8-8689-385118ddb3c3)

- [ ] Crowdloan tab still incorrect
  - Actual: Padding bottom = 16
  - Expect: Refer NFT, Staking tab (Padding bottom = 8)

**Comment by Sokol142196** [comment]
**WebApp**
Version test: https://ee160052.subwallet-webapp.pages.dev

Some case need to test after merge pr 2263 on extension to webapp
- UI bug on the Customize asset display screen on Firefox browser in case Network name is long
- Update the Select account type when create new account
- Placeholder (Subwallet) on the export account screen

**Comment by ThaoNguyen998** [comment]
- [ ] Update text: Create with new seed phrase -> Create with a new seed phrase
- [ ] Update logo SubWallet when connect Ledger device, Import by QR code
- [ ] Update name network: 
  - Substrate: remove "network"
  - EVM: constant 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/899226ca-dbc6-4e2b-9bff-b4d5a346872a)

- [ ] Remove the period at the end of the sentence 
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/41b908af-cbff-4ea4-a2f6-3bfc6dae4e11)

- [ ] Update text in Import by QR code screen: Make sure that you have granted SubWallet the access to your device's camera

- [ ] Change dapp -> dApp

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6076e49d-686a-4892-aab9-0b4e75cccdd2)

- [ ] Update content in Select dApp screen: Reload to fetch dApp information

**Comment by Sokol142196** [comment]
- [ ] UI bug on webapp mobile when srolling in screens:
  - Homepage (Token list)
  - Earning
  - Crowdloans
  - dApp
  
For example with dApp list:
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/59468fce-1203-4290-b043-45925ffdac6f)

**Comment by ThaoNguyen998** [comment]
Version test:
Extension: http://14.224.158.246:8900/s/PaRXb4jpfoLAoX2
WebApp: https://ee160052.subwallet-webapp.pages.dev/

Validation passed.
