### ISSUE TITLE
Update extension to MV3

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2205]
Need to change after converting to MV3
- [x] Technical migration
  - [x] Migrate life-cycle
  - [x] Migrate DApp connection
  - [x] Migrate fetch
  - [x] Migrate storage
- [x] Optimize State
  - [x] Sleep mode
  - [x] Full mode
  - => Improve more later
- [x] Implement new UI design for MV3 migration

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/EHLnEyk36QJrA6w

Please check the issues:

- [ ] Can't connect dApp via WalletConnect
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e89f3fce-1c57-42e4-a98b-fd786595fc9c)

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4a4e2c93-93f5-4c8d-bb93-5e0a5f87e606)


Improve
- [ ] Need to show the number dApp request on SubWallet icon
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e6d1560a-7d43-4080-bc54-c728debc0ed5)

**Comment by saltict** [comment]
[ ] Bug forgot account make extension freeze

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/zHaP75qqy7m9JKS

- [ ] Re-check memory of extension(estimate 10 account)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8eca0a37-244a-45cc-a219-0616bf2c70f0)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/pBipdpwR9tspoRT

Please check issues:

- [ ] Do not sync ZK mode
  - Expect: If not fix this bug then hide ZK mode feature
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9ea85d7d-89e9-4eb7-bf7a-53e32d8f8813)

- [ ] Re-check and handle memory
  - Expect: Max memory = < 600 MB

**Comment by Sokol142196** [comment]
Issues related to MV3 raised in https://github.com/Koniverse/SubWallet-Extension/issues/2681
