### ISSUE TITLE
Browser waste time when load extension

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2207]
#### Current state
The UI is blank when the first time load 

#### Reason
- UI requires some required data to display
- When the network is slow, some services need loading data from the network will be delayed

#### Solution
- Recheck required data to display on `ROOT`
- Handle some services that may be delayed when low network

**Comment by S2kael** [comment]
#### Reproduction
- Open background page
- In network tab:
  - Disable cache
  - Adjust network speed (on the right side of `Disable cache`)
  
![Screenshot 2023-11-21 at 09 51 36](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/551210cb-f37d-452c-b2dc-8ff26448dba8)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/p246GknzxR3kMtN

Validation passed in cases:
- Install
- Upgrade version

Validation record: https://konistudio-my.sharepoint.com/:i:/g/personal/nhungphung_koni_studio/EcEBlQ9cIttEqP3jUREfntABZtdnNTLzQTSzNZQmXK-43A?e=lJrkUf

- Improve UX: resolve later in https://github.com/Koniverse/SubWallet-Extension/issues/2228
