### ISSUE TITLE
WebApp - Continue Fix modal height in mobile

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#2209]
- [x] Forgot password
- [x] Disconnect wallet
- [x] Remove token, NFT, custom network, address book
- [x] ...
- [x] Fix Modal UI issue on desktop

![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/ddad9b45-693b-4f07-9350-61fd22580ae3)

**Comment by Thiendekaco** [comment]
1. List of modified components 
- Wrapped in BaseModal
  + Center position
        1. Delete chain
        2. Token detail
        3. Disconnect wallet
        4. Delete address book
        5. Delete token 
        6. Delete Account
  + Right position
        1. Forgot password
        2. Buy Tokens
        3. Display Payload Modal
        4. Connect Website Modal
        5. Campaign Banner Modal
        6. Receive Qr Modal
        7. Request Camera Access Modal
        8. Request Create Password Modal
        9. Disconnect Wallet
        10. Disconnect Extension Modal
        11. Reset Wallet Modal
        12. Unlock Modal

**Comment by ThaoNguyen998** [comment]
Version test: https://0f2a8bb8.subwallet-webapp.pages.dev/home/tokens

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/90890965-a7ec-43a7-bffd-05061e82d3ca)
