### ISSUE TITLE
WebApp - UI bug on the small screen

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#2210]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/70f6f08a-ac90-4385-b2da-46653b869d47)

Solution:
- On small screen, reduce font size, move action buttons to bottom 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/4e4000aa-ae8e-468b-8fba-683f93f73c44)

**Comment by ThaoNguyen998** [comment]
Version test: https://e4ce5498.subwallet-webapp.pages.dev/home/tokens
Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/05897334-22d5-4453-becc-2abc8124717c)
