### ISSUE TITLE
[WebApp] Effect when open modal Select token, Select account in case Buy token

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#2211]
![2015](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/fc591cc8-9f45-48e2-909c-815bf4de712d)

Actual: Modal move to center then snap back to the right
Expect: Modal animation must show normally

**Comment by Sokol142196** [comment]
Version test: https://c1dfcc94.subwallet-webapp.pages.dev/
Validation passed case update effect
![2211_Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/48cf08b1-8507-47c2-a7d7-d4cd5e4d7c1c)
