### ISSUE TITLE
Support staking AZERO with Ledger

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2219]
Describe the task
Support staking AZERO with Ledger

**Comment by S2kael** [comment]
Aleph leave pool `5CWowLuTE9diZUAot9bTkw3uBfuTXUR4Nj279UiS25jdtJ5V`
Aleph cancel and withdraw `5DPZC5vj5RgSBbzig4kZmqgMKYJ5rBaBUE3gqJqd3asayUC3`
Aleph unstake `5ETmbmonWjsFEHcb9YLqtByvYXxa9NGT2WPsXkNyG1SWz7M3`
Aleph claim reward `5G9usqTEsuZsMDsWgGzizzoBQAmeKJefYkRv3oZUuSwUfZwN`
Aleph withdraw pool `5GTnVoJJnoWBnRQS2TCMJRpwp8i7oaD5mMKvxeABgtYbFpsS`
Aleph stake `5GUfTk8Z9bs95V3CW9Uvh9Qps6eBCA27DkcetNjce8xNbd9L`
Aleph token `5FshyMxL3SfLYeg6M2icjd9fNeH8mi4x9iLm4rpoMma8pihn`
Aleph Nft `5FLZAZUNLxJapT3cohFfC6AtqZLHJBSXg2nPK7tvWec5gjXJ`

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/4iZzzMXsmQ5miW3

Please re-check the issue:

- [ ] Do not show the nominated validator on nomination detail screens
  - Actual: Do not show nominated validator -> User still nominates for another validator
  - Check with address: 5FLZAZUNLxJapT3cohFfC6AtqZLHJBSXg2nPK7tvWec5gjXJ

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b6b125b3-4770-4727-9259-95f1cc77126a)
