### ISSUE TITLE
Extension - Update neway to fetch history data of an account

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2223]
**Describe the task**
Extension - Update neway to fetch history data of an account. Update UX - User need select account to get transaction history

**Comment by lw-cdm** [comment]
Following functions are affected:
- Transfer done
- Staking: action Withdraw and Claim reward in More Action Modal.
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/9a43eb86-467d-42ac-a0de-7c42d200c773)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/ci37JmryFHCReAx

- [ ] Do not show the history of the Crust network

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6cd7404e-b46c-421d-bc56-90a0e07bd7cf)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/LAAZTPrcEPHQNYY
Please check the issues: 

- [ ] Show network not supported in SubWallet 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/74554a9e-3eea-418f-b57e-5f2c5333043a)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/2Jx4bY64oKGWoPr

Validation passed.
Some remaining issues are commented in https://github.com/Koniverse/SubWallet-Extension/issues/2179
