### ISSUE TITLE
Integrate CLV EVM accounts and assets

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#223]
**Describe the solution you'd like**

CLV has recently enabled Clover EVM
Please integrate CLV EVM accounts into SubWallet. Thanks.

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./460-merge-build-0.4.9-1658375618923.zip 

![image](https://user-images.githubusercontent.com/102292476/181457380-b16048ae-9b43-4583-9868-c65d7a3d3513.png)
