### ISSUE TITLE
Re-check all functions on Moonbeam network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2232]
**Describe the task**
1. Re-check all functions on Moonbeam network

@ThaoNguyen998 re-check all features:
Version test: Chrome store version v1.1.22 

- [x] Receive
- [x] Turn on/ turn off
- [x] Change provider
- [x] Transfer assets: Token, NFT
- [x] Staking: Stake more, Unstake, Cancel stake
- [x] Connect dApp
- [x] ...

------
2. Dev fix bug (if any)
- [x] Do not auto turn on Moonbeam network when import account
- [x] Re-check send NFT (Transaction failed)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/809bb539-ac9a-4c97-a41b-676cc235c08b)

- [x] Re-check perform transaction on dApp

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8bf3ee7f-07ff-44d8-932b-ec43848d0cea)

**Comment by ThaoNguyen998** [comment]
Version test: Chrome store version v1.1.22

- [ ] Do not auto turn on Moonbeam network when import account

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/DPWbEeb6xKjkkqP

Validation passed in the cases above
- Extrinsic transfer in app: 
- Extrinsic transfer NFT: https://moonbeam.subscan.io/extrinsic/0xc33213556438d7fc5a94d7bbb5d849db634ea008343e4f36d97f3ed574ffa307
- Perform transaction on dApp: https://moonbeam.subscan.io/extrinsic/0x6c79d4eef40d266c66ea241d2ec2663bb5e92e7cd2b35ceb62268e11466d0283
