### ISSUE TITLE
Showing incorrect data in staking feature in some cases

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2234]
**Describe the task**
Showing incorrect data in staking feature in some cases

I reproduce this issue with Aleph Zero.
Please re-check for all network and fix bug

- [ ] Do not show the nominated validator on nomination detail screens
  - Actual: Do not show nominated validator -> User still nominates for another validator
  - Check with address: 5FLZAZUNLxJapT3cohFfC6AtqZLHJBSXg2nPK7tvWec5gjXJ

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b6b125b3-4770-4727-9259-95f1cc77126a)

- [ ] Show incorrect nominated value 
  - Check with address: 5DPZC5vj5RgSBbzig4kZmqgMKYJ5rBaBUE3gqJqd3asayUC3, 5DSdZxoppiCRxAZWyLZeMgCutjdioHaYFTbNqoNNAz2ZzXsj

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f87f758e-f160-4f70-81b9-e33b04fbbbde)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c8160d96-c8e7-48b2-ae02-95b890742745)

**Comment by NamPhamc99** [comment]
These are due to:
- Deprecated stash/controller mechanism
- Account being validator

**Comment by nampc1** [comment]
No further fix
