### ISSUE TITLE
Improve validator/pool selection UX

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2246]
For nomination pools:
- Show all nomination pools by default, but add earning status on the listing screen so users can tell right away
- Allow users to stake into pools that are not earning rewards (earning status may change in a short time)
- Show nomination pool state and earning status 

For validators:
- Add option to sort by nominated validators

**Comment by NamPhamc99** [comment]
![image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/beac7b33-1f27-4f0b-86aa-5d2d8dbc96b2)
- [ ] Check pool name display with pool #3 on Vara

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/iDXKLbR7pRDC87f

- [ ] Re-check case show pool name 
- [ ] Update UI for the Select pool screen

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/YkwL4xbatqwM6pB

Validation passed in cases:
- Show earning status
- Detect pool/validator/collator/dApp name

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8cd382cd-8a71-4108-bc12-035c52b5ccbe)
