### ISSUE TITLE
Update web-runner v1.1.23 for mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2257]
**Describe the task**
Update web-runner v1.1.23 for mobile app
- Update chain-list (_related issue: https://github.com/Koniverse/SubWallet-Extension/issues/2198_)
  - Add logo for custom network GOS
  - Add price id for KREST
- Update XCM for Astar network (_related issue: https://github.com/Koniverse/SubWallet-Extension/issues/2196_)
- Fixed bug decode dApp address (_related issue: https://github.com/Koniverse/SubWallet-Extension/issues/2139_)
- Fixed bug automatically activate tokens based on account balance (_related issue: https://github.com/Koniverse/SubWallet-Extension/issues/1500_)
- Fixed bug missing crowdloan (_related issue: https://github.com/Koniverse/SubWallet-Extension/issues/2199_)

**Comment by ThaoNguyen998** [comment]
Version test: v1.1.15(245)
Device test: IP 11

- [ ] Do not show logo for custom network GOS
- [ ] Bug missing crowdloan: https://github.com/Koniverse/SubWallet-Extension/issues/2282

**Comment by nguyenduythuc** [comment]
@Sokol142196 @ThaoNguyen998 please, follow up this issue on https://github.com/Koniverse/SubWallet-Mobile/issues/1199

**Comment by Sokol142196** [comment]
> @Sokol142196 @ThaoNguyen998 please, follow up this issue on [Koniverse/SubWallet-Mobile#1199](https://github.com/Koniverse/SubWallet-Mobile/issues/1199)

Ready to store on v1.1.16 (Build: 261)
