### ISSUE TITLE
Update extension dependencies

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2259]
## Overview 
- Update dependencies from `@polkadot`
- Update jest (with resolution method)
- Update ledger lib

## Re-test:
- [x] All features
- [x] Ledger support
- [ ] @saltict re-check security issue

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/TMQ4sQorsTkrmsr

All feature are normal
