### ISSUE TITLE
Handle bug reset data on version IOS 17.1 (Round 3)

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2272]
/**Describe the bug**
Handle bug reset data on version IOS 17.1

**Describe the bug**
* Next round:
  - Update indexed db
  - Clear backup data when remove account or clear app data

The issues are compiled in the file 
https://konistudio-my.sharepoint.com/:w:/g/personal/nhungphung_koni_studio/Ebalh2Nvp8tGvgrBqboIPDABddJ2ra0vnGeXno4x9PHoMw?e=fjgv6q

**Comment by ThaoNguyen998** [comment]
Processed at issue https://github.com/Koniverse/SubWallet-Mobile/issues/1182

**Comment by Sokol142196** [comment]
Rejected apply for app
