### ISSUE TITLE
Update staking for Westend

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2275]
### Description
Removed `api.consts.staking.maxNominatorRewardedPerValidator` function

### Expect
- Find a replace function or fallback value
- Explore why it changed

**Comment by rossbulat** [comment]
Hello! There are also changes to strorage and calls. `erasStakers` and `erasStakersClipped`storage items  are now deprecated in favour of `erasStakersPaged`, `erasStakersOverview`. There are also changes to claiming payouts - the PR related to these changes can be found at https://github.com/paritytech/polkadot-sdk/pull/1189.

**Comment by NamPhamc99** [comment]
Thanks a lot for the headsup @rossbulat, we'll follow this closely and update asap

**Comment by S2kael** [comment]
Will be resolved in #2324
