### ISSUE TITLE
Check staking earning status on CreditCoin

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2277]
SubWallet is showing not earning status for this account 5DvWi3n7P8KZ23VotewSJjQNBsuWhmh8KfyqXVapsnQC7Cqx. Please confirm

**Comment by S2kael** [comment]
Status of this account:
- 2 nominators have `not earning` status (nominator not at top of validator's nominators)
- 1 nominator has `waiting` status (nominator not in list validator's nominators)
-> Status is `not earning`

**Comment by S2kael** [comment]
> Status of this account:
> 
> * 2 nominators have `not earning` status (nominator not at top of validator's nominators)
> * 1 nominator has `waiting` status (nominator not in list validator's nominators)
>   --> Status is `not earning`

Because the list nominator returned is unsorted, so result is wrong.

--> Sort the raw list before exporting the top list
