### ISSUE TITLE
Simple chainlist report

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2278]
Input: 
- Chain list API: https://content.subwallet.app/api/list/chain
- Chain asset: https://content.subwallet.app/api/list/chain-asset

Output:
- Chain Number
- Number EVM
- Number Substrate
- XCM Support List: `ChainAssetList.assetRefs` of chain assets has value
  - Count number
  - Listing all XCM support
- Staking List: `substrateInfo.supportStaking = true`
  - Count
  - Listing all network - symbol

**Comment by Thiendekaco** [comment]
link demo
https://codesandbox.io/p/sandbox/dazzling-kate-l37wkh?file=%2Fsrc%2Fstyles.css%3A40%2C14
