### ISSUE TITLE
Support Ledger for Vara network

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2283]
https://github.com/gear-foundation/ledger-vara
https://github.com/gear-foundation/ledger-vara/blob/master/docs/adpu.md

**Comment by S2kael** [comment]
Follow up, the app don't listed on Ledger Live app store

**Comment by Sokol142196** [comment]
Currently, all substrate chains have migrated to use Polkadot generic app. This issue is no longer required
