### ISSUE TITLE
The default pool setting for Vara is SubWallet Official

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2291]
**Describe the task**
The default pool setting for Vara is SubWallet Official
Implement for:

- [x] Extension
- [x] Mobile app

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/pqYKk3Eso2g3SSY

Validation passed on extension

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ef919fd4-3cf4-4687-9f38-787f480088f8)

**Comment by ThaoNguyen998** [comment]
Version test: PR #1188 11:05 01/12/2023
Device test: Samsung S20 FE 5G

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/c229105c-ef5a-4c23-80a8-9378ddb0c8e9)
