### ISSUE TITLE
Instruction for Staking feature on mobile app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2294]
**Describe the task**
Implement Instruction popup for Staking feature on mobile app

- [x] Instruction for Staking
- [x] Popup warning message lỗi

Link doc: https://www.notion.so/subwallet/Instruction-for-Staking-feature-on-mobile-app-a7674282f4184c69bee53d2f67d5d4e6?pvs=4

**Comment by Sokol142196** [comment]
Version test: v1.1.14 (252)
Device test: S20 FE 5G

Please check the issues:
- [ ] Hide the scroll bar
- [ ] The icon incorrect
- [ ] Handle case open the app in case pooled
  - Actual: Open the popup when the user opens Staking tab
  - Expect: Open the popup when user open the Pooled details screen of the VARA network
- [ ] Still shows popup multiple times on the first visit after version upgrade

**Comment by ThaoNguyen998** [comment]
Version test: PR #1194 19/21/2023
Device test: IP 11

Validation passed in case
- Stake, Stake more
- Unstake, Unstake all
- Withdraw
- Claim reward
