### ISSUE TITLE
Update precise start/end time of an era

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2313]
Currently, staking withdrawal time is an estimate. It's based on the current era and the target era of the withdrawal. This leads to sometimes the withdrawal time can fall behind by a lot (~24hrs). We need to find the exact start/end time of an era to calculate the withdrawal time

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/wSf5a57wp8ZRJYK

Validation passed in cases: 
- > 1 day
- < 1 day

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/188eaa42-6a91-4991-a0d4-ef9140c3f49f)
