### ISSUE TITLE
Do not navigate when click on hyperlink(Extension)

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#2316]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a2d5530d-4481-41de-99b3-22b7d6d7eb11)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/r2nzfftjJWQLcT4

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d95af273-3c86-417a-a2cf-cf5ec571cc2c)
