### ISSUE TITLE
[Extension] Add popup to remind users to perform backups

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2317]
**Describe the task**
Add popup to remind users to perform backups

Expect: Remind users to backup the seed phrase periodically
For example, the user's most recent activity was 1 month ago, and when the user logs in again, they will see a popup

Link doc: https://www.notion.so/subwallet/Remind-backup-seed-phrase-e8d72949a2314f46bc7425f344bc40ff?pvs=4
Link design: 
- Extension: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=15074-222730&mode=design&t=KzHxQn2ErRBSrORN-4
- WebApp: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=15117-185097&mode=design&t=KzHxQn2ErRBSrORN-4

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/Tse5TG7D4zrwyRs

- [ ] Popup always display after perform back up now
**Expect**: After perform with popup , don't show again

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ea44e5a5-e91e-4066-880e-cb27b5afbbdc)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/Tcie3G75AEbDpy6

- [ ]  Bug when having marketing campaign
Expect : Show popup Backup seed phrase first then popup MKT campain


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/90337ac1-4f07-48f7-921a-64352003ef13)

- [ ] If you haven't worked with the popup and turn off the extension, the popup will still be displayed after reopening


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/74de579e-0907-4364-9b73-c4d5a58b1604)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/wkHgTaxi9WmSWeE

- [ ] Popup must be display on 2 screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2547f5b4-259f-44a3-85fa-932ab730634b)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/BoCB3EPjFxtyoiZ

- [ ] When click back to on Export account screen
Actual : Navigate to Account details screen
Expect : Navigate to previous screen



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/48b855e5-177f-4132-a641-17d4868f64de)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/G2PjPqYM4xHmSZJ

- [ ] In case you have just installed the extension and have not worked with the extension in the right corner of the screen
Actual : The popup flashes and then appears in the extension screen on the right corner of the screen
Expect : Popup must be display



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cc62cede-156e-4997-aab5-0bcc7d813876)

- [ ] Popup display every time althouh have worked with it


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cd70c166-71af-4ae3-b307-bb6c4a3a67ab)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/QQwyLCBLsx3PRJL

- [ ] In case the banner is displayed, after exiting and re-entering the extension, the banner operation must be performed to display it again.
Expect : Banner appears after reopening the extension



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d7dbc99a-1d52-4d60-a4cc-1ff5f6f9f79e)

- [ ] In case after perform transaction
Actual : Popup displays before the Transaction history screen
Expect :  Popup displays after the Transaction history screen



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/fbc0cc56-5ac7-44d8-8b8b-b83e149db60b)

**Comment by haiyenvu23** [comment]
- Update version
- Updated online time
- In case there is marketing campain running


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/af010a8f-4214-46da-8397-1d9c0fafd2e4)


- All account mode


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f9cf227e-28aa-4645-b881-f2a2d783b8e3)


- Specific account ( Normal account)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4b60af89-a9e0-40d5-9f8c-e0e47c558321)


- Specific account ( Ledger account, QR signer account, Watch-only account) 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4f8feaa7-54a5-4c56-ad33-33ed1d16bc88)

- In case the screen is in the transaction screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7810755a-f201-4aa4-ac5c-495bd1c40b36)

**Comment by haiyenvu23** [comment]
- [ ] Add highlight button Export multi account when navigate to select account screen
Link design : https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=842-53043&t=bZpVh3t7rrJRHhVH-4
- Context tooltip : "Export and back up account"
Expect : 
- On All account mode/Specific accoun mode ( Ledger account/QR signer account/Watch-only account), after click button Back up now on popup Back up seed phrase -> Navigate to Select account screen with Export multi account button highlighted
- Note : The default tool tip will appear until the user completes the update
