### ISSUE TITLE
Re-check case List token to buy is empty after run static content

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2322]
**Describe the bug**
Re-check case List token to buy is empty after run static content

**Actual**: User can't select token to buy
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2266696c-8da3-4ae4-9554-477f21bcc0c0)

**Expect:** Always token list is not empty

**Comment by saltict** [comment]
Resolved with fallback data
