### ISSUE TITLE
Update top nominators getting rewards

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2324]
Polkadot now allows all nominators of validator to receive rewards, not jsut the top 512 nominators

**Comment by NamPhamc99** [comment]
https://github.com/paritytech/polkadot-sdk/issues/422

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/FP8NBmkJyMN9Kbz
- Re-test staking feature is normal
