### ISSUE TITLE
Update rdns for EIP-6963

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2328]
Please update rnds for EIP-6963 from `extension.subwallet.app` to `app.subwallet.wallet`
This feature is for technical aspects only.
Currently, we are using DNS and not Reserve-DNS and it will be fixed asap before integrate with another partner

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/8YCegGgsLw65Hna

Validation passed in cases:
- Connect to https://eip6963.org/
- Connect other EVM/Substate dApp
