### ISSUE TITLE
Check fee estimation on EVM networks

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2336]
Fee seems to fluctuate a lot sometimes on EVM networks. We need to follow to see if it's due to increased traffic on-chain or a bug in the logic

**Comment by S2kael** [comment]
Checklist:

- [ ] Send fund
- [ ] Send NFT
- [ ] Sign from dApp
- [ ] Sign with Ledger

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/8gc3NqpYwmZtegR

Please check issues:

- [ ] Submit failed 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d10ad458-90ec-4e9f-9d76-39252d7f6908)

- [ ] An error occurs when transfer tokens with Ledger account
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/45628c82-03e0-4a27-a24f-2be0dc64ceb5)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/FFg5ySXz7aaS6Dp

Validation for cases:
- Send NFT: https://moonbeam.subscan.io/extrinsic/0x91a13b0036fbe0c5d62a3cdcebb8090183a5452374317cf44d0f4b543b3bd70b
- Send token:
  - Native token
    - GLMR
    - MATIC (network busy): https://polygonscan.com/tx/0xd5be677de3fdc6758ae11859bfb5b01494229d3d13c96e92c16487025297f12b
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8fa1d88d-9660-41e3-94ad-f1e817b53e5d)

    - SDN
    - ACA: https://blockscout.acala.network/tx/0x9b5a9fac08b78f2b0e184aba3b4b72346d49a4e94e51b256e962fa9d110a173f
  - Local token
    - xcUSDT (Moonbeam): https://moonbeam.subscan.io/extrinsic/0x6e4d8901294cbdc63272600409268e14580fa8966f1d9fa5f9de8c2c274cb7a6
    - ARSW (Astar-EVM): https://astar.blockscout.com/tx/0x8fd8fbd97777ab69d3fed093befb1341d10fa0d5424da28dcd6d91224b43921b
- Sign with dApp
- Sign with Ledger account: https://astar.blockscout.com/tx/0xf303b9458099af1fa1d2f53470bc86c0ccfd821bafd8dd5815f3a9815800a002
- Sign with QR-signer account
