### ISSUE TITLE
Add support transfer Bifrost sub token

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#234]
**Add support transfer Bifrost sub token follow issue #118 **

Create new API for token transfer () in packages/extension-koni-base/src/api/dotsama/transfer.ts

- [x] Bifrost

Modify checkTransfer and makeTransfer to impletement new API in same interface with other transfers

- [x] Bifrost

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./master-pr-1520-build-1.0.8-2023-06-12T02-42-40UTC.zip

Validation passed with list tokens:
Bifrost Kusama: 
- KSM
- vKSM
- vsKSM
- vMOVR
- vBNC
- kUSD
- KAR
- MOVR
- RMRK
- PHA

Bifrost Polkadot:
- USDT
- vDOT
- vsDOT
- vGLMR

Re-test: 
- BNC (Bifrost Kusama): OK
- BNC (Bifrost Polkadot): Resolve bug on https://github.com/Koniverse/SubWallet-Extension/issues/1522
