### ISSUE TITLE
[WebApp | Extension] Update the Token details screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2340]
**Describe the task**
Update the Token details screen
Expect: Only show accounts have balances on the Account details tab
- If No accounts have balances then show the message 
  - Header: No account with {token} balance found
  - Content: Switch to another token to see account balance
  - CTA: Back to home

Tiếng Việt:
Header: Không tìm thấy tài khoản có số dư {token}
Content: Vui lòng chọn token khác để xem số dư tài khoản
Button: Trở về trang chính

Tiếng Trung:
Header: 未找到有{token}余额的账户
Content: 请选择其他代币查看账户余额
Button: 返回主页

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/xPWi4C7ceDrxsra

- [ ] Still show account haven't balance on the Account details tab with custom token

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/b7f12e8f-32c4-4f1b-8336-e1f434a74b2f)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/SQZtewTzsmcq3B7

Validation passed. 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/27449518-e25b-4018-8a83-19e8d7e7b6b2)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/16838925-a479-434b-bda9-279f6eb52f49)
