### ISSUE TITLE
Do not show token when standing on All accounts mode in case token does not get balance

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2352]
**Describe the task**
Do not show token when standing on All accounts mode in case token does not get balance

For example, I turn on Subspace Gemini 3f (tSSC) but do not get balance
Then, i switch to "All accounts" mode with setting **Show zero balance is true** and observe list token displayed

**Actual:** Do not show tSSC (Subspace Gemini 3f) token 
- Note: Specific account mode still showing token

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1850fc62-4b51-4343-af68-aa5e97c73c10)

**Expect:** Show token

**Comment by dungnguyen-art** [comment]
I cannot reproduce this error at the moment. @ThaoNguyen998 Please check it.

**Comment by dungnguyen-art** [comment]
Problem: For networks that are losing connectivity. In “All account” mode: The example does not display NUUM.
Research: I checked and found that the data returned from the background of BalanceItem in the file (useAccountBalaqnce.ts) has a status of not_support. Therefore, this token is not displayed on the UI.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/pCmdydtjjJFXXZB
Validation passed in case : 
- Install/Update version
- Check show token on Specific/All account mode


![Image](https://github.com/user-attachments/assets/85fa779c-af3a-4e66-9bd0-3019d580e9ec)
