### ISSUE TITLE
Support some XCM transfers

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2353]
Add support for the following XCM paths:
- [x] DOT: Parallel <-> Polkadot
- [x] DOT: Bifrost <-> Polkadot
- [x] DOT: HydraDX<-> Polkadot
- [x] DOT: Interlay <-> Polkadot
- [x] DOT: Acala <-> Polkadot
- [x] INTR: Acala <-> Interlay
- [x] ACA: Acala <-> Parallel
- [x] CFG: HydraDX <-> Centrifuge

**Comment by RyanDinh8** [comment]
Remove the following:
1. Efinity is not running a parachain anymore
2. Nodle has very few XCM transactions
3. Composable has very few XCM transactions
4. Centrifuge has very few XCM transactions

**Comment by S2kael** [comment]
For test:
- bifrost:
  - DOT: 5GbXt7Mp4X6Jvk4qtPCwv4cPWtQkZa4Za4jSXYYYTHheYvjH
- parallel:
  - DOT: p8CotLR4KkSKeNgZ2GM6G4UteQGyY5oknUbZPYDEFU7Pg4Cg2
  - ACA: 5CiJ9yS27Skn8BcPryCiSFYL7XXpaBjSZp6DfQV3FD9daygt
- hydradx:
  - DOT: 7NDmeL7CVSFi5Jke6ncLwdGJHa8HTw8XgdPAECCLguYt828M
  - CFG: 7MHBkkgAixgva8SbYmmtBMKgWvHNhR2shj3tFioPCrGKbqxV
- interlay:
  - DOT: wd7gsM9A5nY73Khnw528n1KdJ78uMbsaUBbjG4PugizoL1qqU
  - INTR: wdC7cSECciaFCGKp7APY9hf3DzoF9XkorVhSAsnwx2ndPmjWd
- acala:
  - ACA: 22L8Si44oNHrwmypmgHXqJK8MSst4YxFX3bhtJKPYbnDpYSx
  - INTR: 21HUxTp7Zp1b8vxcd6vgm24f41WxuxdS8uLiYbB2EDu1QJ3i

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/LikiJHKafRdWw6z
- DOT (Parellel <-> Polkadot): 
  - https://parallel.subscan.io/extrinsic/0x64a0037c77ba72554210fb7a7aad28f27ec5db648f528dd66d935eca45115296 
  - https://polkadot.subscan.io/extrinsic/0xa2d39070cec21200146cd0d0de349c5a8a3dbe3a304a97e8230ab97273ca2add
- DOT (Interlay <-> Polkadot:
  - https://interlay.subscan.io/extrinsic/0x751e9d4d77bdb924cda6c8d08544c92dc812f2dd984bce49637ca5d19f3d61ad
  - https://polkadot.subscan.io/extrinsic/0x32e63aa7e845819bde92ab7d2ce2345bab13b605f009fa40f142e774310db0b2
- DOT (HydraDX <-> Polkadot)
  - 
  - https://polkadot.subscan.io/extrinsic/0xfe5a8b381663be214a423251bccba2f1e0afc4d8e4f9a9d858cb8f78f69d1ec2
- DOT (Acala --> Polkadot)
  - https://acala.subscan.io/extrinsic/0xb14a1d4292472c2eda9671ecd2bdc164cdb372c639e1e3deb74d5c76577e3780
  - https://polkadot.subscan.io/extrinsic/0x9959292a7f20c4d6f4793fd41f82e5ef692a17c9c74050e0d778fc2f8c0823bf
- INTR (Acala <-> Interlay)
  - https://interlay.subscan.io/extrinsic/0x81f4e41f9f74f6f447630dd6c99d1013d1ab0c2e5c3d9bb3261ad62d1127dbb3
  - https://acala.subscan.io/extrinsic/0x69489c56c5457f0cfc564b021edbd6dbbb8fb2c96cb71e9fd99b25b18e107e5c
- ACA (Acala <-> Parallel)
  - https://acala.subscan.io/extrinsic/0x1fea9caf77c859f15393447725fa73514be268a0629fe205aa5962e54c3d2f4a 
  - https://parallel.subscan.io/extrinsic/0x6a462e0efc1a9ae79971360d97f1ba065f91ecfa1261d277df0d8f9a73778ad5
- CFG (HydraDX <-> Centrifuge
  - https://centrifuge.subscan.io/extrinsic/0x7e5daa4589df41f73f434d9069b55bbd2bef31a18289f9226d2505fe9fc6b3f8
  - https://hydradx.subscan.io/extrinsic/0xea6602eae87404967452ed10c26e4bbc5a48704f20e7f06906c56acb07ea19e2
