### ISSUE TITLE
[Extension] Migrate `Staking` to `Earning`

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2361]
Todo:
View screens:
  - [x] Earning Option list
  - [x] Earning Position list
  - [x] Earning Pool list
  - [x] Earning Position Detail
 
Transaction screens:
  - [x] Withdraw
  - [x] unstack
  - [x] Claim reward
  - [x] Earning
  - [x] Cancel Unstake
 
Other:
- [x] Instruction Modal

Components:
- [x] Earning Option Item
- [x] Earning Position Item
- [x] Earning Pool item
- [x] Collapsible panel
- [x] Account Info Panel

**Comment by lw-cdm** [comment]
- Earning Option Item
 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/eac1a724-8329-4a37-a102-da25bb5260be)

 - Earning Position Item
 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/56b34423-d313-4fa9-b088-20c0e53c04e8)

 - Earning Pool item
 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/7f6aab3f-bed7-43bb-bab3-b94199752d78)

 - Collapsible panel
 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/21d229b5-b211-4153-a41e-9c9606b8daa0)

 - Account Info Panel
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/96e90c59-0e96-43bc-b5e0-a3b4cd552d1f)
