### ISSUE TITLE
Update API staking for Astar

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2370]
**Describe the bug**
Do not show dApp list to stake
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c8abbd98-f581-4b12-8cef-0b65b94a7b05)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/97dee3c2-cc05-4c34-a47b-2867ddc7f261)

Expect: Update API staking for Astar -> Show dApp list to stake

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/Q7r2eZRsTbYn3zn

Validation passed in cases:
- Show dApp list on Astar, Shiden and Shibuya
- Re-test all list with remain network

@S2kael please confirm for me the Westend network
- Actual: Westend network have no validator

**Comment by S2kael** [comment]
> Version test: http://14.224.158.246:8900/s/Q7r2eZRsTbYn3zn
> 
> Validation passed in cases:
> 
> * Show dApp list on Astar, Shiden and Shibuya
> * Re-test all list with remain network
> 
> @S2kael please confirm for me the Westend network
> 
> * Actual: Westend network have no validator

Westend network has some problems with staking. At this time, the validators' list at the current era is empty.
