### ISSUE TITLE
Unable to export account when input valid master password

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2376]
**Describe the bug**
Unable to export account when input valid master password

**To reproduce the bug**
Steps:
1. Import account by seed phrase successfully 
2. Import multi account by JSon file( JSON file containing the account in step 1)
3. Perform export account 
4. Input valid master password
5. Observe the displayed screen

Actual: Unable to export account

https://github.com/Koniverse/SubWallet-Mobile/assets/117999489/86127e51-bd16-47d2-a42c-5cbe5385a9a9

**Comment by nampc1** [comment]
Not really a problem, we don't need to solve this case
