### ISSUE TITLE
Add reload balance feature

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2381]
Add reload button in token screen on extension, webapp... and create API for feature "Pull to refresh" balance token on mobile
- [x] Create API
- [x] Implement Extension (still wait final design)
- [x] Implement Extension with compete design 
  - Link design:
    - Extension:
      - Token list: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1172-84994&mode=design&t=Io1fplEFdfSl7ppm-4
    - WebApp: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=2802-84976&mode=design&t=Io1fplEFdfSl7ppm-4
- [ ] Implement WebApp

Require test:
- Fetch balance lifecycle
- Fetch crowdloan lifecycle
- Reload butons actions

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/pDd9AfPdooLTWe8

Validation passed
- Expect: Show correct balance when clicking on the Reload button 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5dd02052-b657-42d9-a3d8-568600eb1283)

**Comment by Sokol142196** [comment]
@saltict please implement for WebApp

**Comment by saltict** [comment]
> @saltict please implement for WebApp

Please check in this version https://4cd75fda.subwallet-webapp.pages.dev/

**Comment by Sokol142196** [comment]
**WebApp**
_Version test: https://4cd75fda.subwallet-webapp.pages.dev/_

Validation passed

Expect: Show correct balance when clicking on the Reload button
![2381_Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c5c4e157-0d34-4aee-ada0-d7ec2135f91b)
