### ISSUE TITLE
Add Azero Domains Pool & Validator as default option when users stake A0

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#2385]
Please add Azero Domains Pool & Validator as default option when users stake A0

- Azero Domain Pool: 5EYCAe5ijiYfAXEth5DFzMi9EMFCV6EFRyFuvwLky6Xx6dx8
- Azero Domain Validator: 5FTsYv3dgJsjndE3ktF1Rp3rF6UjGybGW2mcYVuaFzfrC4Cv

**Comment by S2kael** [comment]
At this time, apply default for staking pool only.

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/SfRGdb4acgqaTjt

Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0139ebe9-720f-46f2-887c-633796ed8338)
