### ISSUE TITLE
Update history status of the local history in case timeout

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2387]
**Describe the task**
Update history status of the local history in case timeout

**Actual:** The history show status = Failed if timeout (2 minutes)
**Expect:** Sync status with Subscan to show correct status

**Comment by lw-cdm** [comment]
- check handleTransactionTimeout in transaction-service/index.ts
- check addHistoryItems in history-service/index.ts

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/7tzKZ9mZ94FbMjb

- [ ] Update text: Time out -> Time-out

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/CQgrWXjkLMXQ58P

- [ ] Update popup message : Transaction timeout -> Transaction timed out


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c9f7bb89-dba0-4b89-b052-91f0c54eb108)



Validation passed in case : 
- Text :  Time-out 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cd536856-e094-40d0-bdf3-c6fceee473ce)


- Do resynchronize history when experiencing time-out


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e3fb0fd2-3765-4750-be7c-0b5c42dd8396)

**Comment by haiyenvu23** [comment]
Version : http://14.224.158.246:8900/s/65pfoiBKMAjrQ6a
Validation passed in case : 
- Popup message :  Transaction timed out

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ec2ced55-f5d5-497e-903c-0337612f1873)

- Tested on Pioneer Network, Aleph Zero Testnet and Moonbase Alpha network with stable network conditions : OK
