### ISSUE TITLE
Get an existential deposit warning when doing a sign transactions

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#239]
Would be nice to get an existential deposit warning when doing a transfer.  I used the Acala bridge to bridge DOT to Acala and they don't do the existential deposit warning when you click max.  I miscalculated fees and ended up having my account reaped.  Would be nice to get a catch on that before I approve the transaction on Subwallet

**Comment by sokol142** [comment]
There is now a warning when sending tokens with a minimum number of transfers (ED).
@hieudd @daodinhhieu Please confirm this quest is still implementing
