### ISSUE TITLE
Do not detect phishing page in case have no account in wallet

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2390]
**Describe the bug**
Do not detect phishing page in case have no account in wallet

**To Reproduce**
1. Install wallet
2. Visit to any phishing page
3. Then observe the screen displayed

Actual: Still show the Welcome screen
Expect: If the wallet have no account then still show phishing page
- Click on "Get me out" on the Detect phishing screen then back to Welcome/Login page

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/XY3qK4pA5d6DKar

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/54b1be9e-21cd-42db-a2d2-c3ed0b6cb008)
