### ISSUE TITLE
WebApp - Show $balance = NaN in the history screen when get price service is down

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2393]
**Describe the bug**
Show $balance = NaN in the history screen when get price service is down

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e8d8452c-d236-4f4b-a263-e8bcb8f479da)

Expect: Show $balance = 0

**Comment by ThaoNguyen998** [comment]
Version test: 
Validation passed on device @Thiendekaco 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/bff7c06d-e881-449d-947c-8d3e89a7a08c)
