### ISSUE TITLE
WebApp - Show incorrect account on the Token detail screen when disconnect account injected

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2394]
**Describe the bug**
Show incorrect account on the Token detail screen when disconnect account injected

**To Reproduce**
1. Open the WebApp
2. Perform connecting extension successfully
3. Switch to All accounts mode
4. Go to the token details screen of any token (Substrate token)
5. Observe the list token displayed
6. Disconnected any Substrate account on Extension
7. Back to token details screen on WebApp then observe the list token displayed again

**Actual:** Still shows account disconnected
- Only show address, not show account name
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b69c15cc-406e-4cd0-8b1f-f1064fcb30e3)

**Expect:** Do not show disconnected account

**Comment by saltict** [comment]
@lw-cdm, method `BalanceMapImpl.removeBalanceItems` will be useful in this case

**Comment by haiyenvu23** [comment]
Version test : https://aa80be5e.subwallet-webapp.pages.dev/
Validation passed

- When connecting to extension : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/975b943c-c7ac-4894-bf89-4e6a26933810)

- When not connected to the extension : 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/85e46153-3c9c-455e-ae35-5dbf1d1422e1)
