### ISSUE TITLE
Fix bug "Invalid character" on earning

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2400]
Fee numbers can sometimes get incorrectly rounded, which causes error to some libs
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/0b34943d-7172-4b92-9656-568ddc794e0d)

**Comment by Sokol142196** [comment]
Version test: https://c6cb796b.subwallet-webapp.pages.dev/

Validation passed 
- Next step successfully
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/af06bfbf-eaab-42f1-9ca3-c7fe3ddc486f)
