### ISSUE TITLE
Extension - Wallet Connect not show connection popup

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2407]

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/H4CmTmoaoFg7Z5G

- [ ] When click Cancel, back to New connection screen
**Expect** : Back to WalletConnect screen



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/08a44046-93c1-470b-920f-7f8fbd800045)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/pfKagRbQBpHfH8m
Validation passed in case : 

- Expired 

- Connect with un-supported network


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c633f495-faff-4ef6-bfc7-c1494a818a57)


- Connect with support network


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cf485edb-a39f-4942-9c00-ac7d3f26ef1c)


- Connect when there is no account of the same type


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8de51957-b704-4474-b0ca-36a773f4dc05)
