### ISSUE TITLE
Hot fix estimating EVM transaction fee

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#2412]

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/CHmzzoGcoRi4Qom

- [ ] Handle case transfer Max on some chain (example: AVAX)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d107c66d-345f-4416-8313-7ec67701c433)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/qgCAJYTq6ey4iww
Still, I reproduce this issue https://github.com/Koniverse/SubWallet-Extension/issues/2412#issuecomment-1870243939

**Comment by Sokol142196** [comment]
> Version test: http://14.224.158.246:8900/s/qgCAJYTq6ey4iww Still, I reproduce this issue [#2412 (comment)](https://github.com/Koniverse/SubWallet-Extension/issues/2412#issuecomment-1870243939)

Resolve later in https://github.com/Koniverse/SubWallet-Extension/issues/1549
