### ISSUE TITLE
Extension - Can not connect Wallet Connect with extension

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2413]
### Describe the task
Can not connection extension via Wallet connect from some app like https://zealy.io/

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/11567273/81f5544a-bd0a-42b0-8500-7f4a5420f0b8)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/11567273/1fa5d0d0-d785-40c7-9e61-4d3e620b957a)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/L62Mw36rR7AzQg4

Validation passed in cases:
- Connected zealy.io with SubWalelt
- Connected zealy.io with SubWalelt via WalletConnect
- Regression test with connecting dApp feature
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/43d33f9a-e73a-4a9a-b95c-bb1fac44a324)
