### ISSUE TITLE
Update balance service

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2416]
Update balance service to the new service architecture like another service.
- [x] Move all balance function from subscrition, state to balance service
- [x] Optimize balance service and resolve some problems
  - [ ] #2352 
- [x] Hanle case cached data (balance and earning)
  - Actual: Sometime, user remove account (reset wallet) but data do not clear -> Show incorrect on UI

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/L9TEiHrngqoCGQH

Validation passed
- Get balance when import account
- Balance when perform transaction(transfer, staking)
- Remove account 
- Switch account
- Reset account/ Reset all
