### ISSUE TITLE
WebApp | Extension - Fix some UI bug (Round 2)

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2417]
Describe the bug
- [x] UI bug in the Manage network screen on Firefox browser
  - Expect: refer Chrome/Brave browser
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/61540400-7094-4ba8-8689-385118ddb3c3)
- [x] Update text in Import by QR code screen: Click the "Scan QR" button, or read [this instruction](https://docs.subwallet.app/main/extension-user-guide/account-management/import-and-restore-an-account#import-by-qr-code), for more details
- [x] Withdraw --> Withdrawable

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/3ee04221-1b7f-4385-9cc3-c04d9910f04e)

- [x] UI bug on webapp mobile when srolling in screens:
  - Homepage (Token list)
  - Earning
  - Crowdloans
  - dApp
  
For example with dApp list:
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/59468fce-1203-4290-b043-45925ffdac6f)

**Comment by Sokol142196** [comment]
**Extension**
Version test: http://14.224.158.246:8900/s/GLitWSNSieSj4cy

- [ ] Improve: Open new tab when click linktext https://docs.subwallet.app/main/extension-user-guide/account-management/import-and-restore-an-account#import-by-qr-code on the import account by QR code screen

**Comment by Sokol142196** [comment]
**Extension**
Version test: http://14.224.158.246:8900/s/xFApyrz5FdMsdaT

Validation passed in cases 1, 2, 3
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/fda2525c-b5dd-4014-9b5d-d76fb32f9e6f)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/923d4543-e812-47a0-81ea-6af6ad3b5f3f)

**Comment by ThaoNguyen998** [comment]
Version test: https://0efc97c2.subwallet-webapp.pages.dev/

- [ ]  UI bug on webapp mobile when srolling in screens

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/5f9cd1e5-ffa7-4c29-a4e1-c4db4292952f)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/7aad1c99-195a-400d-8ddb-77f725aab76c)
