### ISSUE TITLE
[Balance] [PSP] Convert free type from number to string 

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2418]
![Screenshot_2023-12-28_12-38-23.png](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/219a7320-6f19-4651-876d-1ad9149c08d7)

![image.png](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/10220ee2-816f-4b45-8c96-0fac077f6257)

**Comment by bluezdot** [comment]
Resolved in #3041
