### ISSUE TITLE
WebApp - Add T&C for webapp

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2427]
**Describe the task**
Add T&C for webapp

Link doc: https://www.notion.so/subwallet/SubWallet-Th-m-T-C-cho-ng-d-ng-243dabfe04f74347bfc400277655485d?pvs=4
Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=14558-131362&mode=design&t=olAR2RwF7QyBN7Yj-4

**Comment by ThaoNguyen998** [comment]
Version test: https://3f91d546.subwallet-webapp.pages.dev/home/tokens

- [ ] UI bug

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/aba87db3-7031-495c-ad64-37a8e0960b5e)

**Comment by ThaoNguyen998** [comment]
Version test: https://6cfa25a7.subwallet-webapp.pages.dev/

Validation passed in case
- Install
- Create a password
- Change password
- Create with a new seed phrase
