### ISSUE TITLE
Do not display the account in the account details tab in case the entire account balance is locked

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2429]
**Describe the bug** 
UI bug on Token detail screen

**To reproduce the bug**
Actual: Do not show Account on Account detail screen in case account have Transferable = 0 but Lock >0

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/789a8587-e7e6-4d3d-b71f-5bcde645be84)

Check with address: 5HbcGs2QXVAc6Q6eoTzLYNAJWpN17AkCFRLnWDaHCiGYXvNc
Expect: Show Account on the Account detail screen

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/yi6RHPw86MF3iDj

Validation passed
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4a43f828-d6d0-4f59-bd1e-e84ebc334d7b)
