### ISSUE TITLE
Update Astar dapp staking v3

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2433]
Astar is updating dApp staking logic, we need to understand the new logic from stakers side and from dapps side
https://docs.astar.network/docs/learn/dapp-staking/

**Comment by bluezdot** [comment]
logic upgrade discussion: https://forum.astar.network/t/dapps-staking-v3-proposal/4206

**Comment by bluezdot** [comment]
Problem of old dApp staking mechanism: 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/72647326/88d80d68-0a1e-4f3f-a71e-b59bcb3558f5)

**Comment by bluezdot** [comment]
Update logic for all actions in dapp staking v3
Update UI for dapp staking v3
get reward state info

**Comment by nampc1** [comment]
This has been postponed until further notice
