### ISSUE TITLE
WebApp | Extension - Handle the case of default untick checkbox Bond reward when Claim reward

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2438]
**Describe the task**
Handle the case of default untick checkbox Bond reward when Claim reward

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/Fb4ztwxsnjWrSFF

Validation passed 
![2444_Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/01049d29-9bd1-43a9-8aaa-ea309b7c4785)
