### ISSUE TITLE
Extension - Fix some UI bug

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2449]
Describe the bug
**Extension**

- [x] #2481
  - Check with address 5Fnd4pSWZ7bJK3Q8o5GmK4r98iHZ1scqhUehAJHourDWwC2M
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/837934fd-77b2-4831-8ba8-eb43dbd5d413)

- [x] Text "SubWallet"

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a3d6e22a-07b4-4a42-a6bf-e332f6dc420d)

**Comment by Sokol142196** [comment]
@dungnguyen-art please handle this case below

- [ ] Remove the "download seed phrase" option on the export account screen
  - Note: After fixed this issue, need to re-check the "Create a new account" screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/72c7aa9b-3d73-4b12-9894-02d910164739)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/Yxxb6ZENLCHMY8a

- [ ] UI bug on Firefox 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/bd1d1df3-10bf-4f71-9bd3-154c21094abb)

**Comment by dungnguyen-art** [comment]
@Sokol142196 @ThaoNguyen998 @haiyenvu23 I fixed the Extension-related issues, but I have not fixed the Web App-related issues. Please, let's testing it.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/WoQQ53L3XA3y94Z

Validation passed in case : 

- Ui bug on Firefox 
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/19abaf02-96c1-4388-8cd3-178837a513d9)

-  Remove the "download seed phrase" option on the export account screen in Extension
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/adf775fb-2a5b-4045-ad4e-766b45b5699e)

------------------------------------

- [ ] Text "SubWallet"

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6e48814f-b09d-4420-ad48-441b5f9a2b05)

- [ ] UI bug with token name long on Select token screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d8e46eaa-ae3b-47d5-9ae2-8261af2709bb)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/2NCXCCmoEc2iZik
Validation passed in case : 
- UI bug with token name long on Select token screen
- Text "SubWallet"
- Remove the "download seed phrase" option on the export account screen in Extension
- UI bug on Firefox

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/63885f7c-17b1-4f27-90d2-5b77cd0c0565)
