### ISSUE TITLE
Integrate on-ramp feature to buy crypto from fiat currencies

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#245]
**Describe the solution you'd like**

It's important to allow users can buy cryptocurrencies (Eg: DOT, KSM, ...) from fiat currencies directly from SubWallet. 

**Some options for on-ramp feature integration**

- Moonpay (https://www.moonpay.com/)
- Transak (https://transak.com/)

**Comment by hieudd** [comment]
### Update later:
- Supercharge (https://supercharge-fi.notion.site/Supercharge-1-pager-ebf0ed40e8a4428a96cf69e4ec336441)
- Ramp (https://ramp.network/)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./575-merge-build-0.5.5-1661252295987.zip

Please check bugs: Show incorrect information in cases:

- [ ] Switch Account

Steps:
1. Open the extension
2. Stand on All Account (Allow use on any chain), click on Buy button then observe the screen displayed
3. Switch to any account, click on Buy button then observe the screen displayed

Actual: Show the information displayed in the previous step (Showing the Account Selections screen)
- If close popup then re-open, it correctly
![245_bug1](https://user-images.githubusercontent.com/102292476/186569498-e3002f76-7b72-4d3a-91a2-42e01e1ea8e5.gif)

- [ ] Switch Network

Steps:
1. Open the extension
2. Stand on any account, any network (example: polkadot), click on Buy button then observe the screen displayed
3. Switch to another network that unsupported to buy (example: rococo), click on Buy button then observe the screen displayed

Actual: Still enable button "Continue with Transack" and show the information displayed in the previous step
- If close popup then re-open, it correctly
![245_bug2](https://user-images.githubusercontent.com/102292476/186569536-60f42583-54ab-4dd4-9494-d85b5e137b85.gif)


Expected: Showing information correctly

Improvements:
![image](https://user-images.githubusercontent.com/102292476/186568833-ec5e175b-581c-46db-b3bf-a2e171133647.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./575-merge-build-0.5.6-1661416370485.zip

- Bug fixed

Waiting apiKey from Transak to integrate! => Re-test later

**Comment by sokol142** [comment]
Validation passed.
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./575-merge-build-0.5.6-1661855501591.zip

**Comment by sokol142** [comment]
Validation passed.
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./575-merge-build-0.5.6-1662455068019.zip
