### ISSUE TITLE
Extension - Show custom network on the token list when nominate

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2452]
**Describe the bug**
Show custom network on the token list when nominate

**To reproduce the behavior**
Steps:
1. Perform import a Substrate network successfully (example: wss://archive.mainnet.cere.network/ws) 
2. Go to the staking tab then choose nominate for any account
3. On the select token to nominate, observe the list displayed

**Actual:** Show custom token on the list

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ab2315cc-c5e9-4aea-8aae-3d1590656145)

**Expect:** Do not show custom token on this list

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/CemipJWekfyLnQc

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ff43a3d0-4561-4694-98c4-bb1a93171b85)
