### ISSUE TITLE
Integrate Polkadot Ledger app from Zondax

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2453]
https://github.com/Zondax/ledger-polkadot

**Comment by nampc1** [comment]
Update April 23rd:

- [ ] Integrate Zondax API to shorten metadata

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/cncEFC69kAZtQkz

Validation passed in cases:
- Attach account
- Migrate data
- Perform all actions with Legacy and Generic app
