### ISSUE TITLE
Update Chain Service with online Resources (Round 1)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2463]
- [x] Automatically shuffle RPC providers every time the app/web runner restarts (except for light client and custom provider)
- [x] Periodically check new RPC providers to make sure the app stays up-to-date

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/Gw9wBSA2HCEZqKo
Please check issues:

- [ ] Can't load extension when change to light client RPC 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ccdc4c7c-f9be-4613-8842-9cedd8baa29a)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f501aaa6-c01a-4825-985a-660fa198d983)
