### ISSUE TITLE
Extension | WebApp - Support "Request a feature" feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2467]
**Describe the task**
Support "Request a feature" feature

Expect: User click on button "Request a feature" on Setting screen then redirect user to the Send email with information below:
- To: agent@subwallet.app
- Subject: [SubWallet In-app Feedback]
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a35d5932-078c-48f2-99e7-23717eca52e1)

- Refer design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=14361-193742&mode=design&t=moB9BDupCz0rZo0z-4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/NpfAsYxaoCM3SJS
Validation passed 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/34ea62bd-9e8b-4225-bb5d-15b62a26c712)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/3teKwbsRWzc24eB
Validation passed on Chrome and Firefox
