### ISSUE TITLE
Auto import EVM network with source from online resources

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2472]
Auto import network with source from https://chainid.network/chains.json
This feature will help resolve some problems:
- Wallet Connect Dapp not support EVM network
- Connect to not support chain list

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/r9wTSG8AQPyX8qW
Validation passed in cases:
- Connect wallet
- Migrate data in case upgrade version
