### ISSUE TITLE
WebApp - Add content in case search haven't result

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2475]
**Describe the bug**

**To reproduce the bug**
- [x] Select account
- [x] Select token
- [x] Select address book
- [x] ....

Steps: 
1. Go to Select token screen
2. Input token not exist
3. Observe the displayed screen

Actual: Show blank screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/084834b3-1f5f-4d66-bb1c-835ce01a4605)

**Comment by haiyenvu23** [comment]
Version test : https://7def5afc.subwallet-webapp.pages.dev/
Validation passed in cases: 
 - Select account
 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/960cf31d-aa61-4a72-8a0d-ae299f800240)



 - Select token
 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/62ddae84-3f5e-43e0-9561-c5668bb2428c)


 - Select address book
 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a8ea8356-0bb6-442c-b086-39e276ad518a)


 - ....

**Comment by haiyenvu23** [comment]
Version test : https://7def5afc.subwallet-webapp.pages.dev/

- [ ] Button Transfer on Transfer screen 
- [ ] Button Buy now on Buy token screen

Expected result : The button's location is near the fields
Actual result : The button's position is far away from the fields

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4978c269-d10b-4925-97ce-ba377a20d692)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a894e19b-98b0-417d-957a-8026684ab5bb)

**Comment by haiyenvu23** [comment]
Version test : https://8784840b.subwallet-webapp.pages.dev/
Validation passed
