### ISSUE TITLE
WebApp - Add banner for token list page 

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#2482]
![image](https://github.com/Koniverse/SubWallet-Extension/assets/92499846/8bc48362-69ca-4d87-8001-01d8f3a49613)

**Comment by ThaoNguyen998** [comment]
Version test: https://47fe9cd2.subwallet-webapp.pages.dev/home/tokens/detail/DOT-Polkadot

Validation passed.
![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/95135080-bab2-447a-be5d-190142e92093)

**Comment by Sokol142196** [comment]
- [ ] Do not show footer in token detail screen in case responsive
  - Actual: Open page on mobile device then click on Search button on header then observe the screen displayed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8b10ee35-136e-4c36-ac00-1978786ec5af)
