### ISSUE TITLE
Support Krest staking

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2492]
https://docs.peaq.network/docs/node-operators/become-delegator/
https://www.peaq.network/blog/krest-expands-collator-and-delegator-pools

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/TD8Kdmsba87s2Y7

Validation passed in cases:
- Show staking item
- Stake/stke more (approve transaction
- Unstake (approve transaction)
- Withdraw (follow-up then check later)

**Notes:** This network same as Amplitude
- Max validator = 1
- Do not support Cancel unstake
