### ISSUE TITLE
Extension - Change "Claim rewards" to "Check rewards" for dApp staking

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2497]
**Describe the task**
Change "Claim rewards" to "Check rewards" for dApp staking

**Expect:**
- Change "Claim rewards" to "Check rewards"
- Always enable button "Check rewards"
- Click on "Check rewards" button then navigate to Astar portal (https://portal.astar.network/astar/dapp-staking/discover)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/7p6CXegdjaActH2
- Validation passed in case:
- Change "Claim rewards" to "Check rewards"
- Always enable button "Check rewards"
- Check the case for stake types other than dApp, the button is still displayed as "Claim rewards"
- Click on "Check rewards" button with watch-only account
- Click on "Check rewards" button with Polkadot Vault account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8918385a-3509-48df-9568-e428a96ebbb6)
