### ISSUE TITLE
WebApp - Update earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2498]
**Describe the task**
Update earning feature
- [x] Migrate staking and update new UI
- [x] Update unstake period of the StellaSwap 
  - Expect: Show message "Once unstaked, your funds will be available for withdrawal after upto 28 days"

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f31cd8be-2c78-4201-8483-207c55775cb5)

- [x] Support withdraw action for StellaSwap

**Comment by haiyenvu23** [comment]
Version test : https://webapp-demo.subwallet-webapp.pages.dev/welcome

- [ ] UI bug when changing responsive ( on Chrome)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/784fcabf-d66e-4526-8e9c-1a0078ccb905)

- [ ] Can't scroll on Start earning screen when changing screen size
![1122](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/46e2aad7-7a02-44cc-b7e4-9e2d029f9c47)

- [ ] Mainnet token list is not displayed when selecting to search for both mainnet and testnet
![2233](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/384284a0-fc62-451e-843f-fb9032e1e8e0)

- [ ] Don't show popup Earning infor and button Stake  when on small screen
![3434](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5f9a83f3-10d0-492b-a293-9b7fd23632a5)

**Comment by ThaoNguyen998** [comment]
Version test: https://webapp-demo.subwallet-webapp.pages.dev/

- [ ] Hide button Cancel unstake in case earning type not support

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/bff1c94f-f093-44b9-86b8-bd3eab64a821)

- [ ] Disable action when submit
- [ ] Re-check connect when earning Ledger EVM account 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a3344be4-fb34-40f2-bb7a-e434781bfd15)

**Comment by Sokol142196** [comment]
Bug related to this feature in issue https://github.com/Koniverse/SubWallet-Extension/issues/2652
