### ISSUE TITLE
Extension - Do not show Signature popup in case not enough balance to cover gas fee

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2501]
**Describe the bug**
Do not show Signature popup in case not enough balance to cover gas fee
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ec24899a-4d20-48a5-a3b7-75d3288699df)

To reproduce the behavior
For example with earning action
Steps:
1. Open SubWallet dashboard
2. Connect to SubWallet extension successfully _(Connected account have GLMR < 0.018)_
3. Perform earning with SubWallet then observe the screen display when approve transaction 

Actual: Do not show popup to sign to approve transaction

Link content : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#c4d244ebfc2049f4b99baa0bf2cc9c2a

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/fSkEWaPMBCScpSs

- [ ] In case enter a receiving address that is different from the sending address type


![Image](https://github.com/user-attachments/assets/26620367-d573-4d4e-9787-3262627f5671)

- [ ] In case enter receiving address invalid


![Image](https://github.com/user-attachments/assets/9c56c562-80ee-45bd-b944-fc8ea4617f7c)

- [ ] In case input Amount invalid

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/W8CkBtEDGDH8Ggs

- [ ] Update message for some case


![Image](https://github.com/user-attachments/assets/a6a4ccda-3307-4cf3-b7ff-07fdf01bf8ca)

- [ ] Change content and icon for button
Actual : 


![Image](https://github.com/user-attachments/assets/3e0edc60-02e1-485a-89c7-c5b410899564)

Expect : 


![Image](https://github.com/user-attachments/assets/574ed032-2f8f-4a03-9c46-1f46b9987d7e)

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/APz9WYrpMambSib
- (Firefox): http://14.224.129.242:8900/s/8ryCwrmrYnAARnd
Link dApp : http://192.168.10.103:9011/
Link content : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#c4d244ebfc2049f4b99baa0bf2cc9c2a
Validation passed in case : 
- Install/Update version 
- Check perform sign with some cases
