### ISSUE TITLE
Re-check issue can not connect SubWallet extension

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2502]
**Describe the task**
Re-check issue can not connect SubWallet extension

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8c91c245-5e92-4684-9f8b-6f07081a3728)

**Comment by haiyenvu23** [comment]
List of dApps to test connection : https://docs.subwallet.app/main/integration/dapp-integrations
Validation passed in case : 
- Connect dApp with SubWallet extension
- Connect dApp with SubWallet and many different extensions
**NOTE** : 
- Khi kết nối dApp đầu tiên với Extension thì sẽ có popup Connect with SubWallet nhảy lên.
- Nếu không thực hiện thao tác gì với popup đó, sau đó thực hiện kết nối dApp thứ 2 với extension thì popup sẽ không hiện lên. Muốn xem được màn Connect with SubWallet của dApp thứ 2 thì phải mở extension và thực hiện hành động với dApp đầu tiên xong mới đến dApp thứ 2 này
- Như extension của Talisman hay Polkadot js, khi ấn kết nối dApp nào thì sẽ hiển thị popup của dApp đó lên
