### ISSUE TITLE
Support TAO in-app staking

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#2505]
- Documents: https://docs.bittensor.com/delegation
- Explorer: https://x.taostats.io/#delegation
- Delegates list: https://[raw.githubusercontent.com/opentensor/bittensor-delegates/main/public/delegates.json](https://raw.githubusercontent.com/opentensor/bittensor-delegates/main/public/delegates.json)

**Comment by bluezdot** [comment]
- [ ] Recheck to update middleware service

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/5zxHDpHBNT4XN4J

- [ ] Don't show list validator
![Image](https://github.com/user-attachments/assets/dfc14e0b-ad57-4445-a819-9f95e485576d)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/CBmyaL5XCgx8AmD

- [ ] Don't show nominator infor 
Actual : 
![Image](https://github.com/user-attachments/assets/47078868-aa4c-416c-87f9-f6fac6d6f221)

Expect : Show nominator infor

- [ ] Re-check time reward
![Image](https://github.com/user-attachments/assets/bdcfdad3-633a-4773-97ff-eec5a3d1779b)

- [ ] UI 
Actual : Show Amount stake
![Image](https://github.com/user-attachments/assets/547f9102-2144-4442-8d41-3b9548ace83a)

Expect : Don't show Amount stake

- [ ] Don't update infor when perform unstake
Actual : 
![Image](https://github.com/user-attachments/assets/d8f1210c-6b6f-46b4-ae52-ee968f9b6ba8)

Expect : Update infor when unstake

**Comment by nampc1** [comment]
https://docs.taostats.io/docs/calculator

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/pBgswd2q74MyYKJ

- [ ] Still do not update Testnet tag
- [ ] Check balance in case of multiple stake/multiple validators/change of validators
  - Actual: Show incorrect stake balance (Check with account 5FCRFMiDpQNfExcnYYK9rfMjhebSn4YS9we7EGZnm4iXvMdM) 
  - Expect: Show correct stake balance

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/ariHzB2QGijk7GK

- [ ] Do not show earning options in case Bittensor network is turn off 
  To reproduce this behavior
  1. Install extension 
  2. Created/Imported account successful
  3. Go to the Earning options screen
  4. Search TAO then observe the screen displayed
  
  - **Actual**: Do not show Bittensor (Mainnet + Testnet) earning options
  - **Expect**: Always show earning options
  ![image](https://github.com/user-attachments/assets/9bced9e6-2121-47aa-8cf4-205af1410e26)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/GJsFiT4wkw2MtFH

- [ ] Update number of validators can choose
Actual 
![Image](https://github.com/user-attachments/assets/7c82ca34-b1c8-486d-910d-91941588c10b)
Expect : Only choose 1 validator
