### ISSUE TITLE
WebApp - Do not show footer in token detail screen in case responsive

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2509]
**Describe the task**
Do not show footer in token detail screen in case responsive
  - Actual: Open page on mobile device then click on Search button on header then observe the screen displayed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8b10ee35-136e-4c36-ac00-1978786ec5af)

**Comment by haiyenvu23** [comment]
Version test : https://585e7f47.subwallet-webapp.pages.dev/

- [ ] Re-check responsive on Chrome

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/33fc1112-2841-446d-a370-5ab3f2b47587)


- [ ] Added footer for some token detail screens according to this list

[Dot-tokens.xlsx](https://github.com/Koniverse/SubWallet-Extension/files/14095227/Dot-tokens.xlsx)

**Comment by haiyenvu23** [comment]
Version test : https://be2cc687.subwallet-webapp.pages.dev/

Validation passed
