### ISSUE TITLE
Research swap pallet on asset hub

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2512]
Research `assetConversion` pallet

**Comment by nampc1** [comment]
- [ ] Read source code of `assetConversion` pallet
- [ ] Estimate workload and timeline
- [ ] Implement into swap service

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/f37q93wKfz6jmWf

Please check issues:

- [ ] Add warning in case low liquidity
- [ ] Add logo for Provider
- [ ] Improve validate show swap quote
- [ ] Show incorrect swap quote rate when the input amount is a small number
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d6fe3551-0837-4315-96ce-5af099f07dbc)

- [ ] Confirm the default slippage
- [ ] Handle the ED when swap
  - Actual: Swap all then transaction failed: https://assethub-polkadot.subscan.io/extrinsic/0xb70a57d4865f0920cf488d3831e3904c48da235895496f7c943cb5645a86a55e  
  - Expect: Validate ED

**Comment by Sokol142196** [comment]
Version test: https://5af8730e.subwallet-webapp.pages.dev/

- [ ] Show incorrect message when change swap pair
  - Reproduce: Change from DOT --> USDC to USDC --> DOT with small amount
  - Actual: Show incorrect message
  - Expect: If characters > decimals then convert to 0
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/089c9e46-c2dd-4053-bc77-008bbd9c0666)

- [ ] Validate incorrect with other provider

**Comment by Sokol142196** [comment]
Version test: https://c20004c7.subwallet-webapp.pages.dev/ 
Validation passed in cases:
![swap-USDT-assetHub](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/74324529-d70e-4277-bbe2-fa3087ae3983)

- Swap DOT (Asset Hub) --> USDC: https://assethub-polkadot.subscan.io/extrinsic/0x4ef1e42e466ba543d501f2dd97159790df5d1823a6807ab15314999ef6f4f1df 
- Swap DOT (Asset Hub) --> USDt: https://assethub-polkadot.subscan.io/extrinsic/0xd55969e4894ae88f9e13d47a1867da0e791f6f034c45494a5467b5b1a39da771 
- Swap USDC (Asset Hub) --> DOT: https://assethub-polkadot.subscan.io/extrinsic/0x9c7cc47c28713c75742d28697c236a59f6fb433d5c061868456c5ff2c0e1b66a 
- Swap USDt (Asset Hub) --> DOT: https://assethub-polkadot.subscan.io/extrinsic/0xca56f9cb95a8acdc760202619e12e01ef54d29f8808c0f9b79fc046600e19037
- Swap DOT (Asset Hub) with XCM
- Re-check all validate
  - Amount = 0
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/806c98f4-ef4b-414d-8ac7-a61290886a97)

  - Insufficient balance
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2c3b4381-a68f-4684-8ac5-e9fd4e8408ff)

  - ED of the local token
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9aa73490-eff5-474f-b1c1-93dc11ab07f9)
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/33bd0373-9385-4e24-adbb-8b446af60de1)

  - Change swap pair
- Re-check other provider
