### ISSUE TITLE
Bug can not send fund on Moonbeam with Polkadot Vault account

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2517]
Polkadot Vault can not sign and react transaction from Moonbeam
- After check I saw that:
  - SubWallet is using EVM transaction on send fund (Moonbeam) => Should update substrate interface if it is Polkadot Vault account
   - Polkadot Vault also get this problems. Please follow up this topic https://github.com/paritytech/parity-signer/issues/2134

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3056
