### ISSUE TITLE
Show incorrect tokens on the balance screen in case an account with the type 'ed25519' is imported

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#2518]
Actual: 
Import an account with the type 'ed25519' and then check the balance screen. Ethereum tokens still show.

Expect:
Hide Ethereum tokens on  balance screen

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/kpXNBHKyTC4mqzw
Validation passed
