### ISSUE TITLE
Improve UI for Ledger Account Recovery Tool

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2521]
**Describe the task**

- [x] Update error mesage when input account address EVM type on Basic mode
- Actual : Show Account not found screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/9a5e8a7f-4e5f-4413-9d73-9ad8236c6563)
- Expect : Show error message on Account address field : " Invalid address"

- [x] When edit password on Password field, current password deleted
- Actual : The data entered in confirm password remains the same
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/b0a7cdff-3561-4ae6-9097-7ac8cf1042f6)

- Expect : The data entered in Confirm password field deleted

- [x] Improve when input account index, address index 
- Actual : Can input letters, characters
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/89e5dead-f4fc-4d27-8f95-b444fee915f6)
- Expect : Can't input letters, characters

- [x] Responsive bug on Firefox 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/605c3aa0-0573-4c91-866d-f24caf1f0bb6)

**Comment by haiyenvu23** [comment]
Version test :  https://ledger-recovery.subwallet.app/
                      https://github.com/Koniverse/Ledger-Account-Recovery-Tool/releases

Validation passed

**Comment by ThaoNguyen998** [comment]
@dungnguyen-art Please help me fix some UI bug

- [ ] Logo, Help

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/00356d82-54cc-4f7d-b510-8db509b91e17)

- UI when the screen small

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/beb6b16d-0d93-4275-8d0c-1675212ecfbe)

**Comment by ThaoNguyen998** [comment]
Version test: [master-build.zip](https://github.com/Koniverse/SubWallet-Extension/files/14150845/master-build.zip)
Validation passed.
