### ISSUE TITLE
WebApp - Update RPC and XCM channels online

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2523]
**Describe the task**
Update RPC and XCM channels online
- Check random RPC
- Check hide XCM channels

**Comment by haiyenvu23** [comment]
Version test : https://5dadb22f.subwallet-webapp.pages.dev/
Validation passed in case : 
- Check random RPC
- Check hide XCM channels
- Check custom RPC, light client
