### ISSUE TITLE
Fix bug sending AVL on Avail Goldberg testnet

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2538]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/ac9b61c2-d1a4-453a-bbbd-743990c9cee5)

**Comment by S2kael** [comment]
Backup RPC: wss://san1ty.avail.tools/ws

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/MTbDymaYW9GqF6B

Validation passed 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6f2a590e-aef0-4062-a0a5-ac8c57ba3cb5)

**Comment by Sokol142196** [comment]
- [ ] Check bug join pool failed
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0e5f10f2-c150-4a18-a2e6-324ef476d8fb)

**Comment by nampc1** [comment]
This is related to pool being maxed out on members

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/grYZQyc67nFemaA

- [ ] Do not send 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7858a2c3-3db1-4560-9f21-d999479365fb)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3f4dbf09-b34d-492c-9b80-4b341853cdaf)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/SgirNRRsi6WXM6Q

Validation passed in cases:
- Send normal
- Send Max
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1aa52d23-81c3-4e88-bd5d-abf076bc7786)

Re-check direct nomination and nomination pool
