### ISSUE TITLE
Add feature to allow first-time users to import their Metamask private keys

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#254]
**Is your feature request related to a problem? Please describe.**

When I download and install SubWallet for the first time, there's no option for me to import my Metamask private key into SubWallet.

<img width="457" alt="Screen Shot 2022-05-11 at 14 32 51" src="https://user-images.githubusercontent.com/102496727/167794336-fe3641c2-8e65-46a1-af70-95cd2bbd30eb.png">

**Describe the solution you'd like**
There should be an option for first-time users to import their Metamask private keys into SubWallet. Please add this feature. Thanks.

<img width="460" alt="Screen Shot 2022-05-11 at 14 32 38" src="https://user-images.githubusercontent.com/102496727/167794480-c814832d-f692-43e1-b483-e76b6e90462d.png">

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./547-merge-build-0.5.4-1660201510563.zip

Validation passed!
