### ISSUE TITLE
Fix bug not showing GENS token from Genshiro

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2540]
The logic for fetching balance has been updated

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/fCLeHgMaNCgkFC7
Validation passed
- Notes: Do not support transfer GENS token
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/aa9da5e2-6844-46a7-a782-dd2cbafe48ee)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/766ef9d0-2bfb-442a-9b2f-8457b5c1f053)
