### ISSUE TITLE
Update unstake info for Krest

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2544]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/ff5fded0-6590-415d-8833-414eaf2ea969)

**Comment by S2kael** [comment]
- Select validator: No problem
- Fetching account staking data: Have log error -> Fixed

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/j2F7cAc2iLsy8SZ

Validation passed in cases:
- Do not show log error
- Re-test stake (to approve step)

**Comment by S2kael** [comment]
- Update unstaking request info: now can show multiple unstaking requests (previous show 1 record only)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/GqCkt5np4NSSzts

Validation passed for cases:
- Show unsaking info with multi-request
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/13bfc995-74da-46f5-9440-9e801be66824)
- Re-test unstake, stake, withdraw action (Approve step)
- Re-test showing with Amplitude
