### ISSUE TITLE
Extension - Add popup want to user claim reward when Astar update dApp staking v3

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2545]
**Is your feature request related to a problem? Please describe.**
Add popup want to user claim reward when Astar update dApp staking v3
- Case 1: Show when open app
  - Condition to show: User have dApp staking 
- Case 2: User click on dApp staking details with dApp staking (ASTR, SBY, SDN)

Content: 
- Header: Claim ASTR staking rewards
- Message: Astar dApp staking V3 is launching in early February. Make sure to claim any ASTR rewards before the launch or they will be lost.
  - Add hyperlink to "Astar dApp staking V3"
  - Hyperlink: https://docs.astar.network/docs/learn/dapp-staking/dapp-staking-faq/#q-what-about-unclaimed-rewards
- Button: Dismiss / Claim now
  - Dismiss: Close popup
  - Claim now: Redirect user to Astar Portal (https://portal.astar.network/)
  
  Refer design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=16743-144961&mode=design&t=FefFPGnsCxNeJ4Xq-4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/bdqoJkWHfY364YX

Validation passed in case : 
- Update version
- Open app
- User click on dApp staking details

- [ ] UI bug 
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1272f3c6-3d3a-4e64-ae5d-387d325c951c)

- [ ] When start earning with dApp staking (ASTR, SBY, SDN), don't show popup


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/b2f7079e-174d-4dbb-9d2a-4ead096a58d5)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/xeekc7WP5JHZwiJ

Validation passed in case : 
- UI
- Update version
- Open new app
- User click on dApp staking details
- Check case when user click on non-dApp staking details
- Banner Earn now must be displayed the next time you open the app
- Check case update version while displaying the banner



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/795e75bb-fad8-4fcf-ac42-cc9559423557)
