### ISSUE TITLE
Improve data fetching for better performance and UX

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#255]
Description:

- [x] - Caching data in chrome store
- [x] - Show most recent data instead of loading icon in case of connection failure
- [x] - Remove some cron and subscription jobs when idling
- [x] - Allow user to manually refresh data
- [x] - Add refresh button for network can't connect
- [x] - Add update endpoint button for network can't connect

**Comment by sokol142** [comment]
Pls check Transaction History in the fist time after upgrade extension
Actual: Display transaction history incorrect (see file attachment below)
![image](https://user-images.githubusercontent.com/102292476/171814587-ae8fe156-9fcf-4831-86aa-8985c6bbf029.png)

**Comment by sokol142** [comment]
Check issues:

- [ ] Informations is incorrect when switch account in case turn on - turn off extension
Steps:
1. Open the extension (both expand & popup mode)
2. Current Account = All Account
3. Turn off the extension for 3 - 5 minutes
4. Turn on the extension
5. Switch form All Account to Account A
6. Observe the information being displayed
Actual: Still showing information of the All Account even though current account is Account A
Expected: display data is correct
![255_cf](https://user-images.githubusercontent.com/102292476/175893129-7ab5bb29-6c2d-42ef-a716-eab945885db1.gif)

- [ ] Still displaying NFT of the network which is inactive
Steps:
1. Open the extension & switch to any network (example: switch to Kusama)
2. Go to NFTs tab then observe NFTs being displayed
3. Go to Custom Network screen, then disconnect Kusama chain
4. Back to NFT tabs then observe NFTs being displayed again
Actual: Still displaying NFT
![255_cf_2](https://user-images.githubusercontent.com/102292476/175894660-8e6bebe8-b857-47c7-9009-8d402d367019.gif)

- [ ] Displaying wrong information on balance, NFT,... when switching accounts after a period of opening without using extension
Steps:
1. Open the extension on expand mode
2. Switch from Account A to Account B then observe the balance, tokens, NFTs,...
3. Still open the extension but don't use it for 3 - 5 minutes
4. Back to the extension, switch from Account B to Account A then check data being displayed
Actual: Still showing information of the Account B even though current account is Account A
![225_Exxpandmode_SwitchAcc](https://user-images.githubusercontent.com/102292476/175896234-d2b11c1f-83e4-438f-94d0-0cf1d72d7a86.gif)

- [ ] Still showing sent NFT
Steps:
1. Open the extension on Firefox browser
2. Switch to Account A & check the NFT is showing 
3. Open the extension on Chrome browser, still with Account A on, the user sends any NFT from Account A to another Account
4. After send NFT successfully, back to Firefox browser then check NFT is showing
5. Perform switch to another account then check NFT is showing
Actual: 
- The sent NFT is still displayed in Account A
- Even though the switch account is still showing the sent NFT
- NFT is updated only when user performing Reload Extension
![image](https://user-images.githubusercontent.com/102292476/175897598-37fff702-8dfe-4f11-b3ba-15820231de94.png)

**Comment by sokol142** [comment]
Please check:
- [ ] EVM chain balance updated continuously
![255_LoadBalance](https://user-images.githubusercontent.com/102292476/176083585-9464cfb3-d6cb-4494-8ce0-3cf3a7b3366c.gif)

Note for tester: Check this case after dev fixed bug "Still showing sent NFT"
- [ ] The sender address shows wrong balance after send fund successfully
**Steps:**
1. Open the extension
2. Switch to Account A and check its balance
3. Go to the Send fund screen
4. Select tokens = ROC then perform send fund successfully
5. Back to Homepage & check this account's ROC balance
**Actual:**
- If the receiving address and sending address are on the same session then ROC balance = receipt address balance
- If the receiving address and sending address are on the difference session then ROC balance = All balance
**Expected:** Shows correct balance
![255_Wrongbalance](https://user-images.githubusercontent.com/102292476/176083127-8c500b7b-3437-44b9-a9d1-1c8970923742.gif)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./346-merge-build-0.4.7-1656662903820.zip
Pls check this issues:
- [ ] EVM accounts update Sub-token, balance is delayed when user perform:
- Switch Account
- Turn on popup
- Import tokens
- Network Setting
See this file attachment: https://www.loom.com/share/e6bafbe5a51a4f3bae21cd3766c0bfec

**Comment by sokol142** [comment]
Version test:

Please check this issue:
- [ ] Can not loading information in case the browser shuts down improperly

**Steps:**
1. Open the expand extension on browser Brave
2. Use extension
3. Shut down the device (case: the browser shuts down improperly)
4. Reopen your device & browser Brave
5. Then observe the information displayed

**Actual:** Can not load the information
- User must be reload extension or open the popup extension to load the information
**Expected:** Load & show correct information
(File record step 4, 5:
![346_loading](https://user-images.githubusercontent.com/102292476/180723666-7aaeaacf-90e6-4b0d-80c9-27e18b69b51b.gif)
