### ISSUE TITLE
Optimize performance by separate chain status and chain state

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2550]
- [x] Separate chain state vs chain status
- [x] Extension
- [x] WebApp
- [x] Web-Runner
- [x] Mobile

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/ATdRQWeHHWSmFdb

Validation passed in case:
- Check balance, NFT, Earning positions when turn on/off network
- Enable network when import account/NFT/ Token, Transfer, Earning, connect dApp
