### ISSUE TITLE
WebApp - Support marketing campaign feature for webapp

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2552]
**Describe the task**
Support marketing campaign feature for webapp

Ticket: https://discord.com/channels/447263980252037141/1240282302735716554
BA doc: https://www.notion.so/subwallet/T-ng-h-p-c-c-t-nh-n-ng-support-cho-Maketing-Campaign-5cf18ae82ec04613b7060d153f85840a?pvs=4

- [ ] App banner
  - [ ] Show on positions
    - [x] Portfolio
    - [x] Token details
    - [x] Earning positions, earning options
    - [x] NFT
    - [x] Crowdloan
  - [ ] Show with conditions
    - [ ] Has balance
    - [ ] Has earning position
    - [ ] Has NFT
    - [ ] Has money
    - [ ] Has crowdloan
  - [ ] Navigate to Instruction

**Comment by haiyenvu23** [comment]
Version test : https://48381a31.subwallet-webapp.pages.dev/home/tokens

- [ ] Don't show banner in case responsive


![Image](https://github.com/user-attachments/assets/2dc1439f-79a1-4572-9672-dcdb1fbe33a4)

**Comment by haiyenvu23** [comment]
Version test : https://4e75e5f0.subwallet-webapp.pages.dev/home/tokens

- [ ] Re-check border for banner


![Image](https://github.com/user-attachments/assets/f305b525-f96c-4b8e-9b19-a8ee9895ef20)

- [ ] Re-check size for banner


![Image](https://github.com/user-attachments/assets/aa0a9eef-a3f8-4455-96a5-e41cde61619a)

**Comment by haiyenvu23** [comment]
Version test : https://1b285735.subwallet-webapp.pages.dev/home/earning

- [ ] Ui bug on slide 


![Image](https://github.com/user-attachments/assets/056dcf2f-4100-4d9e-b33b-c75bd7d3cfb7)

**Comment by haiyenvu23** [comment]
Version test : https://9eadc23c.subwallet-webapp.pages.dev/home/tokens

- [ ] Re-check UI case responsive


![Image](https://github.com/user-attachments/assets/0a52c757-92f2-41c1-af15-5d458a8002fb)

- [ ] Setup banner slide running time = 7s
Actual : Time = 2s

- [ ] Update padding for pagination
Expect : top = 6px, bot = 8px, margin = 8px


![Image](https://github.com/user-attachments/assets/0e2a92ff-7542-44cd-8d51-e48180c046ba)

**Comment by haiyenvu23** [comment]
Version test : https://69011d97.subwallet-webapp.pages.dev/home/tokens
Validation passed in case : 
- Responsive
- Show banner on positions : 
 - Portfolio
 

![Image](https://github.com/user-attachments/assets/eded07bb-97da-4598-81e2-aaf871bba11f)


 - Token details
 

![Image](https://github.com/user-attachments/assets/c8cebbfc-2bdf-4bd1-8a05-208c80b6512a)


 - Earning positions, earning options
 

![Image](https://github.com/user-attachments/assets/d7e800c2-eacf-4a63-a4fe-e4f67c44c3b8)


 - NFT


![Image](https://github.com/user-attachments/assets/c9d66035-bd41-484e-b0b3-3d9e9ecfdc6b)


 - Crowdloan
 

![Image](https://github.com/user-attachments/assets/35d80651-5f64-478b-9443-ad1ef18a6852)
