### ISSUE TITLE
Add show/hide password for case input password

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2555]

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/i6EckoCi889yqEY

- [ ] Add show/hide on Create a password screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1fddbf45-928d-40d1-9210-fe9f871ceded)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/x5emgEJqe9mcN89
Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/50cbcb63-b6b7-45ae-94cd-d513ce8d9357)
