### ISSUE TITLE
[Extension - Earning] Bugs related to the earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2558]
**Describe the bug**
Bugs related to the earning feature
**UI bugs**
- [x] Error page when click on Erning tab in case account have no earning option
- [x] Navigate incorrect when switch account
  To reproduce:
  1. Go to the Earning options screen of the Account A
  2. Switch to Account B (Account B have earning positions)
  3. Observe the screen displayed

  Actual: Still show eaning options screen
  Expect:
    - If Account B has earning position then show Earning positions screen
    - If Account B has no earning position then show Earning options screen

- [x] Do not show sub-logo of the StellaSwap
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/76922d0e-c6b0-44f2-b8da-63f1f9d3c505)

- [x] Change "Stellaswap" to "StellaSwap"
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/bfd4bf18-315d-4ff5-86b8-10f0a18e2a3f)

- [x] Update position details of the dApp staking 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/58c99a56-2bc5-441d-bdb4-8ee732d37b4c)

------
**Logic bugs**

- [x] Do not load pool info after connected network
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d90997f0-926e-490d-a8b7-c00c936d27db)

------
Improve

- [x] Add reload button on header of the Your earning positions screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/45d1ed63-bb52-4513-a335-e9d157b22e6e)

- [x] Merge "transaction type" = "leave pool"/ "unbond" to "unstake" in the history details screen
  - Actual: Show "transaction type" = "Leave pool"
  - Expect: Show "transaction type" = "Unstake"

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/CrCm4XfPzr28Rs4

- [ ] With new account, displays an error screen when clicking Earning

![1122](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/32653398-bbe8-4b8e-97c4-afef59d26db5)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/gS2WBkXeNLoadWm

Validation passed in case : 

**UI bugs**
- Error page when click on Erning tab in case account have no earning option
- Navigate incorrect when switch account
- Do not show sub-logo of the StellaSwap
- Update position details of the dApp staking
- With new account, displays an error screen when clicking Earning/Displays an error screen when clicking +

--------
**Logic bugs**
- Do not load pool info after connected network

------------
- [ ] Change "Stellaswap" -> "StellaSwap"
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/02dfd52d-2270-41f5-aff1-4dba294ed622)

- [ ] UI bug when click icon reload with a account mode
      Expect : When you click reload, you must stay at the Your earning positions screen
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1e6e35b5-8e29-4a8f-84b6-7e43f75d81d3)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/gp4YWrnHETx2yR6
Please check issues:

- [ ] Do not show earning options if networks is turn off
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6db9fbe2-a210-40f0-bb47-af706a0061fe)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/aJkW5iom5JPxg8G

- [ ] Do not stake to earn with Liquid staking and Lending staking on Firefox browser
- [ ] Show incorrect message in case input Amount > Transferable > 0
- [ ] Ui bug on Unstake screen
![Pasted Graphic](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4da4196c-3964-4335-b5e5-c0c76c141d11)
