### ISSUE TITLE
Update staking APY formula for relaychain

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2563]
Refer to APY formula from Polkadot staking dashboard

**Comment by nampc1** [comment]
Check the following files:
`useAverageRewardRate`
`useErasPerDay`

**Comment by bluezdot** [comment]
Check file:
`ValidatorEntries`

**Comment by bluezdot** [comment]
summarize formula: `simpleAPY = 365 * ExpectedEraReward * ErasPerDay / totalIssurance`

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/LZBJKT97YWW3WgN

Validation passed in cases:
- Install
- Upgrade version

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/494d229a-5dab-4863-ab9b-0ea07ddc183e)
