### ISSUE TITLE
Fix bug showing withdrawal time on unstaking

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2581]
Withdrawal time fluctuates randomly on Vara

**Comment by bluezdot** [comment]
![image](https://github.com/Koniverse/SubWallet-Extension/assets/72647326/d0b0e49c-8900-4b52-9300-bd6a9c315c80)

CurrentEra usually switches to a new Era a short time earlier than predicted, while activeEra changes exactly according to timestamp.

**Comment by bluezdot** [comment]
critical-error: Withdrawal at the start of target era, not the end of target era

**Comment by bluezdot** [comment]
<img width="245" alt="image" src="https://github.com/Koniverse/SubWallet-Extension/assets/72647326/6fd9e0fb-4be5-449b-82ec-c25f1550663d">
EraProgess on AlephZero remain 0.

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/KktTZeZz5wCfka9

Please check issues:

- [ ] Still show "Withdrawable in 0 hr"

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1fa12ba7-35fa-45b1-9e7b-a5ea319493c9)

- [ ] Do not auto update withdrawable time 
  - Actual: Example with nomination pool, i perform reloading or switching acc then data updated

**Comment by bluezdot** [comment]
todo:
Check and update timestamp for all staking chains later:
- [ ] bifrost
- [ ] parallel
- [ ] amplitude
- [ ] astar
- [ ] para-chain

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/DpA8dkgGbcYH2MF

Please check issues:

- [ ] Show withdraw time with 60m/ 24hr

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5b840031-cc73-40de-96cc-88e2aa6a5665)

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1f732cbd-9061-4766-b778-c7db68129003)

- [ ] Re-check case update withdraw time with parachain

**Comment by bluezdot** [comment]
todo:

- [ ] Fix case 60m/24hr by still using round, and force the last 30 s to return 1 m. Alternative solution: display to ['m', 's'] unit

**Comment by Sokol142196** [comment]
- [ ] Handle case auto-withdraw
  - Actual: Show message "Available for withdrawal" => confuse 
  - Expect: Discuss more
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3ecf603a-4ed0-4e5a-b6ab-3b72958eab7b)

- [ ] Hanle case normal unstake of the liquid staking
  - Actual: Incorrect countdown: https://github.com/Koniverse/SubWallet-Extension/issues/2652

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/YbddQH66zRQpQTN 

- [ ] Handle case automatic withdrawal (Paralellel, Bifrost)
  - Actual: Still show Withdraw button
  - Expect: Do not show these highlight in this picture
  
   ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5311c1ca-ee16-4479-bed7-0d4728494d76)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/ptSNfKwQ9BwFQBx

Validation passed in cases:
- Nomination Pool: countdown withdraw time
- Direct Nomination Relaychain: countdown withdraw time
- Direct Nomination Parachain: countdown withdraw time
- Liquid staking
  - Withdraw type = Manually -> Show "Waiting for withdrawal"
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/591de200-35fc-415a-b71a-86b0b81e9687)

  - Withdraw type = Automatic -> Show "Automatic withdrawal"
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/436c3d0b-3b65-4abf-80c9-42b268070f69)


Re-check lending staking: Do not show Unstake info
