### ISSUE TITLE
Integrate Continuum network

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2585]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcontinuum-rpc-1.metaverse.network%2Fwss#/explorer

- [x] Support showing NUUM token
- [x] Support sending NUUM token
- [x] Support NFT on Continuum

Continuum also supports NFT

**Comment by bluezdot** [comment]
Account has NFT: 5CSq2pKDUZD8xKfyqNBfdmTt7kmVnH41MFiED7z9QQnaoQnF

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2658
