### ISSUE TITLE
Bug can't start uniswap with SubWallet

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2588]
1. Can not work with Uniswap
- Install and enable only SubWallet
- Open https://app.uniswap.org/swap
Actual: Get error:
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/11567273/2786025e-9e10-4573-b027-870b088431bf)
Expect: Dont get error

2. Can not reconnect
- *** install MetaMask to fix 1
- Connect with SubWallet
- Reload
- Actual: Not show previous connected
- Expect: Continue with previous connected account

Recheck:
- [x] Connect EIP6963
- [x] Connect Uniswap
- [x] Connect and test with some common EVM DApp

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/jr4FT2bpMcM9Bsm

Validation passed in cases:
- Connect EIP6963
- Connect Uniswap (Only SubWallet and have any wallet)
- Connect and test with some common EVM DApp: Moonbeam, StellaSwap, Manta airdrop, SubWallet dashboard, Dotinsight

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/jr4FT2bpMcM9Bsm

Validation passed in cases:
- Connect EIP6963
- Connect Uniswap (Only SubWallet and have any wallet)
- Connect and test with some common EVM DApp: Moonbeam, StellaSwap, Manta airdrop, SubWallet dashboard, Dotinsight
