### ISSUE TITLE
Support Paseo network

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2591]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpaseo.rpc.amforc.com#/extrinsics

**Comment by bluezdot** [comment]
Account has Paseo: 5EycVndjB9qTP5EKH8duY6C6Nu4hVm9SBbUBymAryWz1Yh4a

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/AonBXDHkteZaJNs
Data test : 5EycVndjB9qTP5EKH8duY6C6Nu4hVm9SBbUBymAryWz1Yh4a

Validation passed in case :

- Displays the correct balance of the account when on network


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/72b30a5b-6894-472a-acde-a647b7a721c9)


- Can perform Send/Receive tokens


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c048d57c-5846-40da-87b0-d2f1e3573a98)


- Check case when updated version
- Display correct network information

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7c7109bb-5f31-4029-ac36-1c51080b2662)

- Display correct token information

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/041bf76a-58be-4dfd-b601-13d9086f64c6)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/AonBXDHkteZaJNs
Data test : 5EycVndjB9qTP5EKH8duY6C6Nu4hVm9SBbUBymAryWz1Yh4a

Validation passed in case :

- Displays the correct balance of the account when on network


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/72b30a5b-6894-472a-acde-a647b7a721c9)


- Can perform Send/Receive tokens


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c048d57c-5846-40da-87b0-d2f1e3573a98)


- Check case when updated version
- Display correct network information

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7c7109bb-5f31-4029-ac36-1c51080b2662)

- Display correct token information

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/041bf76a-58be-4dfd-b601-13d9086f64c6)
