### ISSUE TITLE
Bridge Hub Integration: View bridged assets from in Asset Hub in Wallet

### ISSUE THREAD

**Issue by alistair-singh** [Koniverse/SubWallet-Extension#2604]
**Is your feature request related to a problem? Please describe.**
Asset Hub now supports foreign assets bridged through Bridge Hub. A user should be able to see any bridged assets that they own in their wallet.

**Describe the solution you'd like**
Simply display any bridged assets that the user owns in the wallet UI.

**Describe alternatives you've considered**
Users would potentially have to query chain state manually.

**Additional context**
Asset Hub now supports foreign assets bridged through Bridge Hub. These assets are stored in a different instance of the assets pallet called [ForeignAssets](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs#L378-L412) from version 1.7 release of Asset Hub.

There are two bridges currently deployed in Rococo
1. Snowbridge (bridges to Sepolia Ethereum testnet)
3. Westend Bridge (bridges to Westend substrate based testnet)

For Snowbridge the token that is Bridged is WETH (Wrapped Ether). Please see [docs](https://docs.snowbridge.network/rococo-testnet/rococo-sepolia-token-transfers) for more information on how to interact with the bridge and query asset balances.

We have plans for launch in Kusama and Polkadot (bridging to Ethereum mainnet) by the end of March. 

- Snowbridge Team

**Comment by nampc1** [comment]
Thanks @alistair-singh for creating this issue. We'll work on this asap

**Comment by bluezdot** [comment]
Account has WETH: 5Eg2fnsjAAr8RGZfa8Sy5mYFPabA9ZLNGYECCKXPD6xnK6D2

**Comment by bluezdot** [comment]
Extrinsic send WETH from Asset hub Rococo -> Sepolia (Ethereum testnet): https://assethub-rococo.subscan.io/extrinsic/3879712-2

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2658
