### ISSUE TITLE
Extension - Update estimating EVM transaction fee for Energy Web Chain

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2606]
**Describe the task**
Update estimating EVM transaction fee for Energy Web Chain

**Comment by S2kael** [comment]
MATIC:
![Screenshot 2024-02-15 at 16 24 35](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/1f113488-4fbe-4298-90f6-eed17a6979fb)

BNB:
![Screenshot 2024-02-15 at 16 26 25](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/ca2ddf79-c851-4503-9875-754c7b91e021)

ETH:
![Screenshot 2024-02-15 at 16 29 39](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/c316a085-db1b-43b8-a16f-bfd372a96a7c)

AVAX:
![Screenshot 2024-02-15 at 16 31 09](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/a3c6da1d-6eec-42eb-b3e6-b06668d9721f)

EWT:
![Screenshot 2024-02-15 at 17 27 06](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/94509a4a-5b9d-4b37-ae9c-5e51402fbfd5)

**Comment by nampc1** [comment]
Please check this issue on Base Sepolia Testnet (84532) as reported by Bit.Country team
![image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/73427ec5-0100-4cf0-9c84-f13abed016f7)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/c9556b51-c1ce-4ad1-a4af-2f93cc1514ed)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/nM2tLqkRXxAboKM 
Validation passed in cases:
- Transfer on dApp
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e537bb19-f973-48d7-919c-89895d44410e)
- Transfer with Base Sepolia Testnet
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/540bc1fd-c1ad-4c94-a2e3-6f2b55f4f470)
- Transfer for some token
  - MATIC: https://polygonscan.com/tx/0x460f34ad3dee4b1bc8876e7443e2bd180aa2f4af7b5d5032ce122fcd278ab2c5
  - ETH: Approve step
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9ac92af1-da92-4978-92f0-e03082f418e2)

  - BNB: Approve step
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ee67c8f7-a817-4dd2-8713-3ccd17e08dc2)

  - GLMR: https://moonbeam.subscan.io/extrinsic/0x88d803e3b1e543fffca69c771897d37fed343aea39b548b3bf311367dc507a57 
  - AVAX: https://subnets.avax.network/c-chain/tx/0xcb73ca8b6463bfacbb61e532285082a69ff53aa4982e3ea8b78ed8b17f0ef5c5
  - EWT: check on testnet
  - Acala-EVM: https://blockscout.acala.network/tx/0x6df1d12b6a7548fdbc1272febd393f31af531b091ffca96acf453b5d89724c84
