### ISSUE TITLE
Extension - Unable to scroll list account when connect a Ledger device

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2608]
**Describe the bug**

- [x] Unable to scroll list account when connect a Ledger device

**To reproduce the bug**
Step:
1. Perform connect a Ledger device
2. On list account, perform scroll and observe the displayed screen

Actual: Unable to scroll list account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/cc64a06e-3e2f-4fcf-8604-576e3bd903ce)

Reason: Zoom in/Zoom out browser

- [x] Navigate to the previous screen when scroll

https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4bf594f5-2bba-4499-9e8a-16bbeb8cffc1

**Comment by haiyenvu23** [comment]
Validation passed on Extension
On webapp, handle on issue #2782
