### ISSUE TITLE
Update IPFS domain for NFTs from Unique network

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2609]
https://ipfs.unique.network/

Use this IPFS domain for NFTs from Unique network

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/QWf8EiXLmfsdYXP

Validation passed 

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e083ddc0-b8d3-4e81-a2c8-56b97b8870cc)
