### ISSUE TITLE
Extension - Still shows earning positions even though the network is turned off

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2612]
**Describe the bug**
Still shows earning positions even though the network is turned off

**To reproduce the behavior**
Pre-condition: Account has an earning positions (Ex: Have DOT - Moonbeam)
Steps:
1. Go to the Earning tab
2. Observe the earning position displayed
3. Turn off Moonbeam network
4. Back to earning tab then check earning position displayed

**Actual:** Still shows earning positions

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/64278cce-1b2d-4c5c-8c69-6f2abcab2255)

- Notes: easily reproduce with account has only 1 earning position 
**Expect:** Do not show earning positions

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/y4xjGC85FKSEpHE
Validation passed.
- Turn on/ turn off network(Re-check list token, NFT)
- Specific account/ All account
- Substrate/ EVM account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/3af3b9f7-a786-4a3b-a33d-d25bd2f1cebc)
