### ISSUE TITLE
Extension - Show duplicate transaction history when transfer local token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2613]
**Describe the bug**
Show duplicate transaction history when transferring local token
**Actual:** Show both local and online history
- Link transaction view explorer: 
  - https://moonbeam.subscan.io/extrinsic/0x7488384784b89296093e7375db68b30069b128a71e8e7df3e6534b5f03045cc6
  - https://moonbeam.subscan.io/extrinsic/0x652d0ddb56606a4a01922a2282d976ef4afd56f9a1cfac342401fde2951e165f

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f5a5ea6d-78c4-4377-9a27-b7a0e7687c70)

**Expect:** Show only 1 item (Prioritize local history)

**Comment by dungnguyen-art** [comment]
![image](https://github.com/Koniverse/SubWallet-Extension/assets/59666831/17429f71-4d84-4d78-a399-1ce17f741e62)
I cannot reproduce this issue at this time.

**Comment by haiyenvu23** [comment]
@dungnguyen-art , pls re-check this issue 
I can reproduce 
Actual : 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/9420e080-6a0b-424f-97b3-716dec8bcfb2)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/Kjcpo7rKLAtFLcn
Validation passed in case : 
- Transfer local token
- Transfer native token
- Transfer custom token 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2eb85c11-d362-4563-871e-aeecf3edfe6c)
