### ISSUE TITLE
Extension - Show incorrect token in case the wallet has only 1 account type

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2616]
**Describe the bug**
Show incorrect token in case the wallet has only 1 account type

**Actual:** Wallet have Substrate account but show tokens of the EVM chain

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5e48cf6e-2340-4df4-9646-ecfcc994c266)

Expect: Show correct token

**Comment by saltict** [comment]
Fixed:

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/11567273/1470de91-35c7-4c44-8bbd-226d0c7abf06)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/6oEWGEwzFfw5LHN

Validation passed for cases:
- Token list in case all accounts are Substrate account
- Token list in case all accounts are EVM account
- Token list in case have both Substrate and EVM account

Re-test list token in feature:
- Send fund
- Buy token
- Earning: fix later on https://github.com/Koniverse/SubWallet-Extension/issues/2598
- Token list in case all accounts are Ledger account: fix later on https://github.com/Koniverse/SubWallet-Extension/issues/2598
