### ISSUE TITLE
Extension - Turn off popup "Remind claim rewards for dApp staking"

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2622]
**Describe the task**
Turn off popup "Remind claim rewards for dApp staking"

**Expect**: Now that dApp staking v3 has been released => need to turn off popup "Remind claim rewards for dApp staking"

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e9bb359f-2d19-4e6c-9267-13f34ae577db)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/XFfYp24nfFCjkwR
Validation passed in case : 
- Update version
- Open new app
- Close then re-open app
- User click on dApp on Earning options screen
- Check case when user click on non-dApp staking details
- Reset all



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/68fb0151-8d20-4d20-b451-5d9a37191d1e)
