### ISSUE TITLE
Extension - Re-check case send token on Acala-EVM with Ledger account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2625]
**Describe the bug**
Transaction failed when send token on Acala-EVM chain with Ledger account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/bd880fe6-3a91-4fe0-a269-922e0668778f)

**Comment by nampc1** [comment]
Also need to check with Optimism

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/QrcXeMa43iqnMkp
Validation passed.
- Acala-EVM: https://blockscout.acala.network/tx/0x2b303749a5278ec81f385e9860f0a9e06e801136323449ed5e279265c104230c
- Optimism Sepolia Testnet: https://optimism-sepolia.blockscout.com/tx/0x23f8f7e7e60269d91b06ab1718cec7052e0316b0f9d0ae695c341cbebd5d3ba7
