### ISSUE TITLE
Webapp - Update for staking reward

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2626]
Update WebApp for Staking Reward
- [x] Update earning preview screen (Wait middleware service for validator list)
- [x] Update Earning Trans Screen
  - [x] Auto enable network
  - [x] Auto select account
  - [x] Auto focus to amount
  - [x] Auto select validators
- [x] Redirect promise (Redirect user after finish create account)
 
BA docs: https://www.notion.so/subwallet/Integration-with-Staking-rewards-2b63d60534fa4e4da4b17dd047ca84bd

**Comment by haiyenvu23** [comment]
- [ ] Update new logic 
BA docs : https://www.notion.so/subwallet/Integration-with-Staking-rewards-2b63d60534fa4e4da4b17dd047ca84bd

**Comment by Sokol142196** [comment]
Please check issues:

- [ ] UI bug in case Invalid account type
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/fe29d38d-0e05-4839-afe6-ee5698fe7963)

- [ ] Show incorect account
  - Actual: Save and show the first account
  - Expect: Selected current account
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/68ca90ca-ac20-45af-93af-5599e9719957)


Disuss more:
- Earning method supported  -> Content
- Automatic turn on network

**Comment by haiyenvu23** [comment]
Version test : 
- Demo page: https://h5tyq5.csb.app/
- WebApp: https://webapp-demo.subwallet-webapp.pages.dev/

- [ ] Update logic when using invalid accounts 
Steps : In the case when the wallet does not have an account
1. Stand on popup Instrucsion earning
2. Click button Start to earn -> Navigate to Welcome screen to Create account/Import account/Attach account
3. Perform Import account/Attach account invalid
4. Click button Finish
**Expect** : 
- Option 1 : Navigate to Earning options screen , display popup Invalid account type
- Option 2 : Navigate to Start earning screen , display popup Invalid account type

**Comment by Quangdm-cdm** [comment]
About issue "Automatic turn-on network when user click on "Stake" button on Start earning screen", keep the flow turn on from preview screen @ThaoNguyen998

**Comment by haiyenvu23** [comment]
Discuss more : In case there are many valid accounts and in All account mode

**Comment by haiyenvu23** [comment]
Version test : 
- Demo page: https://h5tyq5.csb.app/
- WebApp: https://webapp-demo.subwallet-webapp.pages.dev/

- [ ] Can not navigate to Start earning when Import multi-account
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/826ae81d-b010-4f72-8d8e-51425d40ff73)

**Comment by haiyenvu23** [comment]
Version test :
- Demo page: https://h5tyq5.csb.app/
- WebApp: https://webapp-demo.subwallet-webapp.pages.dev/

- [ ] Updated Max validator warning for WebApp

**Comment by haiyenvu23** [comment]
Version test :
- Demo page: https://h5tyq5.csb.app/
- WebApp: https://webapp-demo.subwallet-webapp.pages.dev/
Validation passed in case : 
1. Update logic when using invalid accounts
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/592e186c-f415-492e-99f7-065a8063cf70)

2. Update logic for previously staked account
- Nominated 
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/11d000f0-9405-46a8-82ea-8161b603301c)

- Pooled

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/55e9d084-859c-4f0e-851c-88bb018a5b88)

**Comment by ThaoNguyen998** [comment]
Improve on issue https://github.com/Koniverse/SubWallet-Extension/issues/2708
