### ISSUE TITLE
Adjust showing/validating address on Send fund

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2628]
Disallow inputting general substrate address, all address input must be in its correct form relative to the chain

**Comment by S2kael** [comment]
![Screenshot 2024-02-21 at 14 26 46](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/43233669-ca42-42ed-b05c-ed190969498f)
![Screenshot 2024-02-21 at 14 27 42](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/d2671045-beca-4353-97f1-9ab522fe8820)
![Screenshot 2024-02-21 at 14 27 54](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/50238190-567c-4700-9a93-b197a04e6853)
![Screenshot 2024-02-21 at 14 30 19](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/33399b94-650c-4708-bf23-783b5467db24)
![Screenshot 2024-02-21 at 14 30 53](https://github.com/Koniverse/SubWallet-Extension/assets/41369298/4f6d1642-1982-4c75-9e3f-767bf383f393)

**Comment by S2kael** [comment]
Note: 
After send transaction, can remove receiver or sender account to check additional case

**Comment by Sokol142196** [comment]
Version test: 
Please check issues:

- [ ] Update format Recent address/Address in the screens
  - Address book
  - "Send to" input field

- [ ] Bug do not select image when change token

![Uploading 2628-BugUploadImage.gif…]()

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/mo93sf6nLmkimCR

Validation in cases:
- Send token - single chain (check input - confirmation - history)
  - Select account in wallet
  - Input Substrate address
  - Input Network address
  - Input public key
  - Select Recent address
  - Select Saved contact
  - Scan QR code
- Send token - cross chain (check input - confirmation - history)
  - Select account in wallet
  - Input Substrate address
  - Input Network address
  - Input public key
  - Select Recent address
  - Select Saved contact
  - Scan QR code
- Send NFT (check input - confirmation - history)
  - Select account in wallet
  - Input Substrate address
  - Input Network address
  - Input public key
  - Select Recent address
  - Select Saved contact
  - Scan QR code
