### ISSUE TITLE
Update filtering out blocked validators

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2632]
Filter out blocked validator from the validator list to make sure user can nominate

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/c0ff3999-89b1-4360-8428-e62e5ad79cb8)

**Comment by nampc1** [comment]
Also need to update in middleware service as well

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/PZRWtGi73wDgHzx

Validation passed in cases
- Ternoa
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2f0958fe-ac2e-470e-afdb-4a04c6e83d9a)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/83d97505-ce88-4c68-ae9d-6a923980ed51)

- Re-test other relelaychain
