### ISSUE TITLE
Optimize Earning Performance Round 2 (Caching most of data)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2636]
Update data with caching
- [x] Caching pool target (validator, nominators list)
- [x] Use caching in production
  - [x] Pool info
  - [x] Validator List

Need re-test
- [x] Earning option
- [x] Stake (Fetching validator list)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/kFLdDnSX7d9Bw4e

Please check issues

- [ ] Show eror page in case do not get list validator/collator
  - Reproduce with Westend Direct nomination
  
![2636-Bug](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3fcb5110-732c-4d42-a487-c490562f5668)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/CZybdZdbk2jHpoo

Please check issue

- [ ] Do not update data of the liquid and lending staking after performing any staking actions successully

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/L64kWfkxAAZJseS

Validation passed in cases:
- Check list position
- Check list pool, validator, collator
- Check update data when performing staking actions
 - Nomination pool (WND/ TZERO):
  - Stake/Stake more 
  - Unstake
  - Withdraw
  - Claim
 - Direct nomination - Relaychain (WND/ TZERO):
  - Stake/Stake more 
  - Unstake
  - Withdraw
  - Cancel unstake request
 - Direct nomination - Parachain (DEV/ TUR):
  - Stake/Stake more 
  - Unstake
  - Withdraw
  - Cancel unstake request
 - Liquid staking (Bifrost Polkadot, Manta)
  - Stake/Stake more 
  - Unstake
  - Withdraw: waiting for test later

 - Lending staking (Interlay)
  - Stake/Stake more 
  - Withdraw
