### ISSUE TITLE
SubConnect - Review and test Subconnect

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2639]
**Describe the task**
Review and test Subconnect
Link doc : https://www.notion.so/subwallet/Other-notes-5968b0d4f34349f8963167001315214a
Link design : https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=4833-129911&mode=dev
**To reproduce the bug**

- [x] Update connect with Ledger : Ledger EVM and Ledger Live
- [x] Remove this modal
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/94c9e4d6-13bd-4453-af73-6899b124c1ee)

- [x] Disable Select network type when connect with Ledger
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c0453678-857b-43ea-bf81-d9bbd41afc62)

- [x] Navigate to link in tab when click hyperlink I don't have a wallet
**Expect** : Navigate to link on new tab

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c8de4663-69c7-4090-b502-4ee8804ab762)

- [x] Logo is small
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1be5a662-fb77-469d-8fbc-ae28a36f4849)

- [x] UI bugs on Firefox 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/31c11c2a-4464-4f75-98ad-a5525e853e53)

- [x] When connect WalletConnect, change to "w3o-demo.subwallet.app" on Signature request screen, WalletConnect screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f8ced0df-3ac7-4440-a85c-e2c04a2415e2) 

- [x] Don't display account name and show scroll bar on Select account screen 
**Expect** : Display Account name

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2bf28259-0a65-4f86-98ba-b572cf198d1d)

- [x] Remove scroll bar

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d516c2ca-0ae2-49d4-a71d-49bd28dcd2e4)

- [x] Can not navigate to link when click SubWallet (Substrate), Talisman, Polkadot{.js} on Brave and Cốc cốc

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1c76e5c5-04cc-44bd-992a-3e54d7a63f07)

- [x] Add popup Disconnect wallet when click Disconnect

**Expect** : https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=17097-212101&mode=design&t=8rR2UE7FtC9cA8EK-0

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/11aff568-b086-4d6b-a817-25d8c67e838b)

- [x] Can not change account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8638bbc3-99d1-4538-a75c-cb74baba8e4c)

- [x] When click button Sign Dummy in WalletConnect, showing no support on the wallet
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d403a6f6-e3a4-4385-ad01-f31bc3455b8e)

- [ ] Message popup displays for a long time

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3a5ffa6c-3f93-4abf-ac22-5113acf8d484)

- [x] Connection successful screen closes slowly
**Expect** : Connection successful screen closes quickly

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/b41a7cf3-92c8-478a-84d5-8b4693eb6038)

- [x] Displays incorrect text when connecting successfully

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ec0dbaf0-6634-4b6f-abe6-5eed950e88c8)

- [x]  Improve scroll
**Expect** : When scroll, the top of the layout must remain the same

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7a2da513-2e5c-4b93-ad31-ea78bf2e96c8)

**Comment by haiyenvu23** [comment]
Version test : https://w3o-demo.subwallet.app/


- [ ] Update logo according to design
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/519d85b5-8ef0-4890-98cd-76eb7ebd0450)

- [ ] Update Scan QR code screen
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ae3cbe98-1a54-45ef-8233-9a9bb779c305)

- [ ] For quick popup display time
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d1e960d3-2294-4655-a439-c5e2d054f97a)

- [ ] Error popup automatically appears
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/98b7b880-f4d6-48e9-892a-ccad4c9982a3)

- [ ] Error of not being able to change network when connecting with Ledger EVM
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ba1092c6-f8d1-4970-8ff4-6a9ff6446802)

- [ ] UI bug 
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/598286de-49a6-471b-ad40-abfa3c8aadb8)

- [ ] When connecting WallConnect EVM, can not Transfer


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cf7d407f-81b8-4050-9c04-bf2f4d8709c3)

**Comment by haiyenvu23** [comment]
**Improve responsive**

- Chrome

- [ ] Must be separated from the margin
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ff8e0d92-c8a7-404c-abb5-43b729dc09af)

- [ ] Title is wrong

![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/bff25ef2-977c-491c-8698-edd1292e1bbb)

- [ ] Error display Scan QRcode screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d74d21cd-5332-4998-b4e7-789d4022600e)

- Firefox

- [ ] Remove scroll bar, title is wrong, must be separated from the margin
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2a445705-a174-4e7e-a8af-3f20ae14bab2)
