### ISSUE TITLE
Build UI for swap feature

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#2646]

**Comment by Sokol142196** [comment]
Version test: https://a7e7bf04.subwallet-webapp.pages.dev/

Please check issues:

- [ ] Do not show Swap quote on Substrate acc on the first time visit page

  ![2646-SwapQuote](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1299461d-4619-440d-85cb-b0c9ce01434e)

- [ ] Quote show incorrect information when change pair or change Amount
  
  ![2646-SwapQuote2](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a1a652ef-81ac-49c0-a062-b7d0c2f9e7e1)

- [ ] Handle case Swap with Ledger account
  - Expect: Filter out Ledger account if Ledger account is invalid with selected pair. 

- [ ] Clickable area of the Change slippage 
  - Expect: 
   ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/16e3789c-63e8-4e7f-a839-37ba2e00a452)

- [ ] Other UI
  - [ ] Swap token
    - Actual: Show Token name
    - Expect: Show Network
    
    ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d93e508e-6993-4d1b-9741-0a23e9598248)

**Comment by nampc1** [comment]
- [ ] Error page with this route, click on pDOT token on token page

![image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/4396bfc1-e55f-4ae9-ade4-3d668eeded6d)

**Comment by Sokol142196** [comment]
Version test: https://fe247b3c.subwallet-webapp.pages.dev
Please check issues:

- [ ] Do not show popup turn on network on the first time open Swap screen in case stand on Specific account
  - Actual:
 
   ![2646-TurnON Network](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3dbdbf88-e584-450f-a05c-f3b08d8cedfa)

 
  - Expect: Show popup turn on message 
- [ ] Show error message although user do not input data yet
  - Actual: 
  ![2646-ValidateRecipient](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6a35a7a7-5947-40e6-90ea-17a066838aa4)

  - Expect: Only validate require data when user click Swap button

**Comment by Sokol142196** [comment]
Version test: https://f4e9eeba.subwallet-webapp.pages.dev/

- [ ] Update fee transaction
  - Actual: Transaction fee on Swap screen differ Confirmation/ History screen

- [ ] Handle case Ledger account 
  - Expect: Discuss more
  - With Recipient account: Filter out Ledger account 
    ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b9a82898-611b-47e0-b71e-40c48af0cbd8)
  - With Sender account in case Specific account
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7f62b497-3ce7-4659-a32f-c8630153e598)

  

- [ ] Improve UX: Filter swap token by Sender account 
- [ ] Update content:
  - Warning message about swap time on confirm transaction screen
  - Error message

- [ ] Handle case swap quote expired

**Comment by Sokol142196** [comment]
- [ ] Add Terms of use 
- [ ] Handle case swap quote expired

**Comment by Sokol142196** [comment]
Version test: https://b1259d16.subwallet-webapp.pages.dev/
Responsive screen

- [ ] Show incorrect account when changing account 
![2646-ChangeAcc2](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e2bcd4c5-f1c2-478d-85c6-f04803465170)

**Comment by nampc1** [comment]
![Uploading image.png…]()

**Comment by nampc1** [comment]
- [ ] Need to review performance due to the quote reset interval causing the screen to re-render a lot

**Comment by nampc1** [comment]
- [ ] The swap quote is delayed and shows no loading animation. It should show skeleton immediately and fill information later
- [ ] Estimated fee should show only 2 decimal points (swap quote, confirmation, tx history)
- [ ] Complete "Are you there screen"
- [ ] Update T&C content
- [ ] Missing chainflip testnet provider logo

**Comment by ThaoNguyen998** [comment]
- [ ] Bug UI when standing on T&C swap screen

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/18532a53-ab87-4d8e-b4d9-5c1f74e4c888)

- [ ] Do not show message for Receive account field when switch account 
  Steps: 
1. Go to swap screen (All account mode)
2. Select Swap from account = Substrate account and input valid Recipient account
3. Switch Swap from account = EVM account and observe the displayed screen
  Actual: Do not show error message

  ![2646](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/2a07ab1c-5492-489a-858b-685520d05690)

  Expect: Show error message

**Comment by nampc1** [comment]
- [ ] Update low liquidity warning content
- [ ] Update T&C content

**Comment by ThaoNguyen998** [comment]
Version test: https://2c8d0f6a.subwallet-webapp.pages.dev/transaction/swap

- [ ] UI bug T&C

![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4080e91a-e5ad-4f3f-9d65-1b2493c71b5f)

**Comment by Sokol142196** [comment]
- [ ] Add delay time when reset quote
- [ ] Highlight time when time of quote reset <= 10 s
- [ ] Update Quote route: USDC --> DOT: @nampc1 handle

**Comment by ThaoNguyen998** [comment]
- [ ] Do not reset quote in case show popup Are you still there? 

![swap](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/0d31c5b6-b5f2-42ea-bdc7-fa3256fa48d8)

- Follow-up: Reset data before the deadline expires

**Comment by Sokol142196** [comment]
Improve later
- [ ] UI bug with large number

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9c8725d8-c102-4b7f-8120-8a7327182858)

**Comment by ThaoNguyen998** [comment]
Version test: https://447d0246.subwallet-webapp.pages.dev/transaction/swap

- [ ] Show incorrect quote rate in case swap USDC -> DOT

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8dc86e2b-0ef1-4143-b5bc-3cc456693961)

**Comment by Sokol142196** [comment]
Implemention continues in https://github.com/Koniverse/SubWallet-Extension/issues/2780
