### ISSUE TITLE
Extension - Restructure Settings screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2647]
**Describe the task**

- [x] Restructure Settings screen

Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=18108-215272&mode=dev

- [x] Add "Contact support" option
  - Expect _(refer Request a feature option)_
   - When click on this option then show Open mail to send email
   - Subject mail: [In-app Support]
   - To: agent@subwallet.app

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/5iBARbqT4StDa7M

- [ ] Change "subwallet" -> "SubWallet"

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/bae7f738-161f-4bb0-9ec9-c190f117cc46)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/9k6J7wjeSSpz4WF
Validation passed 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d9742615-982b-439c-b797-f4eae781875a)
