### ISSUE TITLE
Extension - Send crash log feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2649]
**Describe the task**
Send crash log feature
- Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=2822-76334&mode=dev
- Update title screen: "Unknown error"

**Comment by ThaoNguyen998** [comment]
@Quangdm-cdm Please help me fix this issue: 
- [ ] Add title follow by design
- [ ] Incorect font size, color content
- [ ] Do not close screen in case click Send report

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/RxQQpG2EZENWHKp
Validation passed.

![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/09c84ddf-985c-4f16-9832-de19f59544a2)
