### ISSUE TITLE
Bug Send NFT when balance is too low

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#265]
**Describe the bug**
Bug Send NFT when balance is too low

**To Reproduce**
Pre-condition: Account A have no balance or balance not enough to cover fees
1. Open Send NFT screen and Send NFT from A to B
2. Input Valid data for the all fields
3. Click on Send button
4. Observe Sign & Submit screen
5. Click Sign & Submit button
**Expected behavior**: My suggestion:
- Option 1: Refer to the Send Fund feature 
- Option 2: Display error message & disable button Sign & Submit

**Actual:** _see files attachment_

![Image](https://user-images.githubusercontent.com/102292476/167995445-62112801-9a4c-4096-aafb-e1b429a8acfa.png)

![Image](https://user-images.githubusercontent.com/102292476/167995481-96618a94-bc29-4e06-95e6-8a40a44faeed.png)

**Comment by NamPhamc99** [comment]
Bug reported by user: Can't send NFT on Moonbeam
https://www.loom.com/share/649b1329151f44a798bb09b1767f6cdf

**Comment by sokol142** [comment]
Pls disable button Send when user do not select "Send to address" yet

![Image](https://user-images.githubusercontent.com/102292476/169743666-86fc60c4-14f6-48cc-9942-eb47cc9d8beb.png)
