### ISSUE TITLE
[WebApp - Earning]- Improve Eaning feature

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2652]
**Describe the task**

- Re-check case update data after performing actions (unstake, cancel unstake, withdraw) of the Direct nomination para chain -> Fix in https://github.com/Koniverse/SubWallet-Extension/issues/2645
  - Actual: Do not update, user must be manual reload to update
  - Expect: Auto-update
  
- Still show unstake balance after withdrawing successfully from dApp -> Fix later in https://github.com/Koniverse/SubWallet-Extension/issues/2645
  - Expect: Update correct data
  
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/42b8f470-9820-4f58-a4eb-cb72495bc671)
  - Event withdraw: https://acala.subscan.io/extrinsic/5630293-2?tab=event
 

- [x] Re-check case fast unstake (check with Acala)
  - Actual: Transaction failed when perrforming in app (In dApp then transaction successfully)
    - Extrinsic in app: https://acala.subscan.io/extrinsic/5630362-2
    - Extrinsic in dApp: https://acala.subscan.io/extrinsic/5630382-2

- Show incorrect token unstake -> Fixed in https://github.com/Koniverse/SubWallet-Extension/issues/2645
  Example: With Acala
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7a7d3d51-dc37-4b93-85f7-74512713069c)

- [x] Update "Your earning positions" screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8a35bfa9-4001-4036-9164-99ec92e5cc19)

- [x] Hide this content on the Earning options screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6ea907c3-8854-410e-9967-6a9dad1076f4)

- [x] Update Text align
  - [x] Token earning options 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/09985123-9644-4592-b817-b766b62994f4)

- [x] Incorrect text color
  
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4d2f5e02-8f70-4256-b467-2742d3c07e27)

- [x] Update Grammarly
  - Earning position detail --> Earning position details
  - .... (follow by design)

- [x] Add "Withdraw" button on the popup "Withdraw info" screen when standing on "All accounts" mode in case click on "View details" 

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/57a73c99-8258-4e01-a909-84c2ca96126b)

- [x] Handle case have cancel unstake and withdraw button
  - Link design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=17031-276955&mode=dev

- [x] Change type message when click Claim rewards in case do not have any rewards 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/bfa56120-06c5-4d82-813c-b10d8463dcc2)

- [x] Update withdraw info
  - Actual:
    - Have withdraw: Show total balance withdrawable
    - Don't have withdraw: the first item
  - Expect:
    - Have withdraw: Show total balance withdrawable
    - Don't have withdraw: total unstake balance
  - Logic show cancel unstake and withdraw button

- [x] Update method staking info on the Start earning screen
 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2d0ee570-39ab-4dc7-a7e9-7ada824f5fd8)

- [x] Bug scroll
  
![2562-Scroll](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/acd97b3f-bb01-4a2a-bf68-be6887be0887)

**Comment by Sokol142196** [comment]
@dungnguyen-art please fix bug below

- [ ] Show icon back on Homepage screen
  - Actual: After performing any actions and back to Home then show icon back on Homepage screen
    - Click on this button then do not navigate
  - Expect: Do not show icon Back button 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/16dd2a54-7212-4e59-8bb3-b1874134f85f)
