### ISSUE TITLE
Review Aleph Zero transfer and staking

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2655]
Aleph Zero had some major updates recently. We need to review token transfer and staking logic
https://github.com/Cardinal-Cryptography/aleph-node/releases/tag/r-13.0

**Comment by bluezdot** [comment]
AlephZero update:  Pallet Balances:
- Remove `tx.balances.transfer`, `set_balance_deprecated`. We are using `transferAll` and `transferKeepAlive` so not be affected of changes.
- Update `query.balances.hold`. We do not use this API.
- Update `consts.balances.maxHold, costs.balances.maxReserves`. We do not use this API.
 Patllet Staking: - Remove `consts.staking.maxNominations`. We currently using this. If do not have maxNominations, we default return to ’16’. I think we need check with AlephZero team to confirm the maxNomination after the updates.  Pallet Contracts: - Many update on Pallet Contracts is not affected to our product

**Comment by bluezdot** [comment]
Plan Mainnet release on March 21st

**Comment by bluezdot** [comment]
The `maxNominations` will be altered by the `nomination_quota` API call. A0 team still work on it.

**Comment by bluezdot** [comment]
Mainnet deployed on 16.04.2024
Node upgrade deadline: 11:00 CET 23.04.2024

**Comment by bluezdot** [comment]
To get maxNominations:

Step1:
![image](https://github.com/Koniverse/SubWallet-Extension/assets/72647326/d63da411-01cd-4992-927b-2cb0f45c6695)
Step2:
![image](https://github.com/Koniverse/SubWallet-Extension/assets/72647326/c3001e4a-9a36-4843-b47f-ffed0c3af98b)

**Comment by ThaoNguyen998** [comment]
Version test: http://file.cdmteck.com/s/XMcrxSxzosszAGZ

Validation passed.
- AZERO
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/20443f25-6ab2-48d1-be22-ccd334c02004)
- Re-check staking Relaychain
