### ISSUE TITLE
Extension - Update transaction result screen

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2659]
Update transaction result with content:
- Transaction submitted!
- Track transaction progress in the History tab or go back to home

-----
**English**
Header: Submitted
Message: 
Transaction submitted!
Track transaction progress in the History tab or go back to home

-----
**Vietnamese**
Header: Gửi thành công
Message:
Gửi giao dịch thành công!
Vui lòng theo dõi quá trình thực hiện giao dịch trong mục Lịch sử hoặc về trang chủ

------
**Chinese**
Header: 提交成功
Message：
交易提交成功！
请在记录页签中跟踪交易进度或返回主页

-----
**Japanese**
Header: 送信完了
Message:
トランザクションの送信完了！
履歴タブでトランザクションの進行状況を追跡するか、
ホームに戻ってください。

-----
**Russian**
Header: Отправлено
Message:
Транзакция отправлена!
Отслеживайте прогресс транзакции во вкладке История или вернитесь на главную страницу

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/gR9NRo5R7y6eD3P
Validation passed
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5f887cc3-4ae2-4342-9ab0-89630f34620e)

**Comment by Sokol142196** [comment]
> Version test : http://14.224.158.246:8900/s/gR9NRo5R7y6eD3P Validation passed in case :
> 
> * Send token
> * Send NFT
> * Stake
> * Stake more
> * Unstake
> * Withdraw
> * Claim rewards
>   ![Image](https://private-user-images.githubusercontent.com/155931563/308157669-5f887cc3-4ae2-4342-9ab0-89630f34620e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNjUxNjEsIm5iZiI6MTcwOTM2NDg2MSwicGF0aCI6Ii8xNTU5MzE1NjMvMzA4MTU3NjY5LTVmODg3Y2MzLTRhZTItNDM0Mi05YWIwLTg5NjMwZjM0NjIwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwNzM0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWY0NzczODAxOTFkYTM1YTA2ZGFlZmM2MTcyOGZjYjk3YTMxMGYyYmFmNTc2ODVhZTRkYWY2YTk4NzllN2FhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fyTn56ACTn-hvRxIf8hxuw1kROw7M9qLdBfsvv0XKyk)

@haiyenvu23 Have you tested other languages?

**Comment by Sokol142196** [comment]
Waiting for updates other languages:
- Japanese
- Russian

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/pGfYkKAPfwKrKwY
- [ ] Wrong transaction header in Chinese language
**Actual** : 
**Expect** : Header: 提交成功

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/9646a140-7ad9-4489-b38b-e45b8af31f93)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/oyx2X72BW3JBzfG

- [ ] Wrong transaction content in Chinese language
Expect : 
Header: 提交成功
Message：
交易提交成功！
请在记录页签中跟踪交易进度或返回主页

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/59e2f128-8b5c-47b6-959f-6bb66708d40a)
