### ISSUE TITLE
Enable priceId update online

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2664]
Allow `priceId` to be updated online without building Chain-List

**Comment by bluezdot** [comment]
- Demo wrong priceId of bittensor

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/72647326/46c1bf99-0d7f-4bcc-980b-f9f9e000d9da)

**Comment by bluezdot** [comment]
- Update and log bittensor priceId successful:


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/72647326/4b7a6cb1-578c-4157-bfdc-1728ea0339bb)

**Comment by bluezdot** [comment]
- Add and log cypress priceId successful

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/72647326/ba5c09ba-1d5f-46f9-b3c8-0427a1a3fa2c)

**Comment by bluezdot** [comment]
Case: Add priceId, not reload extension.
Result: priceId self-update successfully.

![Screenshot 2024-02-27 at 15 50 44](https://github.com/Koniverse/SubWallet-Extension/assets/72647326/753e216c-1446-4a98-8458-974f07b9cbed)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/Cxz3emHYSfgMcLZ

Validation passed in cases: 
- Add price-id
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e41fef7e-b9ae-4797-9f47-719a1a5e857b)

- Remove price-id
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/10fbfba9-1a15-4dc4-add3-3216af5179d9)

- Update price-id
![2664-Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9f7591f6-1c63-4785-9e86-3e61d30f279c)

- priceId for cypress
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c2786a89-6fc7-47f6-90c9-1501131d4dbf)
