### ISSUE TITLE
[Extension] Improve EVM network fee

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2670]
- Hotfix fee for BSC
- Build middleware for EVM fee service

**Comment by S2kael** [comment]
| Action | Transaction type |
| --- | --- |
| Send native token | EVM |
| Send local token | EVM |
| Send xcm | Substrate |
| Send NFT | EVM |
| Native staking | Substrate |
| Stella staking | EVM |

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/5EPspG5fszByBde
Validation passed for cases:
| Action | Transaction type | Test result
| --- | --- || --- |
| Send native token | EVM: Call API | Passed: https://bscscan.com/tx/0xd02d044e5b6d1cbd47e78a56cf4ded6beaf14761437ea545a24386b8cdef0492
| Send local token | EVM: Call API | Passed: 
| Send xcm | Substrate: Do not call API | Passed: Check log call API
| Send NFT | EVM: Call API | Passed: Check log call API and send https://moonbeam.subscan.io/extrinsic/0x64d586b50755e62665bb17db4e35460d6fa4994923f6ee6dfb4484dac31971cb
| Native staking | Substrate: Do not call API | Passed: Check log call API
| Stella staking | EVM: Call API | Passed: Check log call API
| Check fallback | EVM: Call API (Moonbase, Moonriver) | Passed https://moonriver.subscan.io/extrinsic/0x4519eb602775fa6b05a8b89642be4d7fe4b07d2a1b73b0255a6e309cb53ca96c
