### ISSUE TITLE
WebApp - Add status tag on Mission Pool list screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2672]
**Describe the task**
Add status tag on Mission Pool list screen
- Component: https://www.figma.com/file/mfCcK60D4OWv42MlVvrJF4/SubWallet-UI-Base-1.0.1?type=design&node-id=4350-900&mode=design&t=e8wfIBuFto85EpKS-4

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/58e59130-6af9-417b-b613-a7139bbaa3c5)

**Comment by haiyenvu23** [comment]
Version test : https://0fbf4fd7.subwallet-webapp.pages.dev/

Validation passed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/692d525e-25ba-4b60-a537-4b2a178b4d77)
