### ISSUE TITLE
Integrate LLD and LLM from Liberland network

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#2676]
Intergrate Liberland Mainnet and Testnet.
Support LLD and Liberland Merit (LLM) from Liberland.
Support LDN from Liberland Testnet

**Comment by bluezdot** [comment]
Account has LDN (Native token of Liberland testnet): 5GjYePC6HKJGGnEzEZzSvimy6uctuMat4Kr2tjACtKyY9nhT

**Comment by bluezdot** [comment]
Account has LLD (NATIVE) and LLM (LOCAL) on Liberland mainnet: 5EYCAe5hveooUENA5d7dwq3caqM4LLBzktNumMKmhNRXu4JE

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2658
