### ISSUE TITLE
Extension - Improve MV3

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2681]
**Describe the task**

- [x] Bug when remove 1 account
  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/f50e8761-5c3b-42ea-a2ab-7537af785a17)

------
Follow-up
- Follow-up RAM issue
- T&C displayes slowly

-----
Resolved
- [x] Turn off popup in case click Learn more button
  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8f85164d-5d75-4cd6-b42e-aa66024abd93)
- [x] Discuss more "Export All" (sync account)
-  Follow-up the roadmap of the Firefox about Update MV3 and keep update for Firefox

Feedback: 
- [x] Can't enable extension in case upgrade version

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/b84b86a8-38fe-492f-a127-d32a9d53c142)

- [x] Missing account when connecting to dApp (Polkadot js) => #2709

**Comment by Sokol142196** [comment]
- [ ] Do not get data of the Parachain when earning
  - Version: v1.1.51 
   ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d7c8e099-dc90-4292-a7d9-a9db40cd6c3b)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/zH8qXwikyg32w4M
Validation passed in case : 
- Update version ( on Chrome, Brave)
- When remove 1 account 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a1d0a8b1-25a9-4c82-bb8a-e2e691078ed5)

- Get data of the Parachain when earning


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1c88e5f5-b8e0-4357-a70c-3168d81a8fc1)

**Comment by Sokol142196** [comment]
Follow-up continues in https://github.com/Koniverse/SubWallet-Extension/issues/3045
