### ISSUE TITLE
[Extension] Add export multiple accounts

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2690]
Add export multiple account

**Comment by haiyenvu23** [comment]
Version test : 
Validation passed in case : 

Check result export - import when the wallet has >= 1 Substrate account
Check result export - import when the wallet has >= 1 EVM account
Check result export - import when the wallet has both Substrate and EVM accounts
Check result export - import when the wallet contains an attached account (watch only, ledger, polkadot vault)
Check when making transactions with export files from SubWallet (performed on SubWallet , Polkadot js, Talisman)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a7f17366-70e9-4d30-81fc-feac9fc4ea44)

**Comment by Sokol142196** [comment]
Improve

- [ ] Support select account to export
  - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=19603-226834&mode=design&t=hfRjMYhh446GcLc9-4 
- [ ] Handle case import Ledger account on Firefox browser

**Comment by haiyenvu23** [comment]
Implement UI on issue #2819
