### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2694]
**Describe the task**
Update chain-list:
- [x] Update chain data and Asstes data: https://www.notion.so/subwallet/Chain-list-check-7b71bd814e6e42369121fd3d1ab70650

**Comment by bluezdot** [comment]
- [ ] Update block explorer for continuum: https://continuum.subscan.io/

**Comment by bluezdot** [comment]
- [ ] Unsupport transfer Local token for `crabParachain` and `pangolin` chain

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/FJfbttsXBXRAZQB

- [ ] Do not show transferable balance in case transfer ETH (Astar zkEVM)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/847f8bfe-7f8f-44d7-a6ab-1729e34a1968)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/HyCWpLBa2XY82ZB

Validation passed in case:
- Update chain data and Asstes data
- Add support for Astar zkEVM: Show token, balance, transfer(Approve step)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/7a8ae3d5-29ad-46eb-87f5-69a91eb4f71e)

- Update block explorer for continuum

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/7e19ab1b-191c-4a7a-91ee-ba011948c3cd)

- Unsupport transfer Local token for crabParachain and pangolin chain

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9de4df68-e742-4fa3-ba8f-0f3224cb428d)

- Support transfer for transferable NFT collections on Unique network
  - Unsupport transfer

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/da17eb91-a7c1-41d3-b3b8-6a8cedbcf014)

 - Support transfer: 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/7fa806e1-2ef6-4a6b-972d-bc033f44e785)
