### ISSUE TITLE
WebApp - Adjust showing/validating address on Send token, Send NFT, History

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2695]
**Describe the task**
Adjust showing/validating address on Send token, Send NFT, History
- [x] Send token (Input, Confirmation and History details)
- [x] Send NFT (Input, Confirmation and History details)
Expect: Formatting address by Network address
- Refer Extension v1.1.39 to update this issue (https://github.com/Koniverse/SubWallet-Extension/issues/2628)

**Comment by haiyenvu23** [comment]
Version test : https://76eb03ea.subwallet-webapp.pages.dev/

- [ ] Screen freezes when input address

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/76b44125-06ab-47f8-a633-fad2f707a237)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/51e14c84-970d-41a8-819c-e00d47c5016a)

**Comment by haiyenvu23** [comment]
Version test : https://293b6822.subwallet-webapp.pages.dev/

- [ ] When input Substrate address (this account is internal wallet/ Saved contact)
**Expect** : Automatically change to network address

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/de95acde-b64d-4ea4-8a4a-3a0b4ce8ca5c)

**Comment by haiyenvu23** [comment]
Version test : https://9442c831.subwallet-webapp.pages.dev/
Validation passed in case : 
- Send token - single chain (check input - confirmation )
  - Select account in wallet
  - Input Substrate address
  - Input Network address
  - Input public key
  - Select Recent address
  - Select Saved contact
  - Scan QR code
  - "Send to" = Ledger account: Select and input
  

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0597d4ff-aece-4ef7-b885-864c0310389a)

- Send token - cross chain (check input - confirmation )
  - Select account in wallet
  - Input Substrate address
  - Input Network address
  - Input public key
  - Select Recent address
  - Select Saved contact
  - Scan QR code
  - "Send to" = Ledger account: Select and input
  


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2ff58870-9985-4691-9cf4-6c272b3d827b)

- Send NFT (check input - confirmation )
  - Select account in wallet
  - Input Substrate address
  - Input Network address
  - Input public key
  - Select Recent address
  - Select Saved contact
  - Scan QR code
  - "Send to" = Ledger account: Select and input
  
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/642099ed-85fd-4cfe-ac25-4dcf38642937)

- Regression test feature:
  - Manage address book
  - Attach watch-only account
  - Import NFT/ Import token
  - Show address in History details screen after removed account
