### ISSUE TITLE
Update chainlist 0.2.43

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#2698]
- https://github.com/Koniverse/SubWallet-ChainList/issues/181
- [x] GLMR
- [x] ASTR
- [x] BNC
----
- https://github.com/Koniverse/SubWallet-ChainList/issues/188:
- [x] Add chain DENTNet
- [x] Add NATIVE token DENTX
- [x] Add token DENT

- https://github.com/Koniverse/SubWallet-ChainList/issues/187:
- [x] Add chain Tangle Network Testnet
- [x] Add NATIVE token tTNT 
- [ ] Note: Mainnet release on Apr 9th

- https://github.com/Koniverse/SubWallet-ChainList/issues/190:
- [x] Add chain Phyken Network Testnet
- [x] Add NATIVE token KEN
----
- Update provider: https://github.com/Koniverse/SubWallet-Extension/issues/2698#issuecomment-1982266953
----
- Support transfer NUUM (Continuum Network)

**Comment by bluezdot** [comment]
Update providers:
- [ ] ethereum: Add "Llamarpc": "https://eth.llamarpc.com"
- [ ] polygon: Add "Polygon Scan": "https://polygon-rpc.com/"
- [ ] optimism: Add "Kyber Engineering": "https://optimism.kyberengineering.io"
- [ ] moonbase: Remove "OnFinality": "wss://moonbeam-alpha.api.onfinality.io/public-ws"
- [ ] parallel: Remove "Parallel": "wss://polkadot-parallel-rpc.parallel.fi"
- [ ] sora_ksm: Update "Soramitsu": "wss://ws.parachain-collator-1.c1.sora2.soramitsu.co.jp" -> "Soramitsu": "wss://ws.parachain-collator-2.c2.sora2.soramitsu.co.jp"
- [ ] ajunaPolkadot: Remove "viaAjunaNetwork": "wss://rpc-parachain.ajuna.network"
- [ ] automata: Remove "Automata Network": "wss://api.ata.network"
- [ ] avalanche_c: Add "Avax Network": "https://api.avax.network/ext/bc/C/rpc"

**Comment by nampc1** [comment]
- [ ] BNC on hydraDX needs to have multichainAsset

**Comment by bluezdot** [comment]
MULTICHAIN ASSETS
aUSD Karura -> aSeed Karura:

- [ ] - moonriver-LOCAL-xcaSeed
- [ ] - shiden-LOCAL-aSEED
- [ ] - shidenEvm-ERC20-aSEED-0xfFFfFFfF00000000000000010000000000000000

multichainAsset aUSD Acala -> aSeed Acala:

- [ ] - astar-LOCAL-aSEED
- [ ] - astarEvm-ERC20-aSEED-0xfFFFFfFF00000000000000010000000000000001

**Comment by haiyenvu23** [comment]
https://github.com/Koniverse/SubWallet-ChainList/issues/188

Verson test : http://14.224.158.246:8900/s/maCSjF8gNWJ3Szn
Validation passed in case : 
- Displays the correct balance of the account when on/off network
- Can perform Send/Receive tokens
- Display correct network information
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/b3995850-67f2-4bbe-b389-7d6fe15d6294)
- Display correct token information
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8e3ebcd9-5add-4c7d-b2de-c0914212cb4c)

**Comment by haiyenvu23** [comment]
- https://github.com/Koniverse/SubWallet-ChainList/issues/190
Version test : http://14.224.158.246:8900/s/6gTjgCAfd2Q9wcQ
Data test : n9UFbujKLWbtcUqB5QjCiUi5wCX4zoDDy58RSN6fXdsRSgfz4
Validation passed in case : 
- Displays the correct balance of the account when on network
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0c4a3fea-4b1e-466a-a984-a804a39ee902)
- Can perform Send/Receive tokens
- Display correct network information
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c54e6fb9-320e-4dfd-be0f-617a2f6128f1)
- Display correct token information
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ffc23c30-ba26-45ce-84df-7b1ff98a7ebb)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/seskcja43LY7Zeg

**Support transfer for NUUM**
Validation passed for cases:
- Transfer
- Transfer all

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/19ab26e1-9c23-4e8e-99f8-20fc3e88ad27)
