### ISSUE TITLE
WebApp - Restructure Settings screen

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2701]
**Describe the task**

- [x] Restructure Settings screen

Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=18108-215272&mode=dev

- [x] Add "Contact support" option
  - Expect _(refer Request a feature option)_
   - When click on this option then show Open mail to send email
   - Subject mail: [In-app Support]
   - To: agent@subwallet.app

**Comment by haiyenvu23** [comment]
Version test : https://4539b0b5.subwallet-webapp.pages.dev/
 

- [ ] Display black background
**Expect** : Show blur background


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/13a9d990-99be-441a-ba7c-0a07662b3397)

**Comment by haiyenvu23** [comment]
Version test : https://6e7030de.subwallet-webapp.pages.dev/
Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0299d9b0-e8d1-4982-8826-1d7c62ebe1b4)
