### ISSUE TITLE
Extension - Adjust showing/validating address on Earning actions

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2703]
**Describe the task**
Adjust showing/validating address on Earning actions

**Expect:** Show network's address

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/4QtwkWMwww2yAFH

- [ ] Validate address when click on avatar 




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ec5557cc-67d3-48e5-8b51-acb69d381ca1)




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e22ee0a6-7c3c-440a-8e99-1c5f6154028a)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/68d796d6-112f-47c6-a955-40c8cc61a524)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e06f2a3e-1c3d-40e1-b741-05bf31bc51ac)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/GsFz7Mq7ooqac2y

- [ ] Input in the address's network when clicking button View on explorer


![Image](https://github.com/user-attachments/assets/e20d81b9-f5a8-42fe-9aeb-72a27787167f)



![Image](https://github.com/user-attachments/assets/d49fca30-eb7f-400c-8301-d78d5b9c8838)

- [ ] Validate when click avatar


![Image](https://github.com/user-attachments/assets/f126e428-f4bb-49ba-ad26-007a0becfc1d)



![Image](https://github.com/user-attachments/assets/43bb9adb-523f-4843-903f-c47ef7de202d)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/PMBqtZxKdN4YFGw

- [ ] Validate when click avt on Cancel unstake


![Image](https://github.com/user-attachments/assets/0d606516-7381-4341-9394-073c4e439a34)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/ZFDo4mJEAqbFAMG

- [ ] Validate when copy address on All account mode
- Unstake

![Image](https://github.com/user-attachments/assets/8286b7aa-fe04-49bc-8d54-edad5dffd76c)

- Claim reward
![Image](https://github.com/user-attachments/assets/0dc65b1d-2fbe-4f7a-9731-2b4fcda44f53)



- [ ] Can't search with network address on Unstake from account screen


![Image](https://github.com/user-attachments/assets/16291e34-44a3-4f4e-98ce-5c7aa9e02626)


![Image](https://github.com/user-attachments/assets/a4226c79-a271-4b3a-8b6f-03f785ec7fe3)

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/fzdi462MynsTQqG
- (Firefox): http://14.224.129.242:8900/s/D3k4Kg5rm5BZ5qK

Validation passed in case : 

- Install/Update version
- Check show/validate address on Earning actions ( All account/Specific account) : 
- Stake
- Stake more
- Unstake
- Cancel unstake
- Claim rewards
- Withdraw

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/2HDe5wEXjzEHAwZ
Validation passed in case : 
- Install/Update version
- Check show/validate address on Earning actions ( All account/Specific account) :
- Stake
- Stake more
- Unstake
- Cancel unstake
- Claim rewards
- Withdraw
Link checklist : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#1cb37ec199d24730b8a242cc08d46407
