### ISSUE TITLE
WebApp - Bug related to earning feature on WebApp (Round 3)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2704]
**Describe the task**
### Need to implement
- [x] Update content
  - Link doc: https://www.notion.so/subwallet/Earning-features-feedback-5ac9f86b47d744ba859bd70014037f78?pvs=4#220419e3ce4543bdbcf7135d0657a2f9

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/2653d0c3-b3e7-43af-a522-b290c9df3189)

- [x] Re-check text color in Nomination info screen
  
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5cf805ca-0c72-4ab2-b13d-708ab9305919)

- [x] Show incorrect info on the stake confirmation
   ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4057a4f6-18df-4598-8736-41816a4ec015)

- [x] Update grammary
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9939b069-5f6d-4ff9-8b9c-1ed13f13e587)

- [x] Update content for Liquid staking

-  Handle case click back button on the Start earning
 In case visit screen from Token earning option screen
 Actual: Back to Position screen
  
  @haiyenvu23 Please raise to another issue. => Related to issue #3107

-------
**Mobile-web**
- [x] Instruction popup error displayed twice on browser mobile

https://github.com/Koniverse/SubWallet-Extension/assets/155931563/48b79014-f841-47bb-bd5d-bf55ab4ff0ac

-------
**Improve**

- [x] Add the warning about locked balance after stake on the Add to bond confirmation
    - Style message: Warning
    - Message:
        - Header: Your staked funds will be locked
        - Message: Once staked, your funds will be locked and become non-transferable. To unlock your funds, you need to unstake manually, wait for the unstaking period to end and then withdraw manually.

    ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ed04f805-e8c0-45e6-bdde-e0303a58ff68)

-  UI bug in case small number
  -  Earning position details screen
 
=> Related to issue #3013

 ![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f03308c7-9184-4a5a-a436-2e7a547b3096)

**Comment by Sokol142196** [comment]
@ThaoNguyen998 please check case 1 again
Currently, I do not reproduce the behavior

**Comment by haiyenvu23** [comment]
- [ ]  Add tab "Staking, Liquid Staking, Lending,..." for Earning positions, Earning options, Token earning options screen
- [ ] In case turn off network, after click Earning type ( Balance > minstake)
Actual :  Navigate to Start earning with Nomination pool
Expect : Navigate to network earning options screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8620c652-71fb-4dc5-a758-3dd530e09042)

=> Refer to issue #2846

**Comment by haiyenvu23** [comment]
Version test : https://8d9d05c0.subwallet-webapp.pages.dev/transaction/earn

- [ ] Update content 
Expect : 
- "Polkadot direct nomination process:" → "Direct nomination process on Polkadot:"
- Update is similar to Nomination pool, Lending, Liquid staking

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/674d0579-ee08-4b7e-8856-76872ed278fe)

- [ ] Add "s" 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4e1e2c39-2969-4e06-b5ec-b7ba798720a6)

**Comment by haiyenvu23** [comment]
Version test : 

- [ ] UI 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1f97d27a-9ec6-44c4-a45b-83fad704458d)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/83e3ed28-eb0c-46f5-9712-94101dfb8201)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a4f394e6-a943-44a8-b709-b6e9ea34ddd7)

**Comment by haiyenvu23** [comment]
Version test : https://7f6a77c4.subwallet-webapp.pages.dev/

- [ ] Standardize all types of stake-related history
Link : https://www.notion.so/subwallet/Earning-features-feedback-5ac9f86b47d744ba859bd70014037f78?pvs=4#75ebbeb0c55c4b269489cc82ec822dd6


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1454702d-76fe-4b83-a3d5-7f8cd7bb1b98)

- [ ] Handle network disconnection cases while earning
Link : https://www.notion.so/subwallet/Earning-features-feedback-5ac9f86b47d744ba859bd70014037f78?pvs=4#437c980146c54953ad3c9bd3649d4d2d

- [ ] Update content trên màn Earning options 
Link : https://www.notion.so/subwallet/Earning-features-feedback-5ac9f86b47d744ba859bd70014037f78?pvs=4#8f269996fb484188ae84a18a8b562cdf



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/48280339-e4d1-4d68-86af-5dd886f36110)

**Comment by haiyenvu23** [comment]
Version test : https://96e0ff16.subwallet-webapp.pages.dev/

- [ ] Padding-top = 3px


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e50133eb-6550-4aad-9f09-46fafdaeb829)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8d5a5368-a9c9-404a-8e93-69caae46e96a)

- [ ] On Earning position details for Liquid staking screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c8949efc-212b-4baa-b626-a192064af0e3)

**Comment by haiyenvu23** [comment]
Version test : https://71fee930.subwallet-webapp.pages.dev/

- [ ] Don't show warning on Add to stake confirm screen when stake Nomination pool


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0d87cf0c-a344-4b83-83e3-6fa8592c8361)

Expect : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/402c6520-e221-4eaf-9c7b-e107bf6de011)

**Comment by haiyenvu23** [comment]
Version test : https://73c4c663.subwallet-webapp.pages.dev/
Validation passed in case : 
- Update content 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/24c8a3dc-dfe9-4fe2-a9be-6e4f9e3d6de3)

-  Text color in Nomination info screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/11dd1917-1815-41b3-aa85-d46dbef3e487)

-  Show info on the stake confirmation


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/df1c87fb-b7d8-4f5c-b948-227965079825)

-  Update grammary


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/07732288-dd72-4ec5-a82c-c883efe410f3)


-  Update content for Liquid staking




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/b858ad38-d84c-4549-820c-350ee59d7170)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d4f21f04-8811-45e2-9525-21d362bed773)

- Instruction popup error displayed twice on browser mobile
- Add the warning about locked balance after stake on the Add to bond confirmation 
Direct : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/fa30ce27-1b3b-4b8a-b852-69a82c47105e)

Pool : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6ab3bff2-3f89-4c1f-85ef-93b775531c07)


-  Standardize all types of stake-related history


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0beb0984-2ae2-4403-b0b7-eda64ee49ea8)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a1c07f82-b0a7-4fbb-b6cd-4954945191df)

- Update content on Earning options screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4862ff62-42d3-4efa-913b-c490ec4bf63d)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/559dab72-1c5f-4b67-b890-7af610a63465)
