### ISSUE TITLE
WebApp - Update transaction result screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2706]
**Describe the task**
Update transaction result screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1f7d7a00-7568-42ea-8d8a-8bc5a4edc3a1)

**English**
Header: Submitted
Message: 
Transaction submitted!
Track transaction progress in the History tab or go back to home

Implement other languages later

**Comment by haiyenvu23** [comment]
Version test : https://8d6a1a45.subwallet-webapp.pages.dev/
Validation passed

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4576dcf1-e556-4d86-8e3f-8d30dbb8f80c)
