### ISSUE TITLE
Extension - MV3 - Handle case displayed account with specific network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2709]
**Describe the task**
- [x] Handle case displayed account has current network
- [x] Handle case import account by JSON file with specific network 

**Actual:**
- After import successfully, still show address of the network on account selector
- When connect WebApp with extension then do not show this account 

**Expected:** 
- In SubWallet extension: After imported then remove current network info 
- In WebApp: Allow displayed account has current network

**Comment by saltict** [comment]
Test case: 
- Import account with network before update => auto remove network after update version
- Import account with network => remove network after import
- Import all account from polkadot{.js} => remove network after import
- Attach Ledger before or after update => keep network

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/LiAxJLWGGRf8S7D
Validation passed in case: 
- Import account with network before update => auto remove network after update version
- Import account with network => remove network after import
- Import all account from polkadot{.js} => remove network after import
- Attach Ledger before or after update => keep network
- Connect dApp: show correct account connected
