### ISSUE TITLE
[Growth] Request to add  Mission Pool to Settings screen on Extension

### ISSUE THREAD

**Issue by katehasw** [Koniverse/SubWallet-Extension#2710]
**Is your feature request related to a problem? Please describe.**
Allow extension users to navigate to the mission pool feature more easily. It also helps promote the mission pool to new user base.

**Describe the solution you'd like**
List "mission pool" with red dot below "security settings" section on the Settings screen.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/2KqREYd3T4ckep3

- [ ] Give Rewards field a newline

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d72db83e-974e-44b8-aa12-bd5ff48bfcc2)

- [ ] Improve UI

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6199c39c-ef50-4f65-bd40-2898e9df081d)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/XPjKYT4JfiFiP8i

- [ ] Improve UI like on mobile

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7a8956e9-d193-448e-84c3-4f0393003c3a)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/dx3wFexwdx4CxES

- [ ] Remove line and color synchronization

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/eac39d76-d3bd-48f7-880d-01631571f194)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/8isZB8PArdLpZLF
Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/da5748a1-fa71-4ea7-8d11-e7eb5e08c60e)
