### ISSUE TITLE
Fix bug not updating blocked XCM channels

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2717]
Extension is not updating the blocked channels even though the data is up-to-date

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/pWRpabWiScTo54S

Validation passed in case:
- New install
- Upgrade version 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7f670300-6aab-4a13-ad38-bf0cbb73a7b6)

- Regression test: 
  - Update RPC
  - Update price-id
