### ISSUE TITLE
WebApp - Update TVS for earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2719]
**Describe the task**
Update TVS for earning feature on the Earning options screen

**Actual:** Total TVS = Total TVS of method staking

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8828d7b4-6a1d-45e4-8d17-4bd424336007)

**Expect:** If network is relaychain then Total TVS = TVS of the Direct nomination else then keep the logic intact

**Comment by haiyenvu23** [comment]
Version test : https://8ff10352.subwallet-webapp.pages.dev/home/earning/pools
Validation passed in case : 

- With relaychain : Total TVS = TVS of the Direct nomination else then keep the logic intact


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1ee3b978-9717-4e07-b3fb-0e437e74c77a)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/58b7b304-2c22-4006-8729-becfae507541)

- With parachain : Total TVS = Total TVS of method staking


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d4a54464-2fb1-4d66-b246-02ca95126e97)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1d0edf4c-75d8-46d9-a213-a435b9fb4ff4)
