### ISSUE TITLE
Merge dApp request from both of interface into one interface

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2722]
Recheck:
- Connect with SubWallet: Show only one popup
- Connect with another site: Normal

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/He6pZaiGasSjE6c
Validation passed 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/39016468-e952-44ef-9d1c-f99424733601)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/He6pZaiGasSjE6c

Please check the issue:

- [ ] Sometimes, Show 2 connections pops up when connecting
  - Then appove/cancel/block then close both these popup
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/84cbc643-b78b-4e6d-8ba8-a28c5103c4a2)

  - Expect: Show only 1 popup connect

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/CPNXkrBLWd58NKx

Please check issue:

- [ ] Still show popup connect EVM account although user connected on Both account type
![2722-Bug](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/dfb02e98-ba2e-499f-8b89-350388a14205)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/YdWWkgC3RJHaaBP
Validation passed in case : 
- Update version
- Check case cancel/block then connect again
- Check case connect with Ledger account ( EVM, Substrate)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f1a98cfa-b20b-48bc-9aa6-c5fbcb18216a)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/YdWWkgC3RJHaaBP

- [ ] Not displaying error notifications when connecting to a dapp in cases where the dapp has been previously blocked
  
  ![Issue_2722](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9818a28c-2af5-4fee-8b66-6cf23dffd9cc)
