### ISSUE TITLE
WebApp - Send crash log feature

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2730]
**Describe the task**
Send crash log feature

- [x] Add title screen
- [x] Bug reponsive on ipad air, Ip 12 pro

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/86a7591e-73cd-4cd7-af24-dec07e98c41c)

**Comment by dungnguyen-art** [comment]
1. Normnal screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/59666831/a88c2d01-a42b-4325-b74e-a4eff1dd19ee)
2. Responsive
![image](https://github.com/Koniverse/SubWallet-Extension/assets/59666831/ddffa139-73d5-4676-894c-ca8eb6fcd5b0)
- Ipad Air
![image](https://github.com/Koniverse/SubWallet-Extension/assets/59666831/06fd664f-b35c-4112-890a-cbb981f532ed)
- Iphone 12 Pro
![image](https://github.com/Koniverse/SubWallet-Extension/assets/59666831/9adb8f47-21e2-4ad3-9be8-2bcb6e21d890)

**Comment by haiyenvu23** [comment]
Version test : https://9d2212ff.subwallet-webapp.pages.dev/

- [ ] Edit context : "Opps! An Error Occurred" -> " Oops, an error occurred! "


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d6703871-b7e9-4871-9955-3e69b9808736)

- [ ] Edit location
**Expect** : The position must be in the middle

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0f9d84f7-e561-4849-b043-0aab3a9e91d5)


- [ ] Edit size button
Refer to this design : https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=12891-212913&mode=design&t=Mqttk8sAbYIEaTq2-4

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8bb2c158-223f-480b-8705-7bdd4af7e6ac)

**Comment by haiyenvu23** [comment]
Version test : https://f33e2adb.subwallet-webapp.pages.dev/

- [ ]  Edit context : "Opps! An Error Occurred" -> " Oops, an error occurred! "
- [ ] Can not click button Send report and Back to home


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5842af6d-e554-4f7e-8582-c9adc961556c)

**Comment by haiyenvu23** [comment]
Version test : https://f25f7e12.subwallet-webapp.pages.dev/

- [ ] Bug when change responsive



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c3141fdd-f0c1-41e7-a7b3-5ed6775b488b)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8d635bea-78af-4e32-9440-b28b22f555f0)

**Comment by haiyenvu23** [comment]
Version test : https://a24ddcf7.subwallet-webapp.pages.dev/
Validation passed 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/b218559b-63c1-4d4f-99e6-1462c1a49744)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/380531a0-9ad3-49ab-b0b9-26b1aa5e90af)

**Comment by haiyenvu23** [comment]
Version test : https://0d153556.subwallet-webapp.pages.dev/
Validation passed
-> Have adjusted the code
