### ISSUE TITLE
Update Subscan Service

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2731]
Please update subscan service with some points:
- [x] Auto decrease limit rate in 30s if get rate limit error (2/s to 1/s)
- [x] Update deprcated api: "/api/scan/extrinsics" to the new api
- [x] Prioritize apis for direct use (historical apis) because these apis are the apis users use in real time
- [x] Disable ordinal API on web-runner and extension. Migrate ordinal API using Subscan service

**Comment by saltict** [comment]
Pass review: Please re-test some feature using subcan api like:
- Auto detect balance when import account
- Fetch history from Subscan

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/TFC9tif82PGqAWr

- [ ] Do not show history transfer Manta atlantic(transaction send) (new install)
Check with account: 5DxyLSczJm1Cx6MarxCSkKoq1pruRJBpcnd1HjS9oB5it2VA

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/30a93376-24e1-4d6e-86ca-102919f3af1c)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/6Q8WA6t8aBs5JJi

Validation passed in case: 
- Update version (History local)
- Install
- Auto detect balance when import, attach account
- History (Subscan)
