### ISSUE TITLE
Auto detect balance

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2732]
Implement auto detect balance
- [x] Detect balance of Substrate Account (Subscan)
- [ ] Detect balance of some EVM network (Birdeye API)
- [ ] Auto disable unused token on EVM networks that can detect balance
- [ ] Create popup ask to enable networks when detect balance (need more discussion)

**Comment by S2kael** [comment]
Auto-detect balance steps:

1. Fetching chain slug balance map from online
2. Fetching multi-chain balance of account
3. Mapping chain and token
4. Enable chain and token

**Comment by S2kael** [comment]
Test case:
manta_network: balanceChainSlug = manta

Step:
1. Update balanceChainSlug on extra info of chain info
2. Save and deploy dev
3. Re check with attaching read-only account

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/PaXgFFBLzicWYaW

- [ ] Do not show balance for local token when attach account
Actual: Show loading, after switch account -> show balance

  ![Issue_2732](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/5c0025e1-72bd-4181-8b99-a90079e95696)

Expect: Show balance

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/X87DSmWHBXtJkfo

Validation passed. 
- Install 
- Upgrade version
- Detect balance
- Turn off network
