### ISSUE TITLE
Add more currency type

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2738]
Support more currency type
Link design : https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=21051-374660&mode=design&t=9TAoEb6EYYuOGO6D-4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/boGN8Q99n6yxJAS

- [ ] Update currency characters


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/64d0c3a7-5d95-4c5b-b052-18148dabe69b)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/AStWJP56tdg52tT

- [ ] Update UI according to design



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/27d0d078-d38a-4fcf-ac9d-2457dd48b355)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/HFbpLXDW6anttWj
Validation passed in case : 
- Change currency
- Update version
- On/Off extension


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e252bc9a-ee09-474d-9a43-c247d977db05)

**Comment by Sokol142196** [comment]
Update for Swap feature

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/KZ45XRTb36wGcYT
Validation passed in case : 
- Convert currency values ​​according to each country correctly
- Currency symbols display in the following locations : 
  - Tokens feature: 
    

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a967a480-7a24-4ae2-97ee-d137d7727ae7)

  - Earning screen : 
    
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7fdab521-5c1a-470a-8144-92e258531694)

   - Crowdloan screen
      

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1bd37441-35f5-474f-834b-476bb59b423a)


   - Swap feature : 
     

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3f07b9b0-418b-4794-9b21-18982b8e71e7)

**Comment by Sokol142196** [comment]
Temporary hide this feature because show incorrect exchange rate

@haiyenvu23 @Thiendekaco please fix bug

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/D8XZY7PZ97N2XQ8

Validation passed
![2738-Validation-2](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/562f7926-1f34-4d8c-8dfd-be254df5cb4c)
