### ISSUE TITLE
WebApp - Update earning preview screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2741]
**Describe the bug**
Do not show earning options in case invalid account type

**To reproduce the behavior**
Pre-condition: On webapp has only 1 account type (example: EVM account)
Steps: 
1. Go to the earning preview screen https://webapp-dev.subwallet-webapp.pages.dev/earning-preview
2. Click on any token option then observe the screen displayed

**Actual:** Show mistake token earning options

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b573dfbf-82ca-4972-8349-f56c7183eb94)

**Expect**: Show all token earning options

Note for @haiyenvu23: You need check:
- Verify issue above 
- Regression test all case navigate from earning preview to WebApp (refference Staking Rewards)

**Comment by haiyenvu23** [comment]
Version test : https://6954290e.subwallet-webapp.pages.dev/crowdloan-unlock-campaign/check-contributions

- [ ] In case the wallet does not have an account, create an account other than the selected Earning type
**Actual** : Navigate to Start earning screen and can not select account
**Expect** : Navigate to Earning options screen and show popup Invalid account type
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a65d6028-5314-4ce1-9cff-09f95733cf2f)

**Comment by haiyenvu23** [comment]
Version test : https://f91f0f1f.subwallet-webapp.pages.dev/crowdloan-unlock-campaign/check-contributions

- [ ] Error in case have a EVM account type on wallet


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ad62280f-4595-47a6-804a-d93c973c0d1f)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5bb15166-cd13-47f8-8776-c36ec85e586e)

**Comment by haiyenvu23** [comment]
Version test : https://0ab2a4ab.subwallet-webapp.pages.dev/crowdloan-unlock-campaign/check-contributions
Validation passed 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/bc6e1bee-01f0-49f9-aade-41bd11415a65)
