### ISSUE TITLE
Extension - Still display start earning screen although back to earning positions/ Earning options screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2742]
**Describe the task**
Still display start earning screen although back to earning positions/ Earning options screen

**To reproduce the bug**
Steps:
1. Go to the start earning screen
2. Click Back icon to back to the earning positions/ Earning options
3. Close popup extension
4. Re-open popup extension then observe the screen displayed

**Actual:** Still show start earning screen (or start earning with instruction screen)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/abd7ccd2-072c-47f6-a8c0-1df1a5bebe68)

**Expect:** Show earning positions/ Earning options screen

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/xAAo3bHHW3rEk8E
Validaton passed in case : 
- Install/Update version
- All account mode
- Specific account mode


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d5ce7bb6-b41e-4984-8b2f-06b7d08ae7a5)
