### ISSUE TITLE
Improve display collators list

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#2751]
**Describe the task**

- Update display collators list for direct staking in-app, using selectedCandidate

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/znitqMnTqomz67T
Validation passed.
- Install/ Upgrade verison
- Check list collator for parachain: 
    'moonbeam',
    'moonriver',
    'moonbase',
    'turing',
    'turingStaging',
    'bifrost',
    'bifrost_testnet',
    'calamari_test',
    'calamari',
    'manta_network',
    'polimec'
- Check show earning position  with collator not support
- Check case unstake
- Re-check earning for relaychain, pool, amplitude
