### ISSUE TITLE
Integrate HydraDX swap SDK

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2758]

**Comment by nampc1** [comment]
- [ ] DOT <-> HDX
- [ ] DED <-> DOT
- [ ] USDT <-> DOT

**Comment by nampc1** [comment]
- [ ] Allow slippage change when quote is from HydraDX
	- [ ] Options are 0.1, 0.5, 1, 3%
	- [ ] Slippage will be 1% be default
- [ ] Add the swap provider logo for HydraDX

**Comment by Sokol142196** [comment]
- [ ] Do not update "Estimated received" on the Swap quote screen after reset quote
  - Actual: Still show "Estimated received" on the first time
  - Expect: 
    - Reset "Estimated received" when reset quote
    - Update and show the "Estimated received" of each Swap quote
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3bf669f2-0f51-4509-8f19-73bd2ea532e4)

- [ ] Handle case XCM flow
- [ ] Re-check validate amount in case Available = 0
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/190c4924-af35-46e6-8539-855fd8b69e6c)
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/99d971f3-885d-4a9b-bb4a-da11b4e4c6c8)

**Comment by Sokol142196** [comment]
### Improve

- [ ] Update history details screen
  - If Origin chain same as Destination chain then only show only 1 field "Networks"
  - Else show "Origin network" and "Destination network"
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/88f0d08e-008c-4e75-9628-b47fea617a2b)

- [ ] Update the Swap confirmation screen
  - If wait time > 0 then show warning
  - Else then hide warning
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/803a3a53-e53c-49a3-82d9-9e5cd0dab261)

**Comment by haiyenvu23** [comment]
Version test : https://9b143512.subwallet-webapp.pages.dev/
**Improve responsive**

- [ ] Update padding : "24px"

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3a59f133-605f-4551-b4b0-e4fbdd4e582c)

**Comment by ThaoNguyen998** [comment]
@dungnguyen-art Please fix: 

- [ ] Show incorrect Minimum received for Chainflip
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4cf27da2-5398-4d7d-b694-1488a0be07e0)

**Comment by Sokol142196** [comment]
Improve in https://github.com/Koniverse/SubWallet-Extension/issues/2780
