### ISSUE TITLE
Update explorer for Avail testnet

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2767]
- [x] Update explorer URL for Avail testnet: https://avail-testnet.subscan.io

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/Mbt7Zjebx4zQgk2
Validation passed in cases:
- Show explorer 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/0894f3a2-3ead-4f19-81c9-0b4fe5eb3d34)

- Show history
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/59831df2-5689-4573-984f-2bef94a93fd4)

- Detect balance: improve later
