### ISSUE TITLE
Update chain-list (0.2.45)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2771]
Describe the task
- [x] Update Network name for OriginTrail (NeuroWeb Mainnet)
- [x] Symbol not update in case upgrade version

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/03439db4-7d44-495c-bc9b-c713bd548b7e)
....

**Comment by nampc1** [comment]
#2772 
[#](https://github.com/Koniverse/SubWallet-ChainList/issues/183)

**Comment by bluezdot** [comment]
Recheck blockexplorer for these chain:
- [ ] moonbeam
- [ ] moonriver
- [ ] moonbase

**Comment by bluezdot** [comment]
- [ ] Add RPC for polimec: Amforc: wss://polimec.rpc.amforc.com

**Comment by bluezdot** [comment]
Add token DED: https://github.com/Koniverse/SubWallet-ChainList/issues/193#event-12167902323

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/EAAYWdQcQdLTQpN
Validation passed in cases:
- Update Network name for OriginTrail 
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/53a3869e-2879-4acf-ad26-d03f42ebe8b4)

- Symbol not update in case upgrade version
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3f2b047e-d36d-4e9e-b19e-ef83614dbe40)

- Price_id and explore URL for Polimec
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/67b4b18d-1e06-4025-8d3b-f8a8a190f2ac)

- Update Astar and Astar EVM chain logo
 ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/93bd4ef4-8327-4961-aa3a-9ee83975b1e4)

- Update ASTR token logo on all chains
 ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b9a2be0e-357d-4861-a3e7-8c941af7dd9b)

- Update symbol, network name for Tomo chain: VIC, Viction
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2633d3da-3a06-451c-a2db-9b0f3dd6db2e)

- Add RPC for polimec
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b8c79faf-e01c-4d8b-96b4-e634d721af82)

- Add token DED
  - Show token
  - Transfer token (Approve step) 
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e48fac7e-962d-4777-b8a4-8a25a934279f)

- Re-check explorer on Moonbeam, Moonbase, Moonriver


-----

- [ ] Please update logo of the ASTR group token
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f5f6369a-4f51-4108-b350-50e4c41ee096)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/5RRemi873bBWMBF
Validation passed in case update logo of the ASTR group token
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6a0df98e-cce0-4344-93d6-070d3233b169)

- [ ] Please check transfer DED
  - Actual: Transfer failed: https://assethub-polkadot.subscan.io/extrinsic/0x3bb728b7e7606b10077f61bceb25f172ae3e435c2bb40be56c4a63f1abe19921

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/eXsfFGfDfzBj5yj

Validation passed in cases:
- Support staking for Polimec 
  - Show earning position
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/371a9392-0b8c-41ac-bd9f-3a3fe5d12c54)

  - Show earning options
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9a1b75ce-d280-4222-af8a-5525f62a9d4f)

  - Unstake/Stake more (approve step)

- Support transfer/ transfer all DED 
  - Extrinsic: https://assethub-polkadot.subscan.io/extrinsic/0xf8ceecbfb73aa7a4c059b8e72b956dfe2554d7bd7c3067cb26b625eab4671d5f

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/dRLSTcZsMGDMa7E

Validation passed these cases
