### ISSUE TITLE
WebApp - Bug related to the popup Recommended validators

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2774]
Describe the bug

- [x] Do not show error message after click Continue on popup recommended validators

To reproduce the behavior
Steps:
1. Switch to All accounts
2. Go to Start earning screen and input:
   - Choose account do not have enough balance to earn
   - Select validator < Max validatator
3. Click to Stake button
4. Click to Continue on popup Recommended validator

Actual: After click Continue the close popup but do not error message
Expect: Prioritize error message display

------------
- [x] Disable button Continue after click button
Actual: Popup does not turn off immediately, allowing repeated clicking of a button results in multiple confirmations
Expect: When user click button Continue, you need to turn off the popup immediately and do not allow click multiple time to button

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/19ae1470-cd29-4b15-9869-73e489811bed)

**Comment by ThaoNguyen998** [comment]
Version test: https://dfda53a2.subwallet-webapp.pages.dev/
Validation passed in case: 
 - Do not show error message after click Continue on popup recommended validators
 - Disable button Continue after click button
 - Re-check validate earning
