### ISSUE TITLE
WebApp - Bug related to Swap feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2780]
**Describe the task**

- [x] Not allow close popup "Still there" when out focus
  - Actual: When out focus (click on background) then popup "Still there" is closed and quote do not reset
  - Expect: Do not close popup "Still there" when out focus

- [x] Add validate require for Amount and validate Amount > 0
- [x] Handle case show history of the recipient account in case recipient account in wallet
  - Actual: Do not show history
  - Expect: Show history

- [x] UI bug with large number

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9c8725d8-c102-4b7f-8120-8a7327182858)

- UI bug when Select token => Do not reproduce, temporarily skip
  
   ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/3ad056f6-a712-467b-9c8b-dce86e7c12d6)

- [x] Update style 

    ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/cbf8c1c1-daaa-4ff1-99c6-b9d96cc9abb2)

- [x] Update style token name
  
   ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e80f5053-d11d-469b-92a7-7283b43f775a)

- [x] Update text on Swap confirmation 

   ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/c9b599c3-11d3-4f91-ba63-e4022463e786)

- [x] Filter out "To token" by "From token"
  - Actual: "From token" is empty but 'To token' still show all -> incorrect pair
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4cdbb8c5-98ad-4c0a-ae1c-ebfd8febec2b)

  - Expect: Filter out "To token" by "From token"

---------
### Bugs on responsive 

- [x] UI bug on the Term of service screen

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7924c274-e282-46f4-a30e-66c9223e9ec5)

- Disable all actions when submitting data => Related to issue #3428
- [x] Swipe up and down on the pop-up screen but scroll on the bottom screen
  - Example: Swipe up and down on the Swap quote pop-up but scroll o Swap quote details screen

-  #3429
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8d4fa949-22e5-4993-a305-d13188960b42)

**Comment by haiyenvu23** [comment]
- [ ]  Handle case Ledger account

Actual: Still show token which not supported
Expect: Filter out token not support

![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3ca6f627-0c8f-4ef9-804f-7dd0c39a3d88)

- [ ] Update UX in case swap with XCM
- [ ] Add message on XCM confirmation screen when swap
- Header: Action needed
- Message: The amount you entered is higher than your available balance on X network. You need to first transfer cross-chain from Y network to X network to continue swapping
- Type message: info

- [ ] UI bug
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a11bfabb-d89c-4a67-9e37-e4dab807b0c3)
