### ISSUE TITLE
Do not allow send to empty account (Native token balance = 0) on Asset Hub

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2783]
**Describe the task**
Do not allow send to empty account (Native token balance = 0) on Asset Hub

**Actual:** Allow transfer but transaction failed 
**Expect:** Do not allow transfer and show error message

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/bdyzDXn9LXJrrk4

- [ ] Update message: "The recipient account has 0 DOT which can lead to your DED being lost. Change recipient account and try again"
@bluezdot please find an account with a DOT locked balance
