### ISSUE TITLE
Extension - Add Swap button

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2784]
**Describe the task**
Add Swap button for extension
- When click button -> Navigate to the Swap feature on WebApp
- Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=243-8468&mode=design&t=G7e7C0KVkIu1Gfl4-4
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=1115-36215&mode=design&t=G7e7C0KVkIu1Gfl4-4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/NnseSxLo5T9rFkJ

- [ ] In case there is no account in the wallet
**Actual** : After create new account then navigate to Home screen
**Expect** : After create new account then navigate to Swap screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ca70d4e4-8ae2-47fb-923b-28aedc2c0beb)

- [ ] In case specific account mode, after click button -> Navigate to the Swap feature on WebApp
**Actual** : Can not select account type
**Expect** : Auto select account 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8baf4456-1283-40da-b30c-94407d4275f6)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/98NJQ5W9t8PARqE
Link test : https://webapp-dev.subwallet-webapp.pages.dev/redirect-handler/swap

Validation passed in case : 

- The wallet does not have an account


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6cb92b1a-134b-4f55-8171-ba70b374f1ca)



- The wallet has an account


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e6e62cbc-9933-47ec-948b-86d18340674d)

**Comment by haiyenvu23** [comment]
Version test : 

- [ ] UI bug when balance is long
**Expect** : When scroll screen, temporarily hide the Buy button


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/622ce750-7dac-47f9-9ae5-c36918bfdf20)

**Comment by haiyenvu23** [comment]
Version test : 

- [ ] Align it close to the margin

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4a7d99d7-90db-4d8a-b7c3-c0dc12a7615c)

- [ ] UI bug when balance is long on Token detail screen
**Expect** : When scroll screen, temporarily hide the Buy button

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ad9486e0-74d1-4947-afc8-a6fe8c504e79)

- [ ] Only remove button Buy when the balance affects the UI

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e13e67a6-df3e-4def-80cb-6c12bd27451c)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/7faFXeK98WQb8Nd
Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7929668b-3853-4db9-8da2-199c09c600c2)
