### ISSUE TITLE
Add support XCM for xcPINK

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2786]
**Describe the task**
Add support XCM for xcPINK

**Comment by nampc1** [comment]
- [ ] Bifrost <-> Asset Hub
- [ ] Astar <-> Asset Hub
- [ ] Phala <-> Asset Hub
- [ ] Acala <-> Asset Hub
- [ ] InvArch <-> Asset Hub

- [ ] Crust <-> Asset Hub
- [ ] Darwinia <-> Asset Hub
- [ ] Unique <-> Asset Hub

**Comment by bluezdot** [comment]
Address has PINK:
- Bifrost:
- Astar: YSS3vdcp8EoThvdDb32CmZYMaGaQUfTCvpH3paWJ1Ddc7Ym
- Phala: 
- Acala:
- InvArch:
- Crust:
- Darwinia:
- Unique:

**Comment by bluezdot** [comment]
Remove providers:
- [ ] "LuckyFriday": "wss://rpc-polkadot.luckyfriday.io" (polkadot)
- [ ] "1rpc": "wss://1rpc.io/glmr" (moonbeam)
- [ ] "Lucky Friday": "wss://rpc-asset-hub-polkadot.luckyfriday.io" (statemint)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/MqRKGfEZqseH3mA

Validation passed in case
- Add PINK token on Bifrost, Astar, Phala, Acala, Crust, Darwinia 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/08197b81-b5d7-499e-80ff-46cf791e9339)
- Show PINK balance on Acala, Astar (remain chains do not have holder yet)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6705b47f-455a-42de-b823-f476869d0d7a)
 
- Default enable DOT, DED, PINK on Asset Hub and xcPINK, xcDOT on Moonbeam
- Update Max (XCM) = Transferable - ED*1.2 - fee
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/72c5a292-5e99-47e0-8acf-39910142dee8)

**Comment by Sokol142196** [comment]
> * [x]  Bifrost <-> Asset Hub
> * [x]  Astar <-> Asset Hub
> * [x]  Phala <-> Asset Hub
> * [x]  Acala <-> Asset Hub
> * [x]  Moonbeam <-> Asset Hub
> * InvArch <-> Asset Hub
> * Crust <-> Asset Hub
> * Darwinia <-> Asset Hub
> * Unique <-> Asset Hub

Update later
