### ISSUE TITLE
Integrate asset online

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2790]
- [x] Support adding/removing custom tokens online
- [x] Support adding/removing XCM channels online
- [x] Support enabling tokens online

**Comment by nampc1** [comment]
Enable these tokens:
- [ ] VARCH
- [ ] PDEX

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/Gtf9gAYdmty3bCK

Validation passed in cases with both mode (new install, upgrade version) 
- Add token
- Remove token -> Check history details
- Add NFT
- Add XCM channels
- Remove XCM channels -> Check history details
- Enable token default
- Disable token default
