### ISSUE TITLE
Extension - Do not show balance in case standing on History list to search token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2791]
**Describe the bug**
Do not show balance in case standing on History list to search token

Steps:
1. Open the extension
2. Go to the History tab
3. Close the popup extension
4. Re-open extension then click on Search token icon on Header
5. Observe the token list displayed 

Actual: Do not show balance
![Bug_ShowBalance](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5dccd167-be4a-47db-bf58-94a9c892c793)

Expect: Show balance

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/dcYzNZGB2LZ3Jpa

Validation passed 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/74da32a3-fcc8-48e1-935b-3719c926941b)
