### ISSUE TITLE
Handle case slow getting max transferable cause wrong amount when submit max transfer

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2793]
### Reason
- Delay at the fee estimate step when interacting with RPC
![2793-Bug](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/cdfdfa72-9eb6-470b-a8fc-3155ad325775)

  
### Solution
- Disable submit button when getting max transferable

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/bTtkFFwai7CGpGA
Validation passed 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f61bb72c-586d-4ff4-b30b-a0b1c9043928)
