### ISSUE TITLE
Re-check bug transfer Max

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2795]
**Describe the bug**
- Error page occurs when transfer token
@saltict please add log to @S2kael debug

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/wrQd8X4YYPtrQoe

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/f19bb571-c776-4cfe-9092-4cc2a6a29ec9)
