### ISSUE TITLE
Error parsing token balance for frozen asset on Asset Hub

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2799]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/d72da42a-6cf6-45ba-9b1b-cd23e9c791ad)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/b425f7a9-9cbd-4176-81ac-0e8808b749c6)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/fAwL67rpPcnXqKt
Validation passed 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/62cd2d27-8dd8-4838-a232-fbbef6e9170a)

Notes:
- Status include:
  - Liquid: allow transfer, receive
  - Frozen: Do not transfer
  - Blocked: Do not receive and transfer
