### ISSUE TITLE
Extension - Improve the Marketing Campaign application mechanism(Phrase 1)

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2806]
Improve Marketing Campaign application mechanism
Roadmap: https://xmind.ai/share/rw9QKKI1?xid=1z6I9jKT
Phrase 1: 

- [x] Build the core to manage online resources: 
 - Response is adjusted according to frequency
 - Displayed according to conditions from balance and earnings
 - Perform actions according to the settings
 - Supports instruction before performing actions

- [x] Supports App Popup display
- [x] Supports App Banner display

Phrase 2:  Related to issue #2807

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/KqDk9TFzcxcHRCe

- [ ] Error page in case click token detail

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/72d4e958-c252-4f61-94a3-e74f596cd81f)

- [ ] Re-check padding title popup, button

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/15f13346-5ebe-4d79-a68d-3b8279dd019a)

- [ ] Font size text

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/mNBYDZa35ZY98zD

- [ ] Do not navigate in case click the button on Instruction
 Actual: Open the new tab
 Expect: Navigate to Earning

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ef49b2e8-f222-46d0-a379-d8f800f41b7f)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/CmtfZxHgyHmWi6L

- [ ] Auto back popup screen in case open instruction the first time
- [ ] Re-check the condition balance of banner
Actual: The banner is still displayed when the condition is not met

**Comment by Quangdm-cdm** [comment]
Navigate to Start earning screen in case have 1 Token earning options: improve later

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/4cxRHWyrWnr6E4R
Validation passed.

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/BBxJPQDXTq3TiJX
Validation passed 
- Fix bug do not show banner on instruction (Token detail, Crowdloan)
- Fix bug do not navigate in case click the hyperlink on the popup
