### ISSUE TITLE
Extension - Add some features of marketing campain ( Phrase 2)

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2807]
**Describe the task**

- [x] Added checks for several types of conditions:
 - Crowdloan
 - NFT
 - Has money

- [x] Supports App Confirmation display

**Comment by ThaoNguyen998** [comment]
- Navigate to the Start earning  screen in case you have 1 Token earning options

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/093dd32f-4dae-43ba-a94f-63993cafff17)

- Show incorrect instruction in case multi banner on Crowdloan
- Show duplicate popup in case multi-campaign(Create new account)

**Comment by Quangdm-cdm** [comment]
With case Navigate to the Start earning screen in case you have 1 Token earning options: We cannot check how many records there are before accessing the screen, so doing this is impossible. @ThaoNguyen998
