### ISSUE TITLE
Display wrong tokens on Interlay and Kintsuigi

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#281]
**Describe the bug**
I think there are some bugs with the tokens displayed in Interlay and Kintsugi. 

- DOT and INTR should not be in Kintsugi; and KSM, KINT, kBTC should not be in Interlay.
- There should be iBTC on Interlay; and kBTC on Kintsugi

Please see the picture below:

<img width="455" alt="Screen Shot 2022-05-18 at 14 29 30" src="https://user-images.githubusercontent.com/102496727/168984536-f2c207d7-3967-4224-8d5d-943ed5a6b6ac.png">
<img width="457" alt="Screen Shot 2022-05-18 at 14 29 46" src="https://user-images.githubusercontent.com/102496727/168984583-b5dcefc3-a8e3-4d92-a023-2e983ef82d48.png">

**Desktop (please complete the following information):**
 - OS: Macbook pro 2016
 - Browser: Chrome, Version 101.0.4951.64 (Official Build) (x86_64)
 - Version 0.4.1

**Comment by S2kael** [comment]
The list of tokens is taken down from the chain, this is correct list.
