### ISSUE TITLE
WebApp - Show Validator details pop up when navigating from the Staking Rewards page

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2812]
**Describe the task**
Show Validator details pop up when navigating from the Staking Rewards page

**Actual:** Show Instruction popup
**Expect:** 
- When click on Stake with SubWallet on Staking rewards page then navigate user to the Earning-preview screen and show popup Validator details
https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=20068-164447&mode=design&t=3PCZeZWi3ZbIHM2x-4 
- User click "Stake to earn" on Validator detail popup then navigate to the Start to earn screen and show Instruction

**Comment by haiyenvu23** [comment]
Version test : https://f276ffe1.subwallet-webapp.pages.dev/

- [ ] Don't navigate to Start earning when click some option on Earning preview screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/851f359c-609b-4bcb-88ec-1700e29a75b2)

**Comment by haiyenvu23** [comment]
Version test : https://e5d462c1.subwallet-webapp.pages.dev/

- [ ] Display wrong information popup Instruction


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/563a893a-3385-4e70-a1db-c1b40d04b7d5)

- [ ] Display wrong information popup Validator detail

**Expect** : If close popup Validator detail on Earning preview screen then choose another Earning, there is no need to display popup Validator detail

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/aaca0350-2e53-42b1-9151-63e641f92a67)

**Comment by haiyenvu23** [comment]
Version test : https://69e91682.subwallet-webapp.pages.dev/
Validaton passed in case : 
- Display correct information validator detail
- Display the correct position of popup Instruction



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/61bd7614-5386-43fe-9ca6-0bcda972a9c4)

**Comment by Sokol142196** [comment]
@haiyenvu23 please re-check Crowdloan page

**Comment by haiyenvu23** [comment]
Version test : https://69e91682.subwallet-webapp.pages.dev/crowdloan-unlock-campaign/check-contributions

- [ ] In case the wallet has both account Substrate and EVM, error display popup 
Steps : 
1. Choose Earning ( EVM) type)
2. Observe the display screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/452c6040-0fb1-48a1-adc7-f345a4f18902)

- [ ] Not display network name in the above case

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/73c4f3fd-1139-40a8-97f8-95cc6c0dfb5d)

**Comment by haiyenvu23** [comment]
Version test : https://3f770875.subwallet-webapp.pages.dev/crowdloan-unlock-campaign/check-contributions
Validation passed 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1c3e067e-035f-4915-a8dc-94e1187a64e3)
