### ISSUE TITLE
Error screen appears when performing XCM on Kusama

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2814]
**Describe the bug**

In case account has balance, error screen appears when performing XCM on Kusama

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5674ebe8-1906-40cd-a13b-2ec1e68a4db0)

- Log bug : 
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/9d47441d-1963-43cb-86ac-c96538922d53)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/4izMAcBS6FYkA87

Validation passed.

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/734bd448-1614-4250-b6fd-3b276c161d01)
