### ISSUE TITLE
Extension - Implement UI for export multi-account

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2819]
**Describe the bug**
Implement UI for export according to the selected account list

- [x] Support select account to export
  - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=19603-226834&mode=design&t=hfRjMYhh446GcLc9-4 
- [x] Add message for case import Ledger account on Firefox browser
  - Content : " Incompatible browser. Use a Chrominum based browser like Chrome and Brave and try again."

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/aKbjTry73BGg5Ei

- [ ] Add "s" to the word "account" when choose > 1 account

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1f19c6cd-3874-4d27-822c-368dfd5d2c5d)

- [ ] Add condition when input password

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e3b46bde-251a-4444-9834-b7a7d15f50bf)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/9FidzeZ3xwJJGF6

- [ ] Do not reset selected items in case re-open Export account screen
Steps: 
1. Open Export account screen
2. Select account 
3. Back to Select account screen
4. Re-open Export account screen and observe the displayed screen

Actual: Do not reset selected items

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/3d8ed1fe-30ae-4aa6-b34c-a6475bd60cac)

Expect: Reset selected items

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/LMdcJNipLJigTM9
Validation passed in case : 

- Add message for case import Ledger account on Firefox browser

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/94cbd337-ef60-4cb9-9dff-13187bc1e783)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2c803666-6302-46fd-8863-381ef6208a07)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/LMdcJNipLJigTM9

- [ ] Display error when perform Transaction 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/26ea5a13-31bb-4a99-a928-b46e7d4aeba1)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/FSpNCxgKWYQ4a4P
Validation passed in case : 

- Add message for case import Ledger account on Firefox browser

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/94cbd337-ef60-4cb9-9dff-13187bc1e783)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2c803666-6302-46fd-8863-381ef6208a07)

- Support select account to export

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/07005092-a622-4932-bd18-9c4815833c06)

- Check result export - import when the wallet has >= 1 Substrate account
- Check result export - import when the wallet has >= 1 EVM account
- Check result export - import when the wallet has both Substrate and EVM accounts
- Check result export - import when the wallet contains an attached account (watch only, ledger, polkadot vault)
- Check when making transactions with export files from SubWallet (performed on SubWallet , Polkadot js, Talisman)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/9c62e72a-0755-448b-b830-02b03fdb58bd)

**Comment by haiyenvu23** [comment]
- [ ] Added tooltip for button icon

![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/fe626a44-8f20-49a7-b009-f2ab44e3e729)

- [ ] Wrong size of Export account button in Select account screen

![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cce51bf8-6a89-46b9-8727-4aa9574eb688)

- [ ] Automatically tick the "All accounts" option when all accounts in the list are ticked

![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/764266ec-d42a-4f5a-8aad-6ff0d85ec932)

- [ ] Disable account export button when no account has been selected

![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3dda44f2-8855-4af0-a079-927f389df541)

- [ ] Change the style of the Incompatible browser notification to error type

![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/859c93f8-2f83-431b-bfaf-9477a2ca7cb4)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/Np4dBbTxf29tC3N

- [ ] Change the style of the Incompatible browser notification to error type when perform transaction ( with Ledger account on Firefox)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/29f4da18-605d-432b-bb14-e95671808e33)

- [ ] Tooltip is missing a corner

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/94effae8-debf-4ebe-9b55-2e8d2504a276)

- [ ] Displays the address of the Ledger account according to the network

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3115b594-d7ff-461b-bbb6-1cd3297f758e)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/8jgHEZc2PD4Hm6w
Validation passsed in case : 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/30a09fc2-db1a-4c3f-b45f-ebd1a9d0f612)


-  Change the style of the Incompatible browser notification to error type when perform transaction ( with Ledger account on Firefox)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/59b0f467-0b79-428b-8184-fa88a8ad6cf5)


- Displays the address of the Ledger account


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1e83047c-f6d5-4d5d-8831-0e47447a8632)
