### ISSUE TITLE
Extension - Update UI for earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2827]
**Describe the task**
**Update UI for earning feature**
- [x] Add tag "Mainnet", "Testnet" on Earning options, Earning positions screen
- [x] Remove default "testnet" filter on Earning options screen
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f53894ae-744a-411e-ab4e-ffaf53ebfc35)

- [x] Update UI for Start earning screen
  - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3360-80540&mode=design&t=QhQxqqNgF6QYluNE-4
    - Remove "Auto-select Pool recommended"
    - Change label from "Select pool" to "Pool"
    - Add "recommended" for SubWallet pool
- [x] Show SubWallet pool to top list
- Hide "Direct nomination" of the relaychain if available balance < min stake => Implement in https://github.com/Koniverse/SubWallet-Extension/issues/2877
- [x] Add the Minimum stake on the Start earning feature after select validator/collator
  - Actual: After select collator then do not show minimum stake on this screen
  - Expect: Always show min stake  
    ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/198d9ceb-559d-49e0-890a-f124a9e6c810)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/Fja9msNpck8pxY9
Validation passed in case : 

- Add tag "Mainnet", "Testnet" on Earning options, Earning positions screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/07f7d1b0-1c37-40fc-ae5e-1ee3fdc333db)

-  Update UI for Start earning screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7c481ba5-114b-4a97-8f6b-e90a25b532cc)

-  Show SubWallet pool to top list



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8e2b66e8-582d-4dd3-b02a-dbd2d54c96e5)

-  Add the Minimum stake on the Start earning feature after select validator/collator


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/89e503f4-ae08-4698-ad60-9e0076255521)

- Hide "Direct nomination" of the relaychain if available balance < min stake => Related to issue #2877

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/JxkDJkbBBpY39sQ
Validation passed in case
- Remove tag "Mainnet"


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3f28e520-f86b-4c6a-bde5-d2551931de1d)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f6f7e645-27eb-462e-a2b5-dd9c79b95210)
