### ISSUE TITLE
WebApp - Update UI for earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2846]
**Describe the task**
Update UI for earning feature
- [x] Add tag "Mainnet", "Testnet" on Earning options, Earning positions screen
  - Design: 
    - Earning options: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=10198-484897&mode=design&t=JUESFzqCX0J2UrBD-4 
    - Earning positions: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=10420-232642&mode=design&t=JUESFzqCX0J2UrBD-4  
- [x] Remove default "testnet" filter on Earning options screen
-  Add tab "Staking, Liquid Staking, Lending,..." for Earning positions, Earning options, Token earning options screen => Related to issue #2704 
- [x] Remove label "balance" on the position

   ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d6b6a77a-d585-49ae-aa98-a0f2fbdf8cdb)

- [x] Show SubWallet pool to top list
- [x] Hide "Direct nomination" of the relaychain if available balance < min stake
- [x] Add the Minimum stake on the Start earning feature after select validator/collator
  - Actual: After select collator then do not show minimum stake on this screen
  - Expect: Always show min stake

   ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2bb7aa26-f62c-40f2-ae02-7b7b8c1325e3)

- [x] Update UI for Start earning screen
  - Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=3360-80540&mode=design&t=QhQxqqNgF6QYluNE-4 
    - Remove "Auto-select Pool recommended"
    - Change label from "Select pool" to "Pool"
    - Add "recommended" for SubWallet pool

**Comment by haiyenvu23** [comment]
Version test : https://a7838a8f.subwallet-webapp.pages.dev/

- [ ] Remove this icon


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/9d1f906a-9eb8-4904-88c2-6cf9eda74870)

- [ ] Can not display Nomination pool type 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d0d5700b-d8f6-4771-be98-89db226999d5)

**Comment by haiyenvu23** [comment]
Version test : https://7e108361.subwallet-webapp.pages.dev/

- [ ] Re-check :  Hide "Direct nomination" of the relaychain if available balance < min stake

**Comment by haiyenvu23** [comment]
Version test : https://f59b2d5c.subwallet-webapp.pages.dev/
- [ ] Add "recommended" for SubWallet pool on Pool list screen
- [ ] Update title "Pool"
**Expect** : " Select pool" 

- [ ] When softing, don't let enemy SubWallet pool take the lead
- [ ]  In case balance = minstake ( Specific account)
**Actual** : Don't show direct nomination
**Expect** : Show direct nomination

- [ ]  In case balance = minstake ( All account)
**Actual** : Don't show direct nomination
**Expect** : Show direct nomination

- [ ] In case account has staked, if balance = 0

**Expect** : Show direct nomination

**Comment by haiyenvu23** [comment]
Version test : https://0e0e1363.subwallet-webapp.pages.dev/

- [ ] "Pool" -> "Select pool"


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/60ce6006-d344-4cf6-a658-3d9f899cab27)

**Comment by haiyenvu23** [comment]
Version test : https://907d86ac.subwallet-webapp.pages.dev/home/earning

- [ ] In case turn off network, after click Earning type ( Balance > minstake)
Actual :  Navigate to Start earning with Nomination pool
Expect : Navigate to network earning options screen

**Comment by Sokol142196** [comment]
@haiyenvu23 @dungnguyen-art please re-check this UI

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/3fe561c1-e424-4a98-9ab5-0d7fe923fbbc)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/bf1e202d-3266-49c8-b5e7-d0127de931f6)

**Comment by haiyenvu23** [comment]
Version test : https://b8e660ab.subwallet-webapp.pages.dev/

Validation passed in case responsive : 




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a195eb46-04d2-4a49-a767-39fd10562e10)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/1e4b9e7a-c16d-4cf4-8411-8aba4da691cf)




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/21c40b98-d798-455e-a3ea-f579f2133f73)
