### ISSUE TITLE
Update message when navigate user to the Astar portal to stake

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2847]
**Describe the task**
Update message when navigate user to the Astar portal to stake

**English:**
- Header: Enter Astar portal
- Message: Navigate to Astar portal to view and manage your stake in Astar dApp staking v3
- Button: Cancel / Enter Astar portal

-----------
**Chinese**
- Header: 登录Astar portal
- Message: 请导航到Astar portal以查看并管理你在Astar dApp staking v3里的质押
- Button: 取消 / 登录Astar portal

-----------
**Vietnamese**
- Header: Truy cập Astar portal
- Message: Vui lòng chuyển hướng đến Astar portal để xem và quản lý stake của bạn trong Astar dApp staking v3
- Button: Huỷ / Truy cập Astar portal

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/XZCrXkr4ogReJMW
Validation passed 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/238be931-25d3-4918-bb2b-45e41042f97f)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e3e5ad0c-8945-4b99-aa58-fdbef3c3c46a)
