### ISSUE TITLE
Wrong transferable balance

### ISSUE THREAD

**Issue by Juanma0x** [Koniverse/SubWallet-Extension#2849]
The way transferable balance might not be updated to the current `balance` pallet.
 Example:
Account 15aVbh9j99DyEJo9pYDs6UMB25ybHAteb4xmjnXkiBx855Qo shows a transferable balance of 0 in SubWallet:
![image](https://github.com/Koniverse/SubWallet-Extension/assets/120041850/93a29071-3ff8-4188-91ab-a4fb44abf39b)

While a free balance of 8.47 DOT (at the time of writing) querying the chain state (`system.account`):
![image](https://github.com/Koniverse/SubWallet-Extension/assets/120041850/4e9f69d1-aca1-4b5b-8023-f8a49ac9abd7)

Related:
https://github.com/polkadot-js/apps/issues/9988
https://github.com/paritytech/polkadot-sdk/issues/1833#issuecomment-1805764506

**Comment by nampc1** [comment]
Hi @Juanma0x, we're aware of this issue and actually have an open issue on this. We'll make an update asap, thanks for raising the issue

**Comment by Juanma0x** [comment]
Thanks, @nampc1, for letting me know. I wasn't aware of https://github.com/Koniverse/SubWallet-Extension/issues/2118. Feel free to close this issue since it's duplicated. I apologize for not detecting the previous issue.
