### ISSUE TITLE
Support showing balance & transfer for GRC20 tokens

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2852]
https://wiki.gear-tech.io/docs/developing-contracts/standards/grc20

**Comment by bluezdot** [comment]
[x] Subscribe balance
[x] Transfer
[ ] Import Token: Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3067

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/dbCgKgmAzYy54Bi

Validation passed in cases:
- Show/hide token
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5c66f516-fd2c-4c5e-b81a-8e34812e0530)
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a7722986-83ce-4140-a1f5-8eef3af6ff9d)

- Show balance
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8a867460-4ace-4f9c-a937-79b2e4208cc8)

- Send token
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/49f55092-1498-4589-a436-25275698cf5b)

**Comment by Sokol142196** [comment]
Waiting for update data (remove data test) then release

**Comment by Sokol142196** [comment]
Check with contract:
- 0xa9a91df28c09f2fa1aaba9db93fa3f4edadb7c1999dbcf5d23762005cccc3c49 (Vara Testnet)
- 0xa10de81234db79ba2726c9410da9005d1a67e53888259818ad2b03ee434ce18f
- 0x5fdbe9407c70dd13dc8c95fbe1b6b07dce860d53aa67cf3fb41899c4a61f6eaf
