### ISSUE TITLE
Bump Polkadot dependencies

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2853]
Might resolve signing issue on Zeitgeist dApp

**Comment by nampc1** [comment]
![image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/a0f7d69e-be38-4a6a-b193-0db6544d876a)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/KwGHbSCGzrLM9fd
Validation passed : Retest all features of the app
- General settings
- Security settings
- Mission pools
- Manage website access
- WalletConnect
- Manage networks
- Manage tokens
- Manage account
- Managa address book
- Community & Support
- Reiceive token
- Buy token
- Send funds ( cross chain, on chain)
- Manage NFT
- Earning
- Crowdloans
- History
- Swap
