### ISSUE TITLE
Extension - Invalid recipient address when Dapp deploy smart contract

### ISSUE THREAD

**Issue by Thiendekaco** [Koniverse/SubWallet-Extension#2859]
### Contract Deployment fails when using SubWallet 

![Screenshot (685)](https://github.com/Koniverse/SubWallet-Extension/assets/139972251/3351cb84-357d-4238-b024-5cdc163a3810)

**To reproduce:** 
-   Deploy smart contract on mainnet: [https://metamask.github.io/test-dapp/](https://metamask.github.io/test-dapp/)
-   Deploy smart contract on testnet: [test-dapp-7vf9.vercel.app](https://test-dapp-7vf9.vercel.app/)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/SGFnSozAFsyoyTN
Deploy smart contract on testnet: https://yhj48x.csb.app/
Validation passed 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2db6c4a8-c3e2-4d86-a058-16a2ad46acc1)

**Comment by Sokol142196** [comment]
@saltict @Thiendekaco please implement page to test like to page https://metamask.github.io/test-dapp/ to test all method

**Comment by Thiendekaco** [comment]
@Sokol142196 Demo Dapp to test all methods on the Moonbeam Alpha Testnet network  [test-dapp-7vf9.vercel.app](https://test-dapp-7vf9.vercel.app/)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/SGFnSozAFsyoyTN
Validation passed when click on some methods deploy smart contract : 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3c93fbcd-d117-41d0-b7c5-f71fd2d4af77)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/30c789b2-1281-46b7-a465-bf5ea794cf69)

- Display on subscan 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/38a5b02d-5625-428f-ae99-7d9fc20a21f2)

**Comment by haiyenvu23** [comment]
The link summarizes the results of the methods : https://www.notion.so/subwallet/Other-notes-5968b0d4f34349f8963167001315214a?pvs=4#9ef967213fe746e6be4184f70b0ffd31

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/SGFnSozAFsyoyTN
Validation passed when click on some methods deploy smart contract 
=> Follow-up other methods

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/4aypwRnRBFro6aM
Validation passed in case : 
- Deploy smart contract with Ledger account


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a74cba74-e177-42d7-bbf8-ecdd567ae220)

- Deploy smart contract with normal account


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/119c92a5-f487-4a9b-8937-e66b69412dde)
