### ISSUE TITLE
Extension - Improve the Substrate Provider to meet the demands of dApps utilizing both EVM and Substrate.

### ISSUE THREAD

**Issue by Thiendekaco** [Koniverse/SubWallet-Extension#2869]
**Describe the update**
Improve the Substrate Provider to meet the needs of dApps using both EVM and Substrate.

- [x] Add a method to check whether the node is connected or not.
- [x] Display the EVM address if allowing connectivity for both methods.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/o6qrxeHdNfCcm5T

Validation passed 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cb3851e4-f4b8-42cb-b7cc-027f7ac7559b)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/90316283-4ac4-412a-b11a-f11bcdc265e8)

**Comment by Sokol142196** [comment]
@saltict @Thiendekaco please re-check expect for this issue
I prefer expect:
- The dApp supports any acc type, it will display that acc type like the previous logic
- With Polkadot js application, it is handled separately

**Comment by saltict** [comment]
Please update this task with:
- Enable by domains: https://polkadot.js.org/apps
- Enable with method: `wallet.enable(null, {evmAccount: true})`

**Comment by saltict** [comment]
Demo link: https://mkr52n.csb.app/

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/ctxJwF8skzYKoHL
Validation passed in case
- Connect/perform transactions with account EVM on Polkadot js (https://polkadot.js.org/apps)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6a8e9772-7bfb-4c87-9894-9cdccc5b16ff)

- Re-check connect/perform transaction with dapp EVM(Moonbeam dapp), dapp Substrate (Acala), Subconnect

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/ctxJwF8skzYKoHL
Validation passed in case
- Connect/perform transactions with account EVM on Polkadot js (https://polkadot.js.org/apps)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6a8e9772-7bfb-4c87-9894-9cdccc5b16ff)

- Re-check connect/perform transaction with dapp EVM(Moonbeam dapp), dapp Substrate (Acala), Subconnect

**Comment by ThaoNguyen998** [comment]
- [ ] Handly case upgrade version when connect with dApp Polkadot js app
Actual: 
  - Show popup request connect after upgrade version
  - Do not show account EVM on Manage website asset in case cancel connect

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e5e7c2d6-5f4a-488a-8da5-5b2b7d9e8fe5)

Expect: Do not show request connect and auto display account EVM on Manage website asset

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/9eiyEYLSH8gN66K
Validation passed

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/1c25ae10-1bf9-4277-a1f4-24c94c6f1c42)
