### ISSUE TITLE
Do not detect balance after reset wallet

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2880]
**Describe the task**
Do not detect balance after reset wallet

To reproduce the bug
1. Attach account have balance
2. Observe the list token displayed
3. Perform reset wallet
4. Import another account have balance 
5. Observe the list token displayed again

**Actual:** Do not detect balance
**Expect:** Auto detect balance

**Comment by PDTnhah** [comment]
Cannot reproduce the bug
