### ISSUE TITLE
[Extension] Re check function `enableChains`

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2882]
### Actual:
  - When scanning to detect balance then auto enable chains and tokens. All detected token is enabled but some chains don't enable them successfully.
  
### Expect:
  - All tokens and chains are enabled for success

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/gDH2bAppLwfE2gB

- [ ] Don't enable chain testnet although that network's token has balance

Actual : 
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cd302ab0-4504-4aa9-8fe8-378e1d90816c)

Expect : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e964b25d-5f29-4d2f-8c64-76a198f7e787)
