### ISSUE TITLE
Error when fetching balance with Enjin Relay Chain

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2885]
Fix error when fetching balance with Enjin Relay Chain

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/dcde7747-7b0b-4def-8319-7b3eac85a1ca)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/sMYgKkfo5Dr9pwL

Validation passed. 

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/35ef5e74-3011-4628-9c98-825b211c5ad9)
