### ISSUE TITLE
Extension - Re-check min active stake for Relaychain

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2889]
**Describe the task**
Re-check min active stake for Relaychain

**To reproduce the task**
Actual: Show incorrect min active stake in case min validator < min network

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/438b404b-74f5-4176-b8d2-42439b7c869f)

Expect: Min active stake  = Max {Min active stake network, Min active stake validator}

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/nH4P9ACAw54x5AR

Please check issue:

- [ ] Show incorrect minimum stake required of the validator on the Validator details screen
  - Actual: Show minimum staked of the network
  - Expect: Show minimum stake required of the validator
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ef9dec16-1aaf-4fd7-b531-c69f0734f5d4)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/YApYJQxZntYz6Jp
Validation passed
![2889-Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/aad54b0d-911d-46b1-9716-9f7840b9b331)

- Notes: Retest other staking type
