### ISSUE TITLE
Extension - Show dApp confirmation although performing transaction in app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2891]
**Describe the task**
Show dApp confirmation although performing transaction in app

Version test: https://github.com/Koniverse/SubWallet-Extension/releases/tag/untagged-a37e641d54a007f1fdad

**Actual:** Show dApp confirmation

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/8e0eef03-c559-49e4-9fe8-469e1468e5bb)

**Expect:** Show transaction confirmation in app

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/deEY4H8RTQQQtLm
Validation passed in case : 
- Show transaction confirmation in app
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/41517da6-a3f4-4062-8f63-435a38e47a31)
