### ISSUE TITLE
Automatically enable network when connecting via Substrate provider.

### ISSUE THREAD

**Issue by Thiendekaco** [Koniverse/SubWallet-Extension#2899]
**Describe the update**
When executing transactions from Substrate accounts via the Dapp, if the network sometimes carries out transactions without being enabled, it will be handled by automatically enabling it.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/LoPHb9JMtTPWnfj
Link dApp : 
- https://w3o-demo.subwallet.app/#/wallet-info
- https://polkadot.js.org/

Validation passed 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8d2a2d87-48ce-4dd9-a18b-9ced86959b73)
