### ISSUE TITLE
Extension - Error displaying 'connection existed' when connecting WalletConnect.

### ISSUE THREAD

**Issue by Thiendekaco** [Koniverse/SubWallet-Extension#2903]
**Describe the bug**
The error message 'connection exsited' is displayed when attempting to establish a connection with WalletConnect, despite no existing connections being added.

**Comment by Sokol142196** [comment]
Waiting for link guide

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/8x3LSP3dWiszRLb

- [ ] When click X, navigate to link guide
**Expect** : 
  - Close popup
  - Reset data on URI field when click button Dismiss/Review guide/X


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/917d1942-c717-4dc9-9f78-79dd49e42e6c)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/83sKYk3n2dwGrX2
Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4a699955-2a8e-4b0c-bbfc-9bb4bd3f48fa)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/HKYtwyjpwisZRww
Validation passed in case : 
- When input URI existed
- When input URI connected on different device
- When turn off internet


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/437d6412-6eef-442d-aebc-aaba90e0bbde)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/ks9XZ2ZytamZ52T
Please check bug error page when sign message with WalletConnect

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6f45f8c7-e76a-46ce-89e5-ab670f0e13dc)

Crash log 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/52ae631c-5715-4c8f-8af0-f2fdf74488d2)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.158.246:8900/s/nEPbrJs9w5P29rg
Validation passed in case : 
- When sign message with WalletConnet , dApp
