### ISSUE TITLE
WebApp - Add more currency type

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2914]
**Describe the update**
Add more currency type
Link design : 
- https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=4701-145122&mode=design&t=7bKxSRHXCWBVV2it-4
- Icon create : https://www.figma.com/file/mfCcK60D4OWv42MlVvrJF4/SubWallet-UI-Base-1.0.1?type=design&node-id=5460-200&mode=design&t=oShoo3Kv0I8QvUgg-4
- Icon Phosphor : https://www.figma.com/file/vBfYyrSDbMmwmd6Mhkpm4G/Phosphor-Icons-(Community)?type=design&node-id=5941-15986&mode=design&t=awEogVecl58lcwzp-4

**Comment by haiyenvu23** [comment]
Version test : https://d9be5650.subwallet-webapp.pages.dev/

- [ ] Update UI 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cf8e6cc8-9bb0-45f0-979b-7dbf7c696c14)

**Comment by haiyenvu23** [comment]
Version test : https://ad483fee.subwallet-webapp.pages.dev/

- [ ] Improve UI 
Link design : https://www.figma.com/file/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?type=design&node-id=24030-234173&mode=design&t=9v9PC9R2PU8bCxK4-4



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f0314e6b-27fe-4b1a-9349-71b0e9752317)

**Comment by haiyenvu23** [comment]
Version test : https://3f40fc27.subwallet-webapp.pages.dev/

- [ ] UI bug in case responsive


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/097de2b1-6bf9-472c-89c9-c1e2e1575891)

- [ ] Update font-size tooltip


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/efe6595d-edda-4da6-adaa-6aad37b510d1)

**Comment by haiyenvu23** [comment]
Version test : https://777daaeb.subwallet-webapp.pages.dev/
Validation passed in case : 
- Convert currency values ​​according to each country correctly
- Currency symbols display in the following locations :Tokens feature, Earning screen , Swap feature ,Crowdloan screen
- Case responsive


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/46223221-f176-4b45-97f2-ef8728cd20a5)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c9d5e7a5-4023-4e5b-8af6-154e72a2a51b)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/94d23677-6132-4bcb-99bb-6b7ab04e200a)

**Comment by haiyenvu23** [comment]
Handle the case of not resetting the wallet to the default state when click Erase all
=> Related to issue https://github.com/Koniverse/SubWallet-Extension/issues/3036

**Comment by ThaoNguyen998** [comment]
Version test: https://777daaeb.subwallet-webapp.pages.dev/home/tokens

- [ ] Bug responsive

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d814634d-e2ea-47db-965d-6abb0302a3a6)
