### ISSUE TITLE
Extension - Do not get Swap quote

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2925]
**Describe the bug**
Do not get Swap quote, if click on Swap button then do not show message warning to user
- I check with ETH --> DOT 
- Notes: The network is enabled and get balanced successfully

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d4b5a380-b8ae-47b6-b50a-f39bef750d53)

**Comment by nampc1** [comment]
Cannot reproduce this issue consistently, we'll circle back to this later

**Comment by nampc1** [comment]
Have not met this issue again, we'll open another issue if this surface again
