### ISSUE TITLE
Re-check case remove custom network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2927]
**Describe the task**
Re-check case remove custom network

**Actual:** Do not remove

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/182023e8-dce1-47ca-9ce7-12f8d3461c59)

**Expect:** Allow remove

**Comment by ThaoNguyen998** [comment]
@Sokol142196 I can't reproduce the bug
Note: Need to disable the custom network
