### ISSUE TITLE
Integrate nfts pallet on Asset hub

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#2934]
Take a look at this address for an example
https://assethub-kusama.subscan.io/account/dmzU8nByokRtp8gmKfsw4PDstcb9G13zQVt7st3wfEymEd3SP

**Comment by bluezdot** [comment]
Asset Hub (Polkadot) and Asset Hub (Kusama) have two type of NFTs: nfts-based and uniques-based pallet. In this issues, we want to support all of them.
Information:
https://assethub-polkadot.subscan.io/uniques_dashboard
https://assethub-polkadot.subscan.io/nft_dashboard (Supported before)
https://assethub-kusama.subscan.io/uniques_dashboard (Supported before)
https://assethub-kusama.subscan.io/nft_dashboard

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/XP8YdqBZyCgTzsb

- [ ] Re-check case NFT is not displayed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/30c5d6ea-3b85-48c0-91b9-eb91de80ba93)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/CF54W7JidELmB47
Validation passed in case 
- Asset Hub (Polkadot)
  - nfts-based pallet 
    Data test : 13urRDmjzXNyQ74QCHiJWutbsyvqr3c22QNgiSkJ7KZ24bZT

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5141697e-5570-4816-aecf-568b3165f50f)

 - uniques-based pallet
   Data test : 155HWw3J9jyYphMm5is4vp9Bzj7ZRRd6HEzCPdWd8cq97KfT
  

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/60774a30-f9b2-4ddf-803b-9466b267e2d0)

- Asset Hub (Kusama)
   - nfts-based pallet 
    Data test : CmWHiv7h4m9tEzKD94DH4mqwGTvsdYQe2nouWPF7ipmHpqA


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cc62e2a1-fbf2-4e1b-b8dc-fb5d0643c4d4)


 - uniques-based pallet
   Data test : JGtWPaYp9ARMjZFAMRGrtyJGVWLYDnh9eAWcjF666qLQXmu
  

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f2cb3042-6624-4bfd-8e69-47398b31ddf1)
