### ISSUE TITLE
Extension - Display list Recommended by label in Select pool screen

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2940]
**Describe the task**
Display list Recommended by label in Select pool screen
Link design : https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=20941-310124&mode=design&t=M1bapyrZBftQFlmW-4

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a292c661-6dd4-4075-b863-5be59417e776)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/oQyP5tctPsM7mjx

- [ ] Re-check sorting lowest total member

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6ef7b86e-2707-456f-b89c-c7ee6bae50ff)

- [ ] Error page when click this pool


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f3d27d10-0e19-4fc4-b210-5ceb69c97d64)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/WyGDRe4xMWDB4B6
Validation passed


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6295e481-e827-4b11-bc6d-bf908caed9e5)

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/x2os6Mqn7FfgtnD

- [ ] Please set default pool = "SubWallet Official 3" (Pool id = 62)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/BbFi4sytqGq6t5R

- [ ] When searching for results, it must display what type of label the result belongs to


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6174c1f9-fb89-4224-b40b-4edfe4027d4b)

**Comment by ThaoNguyen998** [comment]
Version test: http://file.cdmteck.com/s/58nXqwNdZzqScLo
Validation passed in case: 
- Display list Recommended by label in Select pool screen

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ec62a2aa-1599-4505-bcfe-4f0d08ef47e2)

- Set default pool = "SubWallet Official 3" (Pool id = 62) for Vara Network

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/802012b8-1661-4fe8-a50b-97aaaf3bd490)

- Sorting lowest total member

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/88c97fbf-e1ea-4830-90c8-15731676e23d)

- Re-check Recommended list
- UI bug when filter

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/18b14f2d-5ad5-44e6-b6c2-ec716f53d816)
