### ISSUE TITLE
Re-check and update earning status

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2941]
**Describe the bug**
Re-check and update earning status

**Comment by bluezdot** [comment]
Related issue: #2937

**Comment by bluezdot** [comment]
- [ ] Update earning status
- [ ] Update overview information

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/5aSPbg4Z7CRDTgD
Validation passed in cases:
- Show earning status 
- Show direct position of Polkadot, Kusama, Moonbase
- Re-check main staking actions 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/408df157-8162-4a2f-a41a-73d0612b4b10)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6622014e-3d78-48d1-8caf-b3811713b6c1)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2a39399d-27a8-4ee4-91ad-060d1322f456)
