### ISSUE TITLE
Extension - Hide popup Introducing Earning feature

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2948]
**Describe the task**
Hide popup Introducing Earning feature

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/db689286-3f80-42ad-8b36-07921df32774)

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/RC3TJHyP2p6bSJf

- [ ] Do not show campaign popup
  - Actual: Do not show Introducing Earning feature popup, but do not show popup campaign
  - Expect: Show campaign popup as soon as you open the extension

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/LNJXSBR5LBjncdj

Validation passed

![2948-Validation](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/67a7bf64-094c-4027-96be-4aa7d9b03192)

Note:
- Re-check case upgrade version
