### ISSUE TITLE
Update newest code into MV3 version

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#2951]
Update code version 1.1.57 into mv3

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/WDDBPpqsPDrPXHt
Validation passed : 
Re- test all features of the app
- General settings
- Security settings
- Mission pools
- Manage website access
- WalletConnect
- Manage networks
- Manage tokens
- Manage account
- Managa address book
- Community & Support
- Reiceive token
- Buy token
- Send funds ( cross chain, on chain)
- Swap
- Manage NFT
- Earning
- Crowdloans
- History
