### ISSUE TITLE
Extension - Do not show transaction history in case sender account null

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2955]
**Describe the bug**
Do not show transaction history in case the sender account null

**To reproduce the bug**
Check with account: kGfgMX3aQHvFDftJmPY7qMDhf6w351MoLUN1j4npS3Z9U4SV1 (Vara network)

**Comment by S2kael** [comment]
### Reason
- Data from subscan api have `from_account_display` or `to_account_display` is null

### Solution
- If transaction history missing data, don't handle adding the history

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/qzc9p5BMirCfZLQ

Validation passed
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/91d3bb1f-09a4-47ac-83ef-ec68db96f2ec)
- Re-check some networks is normal
