### ISSUE TITLE
WebApp - Implement UI for selecting token to pay transaction fee on HydraDX

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2959]
**Describe the task**
- [x] Implement UI: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?type=design&node-id=20976-202747&mode=design&t=fszQPouDaAYQugvs-4

**Comment by haiyenvu23** [comment]
Version test : https://45d07cdd.subwallet-webapp.pages.dev/

- [ ] Change text "Estimated fee" -> "Network fee"


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4be07aaa-f685-478a-b2e5-d02da373337c)

- [ ] Update UI


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e584170d-24d1-4b5b-8f8c-6ae7ce40c5f1)

**Comment by nampc1** [comment]
- [ ] Allow selecting fee token
- [ ] Implement confirmation for fee token tx
- [ ] Update show history for fee token tx
- [ ] Update show fee in swap confirmation

**Comment by Sokol142196** [comment]
Version test: https://a686c55e.subwallet-webapp.pages.dev/

- [ ] Do not show change fee confirmation screen
- [ ] Re-check flow when have XCM

**Comment by Sokol142196** [comment]
Version test: https://pr-2969.subwallet-webapp.pages.dev/

- [ ] Show incorrect fee 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/c22796f8-c1ef-44d2-adfe-18dfb6dce6b2)

**Comment by ThaoNguyen998** [comment]
Version test: https://e7d98004.subwallet-webapp.pages.dev/transaction/swap

- [ ] Unable to swap in case select fee token = DOT

![Image](https://github.com/user-attachments/assets/4f91c561-e278-49c4-a648-60381ec60cf8)

**Comment by ThaoNguyen998** [comment]
Version test: https://c46ec624.subwallet-webapp.pages.dev/transaction/swap
- Do not show Swap quote in case the change token

  https://github.com/user-attachments/assets/2fc10a0e-4da4-47f6-8adb-d7dca2f147ed

- Re-check Amount max in case swap has XCM
Check with the account: 5CFh4qpiB5PxsQvPEs6dWAhzgAVLHZa8tZKxeE9XsHBg4n9t
Steps: 
  1. Select token = DOT(Hydration)
  2. Input Amount = max(0.85)
  3. Select Network fee = DOT
  4. Click Swap and observe the displayed screen
  5. Input Amount = Max - Network fee
  6. Click Swap and observe the displayed screen
Actual: Show message Insufficient balance. Deposit DOT and try again.

**Comment by ThaoNguyen998** [comment]
Version test: https://efce99f0.subwallet-webapp.pages.dev/transaction/swap

- [ ] Auto choose fee token in case select token = DOT(Hydration)
Actual: Auto choose fee token = DOT

  https://github.com/user-attachments/assets/4cde1102-bb42-490c-9d8e-505267eabf1c

Expect: Choose fee token default Hydration = HDX

**Comment by ThaoNguyen998** [comment]
Version test:

- [ ] Add information token currency on History

- [ ] Do not show the Transaction type on the History setup fee token

  ![Image](https://github.com/user-attachments/assets/74ce49ca-4e9b-45b2-91c5-64f6493fec43)

- [ ] Update message in case input Amount < Min swap HDX
  Actual: Show message "Amount too low. Increase your amount and try again"
  Expect: Show message "Amount too low. Increase your amount above {} and try again"

**Comment by ThaoNguyen998** [comment]
Version test: https://658149af.subwallet-webapp.pages.dev
Validation passed.
