### ISSUE TITLE
[Extension] Add support for Mythos Chain

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#2966]
- https://github.com/Koniverse/SubWallet-ChainList/issues/204

**Comment by ThaoNguyen998** [comment]
Version test: http://file.cdmteck.com/s/QBy8maKBEy5QYXn
Validation passed.
- Network, token info

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/817b6c50-e2d4-4697-9e50-49c6ebb7c3f0)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/43087bed-01dc-45f3-8b21-b239d6d132db)

- Show balance

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/bdf6b5bc-4a3a-485e-a4fc-70c608b69b7d)

- Receive

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/cc1a024d-6c62-4257-b16a-5e116877b4a3)

- Transfer

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/c5618b9f-9246-47ea-a795-39c0938ed7f1)

**Comment by ThaoNguyen998** [comment]
Version test: http://file.cdmteck.com/s/QBy8maKBEy5QYXn
Validation passed.
- Network, token info

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/817b6c50-e2d4-4697-9e50-49c6ebb7c3f0)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/43087bed-01dc-45f3-8b21-b239d6d132db)

- Show balance

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/bdf6b5bc-4a3a-485e-a4fc-70c608b69b7d)

- Receive

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/cc1a024d-6c62-4257-b16a-5e116877b4a3)

- Transfer

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/c5618b9f-9246-47ea-a795-39c0938ed7f1)
