### ISSUE TITLE
Extension - Set default pool for Avail Turing

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2971]
**Describe the task**
Set default pool for Avail Turing
- Pool ID: 11
- Pool name: Avail Space

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Add tag recommended for pool Avail Turing

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/847461da-4909-4333-9746-2585b210d221)

- [ ] Sorting default pool on top list

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/cbcb6074-dbf3-4309-bacf-fada560cb58c)

**Comment by Sokol142196** [comment]
Version test: https://github.com/Koniverse/SubWallet-Extension/issues/2971

Validation passed
<img width="192" alt="image" src="https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9cd27e87-56e7-44f0-84e8-79cf1bf40c0f">
<img width="192" alt="image" src="https://github.com/Koniverse/SubWallet-Extension/assets/130966515/a8e8be1c-1236-4714-83d4-4ec1bd7efdbf">
