### ISSUE TITLE
Extension - Currency settings are reset when upgrade version

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2977]
**Describe the task**
Currency settings are reset when upgrade version
**Steps** : 
1. Upgrade version
2. Setup currency mode
3. Reload extension 

**Actual** : Currency settings are reset 
**Expect** : Currency settings are not reset

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2ada0748-d8e1-43b8-bc50-ff535f2a8367)

------------------

- Re-check run exchange rate currency
![image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a5c2f487-fabc-4488-a086-de0a127f0053)

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/jXHjSzTmcsWtJJR

Validation passed in cases:
- Change currency
- Upgrade version
- Reload background

Actual: Show incorrect exchange rate

**Comment by Sokol142196** [comment]
Resolved on https://github.com/Koniverse/SubWallet-Extension/issues/2738
=> Close this issue
