### ISSUE TITLE
Extension MV3 - Unable to get quote when perform swap

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2992]
**Describe the bug**
Unable to get quotes when performing swap

**To reproduce the bug**
Steps: 
1. Go to swap screen
2. Input valid and observe the displayed screen

Actual: Unable to get quotes

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/3bce8f17-bc7f-4342-84b4-b89d1b7dfea8)

Expect: Show swap quotes

**Comment by haiyenvu23** [comment]
Resolved in issue # 2980
