### ISSUE TITLE
Extension - Bugs related to earning feature ( Round 5)

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#2995]
**Describe the task**
- [x] When submitting then disable all actions 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/b32e0686-040d-48b6-a877-f8d98c040079)

- Support earning for Shibuya => not need fix
-  Error auto reset data on Pool field => Resolved in issue #3001

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2c94a28c-ab3e-4837-af8d-5b68e7f1217a)

-  Error page when click this pool => Related to issue : https://github.com/Koniverse/SubWallet-Extension/pull/2978

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f3d27d10-0e19-4fc4-b210-5ceb69c97d64)

**Comment by dungnguyen-art** [comment]
- 1. Support earning for Shibuya: Not need fix.
- 2. Error page when click this pool: his will be fixed in another issue.
- 3. Error auto reset data on Pool field: This is currently not fixed due to a conflict with another pull request.
- 4.  When submitting then disable all actions: Fixed in PR of this issue. 
@haiyenvu23

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/TdaRCZYwBGs4qxJ

- [ ] After click Cancel on Confirmation screen
Actual : Disable All account mode
Expect : Enable All account mode



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/660468db-d31e-401b-8938-195ec680e696)

**Comment by haiyenvu23** [comment]
- [ ] UI bugs


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/aa1a6392-f245-4919-ab7a-c9fb9c0948a8)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/aoygmxbdbT7y5Wo
Validation passed. 
- Disable all action when submitting data (Stake, Stake more)
- Fix UI bug
- Fix bug disable All account mode After click Cancel on Confirmation screen
