### ISSUE TITLE
Extension - Show incorrect available on Earning options

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#2997]
**Describe the bug**
Show incorrect available balance on Earning options

**To reproduce the bug**
Actual: Available balance on all networks(DOT - Manta does not support staking)

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/cc1e57aa-6bf6-49d9-b934-8c5aedcf4791)

Expect: Available balance only on networks that support staking

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/FDGHnELLpYCM8gA
- http://14.224.129.242:8900/s/6csnKMjBQQGmYDR
Validation passed in case : 
- Install/Update version
Account test : h7rYZE5N6EtBqvBVH4mi41xw5khpSyB5DuSW5xJsq5KKwAS

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5db85cb1-6d4b-4765-993c-107176a7df18)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3a24db5d-033e-4f53-8406-1d1e52398a17)
