### ISSUE TITLE
Extension - Update Validator name/ Collator name

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#2998]
**Describe the task**
Update Validator name/ Collator name

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/e866cb6d-a336-47bb-bd2a-894920f97a1c)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/c5BAWiDoWprdwNR
Validation passed in case : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6f65b0be-3f00-4e8f-a0e1-f3a1ec3ea476)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5fd2b2cc-1588-4ae5-af30-6b4463a386d5)




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/f96944d5-22f3-4fa0-9636-45ffb2e54377)




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c8b51705-135b-4ac2-bf1e-ffc230a5cfcd)
