### ISSUE TITLE
Refactoring code earning service

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#3000]
**Is your feature request related to a problem? Please describe.**
Maintain code earning service

**Describe the solution you'd like**
- Refactoring
- Optimizing

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by bluezdot** [comment]
Update on relaychain native staking
- Position info
- Get pool info

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/cikSjH8RWf2GFHq

- [ ] Can't see Direct nomination of AVAIL 
Account test : 5CFh4qpiB5PxsQvPEs6dWAhzgAVLHZa8tZKxeE9XsHBg4n9t



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/28760e2e-d32e-4ed3-90e3-47b100cc656d)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/nn5yZiB9J2AjKn2
Validation passed in case : 
- Check on relaychain native staking:
- Position info


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/204d45af-fe98-431c-a570-725939ea963b)



- Get validator info





![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/69804acd-c680-432f-804b-a16444082fdb)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/qz76233jaieTqoD
Validation passed in case when update middleware service :

- Check on relaychain native staking:
- Position info
- Get validator info

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Re-check: do not update ED for Vara Network(Earning)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/43269edb-8618-4aeb-8ce1-26f67872225d).

**Comment by ThaoNguyen998** [comment]
Version test:  http://14.224.129.242:8900/s/EPbwFok9r9Mee7K
Validation passed.
- Update ED for Vara Network(Earning)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/206a8ee0-50c5-4116-abfc-29fa0e152f9d)

-  Re-check: 
  - Check on relaychain native staking:
  - Position info
  - Get validator info
