### ISSUE TITLE
Extension - Error auto reset data on Pool field

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3001]
**Describe the task**
Error auto reset data on Pool field

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2c94a28c-ab3e-4837-af8d-5b68e7f1217a)

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Do not automatically select pool when staking

  ![Image](https://github.com/user-attachments/assets/0f0c8fea-4573-4016-9a23-7aa45400bb41)

  Expect: Auto-select pool on Recommended

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/oCsnK6n6MDMiKnL
Validation passed:
- Fix bug auto reset pool
- Re-check select pool (All account, Current account)
