### ISSUE TITLE
Block attach account Polkadot vault for network Moonbeam, Moonriver, Moonbase

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3022]
**Describe the task**
Block attach account Polkadot vault for network Moonbeam, Moonriver, Moonbase
(Polkadot vault does not support Moonbeam, Moonbase, Moonriver)

Expect: Show message: "Invalid QR code. EVM networks are not supported"

**Comment by Sokol142196** [comment]
Same as https://github.com/Koniverse/SubWallet-Extension/issues/3056
