### ISSUE TITLE
WebApp - Error getting wrong validator address

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3033]
**Describe the bug**
Error getting wrong validator address

**To reproduce the behavior**
Steps : 
1. Stand on Select validator screen
2. Copy and Paste validator address
3. Observe display screen

**Actual** : Displaying by first address 5
**Expect** : Displaying by network address

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8458919d-b340-4357-ad9e-0d6f2472e3b1)

**Comment by Sokol142196** [comment]
Version test: https://pr-3177.subwallet-webapp.pages.dev/

- [ ] @dungnguyen-art @haiyenvu23 Currently, it is only processed at the List validator screen?
  Please check when:
    - Click on avatar on pool details screen
    - Other feature

- [ ] Re-check search feature 
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/56f530d3-3335-453a-bde7-00ffe76cb65e)

**Comment by ThaoNguyen998** [comment]
Version test: https://40a0ebfe.subwallet-webapp.pages.dev/transaction/earn
@dungnguyen-art Please re-check the comment on https://github.com/Koniverse/SubWallet-Extension/issues/3033#issuecomment-2160427795
 -> Still reproduce the bug
