### ISSUE TITLE
Add the feature that allows users to show/hide zero balance of tokens, or delete/hide tokens inside each chain

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#304]
**Is your feature request related to a problem? Please describe.**
At the moment, SubWallet shows all tokens inside each chain. That is a good feature. However, there are many tokens inside a chain and this can result in the fact that users find it difficult to manage their balance/portfolio.

<img width="457" alt="Screen Shot 2022-05-26 at 10 09 43" src="https://user-images.githubusercontent.com/102496727/170408543-a334a8d5-97c8-4499-be1b-a3481c5aeda8.png">

**Describe the solution you'd like**
There should be a feature that allows users to show/hide tokens with zero balance. Also, there should be a feature for users to delete/hide a token that they do not own / do not want to own in the future

<img width="458" alt="Screen Shot 2022-05-26 at 10 09 54" src="https://user-images.githubusercontent.com/102496727/170408942-b74f1bc7-9608-4759-a30a-ff991772a0bb.png">

<img width="356" alt="Screen Shot 2022-05-26 at 10 19 29" src="https://user-images.githubusercontent.com/102496727/170409154-401d062c-b696-4108-85b1-b8c8f261863d.png">

Thank you very much.

**Comment by NamPhamc99** [comment]
Done by new architecture
