### ISSUE TITLE
Extension - An error occured in case of transfering PANX (Aleph zero)

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3041]
**Describe the bug**
Bug when transfer token PANX for Aleph zero

**To reproduce the bug**
Steps: 
1. Perform transfer PANX token
2. Click button max
3. Observe the displayed screen

**Actual:** 
- Extension: User click transfer Max but do not get Max balance
- Mobile: Show Error page with log

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ae11cea5-98a8-4269-8c00-395fd492462b)

**Expect:** Get max amount and Transfer successfully

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/GMmPddwGprtcANq
Validation passed in case : 
- Transfer max/normal Native token
- Transfer max/normal Local token



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0b9ee841-753c-430a-83d5-ffdbaa5f701a)
