### ISSUE TITLE
Extension - Show nomination pool with block status

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3043]
**Describe the task** 
Show nomination pool with block status
- Add status = Blocked on Pool details
- Handle when selecting pool block
  - Option 1: Grey item, do not allow select
  - Option 2: Allow select -> show toast
  -> Discuss more
- Add filter = Blocked

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/oDaT77wFoQSb458
Validation passed in case : 
- Show nomination pool with block status


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a9721f87-5796-41c6-b516-5f249248e77e)

- Check with direct nomination


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2db878c3-d54b-49cf-8b5c-ba030645e79b)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/RSBkM55fpoG7ygL

- [ ] Add tooltip in case hover on pool with status block

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/g5ttowi7P8WC5sD
Validation passed
- Gray item, show tooltip, sorting for pool has blocked state

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/b85a04a1-01a1-4b25-9ce8-177a4b558e30)

- Allow open Pool detail

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/0baa71d1-d27b-4258-8174-8893bf1be21d)

- Add filter Blocked

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ff963f8b-9990-4272-8733-e3b74c5c5e72)
