### ISSUE TITLE
WebApp - Auto reset currency when reloading browser

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3049]
**Describe the bug**
 Auto reset currency when reloading browser 

**To reproduce the bug**
Steps: 

1. Change currency successfully
2. Reload browser and observe the displayed screen 

Actual: Auto reset currency

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/10379f12-c6b9-40f0-8aad-c15c9bc21d5c)

Expect: Do not auto reset currency

**Comment by Sokol142196** [comment]
Do not reproduce the behavior on v1.2.28 1228002
