### ISSUE TITLE
Extension - Add popup remind backup account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3050]
**Describe the task**
Add popup remind backup account
- Refer popup Updated MV3 
- Notion: https://www.notion.so/subwallet/Popup-remind-export-account-tr-c-khi-update-l-n-MV3-a823a8a56cbb4780a861b4cf4bb8dfe9?pvs=4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/jAS5PoD7N2LE2XR

- [ ] Update content
Header : Back up your accounts! 
Content : If you lose your seed phrases/private keys/JSON backup files/QR backup codes, your accounts can't be recovered and your assets are lost. Learn how to back up your accounts to secure your assets now.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/nFkZp5T5SPBj4rC

- [ ] In case reload the extension while the popup is showing
Actual : Popups are disabled
Expect : Popup must be display



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/86a00981-5f57-4951-924c-dd30521b8456)
