### ISSUE TITLE
Extension - Add the "View on explorer" button on the Token details screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3053]
**Describe the task**
Add the "View on explorer" button on the Token details screen

- [x] Add on the Token details screen in case specific account
- [x] Add on the Token details screen in case All accounts

Link design: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=24082-121653&t=eg7PB3edkG4pgGnP-4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/rPiLfRSyGpi7SPQ

- [ ] Update UI according to design
Actual : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ec225669-d2d9-410f-bb01-c81cb67793e9)

Expect : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/042b67bd-f13a-4040-9282-df71d8808caa)

- [ ] Remove button View on explorer in Token details tab when on All account mode


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5bba1325-148e-4dec-a299-4396f3fffe2e)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/S5opoJAFAnfo6ED
Validation passed in case : 
- All account mode 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c61f929d-e303-49c0-9afd-ace0cb516117)

- Specific account 
- Account has balance

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/wBL9MtSoXQ5nYHg
Validation passed in case : 
- Install/Update version
- All account mode


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cb811358-99de-46d9-8e51-c617d18b78f2)


- Specific account mode


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/98b16769-a3cf-4252-bda9-9d2230383a4f)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/ZBX42nY4AGDNRrt

- [ ] Update icon and text on Your address screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6ec92ce6-dc6c-4b05-80d2-a59978e7c8c5)

**Comment by dungnguyen-art** [comment]
![image](https://github.com/Koniverse/SubWallet-Extension/assets/59666831/0626e441-ba63-4293-95de-b130bb4fd00d)
Add sub-logo

**Comment by haiyenvu23** [comment]
Version test : 
- Extension: http://14.224.129.242:8900/s/KHsa4MJbnf33xD4

Validation passed in case:
- Update icon and text on �Your address screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6ec55339-8b11-4fba-83f6-e8fa2dc1d5e6)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7371d67d-4791-4005-b650-207e35b41591)

 - Add sub-logo on Your earning position screen
 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/fcb36c50-15ed-4d7f-b97a-645c6be50e4f)
