### ISSUE TITLE
Extension - MV3 - Auto reset currency in case upgrade version

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3060]
**Describe the bug**
Auto reset currency in case upgrade version

**To reproduce the bug**
Steps:

1. Perform config currency = Euro
2. Upgrade version to MV3 and observe the displayed screen

Actual: Auto reset currency = USD
Expect: Keep the same settings

**Comment by Thiendekaco** [comment]
Need to check carefully like the following steps to reproduce the error: 
- Update or reload extension
- Continuously changing currency.

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/RkK2jrodxCjzsmG

- [ ] Auto reset currency in case upgrade version

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/48973729-139c-4b35-b05b-902c847ca6ec)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/RkK2jrodxCjzsmG
Validation passed in case : 
- Update version 
- When ON/OFF/Reload extension with Authenticate with password mode



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/87f5304b-ab56-44ab-8c53-4add96232f78)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0ad9977c-f681-4c29-81da-866abbf38e1d)
