### ISSUE TITLE
Extension - Unable to back screen in case open General settings to Marketing campaign

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3062]
**Describe the bug**
Unable to back screen in case open General settings to Marketing campaign

**To reproduce the bug**

Steps: 

1. Perform open General settings to Marketing campaign
2. Click button back and observe the displayed screen

Actual: Unable to back

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/047c2a04-d95c-4bd5-afea-ea2d6342a540)

Expect: Navigate to Setting screen

**Comment by ThaoNguyen998** [comment]
Version test: http://file.cdmteck.com/s/QHZS2SA5bo2LJQf
@Thiendekaco please re-check this issue

- [ ] Cannot return to the previous screen on Token detail, Import token, NFT detail

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6750820c-2212-4c22-922f-9f2c87a1b915)

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/GcaSZcDXLyqAqFx
Validation passed in case : 
- Update version 
- Instal vesion 



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5079f847-fabf-49bf-82a9-20d971470ba0)
