### ISSUE TITLE
Refactor logic parsing data from contract response

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#3070]
**Is your feature request related to a problem? Please describe.**
- Current logic is so complicated makes it hard to read and maintain. Need to refactor.

**Describe the solution you'd like**
- Split into small functions to handle each case (token type as PSP22, PSP34, GRC20).
- Handle response by util functions.
- Create interface for returned token info.

**Describe alternatives you've considered**
- No

**Additional context**
- No

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/zECcgNPL46e95mm
Validation passed.
Checklist for issue: https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#eaa631bf6c224f07adbdc031a9ab62ae
