### ISSUE TITLE
Extension - Remove the logic that differentiates between Native tokens and Local tokens in case show sub-logo

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3075]
**Describe the task**
Remove the logic that differentiates between Native tokens and Local tokens

**Actual** : Don't show sub-logo on Native token
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/daf61a73-503c-4636-b8ef-a98537b79bb3)

**Expect** : Add sub-logo on Native token

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/xQicESpii8txNi8

- [ ] Re-check style sub-logo


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ef6ab813-1cfc-4a3c-8500-264f1d9e9176)

**Comment by ThaoNguyen998** [comment]
Version test: http://file.cdmteck.com/s/xQicESpii8txNi8

- [ ] Do not show sub-logo on Select token on search token screen

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/019871ee-4e33-4404-a81f-b5f2f02bf65f)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/Z9LGs87rGYwoPCK
Validation passed in case : 
-  Show sub-logo on Select token on search token screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/069d2b2f-47d1-4dca-85f8-dd1f1463f183)
