### ISSUE TITLE
WebApp - Add message when perform connect and sign transaction with Moonbeam on Polkadot vault

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3077]
**Describe the task**
Block attach account Polkadot vault for network Moonbeam, Moonriver, Moonbase
(Polkadot vault does not support Moonbeam, Moonbase, Moonriver)

**Actual**: Still allow attach account but can not sign transactions cause Polkadot Vault do not support
**Expect**:

- In case attach account: Show message: "Invalid QR code. EVM networks are not supported"
- In case attached account: When perform any transaction then show warning message do not supported : "This feature is not available for EVM QR signer account. Change to another account type and try again."

**Comment by Sokol142196** [comment]
Resolved on v1.2.28 1228002
