### ISSUE TITLE
Add Ledger support for A0 testnet

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3080]

**Comment by Thiendekaco** [comment]
refer: #2453

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/cncEFC69kAZtQkz
Validation passed in case : 
- Send fund in app 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5b05c622-a9fd-4b4c-a1b2-e4f84fa5dc48)
- Stake


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6fd3ccdc-c179-458e-bee4-1a058103b774)

- Unstake


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/5ca58168-3af4-480a-be1e-e85e225f3f21)


- Cancel Unstake


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d0d86bf9-f7b8-42ba-b7bb-ef1af8d3a5d1)

- Send NFT 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/6a2e5cbd-e440-4b0e-8e16-600f5b96de10)

- Sign message 
- Sign transfer with dApp ( Polkdadot js)
