### ISSUE TITLE
[Extension] Fix earning data for update chain online

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3081]
Refer: https://github.com/Koniverse/SubWallet-Extension/issues/3084

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/Atfejbd7riHR6Nk

Validation passed in case
- Check case turn on/off network
  - Check list Chainlist 
  - Check case stake: pool/native staking
 - Check case install
   - Create new/Attach/Import account
- Check case upgrade version
- Check case failed to get PoolInfo the first time
- Check job PoolInfo
- Check case enable default network
