### ISSUE TITLE
WebApp - QR code of the receiving address is lost

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3083]
**Describe the bug**
QR code of the receiving address is lost

**To reproduce the bug**
**Steps** : 
1. Go to the Your address screen
2. Leave the QR screen on for a while
3. Observe the displayed screen

Actual  

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0f6cdc41-c793-43b0-bccf-5e99fe5ad5f0)

Expect : Show QR code

**Comment by Sokol142196** [comment]
@dungnguyen-art Please check on both Extension and WebApp

**Comment by dungnguyen-art** [comment]
I installed the QrCode library for testing, but I can't reproduce the case where the QR code shows as an empty blank. It might be an error with the library.
@haiyenvu23 @Sokol142196
