### ISSUE TITLE
Extension -  Add highlight button Export multi account when navigate to select account screen

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3090]
**Describe the task**
- Refer to issue #2317
- Link design : https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=842-53043&t=bZpVh3t7rrJRHhVH-4
- Context tooltip : "Export and back up accounts"

**Expect** : 
- On All account mode/Specific accoun mode ( Ledger account/QR signer account/Watch-only account), after click button Back up now on popup Back up seed phrase -> Navigate to Select account screen with Export multi account button highlighted
- Note : The default tool tip will appear until the user completes the update

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/TamcE2RcCCCdqCL

- [ ] Update context tooltip :  "Export and back up accounts"
- [ ] Re-check font-size

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/ynK4ker4qTLLSjZ

- [ ] Update size of button export and red point according to design 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7b62864d-7396-43a8-9106-75cdffc8c926)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/9rty9MrsYMpMNQ6
Validation passed in case : 
- Update version
- On All account mode/Specific accoun mode ( Ledger account/QR signer account/Watch-only account)
- Check when click account selector screen



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7b93eac1-a073-4ff3-9bf7-e75096d1061a)

**Comment by Sokol142196** [comment]
Improve Fetch static data in pr https://github.com/Koniverse/SubWallet-Extension/pull/3114
- Distinguish between 2 environments: Dev and Prod
- Refine the code to check display conditions

Validation result
- Install extension: OK
- Upgrade version: OK
for cases:
- Show popup remind backup by frequency
- Navigate when click on "Backup now"
  - All accounts
  - Specific account
    - Normal account
    - Watch-only account
    - QR-signer account
    - Ledger accounty
- Re-test export and backup account
