### ISSUE TITLE
WebApp - Support GRC-20 token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3093]
**Describe the task**
Support GRC-20 token

- [x] Import token
- [x] Show balance
- [x] Transfer

Actual: Do not show Vara/ Vara testnet on the Select chain to import token
Expect: Show Vara/ Vara testnet on the Select chain to import token

**Comment by haiyenvu23** [comment]
Version test : https://ed06d0f6.subwallet-webapp.pages.dev/home/tokens
Validation passed in case : 

- Import token


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8de06651-0644-47dc-898c-1a9e1c32db67)


- Show balance


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/cb89bd24-94b1-4807-a8db-b08b7c76f009)


- Transfer 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/984a1924-1c1d-4706-b1af-71774c838d6b)


- Show Vara/ Vara testnet on the Select chain to import token


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c0294736-447f-4d8b-abe2-40d87a9d5a89)

- Earning features


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/adeaef1d-d9a1-43c8-8b45-ab03eb50b4e5)

**Comment by ThaoNguyen998** [comment]
Version test: https://87f5df8a.subwallet-webapp.pages.dev/home/tokens

Validation passed in case:
- Show token 

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/1b7ca5a3-f054-499f-b912-ff8e606cd252)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/fb38f253-46ba-4498-ba23-42eb48906390)

- Show balance

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/06b011ae-bf5c-40f1-898d-7368046952de)

- Send token

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9ff579a3-d693-4865-87c8-c4855684e575)

- Import token

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/5079d03c-4385-42e2-9f8e-a58a2c87415c)

- Hide Vara/ Vara testnet when import NFT

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/be3ecc41-0216-4554-812a-46046c482288)
