### ISSUE TITLE
Support transfer between PAH - KAH

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3095]
https://wiki.polkadot.network/docs/learn-guides-dot-ksm-bridge#transfer-dot-from-kusama-asset-hub-to-polkadot-asset-hub

- [x] KSM: KAH -> PAH
- [x] KSM: PAH -> KAH
- [x] DOT: KAH -> PAH
- [x] DOT: PAH -> KAH

**Comment by nampc1** [comment]
Add transfer support for foreign assets:

- [ ] DOT on KAH
- [ ] KSM on PAH

**Comment by Sokol142196** [comment]
- [ ] Add warning message when user select XCM channels: PAH --> KAH:
  - Message: https://www.notion.so/subwallet/SubWallet-Popup-update-Firefox-version-v-message-XCM-DOT-ETH-83fe173b7cea4d6b89bbc17e9116b108?pvs=4#afde70821c084ff9862d5e218c5bcb54
