### ISSUE TITLE
Improve swap quote fetching speed

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3104]
Currently, we're asking all providers for a quote even though that provider might not support that pair. Since we're supporting 1 provider per chain, therefore, we can specifically ask only 1 provider to improve performance.

Note: This will only work when there's only 1 provider per chain, we'll need a better solution in the future

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2118
