### ISSUE TITLE
MV3 on Firefox

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3109]
**Describe the task**
Perform testing for MV3 on Firefox

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/ZsHGCcemJYiFoJy

- [ ] Unable to connect SubWallet extension when connect dApp

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/2e586dca-35a3-4747-b636-330a9dea038c)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/Qbg9Ks2HeoZbx5w

- [ ] Unable to connect with dApp
  
   https://media.discordapp.net/attachments/1244959096348872805/1249941593260032000/image.png?ex=66692252&is=6667d0d2&hm=33c394ed90a217535b3beb111b7e4551d5e28c1f0e41836cd253967b69e549cd&=&format=webp&quality=lossless&width=1274&height=660

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/nqD9CFCZxQ7PXMd

- [ ] Request duplicate permission
- [ ] UI bug

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/7a1ccc0e-53f6-4ce6-b6d9-42afa75a2371)

- [ ] Update content, update icon when request permission
- [ ] Auto accept permission in case upgrade version(Access your data for all websites)

**Comment by Sokol142196** [comment]
Re-check on new build https://discord.com/channels/447263980252037141/947710670344945664/1275693119161237504
Re-check with:
- Firefox browser
- Chrome browser

**Comment by Sokol142196** [comment]
Will resolve in https://github.com/Koniverse/SubWallet-Extension/issues/3364
