### ISSUE TITLE
Extension - Update message when import token in case rpc disconnect

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3124]
**Describe the task**
Update message when import token in case RPC disconnect

Actual: Show message: Invalid contract for the selected chain

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a8ead0e9-edb2-4f2e-8750-8049e8e60d59)

Expect:
Show message: Network connection unstable. Change network endpoint and try again

**Comment by Sokol142196** [comment]
Move to https://github.com/Koniverse/SubWallet-Extension/issues/1824
