### ISSUE TITLE
Improve chainlist online patch

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3132]
**Describe the task**

- Do not show Earning positions in case auto enable network with online resource -> not support online
Pre-condition: New install, open expand view

Actual: After enable the network, do not show the earning position

Expect: Show earning position

Note: After switch account  -> show earning position

- [x] Allow hide feature online -> #3814 
- Add Multichain asset -> Not support patch online

**Comment by S2kael** [comment]
Solution:
- Re-order load online resource
- Add event when update chain api

**Comment by bluezdot** [comment]
Support Patch online chainlist with these updates:
- changed chains, added chains, removed chains
- changed assets, added assets
- changed multi-chain assets, added multi-chain assets

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/jmiecZGaP2rgw3k
Checklist for issues: https://www.notion.so/subwallet/Checklist-Improve-chainlist-online-patch-5c7f6a193de8414d975034e617061d99?pvs=4

- [ ] Error page after patch

  ![Image](https://github.com/user-attachments/assets/fbdc9d0d-0dcb-4952-80dd-5463905e2a21)

- [ ] Do not change chain, changed multi-chain assets, added multi-chain assets

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/jmiecZGaP2rgw3k

- [ ] Do not remove network
  Actual: Still show network

  ![Image](https://github.com/user-attachments/assets/5be651f8-e79d-451a-99fb-361354e3d75a)
   
  Expect: Allow remove chain

**Comment by ThaoNguyen998** [comment]
- [ ] Do not show XCM channel
    Actual: Do not show XCM channel after reload the extension
    Open expand view -> show XCM channel
    
    ![Image](https://github.com/user-attachments/assets/5e6f8383-6065-4838-8bcc-4a85e54de0b4)
    
    Expect: SHow XCM channel

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/kBDdRSoQFGBWpmG
Validation passed with checklist https://www.notion.so/subwallet/Checklist-Improve-chainlist-online-patch-5c7f6a193de8414d975034e617061d99?pvs=4
