### ISSUE TITLE
Extension - Show incorrect Amount on Transaction history, Transaction confirmation  for transfer NFT

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3133]
**Describe the bug**
Show incorrect Amount on Transaction history for transfer NFT

**To reproduce the bug**
- Check with account 5CFh4qpiB5PxsQvPEs6dWAhzgAVLHZa8tZKxeE9XsHBg4n9t (Kusama Asset Hub)
- Check with account 5CFvKXryR5EEvSGuphjWfdHHbJWHqMfpBGcsjosefCuoWbUA (Acala)
Actual: Show incorrect Amount 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d73588e2-16c1-45cd-a729-03748e2af105)

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/096a183d-b99f-489b-8d6b-0a9b9fde5457)

Expect: Show correct Amount

**Comment by Sokol142196** [comment]
**Version test:** http://14.224.129.242:8900/s/ocetNFqW4cA9yBW
Validation passed

![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/7f4685eb-4a5c-4caa-b09f-99d46af36a3b)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/34d08e42-201e-4796-80dd-cb8642f9574c)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/eb73a8da-9196-495a-a155-fe00f8548e78)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/540e84cb-ed05-4022-a8be-c3d7cdceba54)
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1107e93d-c172-4a0d-a074-7b99dfc027f4)
