### ISSUE TITLE
Support more XCM channels

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3134]
- https://github.com/Koniverse/SubWallet-Extension/issues/3095 -> Release later
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/231
- https://github.com/Koniverse/SubWallet-Extension/issues/1984 -> Resolve later

**Comment by nampc1** [comment]
- [ ] DOT: Pendulum -> Polkadot 0xec043600010000e40b540200000000000000000000000301010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da554537800
- [ ] DOT: Pendulum -> Asset hub 0xf8043600010000e40b5402000000000000000000000003010200a10f0100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da554537800
- [ ] USDT: Pendulum -> Asset hub 0xf8043600010180841e0000000000000000000000000003010200a10f01002c6dbbcb86ec6791ba672dcff246852de298bf67bc70fa5152e9684e04e3545b00
- [ ] DOT: Polkadot -> Pendulum 0xfc04630803000100b920030001010042d77c715c1d27342fb13a615444f5ec0d4ca1c2d8ce13d7deee1aecea91794b0304000000000700c817a8040000000000
- [ ] DOT: Asset hub -> Pendulum 0xfc041f0803010100b9200300010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da55453780304000000000700743ba40b0000000000
- [ ] USDT: Asset hub -> Pendulum 0x0901041f0803010100b9200300010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da55453780304000002043205011f00022d31010000000000

**Comment by nampc1** [comment]
- [ ] DOT: KAH -> PAH 0x0101041f0b040202090200a10f0400010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da55453780404020109020002286bee0000000000
- [ ] KSM: PAH -> KAH 0x0901041f0b040202090300a10f0400010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da5545378040402010903000700e87648170000000000
- [ ] KSM: KAH -> PAH 0x0501041f08030202090200a10f0300010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da55453780304000100000700e87648170000000000
- [ ] DOT: PAH -> KAH 0xfc041f08030202090300a10f0300010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da554537803040001000002286bee0000000000

**Comment by nampc1** [comment]
- [ ] Transfer DOT on KAH
- [ ] Transfer KSM on PAH

**Comment by nampc1** [comment]
We need to test some extra cases:
- [ ] DOT: Polkadot -> AH
- [ ] DOT: Polkadot -> Acala
- [ ] DOT: Hydradx -> Polkadot
- [ ] DOT: Hydradx -> Acala
- [ ] DOT: AH -> Polkadot
- [ ] DOT: AH -> Acala

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/4j5FY2cte4e7gby
- [ ] Re-check case XCM USDC: Pendulum --> AssetHub

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/HjRnnxHEsyEkKbq

Validation passed 
[XCM verify 06-08.md](https://github.com/user-attachments/files/15747436/XCM.verify.06-08.md)
