### ISSUE TITLE
Extension - Remove Parallel liquid staking

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3139]
**Describe the task**
Remove Parallet liquid staking

Expect: 
- Allow show earning positions
- Do not allow stake new

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/4L336dXy37M5bS5
Please check issues

- [ ] Still enable button "+" to stake more
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/126f37fe-10db-4488-92fd-3f062fc15723)
