### ISSUE TITLE
WebApp - Remove Parallel liquid staking

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3140]
**Describe the task**
Remove Parallet liquid staking

Expect: 
- Allow show earning positions
- Do not allow stake new

**Comment by ThaoNguyen998** [comment]
Version test: https://76081960.subwallet-webapp.pages.dev/home/earning

- [ ] Still enable button Stake more of Parallel

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/b7a78195-5e48-41da-912b-31e682d8a4a9)

**Comment by Sokol142196** [comment]
@ThaoNguyen998 re-check Parallel earning option on the Staking reward site

**Comment by ThaoNguyen998** [comment]
Version test: https://7427734f.subwallet-webapp.pages.dev/home/tokens
Validation passed
- Hide Parallel on earning options

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/67365029-aa03-4c95-8e40-57a41762b626)

- Show Your earning positions 

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ee93bea9-a17e-4bad-bad5-f17bf8653f08)

- Disable action Stake more on Your earning positions, Earning position details

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/0bb42ffe-727f-498a-ac4a-17313d5fdb8e)

- Hide earning options on the earning preview screen of the Check Crowdloan Result page, Staking reward

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/a2e5117c-e65d-4b72-97a8-4725b9feb3cd)

- Re-check Unstake for Parallel, re-check all action for staking
