### ISSUE TITLE
Extension - Re-check bug do not show root screen after remove account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3148]
**Describe the task**
Re-check bug do not show root screen after remove account

**To reproduce the task**
Steps:
1. Open the SubWallet extension expand view
2. Perform remove any account
3. Observe the screen displayed

Actual: Do not show black screen with URL chrome-extension://chlkaejaldjknaipdoljkebfknendkmh/index.html#/
  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/2bbd0823-6097-4592-905f-3ecde2d68391)

Expect: Navigate to the Home screen

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/PaCYMmkCd9SmFsZ

- [ ] Still reproduce the bug
Browser: Brave 

![Image](https://github.com/user-attachments/assets/d982ed75-bd57-44bb-8b88-9844694d6cd9)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/QLTCTMCS5ErS2T7
Validation passed.
Checklist: https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#536db033a637425dae96c35330b6e8d7
