### ISSUE TITLE
WebApp - Remove the logic that differentiates between Native tokens and Local tokens in case show sub-logo

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3149]
**Describe the task**
Remove the logic that differentiates between Native tokens and Local tokens in case show sub-logo

Refer: #3075

**Comment by Sokol142196** [comment]
Version test: https://pr-3165.subwallet-webapp.pages.dev/

Validation passed in cases:
- Portfolio
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/aff39eef-b82b-47a0-b1e0-d342d784fcc9)

- Earnin position
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d6d889d2-d8fe-47db-8ef1-d2e2be7c992a)

- Select token popup
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/6439cbef-7c86-4aab-b5e9-4c451aa3cca0)

- Manange token 
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/776b575b-4d48-45ce-8ad6-402ecf4947bd)
