### ISSUE TITLE
Extension - Update some message related to earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3150]
**Describe the task**
Update some message related to earning feature

- [x] Message in case Insufficient balance when withdraw, claim reward and unstake
  - Actual: Show message "Your available balance is [Available balance], you need to leave [ED] as minimal balance (existential deposit) and pay network fees. Make sure you have at least [x tokens] in your transferable balance to proceed."
  - Expect: Change to message "You don't have enough [token] (network name) to pay gas fee. Top up your transferable balance and try again"

- [x] Message in case Insufficient balance when stake with Liquid staking (re-check lending staking)
  - Example: stake DOT (Acala) and account have xx ACA (xx > ED) and yy (DOT) then input stake amount: DOT > Total DOT on Acala and Polkadot
  - Actual: Show message "You don't have enough ACA (Acala) to pay gas fee. Lower your amount and try again"
     - Incorrect token
  - Expect: Show message "You can only enter a maximum of xx DOT, which is xx1 DOT (Acala) and xx2 DOT (Polkadot). Lower your amount and try again."

**Comment by Sokol142196** [comment]
- [ ] Update Max amount in the message in case Insufficient balance when swap
  - Actual: Shows Maximum Amount to enter but then user enters Amount = Maximum Amount then shows Insufficient Balance error message
  - Expect: Shows the exact maximum amount the user can enter

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/w9crn8y3SLXSmyn
Validation passed in case
- Message in case Insufficient balance when withdraw, claim reward and unstake

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/85f472fa-8698-45e1-b277-4bf88dbefbf2)

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/aa6fe5ca-9022-4ea8-b2fd-592aa2d71dab)

![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8b040866-bc46-4110-8403-8bda86f11e85)

- Message in case Insufficient balance when stake with Liquid staking (re-check lending staking)

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/42d572f5-e0e7-49f8-89ed-c12994a9721b)

-  Update Max amount in the message in case Insufficient balance when swap
 
 ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9a4ec79f-446c-4069-b360-e31c0cae50a8)
