### ISSUE TITLE
Update transferable formula for system pallet v1

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3166]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/8d273e2d-ad96-47b6-9ac9-fdd21859123d)

5DDWms6xzWuQCD1cbEZhDjY3T2BFSUZMWTJiET1Yk76Ke6oB

The correct calculation should be

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/77dffbc6-74b6-4f1b-8982-97c5e9b3d345)

**Formula** 
- transferable = free - max(miscFrozen, feeFrozen, ED)
- total balance = free + reserved

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/rKbEapK6pGKZWqF
Validation passed in cases:
- Transferable for system pallet v1:Energy Web X, Credit Coin)
- Transferable for system pallet v2: Polkadot, Vara 
- Special chain: Interlay

**Comment by Sokol142196** [comment]
- [ ] Check the Total Balance in case the account unstake all nomination pool
  - Actual: Unstake balances are not included in the Total Balance, check with address 13QWr1JHj39MFZbzM3W4jsYZ2U5RWPWEowWhhNa9HxzRLSfP 
  - Expect: Unstake balances are included in the Total Balance

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/ofFPbpman6NWEm6
Validation passed these case
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/1e5628f9-c7df-4586-be1b-a486d032e8ea)
