### ISSUE TITLE
[Extension] Add CheckMetadataHash signed extension support

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3175]
Related: https://github.com/polkadot-fellows/runtimes/pull/337

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/D25rp9qsmSWjQpC
Validation passed
- Install
- Upgrade version
- Perform transactions with Rococo
  - Extension: https://rococo.subscan.io/extrinsic/0x151f0eee711cbc36c408bcf60e5dd33432317219d80fc10f30fd228782edeb44 
  - dApp: Polkadot js app
- Re-check all action: 
  - Transfer/ XCM/Send NFT/ Buy token/Receive/Crowdloans
  - Swap
  - Earning
  - History
  - Manage account/ network/ NFT
  - WalletConnect/ Connect dApp
  - Settings
  - Reset account/Erase all

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/D25rp9qsmSWjQpC
Validation passed
- Install
- Upgrade version
- Perform transactions with Rococo
  - Extension: https://rococo.subscan.io/extrinsic/0x151f0eee711cbc36c408bcf60e5dd33432317219d80fc10f30fd228782edeb44 
  - dApp: Polkadot js app
- Re-check all action: 
  - Transfer/ XCM/Send NFT/ Buy token/Receive/Crowdloans
  - Swap
  - Earning
  - History
  - Manage account/ network/ NFT
  - WalletConnect/ Connect dApp
  - Settings
  - Reset account/Erase all
