### ISSUE TITLE
WebApp- Add portfolio for earning position

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3181]
Describe the task

- [x] Add portfolio for earning position
- [x] Update UI for filter

Design: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=10420-232642&t=BLyojTk7ELWrdfrb-4
- Responsive: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=12162-375119&t=4dOUwPtnDgP0FZNw-4

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5cae832b-fb38-49d0-9dec-ff7bb17bae9f)

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Show incorrect active stake in case account has unstake all

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e95ce4a9-f983-48ce-8f4d-b098c1614a54)

- [ ] Error font size

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ee4aa52d-2ffe-4f25-b324-4e6f40bda4a2)

**Comment by ThaoNguyen998** [comment]
Version test: https://78425316.subwallet-webapp.pages.dev/home/earning
- UI bug responsive

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6ff3c8a0-908a-498e-a1e6-b267b3e0372c)

- UI bug 

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/14a3e0b0-f474-4f59-88d9-f6763faf7d73)

**Comment by ThaoNguyen998** [comment]
Version test: https://e1b00515.subwallet-webapp.pages.dev/home/earning

- [ ] Update UI

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4c929d9c-94d6-409e-a971-31fad513ce9b)

- [ ] Update color tab

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/454c22a9-857c-4d66-84a3-6063d8216fcf)

**Comment by Sokol142196** [comment]
- [ ] Do not show the search bar on responsive screen
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9eafb052-6352-4eec-964e-2b697c543dca)

**Comment by ThaoNguyen998** [comment]
Version test: https://fe11e2b0.subwallet-webapp.pages.dev/home/earning
Device test: 

- [ ] Display search bar in mobile mode 

  ![Image](https://github.com/user-attachments/assets/7bd04a7a-8492-4ae3-b0c2-6cafc9727922)

- Fix UI in case value = 0

![Image](https://github.com/user-attachments/assets/26cfcaa3-3997-4e45-a56a-4a24df29c53f)

![Image](https://github.com/user-attachments/assets/17696b8d-28c8-41da-bb28-ee30d088e3a6)
