### ISSUE TITLE
Update Fallback API for SubWallet API (Price, Exchange Rate)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3183]
**Describe the task**
Ensure Extension working ok if price or exchange service have any problems

**Actual:** API often crashes (403, 502) -> Unable to get token price

**Expect:**:
- Replace chain-data URL with api-cache URL
- Handle with fallback API if api-cache API get any problems
  - Price: https://static-cache.subwallet.app/price/data.json
  - Exchange Rate: https://static-cache.subwallet.app/exchange-rate/data.json
- Handle case can not get anything

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/SY36Rj5tAj4cY4R

- [ ] In case can not get anything, can't change currency




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/467e1e0a-1921-4d89-bc8f-256a2fabc4ca)

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/cRPa7EtqcsKGYtm
- http://14.224.129.242:8900/s/mtJ8m5pjriX3mE5
Validation passed in case : 
- Install/Update version
- In case can not get anything


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/9c463b07-d7e2-4485-acce-010460c93bc3)


- In case fallback API if api-cache API get any problems


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0af008c5-43b0-456c-b61c-1c0a6aca318e)

- In case main api works normally


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/62ee299a-f5b3-484f-8c2d-2608bdafeb30)
