### ISSUE TITLE
WebApp - Update logo for Hydration provider on the Swap screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3192]
**Describe the task**
Update logo for Hydration provider on the Swap screen

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/9c8fb44c-53b6-4761-9d2d-2ae8300d66fa)

- New logo: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=28-180&t=gb6J6itClkRTjEeJ-4

**Comment by haiyenvu23** [comment]
Version test : https://669383f3.subwallet-webapp.pages.dev/
Validation passed in case : 
- Responsive
- Re-check on some screen : manage token, network, send fund ,...
- Check on Swap screen 


![Image](https://github.com/user-attachments/assets/c109b996-78c2-43c5-bf52-a94170962080)




![Image](https://github.com/user-attachments/assets/580b48d8-5446-40e0-97ef-0f2fe220e0fd)




![Image](https://github.com/user-attachments/assets/468a849d-9d67-40ff-b918-98a1201295fc)


![Image](https://github.com/user-attachments/assets/8dddb0e7-6a1b-4319-8d13-bbd512655495)



![Image](https://github.com/user-attachments/assets/59dd5a07-8850-4558-869b-712b83738c9e)
