### ISSUE TITLE
Bug can not backup data in Mobile App

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-Extension#3194]
Mobile App can not backup data when use new WebRunner (1.2.5)

**Comment by Quangdm-cdm** [comment]
Update mv3 causes the backupData function to fail. Therefore, mobile apps cannot backup data and lead to loss of data

**Comment by ThaoNguyen998** [comment]
Fixed on issue https://github.com/Koniverse/SubWallet-Mobile/issues/1656
