### ISSUE TITLE
Check error logs in earning feature

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3197]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/d5173b15-0f1c-4d19-b305-4928e4e4a457)

**Comment by bluezdot** [comment]
Subscan API returns a lack of data response for some cases. -> We need handle these exception.

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/x5nggNDnaQDHskk
Validation passed.
- Do not show log earning feature
- Install 
- Upgrade version
- Re-check show reward history
