### ISSUE TITLE
Extension - Hide the popup Remind backup seed phrase

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3198]
**Describe the task**
Hide the popup Remind backup seed phrase

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/cbfd5c41-3315-4dd5-8f5f-a55f17a215d7)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/3d9Sx2Gjia4XN7R
Validation passed. 
- Hide popup to remind backup seed phrase
- Install
- Upgrade version
