### ISSUE TITLE
Extension - Add popup to remind user upgrade Firefox version

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3202]
**Describe the task**
Add popup to remind user upgrade Firefox version

Expect: Show popup to users who meet the following conditions:
- User SubWallet extension on Firefox browser
- Firefox version < 127
- This pop-up only displays once

BA document: https://www.notion.so/subwallet/SubWallet-Popup-update-Firefox-version-v-message-XCM-DOT-ETH-83fe173b7cea4d6b89bbc17e9116b108?pvs=4

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/75HbctaaPfFjTPo
- Update link user guide: 
 https://docs.subwallet.app/main/extension-user-guide/faqs#i-cant-connect-my-accounts-to-any-dapps-on-firefox.-what-should-i-do

- Show marketing campaign in case Dismiss on popup remind user upgrade Firefox version 

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/1f9f0f78-e215-450c-8ccb-0c83403dbad2)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/d7mEoGZ62BWR9rK
Validation passed

- Add popup to remind user upgrade Firefox version

https://konistudio-my.sharepoint.com/:v:/g/personal/nhungphung_koni_studio/EZ_a56vIfdtCluiztsIVzRMBHpyWINQNB6omlQ-bJ-bZUQ?e=mB6mGA
- Install new
- Upgrade version
- Check with version 127
- Check case enable/disable permission manual
- Check connect/ sign transaction/ sign message with dApp
