### ISSUE TITLE
Extension - Update main tabbar structure

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3212]
**Describe the task**
Update main tabbar structure:
- Move Crowdloan to the Settings > General menu
- Move the Mission pool to the main menu

Design: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=24535-247146&t=fXYmgFPlP7Vw8Xr0-4

**_=> Need to discuss more when implement_**

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/orTaefqNmYENGbJ

- [ ] Re-check shape noti


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/61cc8d5e-08d3-4284-9c33-8b83037d5246)

- [ ] Re-check tab name


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/652f1008-7810-4e1c-9bf0-1308524c7b85)

- [ ] Re-check title name when click Crowdloans on Setting screen 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3a8767c3-bfe4-4fd8-ad51-ade83bb81f9f)

**Comment by haiyenvu23** [comment]
Version test : 
- [ ] Re-check shape  and font-size noti


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/61cc8d5e-08d3-4284-9c33-8b83037d5246)

- [ ] Re-check logo shape


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/aa30f7dc-1557-4566-b628-3f9807fe64af)

**Comment by haiyenvu23** [comment]
Version test : 

- [ ] Update font-weight


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3c81bf45-5678-414c-956d-c009f3011f13)

- [ ] Change text " Category" -> "Categories"


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/aa472919-106a-49fe-ade9-4cb3eac68383)

- [ ] Re-check display description


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/bd8a3d86-142e-441b-93e4-5de5ed95d284)

Expect : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ada52671-6364-40b4-b32e-fdcb00089f38)

- [ ] If the field has no value, it will be hidden


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e6087464-cc4f-438d-ad3a-1dd97e0716e0)

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/EDsSWzTdLgdABop
- http://14.224.129.242:8900/s/dkymHct9PLjpkMq

Validation passed in case : 

- Install/Update version
- Move crowdloans on Settings


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0357c457-c7b7-46ce-99c7-377a6fec7e08)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2ee46123-fbd2-4350-92af-8186ad07cf3c)

- Move Mission pools to the main menu


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/7d0eda0c-4f8d-488f-9522-b6cfdcb8801b)


- Sort according status and ordinal : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/3dd36485-24df-4284-801d-85fdbf1940d4)

- Show tag categories


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d44623b1-12a2-491b-8482-4907f6d4871d)

-  If the Total token supply field  has no value, it will be hidden


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/46b6fba8-6cae-42e9-8348-ceeb4db7242a)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/692e6335-6c92-4fff-90e4-173a1918e128)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c64a57e2-8b13-45ec-ab58-c8a1fd75c555)

**Comment by haiyenvu23** [comment]
- Handles display of mission pool contents
=> Related to issue https://github.com/Koniverse/SubWallet-Extension/issues/3279
