### ISSUE TITLE
WebApp - Show nomination pool with block status

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3217]
**Describe the task**
Show nomination pool with block status
- Add status = Blocked on Pool details
- Handle when selecting pool block
  -  Gray item, do not select and show tooltip
- Add filter = Blocked

**Comment by haiyenvu23** [comment]
Version test : https://4135f559.subwallet-webapp.pages.dev/
Validation passed in case : 
- Responsive 


![Image](https://github.com/user-attachments/assets/5379e15a-1c11-4ded-8e0b-7db7de9abcdf)



![Image](https://github.com/user-attachments/assets/6cc592bf-2daa-4e22-9bc0-8fae395eef95)

- Add status Blocked
- Gray item, show tooltip for pool block


![Image](https://github.com/user-attachments/assets/9579f382-b002-4388-8a69-e3482a007f02)



![Image](https://github.com/user-attachments/assets/ed08e003-ca03-482c-ae99-b2dfe36aedfd)

- Add filter Block 


![Image](https://github.com/user-attachments/assets/f5ad5179-11e9-44d8-bc26-45f75e86a266)



![Image](https://github.com/user-attachments/assets/f1013580-4687-4947-bd32-23cf7b3aac50)

- Re-check with direct nomination
