### ISSUE TITLE
Extension - Remove Interlay lending

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3226]
**Describe the task**
Remove Interlay lending:
- Hide this Interlay lending on earning options screen
- Still show Position
- Disable button + and supply more on the Position details
- Allow withdraw

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/QSN7w4HnYbqmQZ9
Validation passed
- Show earning position

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/6ad0f4e8-84a0-41d6-989a-727fa31575b6)

- Hide on earning options

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/cec57d80-24e9-4490-a591-220c563416f3)

- Disable button + and supply more on the Position details

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/ee5821cb-f417-4d16-abb3-530ea030fd2b)

- Allow withdraw(Approve steps)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e0b5a311-8d76-4357-9140-ac343487932f)

- Re-check qDOT

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e6e01143-8c8b-430c-9c74-2fdc40020843)

- Re-check Install/ Upgrade version
