### ISSUE TITLE
Add support Ledger for Polkadex

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3231]
**Describe the task**
Add support Ledger for Polkadex

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/aHrSxRxCMtq8Stp

- [ ] Error when perform sign Transfer with dApp Polkadot js


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/c1bf304b-fdad-4bed-8585-b6f31e72018c)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/aHrSxRxCMtq8Stp
Validation passed in case : 
- Install/Update version
- When sign message, sign transaction


![Image](https://github.com/user-attachments/assets/c4ce000e-020d-4bad-bcdc-de93cceee110)

- Network supported Earning
