### ISSUE TITLE
Do not show Interlay's earning position

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3234]
**Describe the bug**
Do not show Interlay's earning position

Need to check:

- [x] Show earning position
- [x] Withdraw actions => Tester need check
  - Notes: all balance of the qDOT is locked

**Comment by ThaoNguyen998** [comment]
Verison test: http://14.224.129.242:8900/s/63YwZ5QZ6MKmyby
Validation passed in case: 
- Show earning position

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/083a73a1-c176-42cc-a82d-1bca79c2d9ae)

- Perform withdraw

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/eed14d38-f8c4-45fd-9672-4d04c020503a)

- Re-check qDOT

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/e25dc9da-aa06-45e1-8e1d-b4671d23c636)
