### ISSUE TITLE
Report Rpc connect status

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#3243]
**Describe tasks**
- [x] Report Rpc connect status when unstable or disconnected

**Comment by bluezdot** [comment]
- [ ] Logic turn on/off RPC on Wallet is not affect.
- [ ] Check when connecting to RPC unstable/die, client send API Report successfully
References:
API Report: https://api-cache.subwallet.app/api/health-check/report-rpc
API Count: https://api-cache.subwallet.app/api/health-check/count-report-rpc

**Comment by bluezdot** [comment]
https://github.com/Koniverse/SubWallet-Extension/issues/3170

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/s724fC64aGXzWdB
Validation passed
- Enable and disable the network still works normally
  - Show balance
  -  Show NFT
  - Show earning position
  - Perform transaction: Transfer/Earning
- Send API report in case status = Disconnected or Unstable
- Install/ Upgrade version
