### ISSUE TITLE
WebApp - Review and support Polkadot Ledger app from Zondax for WebApp

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3256]
**Describe the task**
Review and support Polkadot Ledger app from Zondax for WebApp
- Refer: https://github.com/Koniverse/SubWallet-Extension/issues/2453

**Comment by ThaoNguyen998** [comment]
Version test: https://b4919d82.subwallet-webapp.pages.dev/home/tokens/detail/DOT-Polkadot

- [ ] Update logo for Ledger Polkadot new

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/d024ecad-b89f-4068-bf6a-642eec6d55e3)

- [ ] Unable to sign the transaction with Generic app for Polkadot

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/5cc36d53-f78d-430a-9818-d35143d72f8d)

**Comment by Sokol142196** [comment]
Version test: https://80dd5856.subwallet-webapp.pages.dev/
| Case | Validation Result |
|------|----------|

**Comment by ThaoNguyen998** [comment]
Version test: https://80dd5856.subwallet-webapp.pages.dev/home/tokens

- [ ] Show incorrect Injected Account Ledger

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/9fc8181b-78bb-42c7-919c-38f4d029ae4e)
