### ISSUE TITLE
WebApp - Refactor Code to Handle inputValue Not Updating When Clicking Switch Button

### ISSUE THREAD

**Issue by dungnguyen-art** [Koniverse/SubWallet-Extension#3258]
ex. When change swap AssetHub from DOT: USDC to USDC: DOT, the value amount does not change according to the decimals of the fromToken.

![image](https://github.com/Koniverse/SubWallet-Extension/assets/59666831/dde9feb9-5349-4c08-ab37-6893b19c0abe)

**Comment by haiyenvu23** [comment]
Version test : https://8cf4cd7c.subwallet-webapp.pages.dev/
Validation passed 


![Image](https://github.com/user-attachments/assets/9abf021d-6803-408a-b73a-ec4e1ada9013)
