### ISSUE TITLE
Extension - Add validate account in case sign transaction with Ledger account

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3263]
**Describe the task**
Add validate account in case sign transaction with Ledger account

Expect: Show message on confirmation: "Wrong device. Connect your previously used Ledger and try again"

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/DgK8ZwADWBss7BS

- [ ] Can't sign with ledger account

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/DseLF3PQNcSiw4z

- [ ] Re-check error of not displaying message when first clicking Approve button


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e1132387-b579-4aa8-89d8-1e8ca787c282)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/p6n3GRZ8crWSaJR

- [ ] When changing back to ledger but choosing another network, the message is not displayed



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/e9d7749c-9dd9-4c60-b7c8-d782675cac5f)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/15f225b0-e6e6-41fb-9e0e-081e6022e2a6)

Expect : 


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/ec80bee4-580f-419e-8ecf-11cd138e6e91)

**Comment by haiyenvu23** [comment]
Re-check with cases : 

- Check when sign message : 

> - Attach account with ledger A but sign with ledger B

> - Check when changing back to ledger ( choose same network ) 

> - Check when changing back to ledger but choosing another network

- Check when sign Transfer with dApp : 

> - Attach account with ledger A but sign with ledger B

> - Check when changing back to ledger ( choose same network ) 

> - Check when changing back to ledger but choosing another network

- Check when Transfer in wallet : 

> - Attach account with ledger A but sign with ledger B

> - Check when changing back to ledger ( choose same network ) 

> - Check when changing back to ledger but choosing another network

**Comment by haiyenvu23** [comment]
Version test : 
Validation passed in case : 
- Check when sign message 
- Check when sign Transfer with dApp 
- Check when Transfer in wallet 

> Attach account with ledger A but sign with ledger B


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/9bfe2516-02ae-42d1-85dd-1c63e0a58817)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/b9bf5229-869a-420e-9c16-66d962ab893d)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/94439cf8-4d85-4563-8fc6-e26ba2e0119e)


> Check when changing back to ledger ( choose same network )


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/da61a2b8-eee6-4eb6-bc98-7aaf9bd995ea)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/8c8e18f7-e01e-4cdc-92bd-14007fb3c018)



> Check when changing back to ledger but choosing another network


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/747dcc85-878d-44da-9984-69d9c5bf1062)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/0965bc19-0921-4201-a4fa-1eb8b2cf60d6)



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/2797bedf-17ee-40d0-907b-a05a5731bf42)




> Check when not connected to ledger => Related to issue https://github.com/Koniverse/SubWallet-Extension/issues/2568#issuecomment-2222026299


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/669a8d45-4ccb-4116-ad9d-9804a97da5ed)


> Re-check with normal account
