### ISSUE TITLE
Change token type from GRC-20 to VFT

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3268]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/c6d5ff0a-c8b1-45ad-be97-2d41a2b40f60)

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/JkbRNnZtkygBc5w

Validation passed in cases:
- Migrate (Upgrade version)
- Import
- Remove
- Transfer
- re-test import other type
![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/068ab020-5db2-4e36-bfee-1cb9b43af499)
