### ISSUE TITLE
Check Vara token sdk version

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3270]
VARA team asked us to update idl file but we're only using their sdk directly, we might need to check the sdk for update

**Comment by S2kael** [comment]
### Solution

- Add a new type `VFT` for token

### Expect

- [x] Add a new type `VFT` for token
  - [x] Import custom token
  - [x] Display balance
  - [x] Transfer balance
- [x] Deprecate old type `GRC20`
  - [x] Remove type from import token screen
  - [x] Still supports displaying balances for imported custom tokens
  - [x] Still supports balance transfers for imported custom tokens

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/MbFWEGgWNqjfyKJ
Validation passed.
- Add a new type VFT for token
  - Import custom token

  ![Image](https://github.com/user-attachments/assets/0ca9c83a-c82f-4a70-bc53-a17f4f4c99d7)

  - Show balance

  ![Image](https://github.com/user-attachments/assets/1f3593a9-1156-442b-9302-bfaf49fd3693)

  - Receive

  ![Image](https://github.com/user-attachments/assets/876217ea-bef9-4862-9d37-f3a2e536501a)

  - Transfer

  ![Image](https://github.com/user-attachments/assets/7ee64877-3863-41ba-b24d-7a55004baf66)

  - History

  ![Image](https://github.com/user-attachments/assets/e7cf5339-8614-46f4-a195-cae7cd38ba8f)

  -  Remove token

  ![Image](https://github.com/user-attachments/assets/fe53cb95-cfa9-4198-a948-dd3acb1ea5c4)

- Deprecate old type GRC20
  - Still supports displaying balances for imported custom tokens

![Image](https://github.com/user-attachments/assets/315684cb-66e2-453b-8e16-a8fa266c743a)
  
  - Still supports balance transfers for imported custom tokens

  ![Image](https://github.com/user-attachments/assets/21ba1f99-6b36-4f55-b841-33f031bee0be)

- Re-check import NFT, import token, import network
