### ISSUE TITLE
Extension - Add support Swap Asset Hub

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3272]
**Describe the task**
Add support Swap Asset Hub
- Refer: https://github.com/Koniverse/SubWallet-Extension/issues/2512

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/MKqDJXwxCFj87e5

Please check the issues:

- [ ] UI bug on the Swap quote details

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/5f20caf0-3102-43dc-9334-cbdf3316a79a)

- [ ] Update warning for Asset Hub

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/EpwsR68xpxygErd

- [ ]  Error show message when change Swap

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4f4795c6-be94-44af-8d8f-6ee9a8ab1e78)

**Comment by ThaoNguyen998** [comment]
Version test: 
Validation passed
- Swap DOT (Asset Hub) --> USDC: Approve step
- Swap DOT (Asset Hub) --> USDt: https://assethub-polkadot.subscan.io/extrinsic/0x1347fdd491023e94883156c664ff209f094cb0df13f176e536ca4a5a2325ecfc
- Swap USDC (Asset Hub) --> DOT: Approve step
- Swap USDt (Asset Hub) --> DOT: https://assethub-polkadot.subscan.io/extrinsic/0xfef5c83dd99e7569d9511d63c74b3df39ed65801e5135f3ca781cd1f1d015ba6
- Re-check all validate
  - Amount = 0

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/5f7042bd-f1a1-4a1e-b866-b840097b48c8)

  - Insufficient balance

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/8e52ba7c-2e6a-4673-bc57-ee2dd5f897b1)

   - ED of the local token

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/11b40ebb-39a1-4a1b-a18a-038973c6aa5f)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/43d8e8be-e665-4ea3-8f7c-210c91a76c0b)

  - Change swap pair

- Show low liquidity (Price impact < 0.15%)
Check page: https://app.dotacp.mvpworkshop.co/swap

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/db8edcbd-3c6c-4d22-a8f4-97d72f0ef009)

- Add pay attention (auto-scroll)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/bf0da7b5-7481-4c11-a03c-aeceff9a9248)
