### ISSUE TITLE
Fix bug connecting to uquid dapp with Wallet Connect

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3275]
We received some feedbacks about user not being able to connect to this dapp via WalletConnect
https://shop.uquid.com/public/login/my/?_redir_=https://uquid.com/

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/k5ms338CEGKc3DY

- [ ] Network information is not displayed in the import network screen


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/d2900c38-cfc3-4d1c-b307-dc9409d3c2b0)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/F8zjS6aMPA9p6z7

- [ ] Don't show popup Add network to connect
Steps : 
1. Connect to Substrate type WC address
2. Connect to EVM type WC address
3. Observe the display screen



![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/58c0c937-9a20-4fd9-a0f2-4968bad3491e)

**Comment by haiyenvu23** [comment]
Version test: 
- http://14.224.129.242:8900/s/qwgdKNZnqoASreX
- (Firefox): http://14.224.129.242:8900/s/R7ZFmx8PAZMiNDA

Validation passed in case : 

- Install/Update version
- Show popup Add network ( when connect with require network) : 

> - Only 1 network needs to be added

> - Get network information to automatically fill in for the user


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/786a1131-cf8d-4bcd-b448-fe2ecdd51e0a)




![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/09363a39-7f29-4692-9636-a3db3b60c20e)


- When > 1 network needs to be added


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/924afc48-b31a-4b74-8420-6060a807ac73)

- When can't get network information to automatically fill in


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/a874de85-6abc-4b10-804b-985fab9f8a9a)


- When connect with optional network


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/155931563/4dbae4f9-1d0b-4ce9-be71-52d25affe6bb)

- Update content => Related to issue : https://github.com/Koniverse/SubWallet-Extension/issues/2568#issuecomment-2222913822

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/5eEpLYCkQZPE6Nt
Validation passed. 
- Fix bug do not validate rpc in case add network

  ![Image](https://github.com/user-attachments/assets/a8ae5ff8-bdc6-46cd-86fd-984c165d6fbb)
