### ISSUE TITLE
WebApp - Show incorrect Amount on Transaction confirmation for transfer NFT

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3287]
**Describe the bug** 
Show incorrect Amount on Transaction confirmation for transfer NFT Acala
Check with the account: 5CFvKXryR5EEvSGuphjWfdHHbJWHqMfpBGcsjosefCuoWbUA (Acala)

  ![Image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/02647cd0-503f-4ef4-a5f8-a80e07f83114)

**Comment by Sokol142196** [comment]
Same as https://github.com/Koniverse/SubWallet-Extension/issues/3241
