### ISSUE TITLE
Extension - Bug Cannot read properties of undefined (reading 'filter') related to Mission pool

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3289]
**Describe the task**
Bug Cannot read properties of undefined (reading 'filter') related to Mission pool

Log bug 

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/f1f7310d-fcae-4c1b-abc5-1b2ef5c37ae3)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/pHq3EHZbF5DHBFG

Validation passed.
- Install
- Upgrade version

(Reproduce: disconnect internet)
