### ISSUE TITLE
Display Moonbeam/Moonriver NFT

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#33]
- [x] **Supported moonbeam NFT collections:**

- Moon Monkeys
- MoonDAONFT
- GlmrApes
- GlmrJungle
- Moonbeam BAYC
- MonkeyBotsCult
- DEDE the king!
- Moonbeam Punks
- MoonCity
- The Flighters
- GlmrPunks
- MoonbeamZuki
- Hamsters Gang
- GlimmerKongsClub
- Bored Puppet Yacht Club
- Moonbeam Name Service (.moon)

- [x] **Supported Moonriver NFT collections:**

- Zoombies
- CryptoDate
- Pupazzi Punk Salvation

**Comment by NamPhamc99** [comment]
Supported moonbeam NFT collections:
- Moon Monkeys
- MoonDAONFT
- GlimmerApes
- GlimmerJungle
- Moonbeam BAYC
- MonkeyBotsCult
- DEDE the king!
- Moonbeam Punks
- MoonCity
- The Flighters
- GlmrPunks
- MoonbeamZuki
- Hamsters Gang
- GlimmerKongsClub
- Bored Puppet Yacht Club
- Moonbeam Name Service (.moon)

Supported Moonriver NFT collections:
- Zoombies
- CryptoDate
- Pupazzi Punk Salvation

Supported Astar NFT collections:
- Astar Punks
- Kongz Of Astar (KONGz)
