### ISSUE TITLE
Transfer with account keep-alive checks & add transaction tip

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#330]
Improve issue https://github.com/Koniverse/SubWallet-Extension/issues/35

- [ ] Missing toggle "Transfer with account keep-alive checks"

![Image](https://user-images.githubusercontent.com/102292476/171778975-2a12c321-62ac-4e75-8a11-3171f24c174c.png)

- [ ] Add transaction tip: https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=4432%3A13654&scaling=min-zoom&page-id=4%3A14

**Comment by NamPhamc99** [comment]
To be resolved later

**Comment by sokol142** [comment]
@hieudd @hieudd confirm for me this behavior

**Comment by saltict** [comment]
No need to implement in new version
