### ISSUE TITLE
Move step shorten metadata and calculate `metadataHash` to client

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3305]
Use `@polkadot-api/merkleize-metadata` for metadata converter

**Comment by ThaoNguyen998** [comment]
- [ ] Update metadataHash for custom network
Actual: Error when transfer custom network (check Avail Space)

  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/117999489/4c337421-f7e1-44f5-aa1b-71ed4f947196)

**Comment by S2kael** [comment]
Need to improve:

- [ ] Add logic check network active for Ledger case
- [ ] Required to add the network in case sign dApp request (if necessary)
- [ ] Improve logic check and add extra info

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/bwq3Lz6nbqbWe8T

- [ ] Unable to transfer token in case addressPrefix = 0
Log bug: 

  ![Image](https://github.com/user-attachments/assets/02f8036e-8bf7-49c2-91c3-54cfef382af8)

**Comment by ThaoNguyen998** [comment]
Version test: 
- Extension: http://14.224.129.242:8900/s/2ZiMy6nR7TSBzba
- WebApp: https://4941661e.subwallet-webapp.pages.dev/

Validation passed.
- Check all action on Ledger account
- Re-check validation Transfer, XCM, Swap, Earning
- Connect/ perform transactions with dApp
- Install/Upgrade version
