### ISSUE TITLE
Allow to use `Migration Polkadot` App to attach Ledger account

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3307]
- Use migration app to attach account ledger on non Polkadot account

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/79YxG7d2npEAPZg

- [ ] Disable "Kusama" network
- [ ] Enable "Aleph zero testnet" network


![Image](https://github.com/user-attachments/assets/19eaca1f-eb6f-48f7-a5d9-61d9ebc206d2)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/Xt2AaaTAwn2p5xy

- [ ] Re-check display account name in case same address ( generic <-> generic )


![Image](https://github.com/user-attachments/assets/8c107336-2438-421c-951d-53dbc9801492)

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/2ksYsottareDGtJ
- (Firefox): http://14.224.129.242:8900/s/9Y5MnQAdFQjJjtq
Validation passed in case : 
- Test results are mentioned in the link: https://www.notion.so/subwallet/Check-list-Migration-Polkadot-App-to-attach-Ledger-account-b330154648ab4bdf85958379755ef9d3
