### ISSUE TITLE
Hide direct api usage of polkadot/js

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3308]
We should not use direct call from polkadot/js to avoid coupling

- [x] This issue tries to do that for native token balance fetching

**Comment by nampc1** [comment]
This issue refactors balance fetching logic, this will affect
- [ ] Showing balance of all types of tokens
- [ ] Showing free balance in transaction screens

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/isMFWnAZ2iYQpqZ
Validation passed. 
- Showing balance of all types of tokens on all accounts
- Showing balance of all types of tokens on single account
- Showing balance of all types of tokens upon switching/deleting/adding account
- Showing free balance in transaction screens
