### ISSUE TITLE
Fix bug calculating balance for relaychain

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3312]
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/bd7e4f15-ab19-4df3-9049-07640ac726ef)
![Image](https://github.com/Koniverse/SubWallet-Extension/assets/44641118/b229b3ad-d856-473f-a5e1-fc5d6abdaea6)

**Comment by nampc1** [comment]
This is due to `number` in js, the problem goes away with `BigN`

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/9n8jdCRrs7KzeKa

Validation passed in cases:
- AVAIL:
  - Show balance
  ![image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/ff0e6028-037a-4149-b004-eb3a26fc07b6)

  - Transfer
- Re-test the balance of the other networks
  - Transferable for system pallet v1:Energy Web X, Credit Coin)
  - Transferable for system pallet v2: Polkadot, Vara
  - Special chain: Interlay
