### ISSUE TITLE
Staking rewards not being updated for injected accounts on webapp

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3322]
**Describe the task**
Staking rewards not being updated for injected accounts on webapp

**Actual:** User must be switch account to get staking rewards
**Expect:** Get and immediately display staking rewards

**Comment by S2kael** [comment]
- [ ] Must to cherry pick to extension

**Comment by Sokol142196** [comment]
Version test: https://fd837800.subwallet-webapp.pages.dev/

Validation passed in cases:
- Attach account in app
- Import account in app
- Connect/Disconnect with extension
- Remove account
- Enable/Disable network
- Reset wallet
- Perform earning actions
