### ISSUE TITLE
Extension - Improve the staking reward information retrieval

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3326]
Describe the task
Improve the staking reward information retrieval:
- Chery pick issue https://github.com/Koniverse/SubWallet-Extension/issues/3322

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/HwwM4M2kjN57LNs
- (Firefox): http://14.224.129.242:8900/s/jxLAac4MHZpZPnZ

Validation passed in case : 

- Install/Update version
- Attach account ( All account mode, Specific account mode)
- Import account ( All account mode, Specific account mode)
- Remove account
- Enable/Disable network
- Reset wallet
- Perform earning actions


![Image](https://github.com/user-attachments/assets/aeb6c8c4-8c34-4ddb-a723-cb425d6ba6d6)

**Comment by S2kael** [comment]
Since this issue cannot be reproduced on the extension, please double-check the code @nampc1
