### ISSUE TITLE
Extension - Show incorrect withdrawal information of the Bifrost liquid staking when all accounts mode

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3327]
**Describe the task**
Show incorrect withdrawal information of the Bifrost liquid staking when all accounts mode
- Check with address: 
  - 5CFh4qpiB5PxsQvPEs6dWAhzgAVLHZa8tZKxeE9XsHBg4n9t
  - 5CAfi6MtzQBcw8iPniwxW8S8YHKEbGbqk8xSm6K9NzxxxLh7
![Image](https://github.com/user-attachments/assets/46b03e09-11ee-4abd-8a4a-c5d5186ca009)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/CfLskAy7W3BM9JB
Validation passed. 
Checklist: https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#e3b0ac4fae00445aaa569b1f6811996d
