### ISSUE TITLE
Re-test MV3 on Firefox

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3330]
**Describe the task**
Re-test MV3 on Firefox

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/xSqbP7TBcqq6cwX

- [ ] Error page on Expand view mode ( Hang for about 1 hour)


![Image](https://github.com/user-attachments/assets/98bdfd78-cc8b-437a-b08a-f8adf4dd8746)
