### ISSUE TITLE
Add KOL / Kolkadot

### ISSUE THREAD

**Issue by kolkadot** [Koniverse/SubWallet-Extension#3335]
**Describe the solution you'd like**

Please make KOL / Kolkadot visible on SubWallet.

**Describe alternatives you've considered**

- AssetHub asset ID: 86
- Hydration asset ID: 1000199, see https://github.com/galacticcouncil/intergalactic-asset-metadata/pull/5/files#diff-12e598daecade60b04e493f45c134fec9287ac7471114d95d1995b4fb651a6c8
- Logo: https://github.com/galacticcouncil/intergalactic-asset-metadata/blob/master/assets/kolkadot.svg
- PNG Logo: ![kolkadot_final_128](https://github.com/user-attachments/assets/1623cff1-e6e5-4260-a4f0-7d12ceae7847)

**Comment by Mabel-Nguyen** [comment]
- KOL on Polkadot Asset Hub: https://assethub-polkadot.subscan.io/assets/86

**Comment by bluezdot** [comment]
- KOL on Hydration: https://hydration.subscan.io/custom_token?unique_id=asset_registry%2F1ca5b3de13308a0d2b7fa95ef3d9cbd8e63b1445&tab=holders
