### ISSUE TITLE
WebApp - Re-check case totalStake < unstakeBalance

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3339]
**Describe the task**
Re-check case totalStake < unstakeBalance
- Ticket: https://discord.com/channels/447263980252037141/1261299767082881114

**Comment by nampc1** [comment]
Check usage of BN.js for unstaking info

**Comment by haiyenvu23** [comment]
Version test : https://18a18f34.subwallet-webapp.pages.dev/
Validation passed in case : 
- Re-check all action on Earning features : 
- Stake
- Stake more
- Unstake
- Cancel unstake
- Withdraw
- Claimreward


![Image](https://github.com/user-attachments/assets/719f139a-0928-4577-afee-1721de0ffca4)
