### ISSUE TITLE
WebApp - Improve Mission pool feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3342]
**Describe the task**
Improve Mission pool feature

- [x] Add categories
- [x] Sort by status
- [x] Show/hide fields by value
- [x] Show bage

Refer: https://github.com/Koniverse/SubWallet-Extension/issues/3212

**Comment by haiyenvu23** [comment]
Version test : https://250b71e5.subwallet-webapp.pages.dev/home/tokens

- [ ] Re-check UI


![Image](https://github.com/user-attachments/assets/08067f63-bd2b-4c51-b094-88843a3f2fbf)

- [ ] Re-check padding in case responsive


![Image](https://github.com/user-attachments/assets/e62bc791-174f-462c-811b-1eb7382d57c8)

- [ ] Re-check display description in case responsive


![Image](https://github.com/user-attachments/assets/f88a8c4a-fb60-40e0-b46c-45ba1c24868f)

**Comment by haiyenvu23** [comment]
Version test : https://7f641eba.subwallet-webapp.pages.dev/home/tokens

- [ ] Don't show noti number in case responsive


![Image](https://github.com/user-attachments/assets/a0ab4b22-ab7e-45b6-9645-0a8267357323)

**Comment by haiyenvu23** [comment]
Version test : https://8d08333b.subwallet-webapp.pages.dev/home/mission-pools

- [ ] Re-check noti in case responsive


![Image](https://github.com/user-attachments/assets/0747d38c-2dcc-4ece-90c8-a8ea07837181)



![Image](https://github.com/user-attachments/assets/8551da58-de94-45f2-95a4-693cfe5a600d)



![Image](https://github.com/user-attachments/assets/6456224c-b0da-4453-8165-d164ff7c1086)

**Comment by haiyenvu23** [comment]
Version test : 
Validation passed in case :  
- Responsive 


![Image](https://github.com/user-attachments/assets/972526e3-1259-4d64-a04e-5bd92dfdf6d5)


- Sort according status and ordinal 


![Image](https://github.com/user-attachments/assets/d263dd92-11db-4231-b63a-8dd19e0e70f1)


- Show tag categories


![Image](https://github.com/user-attachments/assets/c5eb8ae8-3443-4de7-93b8-5601dd5bb607)


- If the Total token supply field has no value, it will be hidden


![Image](https://github.com/user-attachments/assets/0b44e888-6ecb-4767-8404-94db7b020e6c)



![Image](https://github.com/user-attachments/assets/91636cb9-bd22-4e18-bbde-a1e221cf3fc5)
