### ISSUE TITLE
WebApp - Show blank screen in case sign transaction with dApp used WalletConnect

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3362]
**Describe the bug**
Show blank screen in case sign transaction with dApp used WalletConnect

**To reproduce the bug**
Pre-condition: Connect webapp with extension (Extension has Ledger account)
Steps: 
1. Connect with dApp = WalletConnect use Ledger account EVM
2. Perform transaction on dApp
3. Observe the displayed scene

Actual: Show blank screen 

![Image](https://github.com/user-attachments/assets/6830c9df-5073-43b0-aeda-95431f994574)

Expect: Show Confirmation screen

**Comment by haiyenvu23** [comment]
Version test : https://231644fa.subwallet-webapp.pages.dev/home/tokens
Validation passed in case : 
- Use Ledger account to sign


![Image](https://github.com/user-attachments/assets/c1d888e5-1252-44cd-a771-a4de7307a27a)

- Re-check with account types : QR acc, Ledger substrate acc, read-only acc, normal acc
