### ISSUE TITLE
Update connector version

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3363]
We need to update:
- [x] Metamask injected object
- [x] WalletConnect, Rainbow kit,...

**Comment by haiyenvu23** [comment]
- [ ] Re-check case reload webapp after re-connect with extension


![Image](https://github.com/user-attachments/assets/ed2e1a28-6282-4e67-9e49-ca6ed14b7750)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/KYMemjFm7y2dZBL
Link dApp (EVM) : https://test-dapp-7vf9.vercel.app/
Link dApp ( Substrate) : https://connect.subwallet.app/#/wallet-info
Link walletconnect : https://ex-walletconnect.vercel.app/
Link checklist : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#1e918400134444e6ab6ef6f02b677540
Validation passed in case : 
- Install/ Update version
- Check connect with dapp
- Check perform sign message/sign transaction with dApp
- Check perform Revoke accounts permission method on dApp


![Image](https://github.com/user-attachments/assets/49a1beca-593c-41d5-8a57-da8601157b73)

- Check case reload webapp after re-connect with extension


![Image](https://github.com/user-attachments/assets/ba4d15f4-57ed-43ef-815c-c84dce524424)

- Check when perform Ping on WalletConnect 


![Image](https://github.com/user-attachments/assets/bb72f772-5ae9-4520-9504-6a55a0463993)

**Comment by Sokol142196** [comment]
- [ ] Fill checklist and update content

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/SZa3xAqGpQFxpeP
Link dApp (EVM) : https://test-dapp-7vf9.vercel.app/
Link dApp ( Substrate) : https://connect.subwallet.app/#/wallet-info
Link walletconnect : https://ex-walletconnect.vercel.app/
Link checklist : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#1e918400134444e6ab6ef6f02b677540
Validation passed in case : 
- Install/ Update version
- Check connect with dapp
- Check perform sign message/sign transaction with dApp
- Check perform Revoke accounts permission method on dApp


![Image](https://github.com/user-attachments/assets/49a1beca-593c-41d5-8a57-da8601157b73)

- Check case reload webapp after re-connect with extension


![Image](https://github.com/user-attachments/assets/ba4d15f4-57ed-43ef-815c-c84dce524424)

- Check when perform Ping on WalletConnect 


![Image](https://github.com/user-attachments/assets/bb72f772-5ae9-4520-9504-6a55a0463993)
