### ISSUE TITLE
Extension - Check validate on Firefox when submit MV3 version for Firefox browser

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3364]
**Describe the task**
Check validate on Firefox when submit MV3 version

- [x] Extension ID
- [x] Filesize

**Comment by saltict** [comment]
- I rolled back Firefox to MV2 and also separated firefox packaging
- Please re-test Firefox actions and also overview Chrome Version.

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/rAsXY9QEeZxPSAx
Validation passed. 
Checklist for issues: https://www.notion.so/subwallet/Check-list-all-function-b9c59fa926c64c38a77cbb0adbdb8fd7?pvs=4

Follow up:
- XCM: KSM  PAH -> KAH -> disable
- Do not show NFT Kusama Asset Hub
