### ISSUE TITLE
Extension - Support XCM for Mythos

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3389]
**Describe the task**
Support XCM for Mythos: https://github.com/Koniverse/SubWallet-ChainList/issues/271

**Comment by nampc1** [comment]
- [ ] MYTH: Hydration -> Mythos 0xd8048905030400010100a534001300008a5d784563010000000003010200a5340300dd718f9ecaf8f144a3140b79361b5d713d3a6b1900
- [ ] MYTH: Mythos -> Hydration 0x0901041f0803010100c91f0300010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da554537803040000000013000064a7b3b6e00d0000000000
- [ ] MYTH: Mythos -> AH 0x0901041f0803010100a10f03000101002c6dbbcb86ec6791ba672dcff246852de298bf67bc70fa5152e9684e04e3545b030400000000130000f444829163450000000000
- [ ] MYTH: AH -> Mythos

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/ozMMgoNH9RCeLLj
- (Firefox): http://14.224.129.242:8900/s/i8ggcpyofQCS3ta
Validation passed in case : 
- Install/Update version
- Perform XCM : 
- MYTH: Hydration -> Mythos : https://hydration.subscan.io/extrinsic/0xaafccd0793b3a25a66d05d9f11bc8db8e4c61898289fdfc41f8983df6724a2f0
- MYTH: Mythos -> Hydration : - https://mythos.subscan.io/extrinsic/0xf8d8e814f5e5054c435add19f719920e2dd1cbdb7ccec7589928c94a37600e5f
- MYTH: Mythos -> AH : https://mythos.subscan.io/extrinsic/0x675c002e13357213477eab26d1b867b78fca541d7a25d8a51e5f5baa172fbabf
- MYTH: AH -> Mythos : https://assethub-polkadot.subscan.io/extrinsic/0x9ad40c8834f03484a77705e19882b008917e01de8f3779ed71beb0df573c042d

**Comment by Sokol142196** [comment]
Validation passed with 2 channels:
- MYTH: Mythos -> Hydration 
- MYTH: Mythos -> PAH 

Follow-up with 2 channels in issue https://github.com/Koniverse/SubWallet-Extension/issues/3453
- MYTH: Hydration --> Mythos
- MYTH: PAH --> Mythos
