### ISSUE TITLE
Add new networks (parachain winners on Kusama & Polkadot)

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#339]
**Describe the solution you'd like**
Please add new networks to be supported on SubWallet:

**POLKADOT**

- [x] 1. CLV: https://twitter.com/clv_org #223
- [x] 2. OriginTrail: https://parachain.origintrail.io/
- [x] 3. Bifrost Polkadot
- [x] 4. Totem Kapex: https://twitter.com/Totem_Live_ // Not launch now

**KUSAMA**

- [x] 1. Dora Factory: https://twitter.com/DoraFactory
- [x] 2. Bajun Network: https://parachains.info/details/bajun_network
- [x] 7. Listen: https://parachains.info/details/listen
- [x] 8. Kabocha: https://parachains.info/details/kabocha
- [x] 10. Imbue Network: https://twitter.com/ImbueNetwork

**Comment by sokol142** [comment]
@S2kael Please check:

- [ ] kapex: 
![image](https://user-images.githubusercontent.com/102292476/181473107-f102700f-17a3-4b9b-9713-82ebce03bd01.png)

**Comment by S2kael** [comment]
@sokol142 in this time, Kapex has not been launched yet. So you cannot create transaction in this chain.

**Comment by sokol142** [comment]
@S2kael please turn-off Kapex in this time!

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./494-merge-build-0.5.2-1659063492977.zip

Completed integration networks:
- Clover (CLV)
- OriginTrail
- Bifrost Polkadot
- Dora Factory
- Bajun Network
- Listen Network
- Kabocha
- Imbue Network
