### ISSUE TITLE
Update UI to support unified account

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3396]
Implement UI for these following features:
- [x] Select account
- [x] Account detail
- [x] Import account
- [x] Create account
- [x] Delete account
- [x] Derive account

**Comment by nampc1** [comment]
Some UI bugs:
- [ ] Show account type and derivation path in Account detail screen
- [ ] Check condition to show footer button in Account detail screen
- [ ] Show account type in setting account name component
- [ ] Bug showing word number in Import by seed phrase screen
- [ ] Automatically change to 24 words mode when user pastes in more than 12 words of seed phrase

**Comment by nampc1** [comment]
- [ ] Implement UI logic for account derivation

**Comment by Sokol142196** [comment]
- [ ] Fix bugs in https://www.figma.com/board/Rvcxn7edWpsUUKSK2eddEX/Nhung's-project?node-id=2151-4936&t=VQwuQNBuixSO1WJI-4

**Comment by nampc1** [comment]
Bugs will be fixed in #3457
