### ISSUE TITLE
Update substrate dApp connect interface to allow dApp connect with EVM account

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3401]
Link: https://discord.com/channels/925999372238483486/1245001297250484296

With substrate dApp connection interface: Only `substrate` option (default) and `both` when connecting.

Solution:
- Add `evm` option to interface for some dApps, use evm address only on substrate network

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/KYMemjFm7y2dZBL
Link dapp : https://mkr52n.csb.app/
Validation passed in case : 
- Install/Update version 
- Check connect with : 
- Only Substrate type
- Only EVM type
- All type
- Check sign successfull


![Image](https://github.com/user-attachments/assets/bc54d43d-f88a-45db-bc1d-7910e5fce684)

**Comment by Sokol142196** [comment]
Resolve in https://github.com/Koniverse/SubWallet-Extension/issues/3363 => Follow-up issue

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/SZa3xAqGpQFxpeP
Link dapp : https://mkr52n.csb.app/
Validation passed in case : 
- Install/Update version 
- Check connect with : 
- Only Substrate type
- Only EVM type
- All type
- Check sign successfull


![Image](https://github.com/user-attachments/assets/bc54d43d-f88a-45db-bc1d-7910e5fce684)
