### ISSUE TITLE
Update showing attachable network list for Migration Polkadot app

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3402]
We should display network list according to the Ledger app that users choose

**Comment by haiyenvu23** [comment]
- [ ] Update UI for Connect ledger device screen 
- Link design : https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=864-73078&t=6bhe215HSIFIfz5U-4
- Update content : "Unlock your Ledger and open the selected app. For more information regarding Polkadot and Polkadot Migration app, click here"

- [ ] Update tooltip when choose network for Migration app
Expect : "To use this network, choose Polkadot Ledger app"

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/JnktYZ9KsM9reTz

- [ ] Update logo for Polkadot migration
Link : https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7105-27&t=xZiDeEeKobvCJVYE-4

- [ ] Re-check UI on Connect ledger device screen

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/65TyRL3w63Q8jjf

- [ ] Re-check message when sign message


![Image](https://github.com/user-attachments/assets/90cebdff-8e02-407a-aa90-120e9c4a466e)

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/DCt97JFtik5kGYm
- (Firefox): http://14.224.129.242:8900/s/8FFoqQmkBdH6LYR

Validation passed in case : 

- Install/Update version
- Re-check logic
- Improve UX/UI


![Image](https://github.com/user-attachments/assets/cbc332a3-52c6-486a-afc1-09662476d1b2)



![Image](https://github.com/user-attachments/assets/8df789a6-98e0-46bd-b848-a14f3be2c724)



![Image](https://github.com/user-attachments/assets/ee16e418-716d-49fc-85cd-2850e4fc65e9)
