### ISSUE TITLE
WebApp - Do not show earning position for Bifrost liquid staking 

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3413]
**Describe the bug**
Do not show earning position for Bifrost liquid staking 

**To Reproduce**
Check with address 5CAfi6MtzQBcw8iPniwxW8S8YHKEbGbqk8xSm6K9NzxxxLh7 
![image](https://github.com/user-attachments/assets/73d08936-670b-427c-af24-be7072522fa9)

**Comment by ThaoNguyen998** [comment]
Version test: https://78003767.subwallet-webapp.pages.dev/home/earning/position-detail
Validation passed
- Show Earning position for Bifrost liquid staking

  ![Image](https://github.com/user-attachments/assets/9e766b9c-c56e-4ea9-ba70-cb5e2c86135d)

- Re-check another network
- Re-check all action staking
