### ISSUE TITLE
Integrate Avail Bridge

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3423]
https://bridge.avail.so/
https://gist.github.com/abheektripathy/831fb2b41eb64527aef39e7d39f366cb
https://turing-bridge-api.avail.so/

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/Dkmre48xzQ4HMFP
- [ ] Check the Claim token history
  - Actual: Show status = Failed although transaction is completed
    - tx: https://sepolia.etherscan.io/tx/0xba68c5a2b12122d2bdc42126f7a626cbd20f30407a67424f0639b43f13de4eec
    ![Image](https://github.com/user-attachments/assets/aee1829e-8865-4a19-a973-2d61d0082282)
    - Log 
    ![Image](https://github.com/user-attachments/assets/6c4c0282-ef50-4ae9-a78b-fe888641ff26)

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/YasYyFtjBb2ksJD

- [ ] Update content and UI
  - [ ] Icon Claim for claim token from bridge
    ![Image](https://github.com/user-attachments/assets/3e98e4cd-e71b-49c6-b504-88d7eeb5f1ae)

  - [ ] Update transaction type on the history screen
    ![Image](https://github.com/user-attachments/assets/127363f5-4395-490e-9877-7974d32b46c4)

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/N3ARXZFWYkMs2cp

- [ ] Do not show transaction fee
   ![Image](https://github.com/user-attachments/assets/6cd66f87-9b97-49a5-81a0-e89039546dcb)

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/nf5pHWmeC5wydeQ

Validation passed in cases: 
- Bridge from Avail to Ethereum (Mainnet), Avail <-> Ethereum (Testnet)
- Show notification to claim tokens
- Claim token on testnet
- Claim token on mainnet (Avail: Avail --> Ethereum) - Approve step
- Re-check show fee with other transaction (Transfer token, Transfer NFT, Swap, Earning, transfer with dApp)

Notes for test later:
- Claim on mainnet
- Bridge Avail: Ethereum mainnet --> Avail mainnet
