### ISSUE TITLE
Extension - Input overflow width issue

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-Extension#3441]
![Image](https://github.com/user-attachments/assets/92833202-1ac6-436f-8847-ce5431712f18)

Actual:
The  order number will be hidden if user click the input

Expect:
The order number must be show normally

**Comment by haiyenvu23** [comment]
Verion test : http://14.224.129.242:8900/s/DzDYG3xQc9p8tZ5
Validation passed in case : 
- Install/Update version


![Image](https://github.com/user-attachments/assets/b766a6fc-f006-458c-9442-204221d75619)



![Image](https://github.com/user-attachments/assets/d24e9c31-2e1d-4da2-acab-77af017dd3a5)



![Image](https://github.com/user-attachments/assets/b35bf784-f0a8-479e-97bb-be361e6fafb2)
