### ISSUE TITLE
Update balance calculation for nomination pool runtime update

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3443]
We no longer need to manually add nomination pool staking balance into total balance. This currently applies to Westend only, Polkadot and Kusama will be updated soon

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/nHsKWFRmmt7CCrJ
Validation passed.
- Check total balance if have nomination pool staking: WND, VARA, DOT, TZERO,..
- Re-check balance after stake
- Check with another network
- Install/Upgrade version
