### ISSUE TITLE
Extension - Format error when connecting to dApp 

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3445]
**Describe the task**
Format error when connecting to dApp on Firefox

- Refer to issue #2501

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/5NJCGfL876drQcw

- [ ] Cannot show message in some case validate


![Image](https://github.com/user-attachments/assets/8e775895-4381-464e-9f6f-bd330e05645a)

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/3fRStJpzJ6CACSn
- (Firefox): http://14.224.129.242:8900/s/CLGTZzqJdQZZcHK

Validation passed in case : 
- Install/Update version 
- Check with some case validate

**Comment by Sokol142196** [comment]
@S2kael please review this issue

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/GHf6SpX45DFo9pm
- (Firefox): http://14.224.129.242:8900/s/sNoQoEF9CJow5oz
Validation passed in case : 
- Instal/Update version
- Check case validate according to checklisst : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#c4d244ebfc2049f4b99baa0bf2cc9c2a
