### ISSUE TITLE
Update transfer UI to support unified account

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3448]
- [x] Send fund
- [x] Swap
- [x] Earning

**Comment by nampc1** [comment]
- [ ] Consider move transaction warnings to background

**Comment by Sokol142196** [comment]
- [ ] Do not show Account Name when select To = Account in wallet
  - Expect: Show Account Name (address)
 ![Image](https://github.com/user-attachments/assets/ca5ae4ae-f416-481f-81be-2f0b07defc42)

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/17nOk7rEN_BeJob0bjX6DhZR0R6uz79wB/view?usp=sharing

Validation passed in case:
- Sort balance
- Default token
- UX when changing token
