### ISSUE TITLE
Support transfer on TON

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3449]
- [x] Send TON
- [x] Send Jetton tokens

**Comment by bluezdot** [comment]
Storage Fee:
```storage_fee = (cells_count * cell_price + bits_count * bit_price) * time_delta /2^16.```
bit_price and cell_price config: https://tonviewer.com/config#18

**Comment by bluezdot** [comment]
-> "Compare our estimated fee to other wallets"

ton-wallet (from FT): similar to us, sum up 4 fees type on source fee estimate
openmask: similar to us, sum up 4 fees type on source fee estimate
ton-keeper: use battery for fee -> quite new, maybe a mechanism from wallet v5

**Comment by nampc1** [comment]
- [ ] Update get max transferable
- [ ] Add queryId to message body
- [ ] Handle transaction status for TON and Jetton transfer
- [ ] Update transaction hash
- [ ] Add warning when user inputs bounceable address

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/11OxiJhWeKkHkLl21eLm6UFDso8RTZPWv/view?usp=sharing

Please check:

- [ ] Can't transfer TON testnet to TON Testnet address

This error needs to be resolved before further testing.

**Comment by Sokol142196** [comment]
Version test: https://discord.com/channels/447263980252037141/1257253924910534697/1278998805945253938
Please check issues:

- [ ] Can't transfer TON on new account (account have no tx yet)

![Image](https://github.com/user-attachments/assets/dcc76c72-dd44-4198-9c76-aa4c21e03ba0)

- [ ] Do not show history details


![Image](https://github.com/user-attachments/assets/16968bc2-2be5-4baa-818e-6e4664de25fe)

- [ ] Show incorrect message when input invalid TON address 

![Image](https://github.com/user-attachments/assets/4a9a33e5-5115-47de-98ff-42a58291a04b)

**Comment by bluezdot** [comment]
@Sokol142196, "Show incorrect message when input invalid TON address"
-> Currently, @lw-cdm disable some recipient validation for transfer testing. The above check is resolved in another issue, https://github.com/Koniverse/SubWallet-Extension/issues/3528
Demo:
![image](https://github.com/user-attachments/assets/b8bde158-da29-4972-9c69-fa3c43a0ee6b)

**Comment by bluezdot** [comment]
@Sokol142196 Sokol, "Do not show history details" -> Related to UI bug on history screen

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1EYCD87_fFS1wJSv92ciRZs5F3d9cfc0E/view?usp=sharing

Please check the issues:

- [ ] Transfer Max
  - Ticket: https://discord.com/channels/447263980252037141/1257253924910534697/1280751280234561627
  - Notes: I reproduce this issue with Bounceable address

- [ ] Re-check condition show warning when enter To = Bounceable address
  - Actual: Always show warning
  - Expect: Only show when input bounceable address of the inactive account

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1H9TKwdQsr8LhZyiHqrVJP7M6xa-SE-rE/view?usp=drive_link

- [ ] Hide this alert warning in case send to boundable address

![Image](https://github.com/user-attachments/assets/faf65a5b-70c6-42d1-b9b8-c09c1215d464)

- [ ] Sometimes the transaction is failed
 ![Image](https://github.com/user-attachments/assets/a3059477-e426-4f48-8274-6b6e7187e6d6)

- [ ] Format address on the Confirmation screen and History
  ![Image](https://github.com/user-attachments/assets/2dcbd9cd-7b33-4168-8265-1c6006cff7dd)

- [ ] Re-check transfer Max
  - Actual: When click Transfer all then show err message "Insufficient balance"
  ![Image](https://github.com/user-attachments/assets/5b44c155-afc0-4f20-8dc8-1c86657f0d61)

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1wOe_wYe6BYezGizE2JB_dzWHJ5eZvH79/view?usp=drive_link
Continue resolve issue in #3583 #3589
