### ISSUE TITLE
Extension - Re-check UI on Transfer screen ( version 1.1.24)

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3452]
**Describe the bug**
Re-check UI on Transfer screen ( version 1.1.24)

![Image](https://github.com/user-attachments/assets/031df5e9-de94-4d64-b0d6-a4ae14b8b60b)

- [x] History screen 
![image](https://github.com/user-attachments/assets/f93821a2-dcb7-4cd0-a17c-0d411f9e495b)

**Comment by lw-cdm** [comment]
Recheck:
- Import token
- Connect ledger
- History
- Import NFT
- Send fund
- Send NFT

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/bxfWPXZHn9NN6qP
Validation passed in case : 
- Install/Update version
- Check UI on some screens : 
-  Import token


![Image](https://github.com/user-attachments/assets/91e050a6-4c0d-4ec1-b3a8-803edfbab813)



![Image](https://github.com/user-attachments/assets/3f61e83f-dedd-48fa-a06e-dc850a6e79dd)


- Connect ledger


![Image](https://github.com/user-attachments/assets/f3db02a2-0345-4c3e-b226-8a6232f42b26)



![Image](https://github.com/user-attachments/assets/6570e40f-2283-4525-be4b-d1d5aeab128a)



![Image](https://github.com/user-attachments/assets/32db551e-062a-4bdb-9403-da2efc29a8e4)


- History


![Image](https://github.com/user-attachments/assets/683cae9d-1687-49cb-8cee-cfd5ab62311d)



![Image](https://github.com/user-attachments/assets/9ecf7218-7789-490a-9cfb-18562c05978d)


![Image](https://github.com/user-attachments/assets/74194246-fecc-4327-9c2e-f2bd2c3a6030)



- Import NFT


![Image](https://github.com/user-attachments/assets/e71eb9e4-63f2-4a47-b352-ef6374ad30f9)


![Image](https://github.com/user-attachments/assets/16115fc8-7f07-4f9b-b9d5-69aebb08bba0)



- Send fund


![Image](https://github.com/user-attachments/assets/a3dd29d8-9024-440b-8964-d8784d910f04)


![Image](https://github.com/user-attachments/assets/325e789b-99d1-4844-adf1-744dc6a960ca)



- Send NFT


![Image](https://github.com/user-attachments/assets/6b12d1ac-d9b2-4df8-9ecc-e8f93d0670fe)
