### ISSUE TITLE
Extension - Re-check XCM from PAH, Hydration to Mythos

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3453]
**Describe the task**
Re-check XCM from PAH, Hydration to Mythos
- [x] MYTH: Hydration --> Mythos
- [x] MYTH: PAH --> Mythos (Follow up)

**Comment by bluezdot** [comment]
https://github.com/Koniverse/SubWallet-ChainList/issues/271

**Comment by bluezdot** [comment]
Test these cases:
- [ ] ASTR: Astar -> Acala
- [ ] USDT: Astar -> PAH

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/e4T7YdTdk8eygjP

- [ ] Re-check MYTH: Mythos --> PAH
Transaction fail: https://mythos.subscan.io/extrinsic/0x0b2690f0b9e1f6ec98bbcdc623db1a5544f14b2ad8eb3509a45f1237b377acba

**Comment by bluezdot** [comment]
- mythos -> pah:
0x0901041f0903010100a10f030001010010df8d4e15bfd11d276c650b883ea184c8f122ab3b4ae5a6784b9f4722d4595f030400000000130000f444829163450000000000

- pah -> mythos:
0xe4041f0903010100a5340300010300dd718f9ecaf8f144a3140b79361b5d713d3a6b19030400010100a534001300008a5d784563010000000000

**Comment by bluezdot** [comment]
- Mythos -> PAH:
0x0901041f0903010100a10f030001010010df8d4e15bfd11d276c650b883ea184c8f122ab3b4ae5a6784b9f4722d4595f030400000000130000f444829163450000000000

- PAH -> mythos:
0xe4041f0903010100a5340300010300dd718f9ecaf8f144a3140b79361b5d713d3a6b19030400010100a534001300008a5d784563010000000000

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/e4T7YdTdk8eygjP
Validation passed. 

- MYTH: Hydration --> Mythos
https://hydration.subscan.io/extrinsic/0x8a56151775e0e117cbf3c831c62910c96560a977e59058c26780889068198833
Add warning: 

![Image](https://github.com/user-attachments/assets/b5eced7d-5f78-4412-9f48-e55a6fc02837)

- MYTH: Mythos --> Hydration: https://mythos.subscan.io/extrinsic/0x8c2633eaf1607de8d5bcbe3a7a6df44bd9f8732d582d45b49d856a42fcde54d2

- MYTH: Mythos --> PAH: https://mythos.subscan.io/extrinsic/0x537e0d964d3387c62b260ebdb42bec1e9645dd38ef18695e21d5917af10f5005

- MYTH: PAH --> Mythos: https://assethub-polkadot.subscan.io/extrinsic/0x52351364d37eec521e708be7a7b991192c95e14524b57bc398c83b4808c48acb

- ASTR: Astar -> Acala: https://astar.subscan.io/extrinsic/0x94e0c741762c9f9f26ab36d7ea7e709f03719357f24fb8dc39a1e4da0ac7bc3f

- USDT: Astr -> PAH: https://astar.subscan.io/extrinsic/0x1a69215fe8d8686c84e4e07ea8ae9816861e016bb008a455f369d58c6dee27b6

- Update text: 70$ -> $70
![Image](https://github.com/user-attachments/assets/67bf8ac4-537c-4ecb-a2b6-2f2069a445d1)
