### ISSUE TITLE
Extension - Support XCM for Ledger Polkadot generic app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3458]
**Describe the task**
Support XCM for Ledger Polkadot generic app

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/swbenCn2zzKt35F
Validation passed in case : 
Link checklist : https://www.notion.so/subwallet/BA-QC-Document-57acd6b41e544bc19be3bc50cd6be605?p=13c9e3215ec24762973dc680aec67198&pm=s
- Install/Update version
- Block XCM features for legacy apps
 

![Image](https://github.com/user-attachments/assets/7f1a0df7-7203-4bbb-b905-f4d5a68231c3)

- Check XCM with generic and migration app
- Check XCM when sign with dApp

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/swbenCn2zzKt35F

- [ ] Re-check with legacy app ( Polkadot, Statemint, Statemine, Kusama)
