### ISSUE TITLE
Avail Space - Support mission pool feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3459]
**Describe the task**
Support mission pool feature for Avail Spcae

**Comment by ThaoNguyen998** [comment]
Version test: https://75affe9b.avail-space.pages.dev/home/mission-pools
Validation passed. 
- Add mission pool
- Update mission pool
- Delete mission pool
- List mission pool
- Search/ Filter
- Check status
- Check tab
- Check sorting
- View mission pool details
- Check navigate when click actions on mission pool
