### ISSUE TITLE
WebApp - Allow to use Migration Polkadot App to attach Ledger account

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3460]
**Describe the task**
Allow to use Migration Polkadot App to attach Ledger account
Refer: #3307 #3402

**Comment by haiyenvu23** [comment]
Version test : https://bb2ae5ca.subwallet-webapp.pages.dev/accounts/connect-ledger
- [ ] Update color item according to list pool blocked 


![Image](https://github.com/user-attachments/assets/971cc62f-7c1b-40ed-a5b7-369a6e10de12)

- [ ] Arrange un-select items down

**Comment by haiyenvu23** [comment]
Version test : https://be47c535.subwallet-webapp.pages.dev/home/tokens
Validation passed 
Link checklist : https://www.notion.so/subwallet/Check-list-Migration-Polkadot-App-to-attach-Ledger-account-b330154648ab4bdf85958379755ef9d3
- Handle case XCM for legacy app -> Releated to issue https://github.com/Koniverse/SubWallet-Extension/issues/3531
