### ISSUE TITLE
Extension - Improve marketing campaign for Extension

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3461]
**Describe the task** 
Improve marketing campaign for Extension

- [x] App confimation
- [x] App banner position
  - [x] Token
  - [x] NFT
  - [x] Earning
  - [x] Mission Pool

- [x] App popup position
  - [x] Mission Pool
  - [x] History
- [x] Update popup update version

![Image](https://github.com/user-attachments/assets/9899a062-bfe8-4258-963e-58f248aefd7e)

**Comment by Quangdm-cdm** [comment]
I will skip:
- the dApp section in App popup position because the extension does not have this screen.
- the location filter part because implementing it is quite difficult on the extension and is also related to user information security.
@ThaoNguyen998

**Comment by ThaoNguyen998** [comment]
- [ ] The banner displays in the wrong position

   ![Image](https://github.com/user-attachments/assets/c85eea84-a45c-491e-90ea-0af34e61e118)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/KNxqmiRPFgM9rjq
Validation passed
Checklist for issues: https://www.notion.so/subwallet/Checklist-Marketing-campaign-ef6f5ce4471e41788f395af222ab5c83?pvs=4
