### ISSUE TITLE
Unified account - Filter chains, tokens and features for account types

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3462]

**Comment by Sokol142196** [comment]
Please check isues:

- [ ] Receive account in case stand on Single account
  - Actual: Still show Select account popup
  - Expect: Do not show step Select account

- [ ] List token to swap is incorrect

  ![Image](https://github.com/user-attachments/assets/5815fe6d-dd74-448a-a539-7cc73124629f)

- [ ] Do not show account when start earning

  ![Image](https://github.com/user-attachments/assets/dd432fd9-2b13-401e-a7ef-3fec7bd325c4)


- [ ] Need to confirm
  - [ ] Handle case enable/disable feature

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1FgewyLIHbwxRq8fsyvHx_0-s0eJ1wILh/view?usp=sharing

- [ ] Show incorrect list token to send with Ledger Legacy account
Steps:
1. Attached Legacy ledger account success
2. On the Homepage, click on Send button
3. Select token to send then observe the token list is displayed 

**Actual:** Show incorrect token list (Example: Acala Ledger app but only show tKSM token)

![Image](https://github.com/user-attachments/assets/e4a1b22c-d788-495f-868d-0f64b067474a)

**Expect:** Show all token of the network that supported by account

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/11OxiJhWeKkHkLl21eLm6UFDso8RTZPWv/view?usp=sharing
Validation passed : 
- Case statuses are updated in the checklist : https://www.notion.so/subwallet/BA-QC-Document-57acd6b41e544bc19be3bc50cd6be605?p=b965dc8634aa4fe69bbf34bdbcd8a94a&pm=s

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/11OxiJhWeKkHkLl21eLm6UFDso8RTZPWv/view?usp=sharing
Validation passed 
- The results of the cases mentioned in the link: https://www.notion.so/subwallet/BA-QC-Document-57acd6b41e544bc19be3bc50cd6be605?p=b965dc8634aa4fe69bbf34bdbcd8a94a&pm=s
