### ISSUE TITLE
Extension - Add validate for Solochain when receive, transfer with Generic ledger account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3463]
**Mô tả task**
Add validate for Solochain (Avail, Bittensor...) when receive, transfer with Generic ledger account

- [x] Add warning when receive Avail address with Generic ledger account
- [x] Show error message in case input "To account" is "Generic ledger account" when transfer AVAIL

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/N3iDDPAodPdkc6n

- [ ] Update type warning
 
 ![image](https://github.com/user-attachments/assets/e9655889-50d8-4782-9882-f28ecade85a1)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/y8NMebMDAz3f7EH
Validation passed.
Checklist for issue: https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#7e76d4b2c3344a6cacaa54620c921d8b
