### ISSUE TITLE
Improve fetching era stakers

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3467]
- [x] Check validator list
- [x] Check validator detail
- [x] Check nominations for nominator
- [x] Check earning status for pools, validators, nominators

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/mCNYLsBGqMjXWAD

- [ ] Re-check validator detail
Link status : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#1561470e478b40e2b10da74c1a0a1da4

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/LpRrepbiYpYGPDr

- [ ] Don't auto select pool recommended on Avail network

Actual : 


![Image](https://github.com/user-attachments/assets/d596db04-e3d3-4934-acf7-ed0fbc677297)

Expect : 


![Image](https://github.com/user-attachments/assets/82745e55-030d-49bc-b5d9-befc8ba2d538)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/LpRrepbiYpYGPDr

- [ ] Wrong data


![Image](https://github.com/user-attachments/assets/c2f0e7a8-6aca-46a2-8bb2-a16ab710bc0e)

**Comment by bluezdot** [comment]
- [ ] fix old bug lead to wrong data. Please recheck Validator details info with polkadot.js @haiyenvu23.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/PK5X2S4i6ofJCrc

- [ ] Re-check APY infor

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/2KESoQPc368So6L
Validation passed in case : 
- Install/Update version
- Check validator list/validator detail with version on Store
- Re-check earning features : Stake, stake more, unstake, cancel unstake, claim reward, withdraw, liquid stake
- Handle validator APY is different from Polkadot js => Related to issue https://github.com/Koniverse/SubWallet-Extension/issues/3527
