### ISSUE TITLE
Extension - Improve block transfer to empty account

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3473]
**Describe the task**
Improve block transfer to an empty account
Actual: It is not allowed to deposit tokens into accounts with native token balance = 0
Expect: Any token that requires a native token to keep alive will be blocked from sending

**Comment by Sokol142196** [comment]
Will resolve in https://github.com/Koniverse/SubWallet-Extension/issues/3713
