### ISSUE TITLE
WebApp - Add validate for Solochain when receive, transfer with Generic ledger account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3479]
**Mô tả task**
Add validate for Solochain (Avail, Bittensor...) when receive, transfer with Generic ledger account

- [x] Add warning when receive Avail address with Generic ledger account
- [x] Show error message in case input "To account" is "Generic ledger account" when transfer AVAIL

Refer: https://github.com/Koniverse/SubWallet-Extension/issues/3463

**Comment by haiyenvu23** [comment]
Version test : https://90163511.subwallet-webapp.pages.dev/
- Checked with generic app 

- [ ] Haven't checked with migration app yet

**Comment by haiyenvu23** [comment]
Version test : https://e252cb8a.subwallet-webapp.pages.dev/
Validation passed in case : 
- Responsive
- Add warning when receive Avail address with Generic ledger account


![Image](https://github.com/user-attachments/assets/ba066c9f-56b4-41a3-9393-d66b5539f7c9)


- Show error message in case input "To account" is "Generic ledger account" when transfer AVAIL


![Image](https://github.com/user-attachments/assets/9fadb496-30ec-4d45-8164-d7ee351b3660)

- Test according to the following checklist : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#7e76d4b2c3344a6cacaa54620c921d8b
