### ISSUE TITLE
Update balance calculation for DeepBrainChain

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3481]

**Comment by bluezdot** [comment]
Some account with bridge WETH balance: 16ZrR53r7eucMoemefV2G79SQaLaSE43sojcGShPW4YxhbQ8, 12Yf7iECLhPsjnS4F5tBCpZqWjFbUhxDGoEFcrn9ayaEke6m

**Comment by bluezdot** [comment]
Account has balance: 5DcMyNy8Uv8QJFRYHSqB4fjgf7FwnQQ5CJVmTZno2tYia7hV

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/mdLQra96NKJpgdQ
Validation passed. 
Checklist: https://konistudio-my.sharepoint.com/:x:/g/personal/nhungphung_koni_studio/EZIxo_b6IsxNoLfQsa3YUlEBFy_8-n3XMAJkrDruMacr_w?e=r5YY49
