### ISSUE TITLE
Add Chainflip broker

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3483]
Add Chainflip broker API key to Chainflip swap service

https://docs.chainflip.io/concepts/swaps-amm/deposit-channels-and-brokers#brokers
https://docs.chainflip-broker.io/
https://www.notion.so/subwallet/Chainflip-BaaS-39d52015d71542ca99f14cffc45b8f6f

**Comment by Sokol142196** [comment]
Version test: 
- Chrome: http://14.224.129.242:8900/s/Azxz5SZQczJcwjW
- Firefox: http://14.224.129.242:8900/s/oEZH3fmQSbejDe7
Validation passed in cases:
- Check validate
  - Min amount
  - Max amount
  - Account
- Check swap information
- Check swap (approve step) for 2 pair
  - DOT <-> ETH
  - DOT <-> USDC
- Checkpoint swap pair for other provider
