### ISSUE TITLE
WebApp - UI bug in case import by seed phrase

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3488]
**Describe the bug**

  ![Image](https://github.com/user-attachments/assets/d709db2c-eab9-4a82-9a1f-4dae5143ac3c)

**Comment by haiyenvu23** [comment]
Version test : https://e86a4f87.subwallet-webapp.pages.dev/

- [ ] Seedphrase is reset when responsive changes
![Image](https://github.com/user-attachments/assets/3e354d40-15e4-441e-97d6-51bcb05f4586)
