### ISSUE TITLE
Unified account - Review and update for Ledger account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3491]
**Describe the task**
Review and update for Ledger account
- [x] Regarding account overwrite scenarios when connecting, including:
       + legacy <-> legacy: allow overwriting
       + legacy <-> generic: allow overwriting
             -> Unable to perform, showing an error that an account from another legacy app with the same address already exists.
- [x] Unable to select the Ledger account in the Earning section
- [x] Handle the case of duplicate account names when connecting with different devices.
- [x]  Update logic block transaction action according to the new interface.
- [x] Still show Polkadot Ledger Legacy account when receive token that not supported by Ledger account
  - Expect: Do not show Polkadot legacy account 
  
  ![Image](https://github.com/user-attachments/assets/6b3b7ef2-1984-4eb6-af32-796d45dd4e6a)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1EYCD87_fFS1wJSv92ciRZs5F3d9cfc0E/view?usp=sharing

- [ ] All account mode, in case the wallet only has a TON account and a legacy ledger account
Actual : Don't fillter chains, tokens for Receive, Send fund, Swap, Buy features


![Image](https://github.com/user-attachments/assets/4d81c488-926d-4cdf-9d08-b3ba9193f24e)

Expect : Fillter chains, tokens for Receive, Send fund, Swap, Buy features

- [ ] When perform XCM on send fund feature
Actual : Block XCM with Legacy app : Polkadot, Statemint, Statemine, Kusama


![Image](https://github.com/user-attachments/assets/f0165a0f-fe2f-412d-b0fa-fa6804d9d56e)


Expect : Don't block XCM with Polkadot, Statemint, Statemine, Kusama app

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1nuWeryGaUd1jg8ZQaiz_IvndgZsLpV_f/view?usp=sharing

- [ ] Don't show popup Unsupported network when get the network address that has not been updated at runtime
Expect : Update code from issue #3463
