### ISSUE TITLE
Fix UI bugs for Unified account (round 2)

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3496]
- [x] Update buy token screen
- [x] Update history screen
- [x] Condition to access swap screen (from token/ token detail list screen)
- [x] Navigate when click X button on the QR code screen: https://www.figma.com/board/Rvcxn7edWpsUUKSK2eddEX?node-id=2543-2432#922500144
  - Actual: Back to the Select token screen
  - Expect: Back to home page screen

- [x] Still allow turn off "seed phrase incompatibility" screen when out focus
  - Actual: Out focus then close popup
 
  ![Image](https://github.com/user-attachments/assets/cb24b9ee-37c3-477a-ad20-ed184f0801dd)

  - Expect: User must click on Cancel/Ok button then close popup

- [x] Do not show QR code screen when click on Cancel on the "Seed phrase incompatibility" screen
  - Actual: Back to Select token screen

  ![Image](https://github.com/user-attachments/assets/62ec8454-b215-4c5d-a2fd-580d14156d22)

  - Expect: Show QR code screen

- [x] Do not show Account name of the unified account on the Token details screen

  ![Image](https://github.com/user-attachments/assets/d9fbcc59-8269-4c9e-8bfe-eb5aa7026a67)

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/11OxiJhWeKkHkLl21eLm6UFDso8RTZPWv/view?usp=sharing
Please check issues:

- [ ] UI on the Confirmation screen 

![Image](https://github.com/user-attachments/assets/9dbe15f7-cbbf-4884-96a5-9e0d60074119)

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/open?id=11SrgJetpyNvxbqLVgjMJg5vOjmuu_384&usp=drive_fs

Validation passed for these cases
