### ISSUE TITLE
Send / Receive cross-chain assets

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#35]
## Base on research these articles:
- XCM: https://medium.com/polkadot-network/xcm-the-cross-consensus-message-format-3b77b1373392
- Tutorial: https://youtu.be/5HD5rFBqvQ4
## Send token to Moonbeam xcToken:
Main idea: Transfer token via XCM to Parachain/Account:
```javascript
function transferNativeTokenToXcToken(api, nativeToken, parachainId, address, amount, weight) {
  const currencyId = {
    Token: nativeToken
  };

  const dest = {
    V1: {
      parents: 1,
      interior: {
        X2: [
          {
            Parachain: 1000
          },
          {
            AccountKey20: {
              network: 'Any',
              key: address
            }
          }
        ],
      },
    }
  }

  return api.tx.xTokens.transfer(currencyId, amount, dest, weight);
}

const amount = 1000000000000;
const weight = 4000000000;
const nativeToken = 'KAR';
const parachainId = 1000;
const targetAddress = '0x4deFD3781271F92fA7dc47c97DB576bb3c916e6C';
const transfer = transferNativeTokenToXcToken(api, nativeToken, parachainId, targetAddress, amount, weight);
const {nonce} = await api.query.system.account(account.address);

transfer.signAndSend(keyPair, {nonce}, ({events, status}) => {
  handleExtrinsicCallback(api, {events, status})
});
```
Read more info send xTokens on karura on this [link](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkarura-rpc-1.aca-api.network#/extrinsics)
- Select module xTokens

## Send xcToken with xToken Contract in Other network
Main idea: send xcToken to token to support chain token by [xTokens contract](https://github.com/PureStake/moonbeam/blob/master/precompiles/xtokens/Xtokens.sol):
```javascript
let targetParachain = bnToHex(2001).slice(2); // Bifrost Alphanet
targetParachain = '0x0000000000'.slice(0, -targetParachain.length) + targetParachain;
const accountHex = u8aToHex(decodeAddress("ettAyhG3qXgvc6tFbofxYzQSdXBMzXMehB1TmmSEQd8SxvJ"));
const targetAccount = accountHex.replace("0x", "0x01") + "00"
const destination = [1, [targetParachain, targetAccount]];
const weight = 4000000000;

console.log('Destination', JSON.stringify(destination))

// Encode transfer
const transferData = xTokenContract.methods.transfer(assetsAddress, amount, destination, weight).encodeABI()

// Estimate gas fee
const gasPrice = await web3.eth.getGasPrice()
console.log(gasPrice);


const transactionObject = {
  from: fromAcc.address,
  to: contractAddress,
  gasPrice: gasPrice,
  data: transferData
}
let gasLimit = await web3.eth.estimateGas(transactionObject)
if (gasLimit) {
  transactionObject.gas = gasLimit;
}


// Perform Transaction
var signed = await web3.eth.accounts.signTransaction(transactionObject, fromAcc.privateKey)

try {
  web3.eth.sendSignedTransaction(signed.rawTransaction)
    .on('transactionHash', function (hash) {
      console.log("transactionHash", hash);
    })
    .on('receipt', function (receipt) {
      console.log('receipt', receipt)
    })
} catch (e) {
  console.log(e.message);
}
```

**Implement**

- [x] Design: 
- https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=2848%3A11347&scaling=min-zoom&page-id=4%3A14
- https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=2848%3A11520&scaling=min-zoom&page-id=4%3A14

Screen
 - [x] XCM transfer
 - [x] XCM transfer Authorize transaction
 - [x] XCM result
 
Component
 - [x] Network dropdown

Other:
- [x] Define list of networks can transfer XCM
- [x] Message passing to calculate fee and get fee token
- [x] Function for perform transferring using Polkadot js API
- #326
- [x] Message passing to perform transferring and get response result
- [x] Display transaction result
- [x] If selected network in Network dropdown is not activated, display message: "To perform the transaction, please make sure the selected network in Original Chain is activated first"
- [x] If sender address and origin Chain are not compatible => Show error message.  If receiver address and destination Chain are not compatible  => Show error message

**Comment by saltict** [comment]
## Required to Know:
- XCM: https://medium.com/polkadot-network/xcm-the-cross-consensus-message-format-3b77b1373392
- Tutorial: https://youtu.be/5HD5rFBqvQ4
## Send token to Moonbeam xcToken:
Main idea: Transfer token via XCM to Parachain/Account:
```javascript
function transferNativeTokenToXcToken(api, nativeToken, parachainId, address, amount, weight) {
  const currencyId = {
    Token: nativeToken
  };

  const dest = {
    V1: {
      parents: 1,
      interior: {
        X2: [
          {
            Parachain: 1000
          },
          {
            AccountKey20: {
              network: 'Any',
              key: address
            }
          }
        ],
      },
    }
  }

  return api.tx.xTokens.transfer(currencyId, amount, dest, weight);
}

const amount = 1000000000000;
const weight = 4000000000;
const nativeToken = 'KAR';
const parachainId = 1000;
const targetAddress = '0x4deFD3781271F92fA7dc47c97DB576bb3c916e6C';
const transfer = transferNativeTokenToXcToken(api, nativeToken, parachainId, targetAddress, amount, weight);
const {nonce} = await api.query.system.account(account.address);

transfer.signAndSend(keyPair, {nonce}, ({events, status}) => {
  handleExtrinsicCallback(api, {events, status})
});
```
## Send xcToken to token in Other network
Main idea: send xcToken to token to support chain token by [xTokens contract](https://github.com/PureStake/moonbeam/blob/master/precompiles/xtokens/Xtokens.sol):
```javascript
let targetParachain = bnToHex(2001).slice(2); // Bifrost Alphanet
targetParachain = '0x0000000000'.slice(0, -targetParachain.length) + targetParachain;
const accountHex = u8aToHex(decodeAddress("ettAyhG3qXgvc6tFbofxYzQSdXBMzXMehB1TmmSEQd8SxvJ"));
const targetAccount = accountHex.replace("0x", "0x01") + "00"
const destination = [1, [targetParachain, targetAccount]];
const weight = 4000000000;

console.log('Destination', JSON.stringify(destination))

// Encode transfer
const transferData = xTokenContract.methods.transfer(assetsAddress, amount, destination, weight).encodeABI()

// Estimate gas fee
const gasPrice = await web3.eth.getGasPrice()
console.log(gasPrice);


const transactionObject = {
  from: fromAcc.address,
  to: contractAddress,
  gasPrice: gasPrice,
  data: transferData
}
let gasLimit = await web3.eth.estimateGas(transactionObject)
if (gasLimit) {
  transactionObject.gas = gasLimit;
}


// Perform Transaction
var signed = await web3.eth.accounts.signTransaction(transactionObject, fromAcc.privateKey)

try {
  web3.eth.sendSignedTransaction(signed.rawTransaction)
    .on('transactionHash', function (hash) {
      console.log("transactionHash", hash);
    })
    .on('receipt', function (receipt) {
      console.log('receipt', receipt)
    })
} catch (e) {
  console.log(e.message);
}
```

**Comment by sokol142** [comment]
@lw-cdm @Quangdm-cdm Please check issues:

- [ ] Bug happens when select Destination Chain

![Image](https://user-images.githubusercontent.com/102292476/171328674-b415a4fa-b4d9-44ac-b26a-46da83a4e54d.png)

- [ ] Can't cancel the XCM Transfer screen when user select Inactivated Original Chain
- Expected: Displaying Cancel, Transfer button & Enable button Cancel

![Image](https://user-images.githubusercontent.com/102292476/171329026-e6415f2c-453a-498e-b7ae-412111f8f8be.png)

**Comment by sokol142** [comment]
Pls check XCM Transfer for "Bifrost" Chain
![image](https://user-images.githubusercontent.com/102292476/171779621-f36378ef-8a8f-4cf6-8491-d01a9b1c22b5.png)
