### ISSUE TITLE
Unified account - Fix bug related to the Swap feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3503]
**Describe the task**
Fix bug related to the Swap feature

- [x] Add "To" field when swap DOT (Polkadot) <-> ETH/USDC (Ethereum)

  ![Image](https://github.com/user-attachments/assets/d393cd42-0119-42fd-867b-f9104f1327b0)

- [x] Remove "From" field when stand on Single account

  ![Image](https://github.com/user-attachments/assets/2f9a5695-bc86-4ddb-89bf-a1a40a770e29)

- [x] Only show swap quote when input all information
  - Actual: When change swap pair then reset account but still show Swap quote

![Image](https://github.com/user-attachments/assets/63bcd922-927a-4f2e-a05b-f2de6fd8a03c)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/drive/folders/18__HpWFJDr4jvkBhCuWcXkHOdScveDVa?usp=drive_link

- [ ] All account mode, don't show From field
Actual : 


![Image](https://github.com/user-attachments/assets/470e3345-8274-4006-b1fd-00bcf5974890)


Expect : Show From field 
Link design : https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=25860-104598&t=q7Lujv2CvTLacCtI-4

- [ ] Don't show account name although account is in the wallet


![Image](https://github.com/user-attachments/assets/f9e31903-195e-4069-a3c7-ae87c151d146)

Expect : 


![Image](https://github.com/user-attachments/assets/3c000be2-7f40-465a-8f7b-11fe9772b9c0)

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/11cZnQDJIpTgTXvULJD-YOiQkM9erpLcK/view?usp=sharing

Please check:

- [ ] Do not show swap history


![Image](https://github.com/user-attachments/assets/b5fc4318-0ffc-4afd-928a-477e4011e192)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1EYCD87_fFS1wJSv92ciRZs5F3d9cfc0E/view?usp=sharing
Validation passed in case : 
- Results are updated in checklist : https://www.notion.so/subwallet/BA-QC-Document-57acd6b41e544bc19be3bc50cd6be605?p=d2e7d0eb5e044e81aaa19afce4435c43&pm=s
