### ISSUE TITLE
Unified account - Review and update connect dApp

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3504]
**Describe the task**
Review and update connect dApp

- [x] Connect dApp
- [x] Manage website access

**Comment by Sokol142196** [comment]
Some bugs related to dApp: https://www.figma.com/board/Rvcxn7edWpsUUKSK2eddEX/Nhung's-project?node-id=2798-3210&t=Fux3myLURZLs6szY-4

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/19tBmJCkxre4p2UWgSahe0fvjdbFvj4HV/view?usp=sharing

- [ ] Error page when perform sign message with walletconnect on substrate account type
![Image](https://github.com/user-attachments/assets/44178000-6147-4f0b-8bab-d7e2d13394b0)

- [ ] When connect dApp with solo account and unified account, choose all account type
Actual : Only connect to unified accounts
Expect : Connect to selected account types
![Image](https://github.com/user-attachments/assets/630e58bc-e87c-4e49-983c-52db2d50b753)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1NDSfPxa7m-FBHvpnwlrwnySqP9anK91D/view?usp=sharing

- [ ] Error when disconnect account
![Image](https://github.com/user-attachments/assets/9a671f45-90b8-46e0-8f29-b4bbc3e81ce8)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1S9wZLbxJzZOL5ZJi3QDXyzciza-tTpNQ/view?usp=drive_link
Validation passed in case : 
- Install/Update version
- Check UI connect account screen
![Image](https://github.com/user-attachments/assets/38ceb0ce-5f76-4923-87db-44f99301f046)
![Image](https://github.com/user-attachments/assets/2f3bd9db-9b15-4d14-82ba-2d26da194b6d)

- Check UI manage website screen
![Image](https://github.com/user-attachments/assets/e028a6c4-ecd7-43ed-8bb0-28df96ba69b3)

- Check UI on Transaction request screen
![Image](https://github.com/user-attachments/assets/eb1ca0e0-7249-412e-b221-797f1f9523d3)
- Check connect/disconnect with dApp

- Check perform sign message/sign transaction with unified account/solo account/ledger account/watch only account/qr signer account
- Check with Polkadot js 
![Image](https://github.com/user-attachments/assets/cf7a97e8-b945-467b-babd-f9c6b90b49f1)

- Check with EVM dApp : https://test-dapp-7vf9-git-wctest-thiendekacos-projects.vercel.app/

![Image](https://github.com/user-attachments/assets/473a7c2a-1f33-47c5-83c8-72867fd5c0f9)

- Check connect with walletconnect
![Image](https://github.com/user-attachments/assets/2813f692-f3ce-48bd-83c3-7f3501d547bc)

- Check Block/Forget/Disconnect with dApp
- Check connect with SubWallet webapp
![Image](https://github.com/user-attachments/assets/01a09717-47ce-4fc0-9167-e10ab6c71e8d)
