### ISSUE TITLE
Unified account - Add validate unique for Account Name

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3505]
**Describe the task**
Add validate unique for Account Name

**Comment by S2kael** [comment]
- [x] Auto-add prefix for duplicate account name
  - [x] JSON 
    - [x] Single account JSON file
    - [x] Multi-account JSON file
- [ ] Error when duplicate account name
  - [ ] Mnemonic
  - [ ] Private key
  - [ ] QR-signer
  - [ ] Ledger
  - [ ] Read-only

**Comment by nampc1** [comment]
Need to update UI logic

**Comment by ThaoNguyen998** [comment]
- [ ] Add "-" when auto-add suffix for duplicate account name

![Image](https://github.com/user-attachments/assets/a65802c1-eb1e-4db6-ac52-8b20e314b521)
