### ISSUE TITLE
Unified account - Fix bug related to Earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3506]
**Describe the task**
Fix bug related to Earning feature

- [x] Do not show earning position

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/open?id=11SrgJetpyNvxbqLVgjMJg5vOjmuu_384&usp=drive_fs

Please check issues:

- [ ] Show incorrect account list when stake more
Steps:
1. Switch to a specific account
2. Open the any earning position details screen
3. Click on Stake more button
4. On the Start earning screen then click on Select account field then observe the account displayed

Actual: Show all accounts on wallet
Expect: Autofill current account and disable Select account field


- [ ] Can't earn with Unified account
  - [ ] Start to earn: Show error message although account has enough balance to earn 

  ![Image](https://github.com/user-attachments/assets/b4edf9b9-19ff-4f45-bf5f-226fea32eb4a)


  - [ ] Stake more: Stake button is disable (click on Stake more button on the Position details screen)

  ![Image](https://github.com/user-attachments/assets/d52a27ae-7f3f-4d93-a898-12a1e05ee74d)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/11t8RVQwp-NH7r3sKj0IdcHsbZQUp-_ZD/view?usp=sharing

- [ ] UI bug on Select account field
Actual 


![Image](https://github.com/user-attachments/assets/3e1bf635-7845-4704-85b7-0aa78c0b7aec)

Expect : 


![Image](https://github.com/user-attachments/assets/cd1fdcc6-2fb7-4c60-b62c-8427be65487c)

- [ ] Don't show collator when Unstake (KMA) on All account mode


![Image](https://github.com/user-attachments/assets/f56f9580-d7d9-49f0-a801-8264f3aaae5a)

Expect : 

![Image](https://github.com/user-attachments/assets/9a80693a-51cb-48ad-9e35-dd3a1fe94c66)

- [ ] Stake button is disable on All account mode

![Image](https://github.com/user-attachments/assets/b66859a4-688c-471e-a7b5-124e2d7d959e)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/17nOk7rEN_BeJob0bjX6DhZR0R6uz79wB/view?usp=sharing

- [ ] Error display reward = 0


![Image](https://github.com/user-attachments/assets/1c86660b-d21f-4949-8bed-1374bbd8c23f)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/18ZN8BwJODbjDZY4d9PSeZLmOGhWubFjl/view?usp=sharing

- [ ] Re-check UI on modal Pool/Validator details
Actual : 


![Image](https://github.com/user-attachments/assets/276b577d-27f7-4a2a-b694-53a46de44db3)

Expect : 


![Image](https://github.com/user-attachments/assets/b5338fcc-bed4-4c44-8099-68d22bf7b366)

- [ ] Re-check UI on Earning position details screen


![Image](https://github.com/user-attachments/assets/15b3020d-1196-4e48-8842-912551be672f)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1wOe_wYe6BYezGizE2JB_dzWHJ5eZvH79/view?usp=drive_link
- Test result are updated at the link  : https://www.notion.so/subwallet/Unified-account-Checklist-Earning-b65f59fa1c15442aa746762a5c193fd9
