### ISSUE TITLE
Extension - Support Notification UI in app

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3507]
**Describe the task**
Support Notification in app
- BA doc: https://www.notion.so/subwallet/Notification-in-app-2a573872cb734b8e863bb90ea8153f8f?pvs=4
- Link design: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=26551-173688&t=ZTT9mKfC4SogHLxt-4

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/Qz25TgzP48aNmSB

- [ ] Hide the Search token button

  ![Image](https://github.com/user-attachments/assets/5314b749-1e88-4732-8da3-5759c5481086)

- [ ] Discuss mỏe: Alert when click on Mark read all?

  ![Image](https://github.com/user-attachments/assets/bf3d5087-08c9-48cf-a32c-c61e206a61af)

- [ ] Automatically enable notification
- [ ] UI bug

  ![Image](https://github.com/user-attachments/assets/68692d47-95d4-4d1e-aca4-0dba5006165e)

  ![Image](https://github.com/user-attachments/assets/eafea027-59ea-4248-945b-849685e290f3)

  ![Image](https://github.com/user-attachments/assets/3f4f34e3-b955-4cab-b1a4-0dbf5f39ac5a)


- [ ] Improve: When save setting then navigate to the Notification list screen
  - Actual: Still standing Notification settings
  - Expect: Navigate to the Notification list screen

**Comment by bluezdot** [comment]
@dungnguyen-art 

- [ ] Fix display Mark read/unread for detail notification item.

Actual: After changing status of one item => all item's status are changed on UI (all three tabs)
Expect: Only updated item changed.

**Comment by bluezdot** [comment]
@Quangdm-cdm 
- [ ] Fix notification detail model (Click read/unread and Click action).
- [ ] Fix Notification setting in General Setting.
- [ ] Handle params for click button save setup in Notification Setting screen.
- [ ] Discuss: Sort notification by time.

**Comment by bluezdot** [comment]
@Quangdm-cdm 
- [ ] Display notification count 
![image](https://github.com/user-attachments/assets/4e5e31cc-1adb-41fd-969b-a42e5f16c89e)

**Comment by bluezdot** [comment]
- [ ] Do not show notification when using unified account

**Comment by Sokol142196** [comment]
- [ ] Update content for Claim, Withdraw actions
  - Link content: https://www.notion.so/subwallet/SubWallet-Content-chi-ti-t-cho-t-ng-lo-i-Notification-d0c309c809f04a428c45c627132add5b?pvs=4

**Comment by bluezdot** [comment]
- [ ] Create claim avail bridge screen

**Comment by Quangdm-cdm** [comment]
@bluezdot please resolve Update content for Claim, Withdraw actions and Handle case remove account

**Comment by ThaoNguyen998** [comment]
- [ ] Update content Claim when bridge Avail
https://www.notion.so/subwallet/SubWallet-Content-chi-ti-t-cho-t-ng-lo-i-Notification-d0c309c809f04a428c45c627132add5b?pvs=4#f0570d5853a74b2c94f856c013b54573

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/Dkmre48xzQ4HMFP

- [ ] Duplicate noti Claim when Bridge Avail

  ![Image](https://github.com/user-attachments/assets/4cdf2fb9-cf72-4299-800c-3d256e25599e)

- [ ] Update content when bridge avail
- [ ] Error when Claim Avail

   ![Image](https://github.com/user-attachments/assets/b53fb221-6415-43e3-9cc8-274d00520c57)

**Comment by ThaoNguyen998** [comment]
@bluezdot 
Checklist for issue: https://www.notion.so/subwallet/Check-list-Notification-in-app-883111ce69dd4411b35b7c8ca5afb5ca?pvs=4

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/YasYyFtjBb2ksJD

- [ ] Re-check timein case edit time on static content
Actual: Still displays notifications according to the previously set time

   ![Image](https://github.com/user-attachments/assets/8e4437b6-52ae-4e4d-b5b2-00fc67c7de77)

Expect: Update new config time

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Update content: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=26551-173688&node-type=section&t=nzoaLdXaHF8pX9au-0
- [ ] Update UX in case turn off network

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/JWcNQ5o3M8TNdrc
Validation passed.

Checklist for issue: https://www.notion.so/subwallet/Check-list-Notification-in-app-883111ce69dd4411b35b7c8ca5afb5ca?pvs=4
