### ISSUE TITLE
add custom network but it show "Unable to connect to the provider"

### ISSUE THREAD

**Issue by kulame** [Koniverse/SubWallet-Extension#351]
**Describe the bug**
1 try to add  custom network
2 when i added a endpoint, it tells "Provider connected successfully"
3 but after 2 seconds, it tells "Unable to connect to the provider"

**Desktop (please complete the following information):**
 - OS: [ubuntu22.04]
 - Browser [firefox]

**Comment by NamPhamc99** [comment]
Can you provide the endpoint please ??

**Comment by kulame** [comment]
the porvider is my private substrate endpoint on intranet.
the substrate net use https://github.com/substrate-developer-hub/substrate-node-template

**Comment by NamPhamc99** [comment]
I'm not sure if this is a fully functional substrate chain, i have never tried with this, but let me try and get back to you, if you need further support, please join the discord server of Subwallet, i can help you with everything in detail. Thanks for trying our wallet
https://linktr.ee/subwallet.app

**Comment by hieudd** [comment]
Temporarily disable the Add Custom Network function
