### ISSUE TITLE
Checklist and Testing for Unified account: Earning, Swap...

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3511]
**Describe the task**
Checklist and Testing for Unified account: Create, Import...

- [x] Account details, derived account
- [x] Export account
- [x] Earning
- [x] Swap
- [x] ...

**Comment by haiyenvu23** [comment]
**Finished writing the checklist :** 
- Derived account : https://www.notion.so/subwallet/BA-QC-Document-57acd6b41e544bc19be3bc50cd6be605?p=cb94bfb37cd7434099a1364880c656d0&pm=s
- Export account : https://www.notion.so/subwallet/BA-QC-Document-57acd6b41e544bc19be3bc50cd6be605?p=4c2c130096b045949c526cd1febd8f05&pm=s
- Earning : https://www.notion.so/subwallet/BA-QC-Document-57acd6b41e544bc19be3bc50cd6be605?p=b65f59fa1c15442aa746762a5c193fd9&pm=s
- Swap : https://www.notion.so/subwallet/BA-QC-Document-57acd6b41e544bc19be3bc50cd6be605?p=d2e7d0eb5e044e81aaa19afce4435c43&pm=s

**Retesting the issue :** 
- #3727 
- #3728
