### ISSUE TITLE
[Unified-account] Add feature to switch WalletContract version for ton

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3512]
**Describe the task**
Add feature to switch WalletContract version for ton
- BA doc: 
  - https://www.notion.so/subwallet/C-u-h-nh-WalletContract-version-57626ba694d142dd885962590c3b139d?pvs=4
- Content: https://www.notion.so/subwallet/SubWallet-Chu-n-ho-content-in-app-c-a-t-nh-n-ng-Switch-WalletContract-version-06b49b4889f74bca8936538dbe506686?pvs=4#8c05f709b6e74b9881979ea100531fa5
  - Expect: Only show icon Setting contract version when view Address for TON token
- Link design: 
  - https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=26773-256094&t=dQAV7nOpozX0Rg3N-4
  - https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=26755-252103&t=dQAV7nOpozX0Rg3N-4

**Comment by nampc1** [comment]
Logic is updated, UI will follow

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1Rk-B6vJNVzs1WcDwL7TpP7DfIVQJ_hC1/view?usp=sharing

Please check issues:

- [ ] Do not update address after switch WalletContract version from Receive action
  To reproduce the behavior
  1. Switch to Unified/TON account
  2. Click on Receive
  3. On the QR code screen, click on Switch WalletContract version button
  4. On the Wallet version contract screen, switch to other version then hit Confirm
  5. Observe the address displayed

  Actual: Still show address according old version 
  - Then user click on Switch WalletContract version button again then show empty list
  ![Image](https://github.com/user-attachments/assets/ece43890-848c-490e-aa66-9ce0fa8ba273)

  Expect: Show address according new version 

- [ ] Incorrect wallet version contract address for TON testnet
  - Actual: Display address for TON mainnet although select TON testnet
    ![Image](https://github.com/user-attachments/assets/89d00ccb-d965-4c7a-b0ee-db75be663d57)

  - Expect: Displays the correct address of the selected network Show address for TON testnet

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1LQV5_2gLAT5uz6ICOOemXkl8nAHM_nG0/view?usp=sharing
Please re-check case 2 and 4
I still reproduce these cases

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1Dfr6KG58tM7m4GHbeZv7EOiuTMeAjO2K/view?usp=drive_link

Please check issues:

- [ ] An error occurs when click on Change wallet contract version with watch-only account in case Upgrade version from v1.2.29 to this build
  - I still reproduce this issue in case Upgrade version from v1.2.29 to this build
  - FYI: New install is OK

- [ ] Do not show selected symbol for current Wallet Address Version with Derived account
  - Expect: Mark as selected fo Current wallet address version
  ![Image](https://github.com/user-attachments/assets/51652443-20db-4c5c-8fda-cef0eaa362a7)

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1I043C3fEeeXHuuuuSawrQklFv32By64t/view?usp=sharing

Validation passed for cases:
- Verify for these bugs
- Check with TON account
  - Change address and version from account details
  - Change address and version from account details when click on Receive
  - Check address after change version
- Check with Unified account
  - Change address and version from account details
  - Change address and version from account details when click on Receive
  - Check version for Derived account
  - Check address after change version
- Check with TON watch-only account
- Check with Other account (Ethereum, Polkadot account)
