### ISSUE TITLE
Implement notification logic

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3515]
Refer to this issue https://github.com/Koniverse/SubWallet-Extension/issues/3507

**Comment by bluezdot** [comment]
vara native withdraw: kGioAwP3cNiFgUp1ZuoxAjCsi3zzFKDzBS3277ba21RbRicYj

**Comment by Sokol142196** [comment]
Improve continuing in https://github.com/Koniverse/SubWallet-Extension/issues/3507

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/JWcNQ5o3M8TNdrc
Validation passed.

Checklist for issue: https://www.notion.so/subwallet/Check-list-Notification-in-app-883111ce69dd4411b35b7c8ca5afb5ca?pvs=4
