### ISSUE TITLE
Extension - Re-check bug XCM

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3519]
**Describe the bug** 
Re-check bug XCM

**To re-produce the bug**
KSM: PAH -> KAH 

  ![Image](https://github.com/user-attachments/assets/c1d8b222-6c18-4370-b77f-22c6855a6990)

**Comment by bluezdot** [comment]
- [ ] KSM: PAH -> KAH: 0x0901041f0b040202090300a10f040001010050a1745137e2ffb5a785342d766f1302ec104d6f162579cea4fd54e84469d21904040201090300070010a5d4e80000000000

- [ ] KSM: KAH -> PAH:
0x0501041f08030202090200a10f030001010008610a2aa207b7554a2a30028f3b99edd3e8607842993545a40a93418ee507660304000100000700c817a8040000000000

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/Zq5fj9kMKE2CwQc
Validation passed.
- KSM: PAH -> KAH

  ![Image](https://github.com/user-attachments/assets/085b6cdc-0bc1-4a69-b6ea-2dadafe58eae)

- [ ] Re-check for other XCM channels
