### ISSUE TITLE
Stake Account displaying incorrect on the Staking action/Authorize Transaction screen

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#352]
Related: https://github.com/Koniverse/SubWallet-Extension/issues/42
**Description the bug**
Stake Account displaying incorrect on the Staking action/Authorize Transaction screen

**To Reproduce**
Pre-condition: The extension have multi account & Account A staked successfully
Steps:
1. Switch to Account B
2. Go to Staking screen & perform stake with Account B
3. On the Staking Action & Authorize transaction, check value of the "Staking with Account"

**Actual:** Staking with Account B but showing Account A
See file attachment above

![Image](https://user-images.githubusercontent.com/102292476/173817093-94415170-3389-4631-b554-8bd6fa540777.gif)

**Comment by NamPhamc99** [comment]
Due to passing props to child component. Resolved for this use case
