### ISSUE TITLE
Unified account - Update export/import UI

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3526]
Describe the task
Update export/import UI

- [x] Export UI
- [x] Fix bug show error message in case account existed
  - Actual: Show on Password field
  - Expect: Show on view 
  ![Image](https://github.com/user-attachments/assets/5f98d3f7-a3b8-42d5-9c33-f31f1296ba74)

- [x] Update flow when import JSON file (in case have account existed)
  - Flow: https://www.figma.com/board/Rvcxn7edWpsUUKSK2eddEX/Nhung's-project?node-id=2566-3803&t=moxSpKdRlm7FcUoH-4
  - Design for Account Preview screen: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=26844-750766&t=dQAV7nOpozX0Rg3N-4
  - Content for warning duplicate account name: https://www.notion.so/subwallet/Product-SubWallet-C-nh-b-o-v-advanced-address-setting-tr-ng-account-name-38f78f8a001047c49e843b9bbeed1121?pvs=4#16bac5e1c4b84f49831840977e10cdb2

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1A8Qd0AuAukcLomXHHGwnWsRksv7akJsF/view?usp=drive_link

- [ ] Update popup Duplicate account name:
  - Link content: https://www.notion.so/subwallet/Product-SubWallet-C-nh-b-o-v-advanced-address-setting-tr-ng-account-name-38f78f8a001047c49e843b9bbeed1121?pvs=4#16bac5e1c4b84f49831840977e10cdb2 
- [ ] Do not add suffix for account after user click Confirm on popup warning
- [ ] Update navigation when click on "Backup now" button on the Remind backup seed phrase 
  - Refer: Navigation logic on the SubWallet v1.2.22 (store version)

**Comment by haiyenvu23** [comment]
Version test :https://drive.google.com/file/d/1wOe_wYe6BYezGizE2JB_dzWHJ5eZvH79/view?usp=drive_link

- [ ] Can't export multi account 
![Image](https://github.com/user-attachments/assets/03d7cec6-b7bf-4add-8bbe-7f8c3ee48048)

- [ ] Update content for Import account screen
Link figma : https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=2200-57333&t=2pJL1x3Sqoh3nF1j-4
![Image](https://github.com/user-attachments/assets/e104dedb-3e88-4332-9d3b-11c0812e73f3)

- [ ] Update content for popup Duplicate account name
Link content : https://www.notion.so/subwallet/Product-SubWallet-C-nh-b-o-v-advanced-address-setting-tr-ng-account-name-38f78f8a001047c49e843b9bbeed1121?pvs=4#c2020d8c4250465d90b86ffd27357aed

- [ ] Add warning for case there is no valid account
![Image](https://github.com/user-attachments/assets/8407f9d2-8406-4295-85ca-6dae400e3d6a)
Link notion : https://www.notion.so/subwallet/SubWallet-Chu-n-ho-content-in-app-cho-t-nh-n-ng-Import-account-by-JSON-file-8b4b4806ade94a8188923eccf0bc1bff?pvs=4#435068a9fc8f45c08320b227f0fb8157
