### ISSUE TITLE
Unified account - Fix bug validating recipient address

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3528]
**Describe the task**
Fix bug validating recipient address

Flow: https://www.figma.com/board/ULes5pp2IUV04S9kGct58c/SubWallet-Flow?node-id=124-1110&t=wqgGVKNcMiNyc0t9-4

**Comment by Sokol142196** [comment]
@bluezdot please check more for this issue
- [ ] Allow enter an invalid address when toggle Advanced address detection is OFF
  - Actual: Pass validate and next to the Confirmation screen
  - Expect: Show error message (Incorrect address)

  ![Image](https://github.com/user-attachments/assets/585fe35e-a0bc-4e15-a6f0-98e9d40640d9)

**Comment by ThaoNguyen998** [comment]
@bluezdot please check more for this issue 

- [ ] Auto validate address in case switch account, change destination chain
  Actual: Auto validate
  Expect: Validate when click Transfer

**Comment by ThaoNguyen998** [comment]
Version test: 
Validation passed in these case
