### ISSUE TITLE
The transferable balance of the token on the Astar-EVM chain is incorrect on the Send Fund screen

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#353]
**Description the bug**

- [x] Transferable Balance of the ASTR, ARSW (Astar EVM) is incorrect on the Send Fund screen

**To reproduce**
Steps:
1. Open the extension
2. Go to Send Fund screen
3. Select ASTR (Astar EVM) token
4. Then observe the balance displaying

**Actual:** Transferable Balance of the ASTR (Astar EVM) is incorrect on the Send Fund screen (see file attachment below)
![Image](https://user-images.githubusercontent.com/102292476/174256598-3584ba1a-73f1-4509-8dde-55c1d7309c5c.png)

- [x] Kindly check with all tokens on the Astar-EVM chain

**Comment by sokol142** [comment]
Similar to tokens: ARSW, aUSD
Please check kindly check with all tokens on Astar-EVM chain
![image](https://user-images.githubusercontent.com/102292476/190942213-1ec7da83-a9d1-47de-889b-8d7d75199d27.png)

**Comment by NamPhamc99** [comment]
Cause:
Web3 automatically disconnects after a certain amount of time => Error subscribing balance

Note:
Cron has a mechanism to retry connection but it doesn't work on functions have already used the object before (in  subscription).

**Comment by sokol142** [comment]
Do not reproduce the behavior in the new UI version
