### ISSUE TITLE
Extension - Do not allow entering Amount without selecting an account in the Stake, Unstake screen

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3532]
**Describe the bug**
Do not allow entering Amount without selecting an account in the Stake, Unstake screen
- Refer to issue #1905

Actual : Can input Amount without selecting an account
![image](https://github.com/user-attachments/assets/a823ecc2-09b9-4e17-aabe-5104fa10afbc)

Expect : Do not allow entering Amount

**Comment by Sokol142196** [comment]
Don't fix => Close issue
