### ISSUE TITLE
Unified account - Implement advanced address detection

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3534]
Describe the task

- [x] Add the "Advance address detection" settings
<img width="184" alt="image" src="https://github.com/user-attachments/assets/acbab4ed-a0fc-4548-8a32-09f9467db351">

Expect:
- Only show this option when select token on Polkadot ecosystem
- Toggle = ON then automatically convert Substrate address to Network's address
- Save this setting until user change it

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/17nOk7rEN_BeJob0bjX6DhZR0R6uz79wB/view?usp=sharing

Validate for these cases
