### ISSUE TITLE
Unified account - Update address input component for NFT transfer

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3537]
- [x] Do not show Address book when click on Address book icon in the Send NFT screen

  ![Image](https://github.com/user-attachments/assets/952705a4-eaff-4e5e-a8ed-c1b4b3eff7bd)

**Comment by haiyenvu23** [comment]
Verison test : https://drive.google.com/file/d/1qFP4R02-DtyGw80NuHIW7vpCOFQoDz-k/view?usp=sharing
Validation passed : 


![Image](https://github.com/user-attachments/assets/bb7f48ae-88be-4599-a3ae-751e92e84800)

- Test results are updated in the check list : https://www.notion.so/subwallet/Unified-account-Checklist-Manage-NFT-854517fd7c114e5aacaa58778ba2dc9b

**Comment by Sokol142196** [comment]
@haiyenvu23 please re-test this issue

**Comment by haiyenvu23** [comment]
Verison test : https://drive.google.com/file/d/1qFP4R02-DtyGw80NuHIW7vpCOFQoDz-k/view?usp=sharing

- [ ] Update UX when suggestion have > 3 items


![Image](https://github.com/user-attachments/assets/835c8340-86ae-4526-aba5-3251a25d90a3)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/18ZN8BwJODbjDZY4d9PSeZLmOGhWubFjl/view?usp=sharing
Validation passed  : 
- Test results are updated at the link : https://www.notion.so/subwallet/Unified-account-Checklist-input-address-suggestion-af030a4906304c5fadc45949058da966?pvs=4
