### ISSUE TITLE
Unified account - Update UI for transaction history and confirmation screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3553]
**Describe the task**
Update UI for transaction history and confirmation screen

- [x] Transaction history: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=1309-391018&t=wr9sa68AlWUIiu7j-4
- [ ] Confirmation: Updating...

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/18ZN8BwJODbjDZY4d9PSeZLmOGhWubFjl/view?usp=sharing

- [ ] Update for Swap history
  - Actual: Do not show network

![Image](https://github.com/user-attachments/assets/0fc7ed2d-05f8-476e-8645-cfd35cd92a63)


  - Expect: 
    - Swap signle chain: Show network field
    - Swap cross chain: Show network according the screenshot 

![Image](https://github.com/user-attachments/assets/b7688ebd-b514-40ab-bf5e-f8fa474a1f22)

- [ ] Update address component on the Confirmation screen

![Image](https://github.com/user-attachments/assets/dbc18833-a293-4daa-8104-3c68ad39fe64)


  - Use component: https://www.figma.com/design/lsJoDNOy7hqT41tfiiAk1Z/SubWallet-UI-Base-1.0.1-(NEW)?node-id=8048-2721&t=JlJD8wUFoT5Dyrj6-4

- [ ] Update Approve token confirmation 

![Image](https://github.com/user-attachments/assets/b323df4d-241d-42c9-bddc-2df2644b6dad)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/18ZN8BwJODbjDZY4d9PSeZLmOGhWubFjl/view?usp=sharing

- [ ]  Re-check UI on modal Pool/Validator details 

Actual : 


![Image](https://github.com/user-attachments/assets/276b577d-27f7-4a2a-b694-53a46de44db3)

Expect : 


![Image](https://github.com/user-attachments/assets/b5338fcc-bed4-4c44-8099-68d22bf7b366)

- [ ]  Re-check UI on Earning position details screen


![Image](https://github.com/user-attachments/assets/15b3020d-1196-4e48-8842-912551be672f)

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1H9TKwdQsr8LhZyiHqrVJP7M6xa-SE-rE/view?usp=drive_link

- [ ] UI bug when account name is long 
![image](https://github.com/user-attachments/assets/22208814-9ad4-4e79-a7ff-e5a392e4b68c)

- [ ] Add max width for component 
  ![image](https://github.com/user-attachments/assets/d5995f85-f12f-48d0-816d-eb63a55c9551)

- [ ] Update title position
![image](https://github.com/user-attachments/assets/ce437ac7-2644-4bfa-a092-6231b72bd7a5)

- [ ] Update position when Sender/Recipient has only address 
  ![image](https://github.com/user-attachments/assets/c02ce3f7-df50-4b9f-91b7-027f7ce7811c)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1LYxMbOhk6Ds7ks2tTLLPqR2Pd0iihvxA/view?usp=drive_link

- [ ] Update font-size for address
Expect : Font-size = 12px
![Image](https://github.com/user-attachments/assets/2f1323ae-d055-47a8-89eb-2e9443e23411)

- [ ] UI bug on Confirmation screen 
![Image](https://github.com/user-attachments/assets/246a5f7c-a9f2-4592-beb2-7a6bf25dd9fb)

![Image](https://github.com/user-attachments/assets/86c71e49-8b23-45d2-8405-81a894fffce4)

- [ ] UI bug on Swap transaction screen 
![Image](https://github.com/user-attachments/assets/a684b788-892e-4b27-bd86-ab93eb585d26)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1lNr3LmXaG1DiwW8OfeotJxwm_60L081y/view?usp=drive_link
Validation passed in case : 
- On transaction history screen
- Send on chain
![Image](https://github.com/user-attachments/assets/da69f958-3253-44c2-8015-e03c998fe0be)

- Send cross chain 
![Image](https://github.com/user-attachments/assets/e34b539f-68c8-4fa0-9d0f-27f029aee565)

- Swap on chain 
![Image](https://github.com/user-attachments/assets/8dc7c689-7da0-4b76-8800-853d43fcd599)

- Swap cross chain 
![Image](https://github.com/user-attachments/assets/4504199e-66f6-45f7-bc9f-d6bcfa723e30)

- Stake
![Image](https://github.com/user-attachments/assets/e90cfd56-19dd-405d-a61a-ab38210067ed)

- Unstake
![Image](https://github.com/user-attachments/assets/0a0753e5-4588-41de-8afd-bb9f389d2603)

- Cancel unstake
![Image](https://github.com/user-attachments/assets/e9ced496-4fb6-45e9-90e1-31f09d49d089)

- Claim reward
![Image](https://github.com/user-attachments/assets/0d483d4b-a07f-48b6-9d31-13bb6a99db70)

- Show address for validator/pool
![Image](https://github.com/user-attachments/assets/d4ba479a-fdcc-479a-a596-98adeb4c126d)
![Image](https://github.com/user-attachments/assets/eb62b278-3caf-427b-b729-a26e769442dc)
