### ISSUE TITLE
WebApp - Add warning in case user earn for both nomination pool and direct

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3554]
Describe the task
Add warning in case user earn for both nomination pool and direct

- Condition and content: https://www.notion.so/subwallet/Th-ng-b-o-warning-unstake-v-confirmation-cho-c-c-user-ang-c-c-pool-v-direct-c44ca43088b047488fce087cdfa5565e?pvs=4#ebd2f25b59af41c69734746cecd4fb85
    - Header: "Continue staking?"
    - Message: "You're currently staking DOT via direct nomination. Due to Polkadot's upcoming changes, continuing to stake via nomination pool will lead to pool-staked funds being frozen (e.g., can't unstake, claim rewards)"

**Comment by haiyenvu23** [comment]
Version test : https://daf483b3.subwallet-webapp.pages.dev/transaction/earn

- [ ] Update UI for popup 
![Image](https://github.com/user-attachments/assets/bbfe33ce-e0a7-4b9c-935d-c93eaf8e6f03)
Expect : Adjust alignment

**Comment by haiyenvu23** [comment]
Version test : https://adc81fd9.subwallet-webapp.pages.dev/
Validation passed in case : 
- Test according to checklist : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#9762e2dcb8e4453c9f107a0af51c980f
- Responsive
- #3555 
![Image](https://github.com/user-attachments/assets/37453ec7-54d8-48d9-8606-cb2d79c1c81e)
![Image](https://github.com/user-attachments/assets/c4655a60-c9b4-4b19-b40f-e1cc108ffd7c)
- https://github.com/Koniverse/SubWallet-Extension/issues/3554
![Image](https://github.com/user-attachments/assets/ab200779-f76e-4607-b287-fee7ef3b50c0)
![Image](https://github.com/user-attachments/assets/93cddf12-5899-4ed8-805b-f7fa2ac818d5)
