### ISSUE TITLE
WebApp - Notice of need to unstake for users who are simultaneously staking for both Direct and Nomination Pool

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3555]
**Describe the task**
Notice of need to unstake for users who are simultaneously staking for both Direct and Nomination Pool

Content: https://www.notion.so/subwallet/Th-ng-b-o-warning-unstake-v-confirmation-cho-c-c-user-ang-c-c-pool-v-direct-c44ca43088b047488fce087cdfa5565e?pvs=4#2ff07c7fa9f5455eb84c02bbc7b095b0

**Comment by haiyenvu23** [comment]
Related to issue #3554
