### ISSUE TITLE
WebApp - Update UI when connecting to dApp

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3557]
**Describe the task**
Refer: 
- Format error when connecting to dApp (https://github.com/Koniverse/SubWallet-Extension/issues/3445)
- Update connector version (https://github.com/Koniverse/SubWallet-Extension/issues/3363)

Actual: Allow sign transaction, do not close popup confirmation

![Image](https://github.com/user-attachments/assets/6814f40c-04ce-44ac-b5a7-b06ea27f7d24)

**Comment by haiyenvu23** [comment]
Version test : https://27d358e6.subwallet-webapp.pages.dev/

- [ ] Update UI for some case : 
- [ ] Leave the recipient's address blank
Actual : 
![Image](https://github.com/user-attachments/assets/5f2e7b01-137a-40ff-a8ea-60d0db34f542)
Expect : 
![Image](https://github.com/user-attachments/assets/6524dce6-7a75-4da4-876c-da614a2fe598)

- [ ] Error when there are many requests sent 
![Image](https://github.com/user-attachments/assets/175a9b46-cf87-4284-a8c0-4bffa6f90e63)

**Comment by haiyenvu23** [comment]
Version test : https://4dfebece.subwallet-webapp.pages.dev/home/tokens
Link dApp : https://test-dapp-7vf9-git-wctest-thiendekacos-projects.vercel.app/
Validation passed in case  : 
- Check case validate according to checklist : https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#c4d244ebfc2049f4b99baa0bf2cc9c2a
- Check when perform Ping on WalletConnect
- Check perform sign message/sign transaction with dApp
- Update content for message in case validate when sign message
![Image](https://github.com/user-attachments/assets/6bb81d52-896f-439e-af7c-d877e356b048)
