### ISSUE TITLE
Support Ternoa NFT

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3559]
Document:
https://docs.ternoa.network/build/javascript

We'd like to show Ternoa NFTs from within SubWallet

**Comment by nampc1** [comment]
NFT transfer will be supported later

**Comment by tunghp2002** [comment]
5D22eU35tSELSMChp5bZJZRkkigFWNgh5U95o8gLX4DdmjyJ
Em gửi tài khoản test nhé ạ

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/6j5TXj5YTaKLLWX

- [ ] Do not show Collection 
Log: 
  
  ![image](https://github.com/user-attachments/assets/56533684-40a0-4676-b93b-1cf97b549106)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/y7Hd2zYKQQ75f94
Validation passed in case : 
- Install/Update version
- Show NFT
![Image](https://github.com/user-attachments/assets/f4beec2d-6cbe-4274-bad2-c12d780819ff)
- Send NFT
![Image](https://github.com/user-attachments/assets/d52b806d-4338-46b1-acae-df6c24985584)

- Check NFT infor
- Check search NFT name/ID/Collection name
- Check case turn ON/OFF network
- Check case reload extension
- Check again with other NFTs
