### ISSUE TITLE
Unified account - Update the latest code

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3565]
**Describe the task**
Update the latest code:

- [x] Update for issue https://github.com/Koniverse/SubWallet-Extension/pull/3464
- [x] Update for #3477, #3484
- [x] #2703

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1Dfr6KG58tM7m4GHbeZv7EOiuTMeAjO2K/view?usp=drive_link

- [ ] Validate network address on some screen
Actual : 
![Image](https://github.com/user-attachments/assets/5418546d-2950-43fe-bd5f-a6119fc0b57b)
![Image](https://github.com/user-attachments/assets/abb9327c-8259-4e4c-a62e-33b0de7c2186)

- [ ] Update content for https://github.com/Koniverse/SubWallet-Extension/issues/3477, https://github.com/Koniverse/SubWallet-Extension/issues/3484
Actual : 
![Image](https://github.com/user-attachments/assets/337dd7bd-4b61-443a-9840-431d184caa93)
![Image](https://github.com/user-attachments/assets/0d69bebf-b311-4f9c-a56e-c3550d7a3752)

Expect : https://www.notion.so/subwallet/Th-ng-b-o-warning-unstake-v-confirmation-cho-c-c-user-ang-c-c-pool-v-direct-c44ca43088b047488fce087cdfa5565e#2ff07c7fa9f5455eb84c02bbc7b095b0

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1I043C3fEeeXHuuuuSawrQklFv32By64t/view?usp=sharing
Validation passed in case : 
- Install/Update version
- Check all cases with updated lastest code
