### ISSUE TITLE
Improve EVM DApp interface

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#357]
This issue is a continuation of #235 which delivers the basic feature of the EVM provider for DApp to integrate with SubWallet.

In this issue, we need to improve the EVM provider to support more features or create a better UI.

## Integrate with basic web3 library wallet connector like web3-react
- [x] https://github.com/NoahZinsmeister/web3-react => resolve with [@subwallet/web3-react-subwallet-connector-v6](https://www.npmjs.com/package/@subwallet/web3-react-subwallet-connector-v6)
### New way to use chainId and account in EVM Provider:
- [x] ChainID depends on the current network. It will respond to previous switch network requests or the first EVM network in the list
- [x] Account will return the current account if it is in the allowed list or all allowed accounts if the current account is not in allow list

## Improvement
- [x] Add import EVM token
- [x] Add features wallet_watchAssets like MetaMask
- [x] Add support Shibuya Testnet

### UX/UI
- #393
- [x] Decode sign message typed with better UI:
  - ![image](https://user-images.githubusercontent.com/11567273/177750675-c65ae2bf-6e32-4552-8470-b5f22bcd10dd.png)
- [x] #398

### Performance
- #433

**Comment by hieudd** [comment]
@saltict pls check this for Public-private key encryption
https://docs.metamask.io/guide/rpc-api.html#eth-decrypt
https://docs.metamask.io/guide/rpc-api.html#eth-getencryptionpublickey
