### ISSUE TITLE
Extension - Do not show lock balance in case account have KSM nomination pool 

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3579]
**Describe the bug**
Fix bug do not show lock balance in case account have nomination pool

**To reproduce the bug**
Check with account: 5EjzDc2Y7aVePjW8BgbtNx29pEYHaa18SHqKmcvtDT4ygUvQ

![Image](https://github.com/user-attachments/assets/e23bfa57-c708-47dc-97b9-043e1688729e)

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/9obwNJzKgwPBBcf

Please check the issues:

- [ ] Do not show balance for parachain![Image](https://github.com/user-attachments/assets/6c39c186-019a-4286-a369-776433420f02)
![Image](https://github.com/user-attachments/assets/fcf7d0ca-501b-4d2f-9103-6a891a2d713c)

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/dqGQoX3o5BQ3bTr

Validation passed in cases:
- Show balance and earning position for KSM in cases:
  - Only has KSM direct
    ![Image](https://github.com/user-attachments/assets/691ccb11-dd07-476a-8fac-e792f1c5f4cb)

  - Only has KSM nomination pool
    ![Image](https://github.com/user-attachments/assets/9f285bef-4b42-4423-952f-8919c966db29)

  - Both KSM direct & nomination pool
    ![Image](https://github.com/user-attachments/assets/d1641a6c-e00b-4634-95ec-abe4c2777c01)

- Re-check:
   - Show balance for parachain, solochain
     ![Image](https://github.com/user-attachments/assets/16dc28c7-487b-492b-9abe-dd75d4b83149)

   - Transferable balance for KSM, DOT, ...
     ![Image](https://github.com/user-attachments/assets/7402f2ae-76f0-4923-ba42-bc31376a1845)

   - Network transfer balance has been updated for WND
     ![Image](https://github.com/user-attachments/assets/77ce8eee-5772-49dd-9c65-e48343b0dc49)
