### ISSUE TITLE
Unified account - Improve auto-add suffix for duplicate account name (SubWallet add suffix) in case upgrade version

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3581]
**Describe the task**

- [x] Improve logic auto-add suffix for duplicate account name (SubWallet add suffix) in case upgrade version

- [x] Add popup add account name when import QR code

UI implement on issue #3505

**Comment by haiyenvu23** [comment]
Related to issue #3593

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1I043C3fEeeXHuuuuSawrQklFv32By64t/view?usp=sharing

- [ ] In case update version , there are no duplicate accounts in the wallet
Actual : Show popup Duplicate account name
![image](https://github.com/user-attachments/assets/0aac0978-af9d-4483-a2cf-ac84cdba0c07)

Expect : Don't show popup 


- [ ] In case existed account
Actual : Display old account name
Expect : Display new account name 
![Image](https://github.com/user-attachments/assets/d360dc00-24f2-4e29-9eff-fe6961f43ab0)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1fi5nD20ZM4g8ooecrToAqBu0CGoh8TEv/view?usp=sharing
Validation passed in case : 
- Install/Update version 
- In case existed account => Show new account name in list
- Add popup add account name when import QR code

![Image](https://github.com/user-attachments/assets/dd863e50-cccd-42a8-912c-22b4f37fa68b)
