### ISSUE TITLE
Unified account - Some UI bugs for Send TON

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3583]
**Describe the task**
- [x] Hide this alert warning in case send to bounceable address

   ![Image](https://github.com/user-attachments/assets/faf65a5b-70c6-42d1-b9b8-c09c1215d464)

- [x] Format address on the Confirmation screen and History
  - Expect: Display the correct address entered by the user
 
  ![Image](https://github.com/user-attachments/assets/2dcbd9cd-7b33-4168-8265-1c6006cff7dd)

- [x] Add validate address according network for Recipient 
-  Don't show avatar for account when send TON  token => Related to issue #3667
![Image](https://github.com/user-attachments/assets/b5435cd9-5b73-47ab-b16e-d45f5387166b)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1BJtnGjUl6fA-lHWRKMNuKEGjAQdY2l5b/view?usp=sharing

- [ ] Don't show popup Pay attention when perform transfer max in case send to TON bounceble address
![Image](https://github.com/user-attachments/assets/9b95f2f6-163d-4c71-86f7-21317593602c)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1Ul4kenP_XqsQnbKHrG9xn8WSuaugSHLz/view?usp=sharing
Validation passed in case : 
- Install/Update version
- UX when input Send to : Bounceble address ( inactive)
![Image](https://github.com/user-attachments/assets/c74e856e-2e9e-4eae-beaf-ae77da931815)
- UX when input Send to : Bounceble address ( active ) 
![Image](https://github.com/user-attachments/assets/baea8034-f172-419c-8e0a-468d6d21cef1)
- Re-check when perform : send token, send NFT, swap, stake ... with unified account, solo account, QR account, ledger account
