### ISSUE TITLE
Avail Space - Update the latest code v1.2.28

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3584]
**Describe the task**
Update the latest code v1.2.27, v1.2.28

**Comment by haiyenvu23** [comment]
Version test : https://webapp-dev.avail-space.pages.dev/accounts/connect-ledger

- [ ] Update content on Connect ledger screen 
Actual : 
 ![Image](https://github.com/user-attachments/assets/66ab412c-6bd8-437c-a280-7af0baad0b85)
Expect : " Connect and unlock your Ledger, then open the selected network on your Ledger"
