### ISSUE TITLE
Unified account - Bug transfer TON is failed

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3589]
**Describe the task**
Bug transfer TON is failed

- [x] Case 1: Transaction is failed when. transfer max with inactive account: https://testnet.tonviewer.com/0QCLQG7k6kiPDpdue7-BsbEMSYEOf4CXs6skgHi6AArqhLV6
Steps:
1. From account A Send TON to account B (account B is inactive account)
2. After successful transfer, switch to account B
3. Perform Max transfer on account B

Actual: Transaction failed, check then data runs continuously until the balance is deducted
Expect: Transfer successfull

------
- [ ] Case 2: Sometimes the transaction is failed

 ![Image](https://github.com/user-attachments/assets/a3059477-e426-4f48-8274-6b6e7187e6d6)

**Comment by bluezdot** [comment]
Case 1:
- Affected by `contract deploy` event. It takes more fee than usual transfer

- Try some rcm: https://github.com/ton-org/ton/issues/23#issuecomment-1963723559

**Comment by bluezdot** [comment]
Solution for transfer all:

- [ ] Improve estimate fee value:
- [ ] Improve transfer all action:
- Actual: Manually calculate the maximum transfer amount and set it to the transaction amount (this might not exactly transfer all because the fee cannot estimate exactly 100%).
- Expect: Transfer all remaining balance

**Comment by bluezdot** [comment]
https://docs.ton.org/develop/smart-contracts/messages#message-modes

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1LQV5_2gLAT5uz6ICOOemXkl8nAHM_nG0/view?usp=sharing

Validation passed in cases:
- Verify passed for Case 1
- Transfer TON with bounceable account + account active
- Transfer TON with non-bounceable account + account active
- Transfer TON with bounceable account + account inactive
- Transfer TON with non-bounceable account + account inactive
- Transfer all
- Transfer all with non-bounceable and inactive account: **`waiting check RPC to verify`**

Can't reproduce case 2 => Continuing follow-up Case 2

**Comment by Sokol142196** [comment]
Will resolve in https://github.com/Koniverse/SubWallet-Extension/issues/3698
