### ISSUE TITLE
Extension - Fix bug display wrong APY for Polkadot staking option

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#3601]
*Describe task
- Need to fix display wrong earning APY

https://github.com/user-attachments/assets/edfeab14-741f-40f7-b877-9d4bd8bb05db

**Comment by bluezdot** [comment]
- Remove APY liquid staking DOT (Interlay)
- Remove APY liquid staking DOT (Parallel)

**Comment by bluezdot** [comment]
Account has liquid staking dot (interlay): 5CFvKXryR5EEvSGuphjWfdHHbJWHqMfpBGcsjosefCuoWbUA

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/ioEQLiw9zmoP5pF

- [ ] Still displays incorrect APY for Polkadot staking in case

  ![Image](https://github.com/user-attachments/assets/ae59bc5a-9858-43fb-a911-114be45745e1)

**Comment by ThaoNguyen998** [comment]
Version test:  http://14.224.129.242:8900/s/XiZRH5yZEa2oxAo
Validation passed.
- Install/ Upgrade version
- Update APY: 
  - Current account

    ![Image](https://github.com/user-attachments/assets/1a2777df-7e13-4ab2-a095-1d5bf91ebe92)

  - All account 
  
    ![Image](https://github.com/user-attachments/assets/21f55251-69ce-4019-8601-cf9327772da6)

- Re-check APY for KSM, VARA, MANTA,...
- Re-check APY validator
