### ISSUE TITLE
Unified account - Update content

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3604]
**Describe the task**
- [x] Update message for Recipient field when transfer
Content: https://www.notion.so/subwallet/SubWallet-Chu-n-ho-c-c-message-l-i-li-n-quan-n-t-nh-n-ng-Transfer-0751cf27f85e4d42b8f0a4a827863b43?pvs=4#1f55cfb4d5914a2fb113bf1aeaa6eeb8

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1Rk-B6vJNVzs1WcDwL7TpP7DfIVQJ_hC1/view?usp=sharing
Validation passed in case : 
- Install/Update version
- Check with normal account, QR account, ledger account 
- Check on Send token, Send NFT, Swap features
- Test result are updated at the link : https://www.notion.so/subwallet/SubWallet-Chu-n-ho-c-c-message-l-i-li-n-quan-n-t-nh-n-ng-Transfer-0751cf27f85e4d42b8f0a4a827863b43?pvs=4#bf95e8b01ed44ef890220e429f8cbb2a
