### ISSUE TITLE
Extension - Do not show NFT Moonbeam

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3609]
**Describe the bug**
Do not show NFT Moonbeam
- Check with NFT contract: 0xeCD89793f4B35d2F5B8F18fEE2AB1896f1aa1896
Account: 0x4c9D5Baf7d5AC03694986a1FB6e32A4F14f3A793

- LFD Rising Rhythm - contract: 0x8f6659a4aD50242b23B315dC62ACE06D40EC8F31
Account: 0x3F787930F827348B31056f594A55727a0D13BB39

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/3wngeoS87aqLySn

- [ ] Change the way messages are displayed
Actual : Show tooltip on Contract address field
![Image](https://github.com/user-attachments/assets/6496e45c-5a4a-4503-9f22-036f83847861)
Expect : Show toast message when click button Import

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/c6f8jFp5XFzKoJd

- [ ] Update UI for message
Actual : 
![Image](https://github.com/user-attachments/assets/d4d0c8a0-1da3-4dc3-a654-24262365cc82)
Expect : Displays a UI similar to the message below
![Image](https://github.com/user-attachments/assets/a47e0b0c-bdc5-4448-aec4-ba0c1913f4af)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/AjNSA9Mf4e86AKK
Validation passed in case : 
- Install/Update version
- Show toast when import NFT don't have " tokenOfOwnerByIndex "
![Image](https://github.com/user-attachments/assets/a4619e8c-1cab-437e-91b5-df186873938e)
- Check case validate when input contract address
- Re-check import, remove NFT, send NFT
