### ISSUE TITLE
Unified account - Support save contact for TON address

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3610]
**Describe the task**
Support save contact for TON address

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/16RX4l9iQB0tOQcPVCaRVkQ0489lIQlMt/view?usp=sharing

- [ ] Don't show avatar for TON  address on Manage address book screen
![Image](https://github.com/user-attachments/assets/254d80cf-4a8c-4621-b432-cab5e5bc5df9)

- [ ] Don't show avatar for recent address on Address book screen
![Image](https://github.com/user-attachments/assets/e46d71ed-3ac7-4e6d-894a-e5b835079dde)
