### ISSUE TITLE
FIx bug not showing balance of VFT tokens

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3612]
Token contract: 0xbbf2fe1adf769b4a44fa44a7e2361e83e7819d62260393823e8657f2be4f1fc7
Address: 5GRgwRnEq1rxrLwom8LnPCyfX7ewE55mJMNDJ9K9FuT2Qsrd

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/xmk4B7xifRqRJKL
Validation passed in case : 
- Install/Update version
- Check show balance, send token with VFT token
![Image](https://github.com/user-attachments/assets/610d2b23-0e06-412e-986e-3bb236bab6b2)
![Image](https://github.com/user-attachments/assets/e880574a-1fb6-4493-8235-d34c5198f7bc)
![Image](https://github.com/user-attachments/assets/af614245-49ec-4c3d-be0e-f90681566676)
![Image](https://github.com/user-attachments/assets/6babfa46-7bda-400c-9c80-9bea34286197)
