### ISSUE TITLE
Extension - Re-calculate max transferable for XCM native token

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3617]
**Describe the task**
Re-check XCM max DOT: PAH <--> DOT
Actual: Lost ED after successful XCM max
Check with transaction: 
- https://polkadot.subscan.io/xcm_message/polkadot-cb580886f32c2e4de0c9d7ed51f62f0c4b17e367
- https://polkadot.subscan.io/extrinsic/0x493b3f87e08fa9ef81cda4061828fa2e3af671e5ff2eb6b08e445baea8a88626

**Comment by nampc1** [comment]
Related: https://github.com/Koniverse/SubWallet-Extension/issues/2792

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/QADPTQpfQr8bNGt

- [ ] Re-check XCM max PAH -> DOT
  Actual: Transaction fail
  - DOT: https://assethub-polkadot.subscan.io/extrinsic/0x82b8976df32fe634fa45b8e75afe7c5f57e79c2611e0315fac9c93361bd84a5b
  - USDT: https://assethub-polkadot.subscan.io/extrinsic/0x29e7cfa0072c88e3d4873b19371e14d43b605f356fb42beba356ad90ff2021ce

**Comment by bluezdot** [comment]
@ThaoNguyen998 The estimate fee is not good enough to handle case XCM from chain with small ED. The extrinsic will be failed and take a small fee in this case.
Need to continue researching the xcm fee to completely solve the Xcm max problem.

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/QADPTQpfQr8bNGt
Validation passed.
Checklist for issue: https://konistudio-my.sharepoint.com/:x:/g/personal/nhungphung_koni_studio/EZIxo_b6IsxNoLfQsa3YUlEBFy_8-n3XMAJkrDruMacr_w?rtime=k9Hwe1zY3Eg&nav=MTBfezg3MDVlZTZiLTE2NzUtNDlkZi05ODdmLTM3ODk5NWFjNjg1MX1fe0YxMzdBQUJBLTg0MTYtNDUxQy05OEY0LTkwREVBN0MxQTgwOX0
