### ISSUE TITLE
Add swap pairs on Chainflip

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3633]
Add pairs from all EVM chains supported on Chainflip
https://swap.chainflip.io/

**Comment by Sokol142196** [comment]
Link build to test: https://drive.google.com/file/d/1CyLQBwfwci0RWL-tGzg6PH3MM79PHOR_/view?usp=sharing

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1SQg9XWa_k5MaGdWhjVG6fGnbXOvLknKR/view?usp=sharing

- [ ] Error when swap 
  ![image](https://github.com/user-attachments/assets/02897de5-b469-44ae-ab5a-7ce8d0a342cf)
  ![image](https://github.com/user-attachments/assets/049bb83f-d91f-4044-aecc-5f61b1ec0f58)

- [ ] Error occurs when swap from DOT to new token (FLIP, Arbitrum tokens
  ![image](https://github.com/user-attachments/assets/c2e4c708-3d2b-4509-b15e-0006b7205ea2)

- [ ] Error occurs when swap from FLIP 
![image](https://github.com/user-attachments/assets/0e50533e-6ca8-4c96-af14-d8bdde67d9c1)

- [ ] Error occurs when swap from Arbitrum
   ![image](https://github.com/user-attachments/assets/b9a3e45b-4723-4b94-ac50-757ce78ff8e1)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/aoQ8HpY7YSkPp97
Validation passed.
- Check validate
- Check swap information
- Check swap (approve step)
- Checkpoint swap pair for other provider
