### ISSUE TITLE
Extension - Update default slippage for ChainFlip

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3634]
**Describe the task**
Update default slippage for ChainFlip
- Actual: Slippage = 0 %
- Expect: Slippage = 2%

**Comment by Sokol142196** [comment]
- [ ] Re-check Min received when apply slippage
- Actual: Do not apply Slippage to calculated the "Min received"
- Expect: Re-calculate the "Min received" with slippage

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/B9AZiDRT9e2komg
Validation passed in case : 
- Install/update version
- Update min receive with slippage 2% when perform swap chainflip
![Image](https://github.com/user-attachments/assets/67bae469-02f2-4ff5-b737-e5cdbd31d313)
- Re-check with other swap pairs
