### ISSUE TITLE
Block action online

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3635]
We want to block actions on wallet in case of some emergency outage. Users can still see data and operate normally as usual, but upon tx submission, the action may get blocked by wallet

**Comment by bluezdot** [comment]
There're 2 types block action
- [ ] Block a feature on a chain
- [ ] Block a specific action

**Comment by bluezdot** [comment]
View current blocked action:
https://github.com/Koniverse/SubWallet-Static-Content/blob/main/data/blocked-actions-features/preview.json

View full format for blocked action:
https://github.com/Koniverse/SubWallet-Static-Content/blob/main/data/blocked-actions-features/format.json

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/XK9Sg75Q9TDyQFA

- [ ] Update content: https://www.notion.so/subwallet/SubWallet-Th-ng-i-p-trong-tr-ng-h-p-t-nh-n-ng-tr-n-v-ang-block-t-m-th-i-e2ebb7ae79144f9481e885017c256673?pvs=4#97f3055efab74438adef5d694b02be1a

 ![Image](https://github.com/user-attachments/assets/2cf67dc0-2032-43c8-b89c-fa6f47b280a1)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/MiBHHmaADsffPCY
Validation passed
- Transfer/ Transfer XCM
- Send NFT
- Swap
Check list for issue: https://www.notion.so/subwallet/Checklist-block-actions-Issue-3635-272383eca2f940bda3702a3aea2ea4a5?pvs=4

----
Improve on issue: #3678
