### ISSUE TITLE
Allow importing assets on Asset Hub

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3636]
Allow user to input assetId and import token on Asset hub

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/pxRt9YN3B667CBg

- [ ] Don't reset data when change network
![1122](https://github.com/user-attachments/assets/c1da5426-88f5-4bc5-b47b-dbd6b6883418)

Expect : Reset data when change network

- [ ] Don't reset data when input invalid AssetID
![image](https://github.com/user-attachments/assets/4291743c-1ea9-4491-9311-f8e218a890a1)
Re-proceduce : 
1. Input valid AssetID
2. Input invalid AssetID
3. Observe the screen
Expect : Reset data when input invalid AssetID

- [ ] Update text "AsssetId" -> "Asset ID"
![image](https://github.com/user-attachments/assets/8b6e88ed-888d-463a-9df0-b10a80dff234)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/HpgKfRAYxokjAaE
Validation passed in case : 
- Install/Update version 
- Import token 
![1122](https://github.com/user-attachments/assets/b0e0d8e0-02ff-49b9-84de-f558b9d2bb3d)

- Check show balance with custom token 
![image](https://github.com/user-attachments/assets/aed5c149-480e-4962-ab4c-0900ff7603ef)

- Check remove token
- Check edit token
- Check send custom token 
- Re-check import of other tokens
