### ISSUE TITLE
Extension - Do not show earning position for StellaSwap

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3647]
**Describe the bug**
Do not show earning position for StellaSwap

**To Reproduce**
1. Attach account has earning for StellaSwap (has stDOT balance: 0x40a207109cf531024B55010A1e760199Df0d3a13, 0xBff5935E4C834f2cbE0826C67382dA7AA0135920)
2. Go to the Earning tab
3. Observe the earning position displayed

**Actual:**
Do not show earning position
**Screenshots**
![image](https://github.com/user-attachments/assets/ca75604e-ce13-4f68-8e2d-55d143c680d9)

**Expected behavior**

**Comment by haiyenvu23** [comment]
Version test: http://14.224.129.242:8900/s/G7bYX4S4J5ELkoS
Validation passed in case : 
- Install/Update version
- Show earning position for StellaSwap
![Image](https://github.com/user-attachments/assets/66382cbd-ccb8-4696-ac0b-ad0a9d896ef7)
- Re-check perform Stake, unstake
