### ISSUE TITLE
Unified account - Improve UX on Send fund screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3649]
**Describe the task**
Improve UX on Send fund screen

- [x] Update component for "From" field according design
  - Notes: Update for screens: 
    - [x] Send fund
    - [x] Swap
    - [x] Buy
    - [x] Earning

- [x] Update Transfer Max when changing Destination chain
  - Actual: Still show button Transfer all and old maximum amount according destination chain
  - Expect: Update Transfer Max when changing Destination chain

- [x] UX when selecting an account in Address Book and changing the Destination String (NOT enabling advanced address detection configuration)
  - Actual: Show error message, display Account Name (Address) in old string => User must select again in address book to get correct address
  - Expect: Reset "To" when changing Destination chain

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/16RX4l9iQB0tOQcPVCaRVkQ0489lIQlMt/view?usp=sharing

- [ ] Update color for text " Select account on From field 

Actual : 
![Image](https://github.com/user-attachments/assets/a7cc6d84-0b8b-403d-ae25-6f81b612c9f4)

Expect : 
![Image](https://github.com/user-attachments/assets/884e9bd0-fc99-4d82-b29e-1fb1b0a908f4)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1NDSfPxa7m-FBHvpnwlrwnySqP9anK91D/view?usp=sharing
Validation passed in case : 
- Install/Update version 
- Update component for "From" field according design

![Image](https://github.com/user-attachments/assets/e6a685a8-e27d-4c69-85cf-cf0fd296ba9a)
![Image](https://github.com/user-attachments/assets/70c28489-3927-4253-9068-b3ae1b4d9a9a)
![Image](https://github.com/user-attachments/assets/08713ecd-4c25-4948-b205-f53f16e18bdd)
![Image](https://github.com/user-attachments/assets/e802bea9-881e-4693-9c10-b509ea1bd3f0)
- Update Transfer Max when changing Destination chain
- UX when selecting an account in Address Book and changing the Destination String 
![Image](https://github.com/user-attachments/assets/e00df35f-96ca-4301-a480-7c8e70d06e5b)
