### ISSUE TITLE
Add swap pairs on Hydration

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3651]
Support all swap pairs between these tokens:
DOT, 2-Pool (USDT- USDC), 2-Pool (iBTC-WBTC), vDOT, USDT, ASTR, CFG, GLMR, 4-Pool, WETH, HDX, PHA, KILT, BNC, CRU, INTR, vASTR, ZTG, WUD, MYTH, DED, WIFD,  SUB

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1Oa1NEo1COFmYigNcVo3bltIioGUq87vC/view?usp=sharing

Please check issue:

- [ ] Update logo token for 2-Pool (USDC-USDT)
- [ ] Fix UI bug when select 4-Pool 
  ![Image](https://github.com/user-attachments/assets/1c90eda5-56d5-47ef-86c7-3276dd5a3ae0)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/aoQ8HpY7YSkPp97
Validation passed.
- Checkpoint with token: 
  - HDX -> 2-Pool: https://hydration.subscan.io/extrinsic/0x72f294af072c4adba499d9a613ff6b8b60cd9c5a068465517661990ae94574fd
  - ZTG -> KILT: https://hydration.subscan.io/extrinsic/0xc4cb6343e7a094b795820f0db80de1cfabaf40823f0f16c1034e54303785fea8
  - CRU -> 4-Pool: https://hydration.subscan.io/extrinsic/0x2827bc6055c16cff36b78036f2ae7a14e3822079a19a1bdd5fa44c9e58d42685
  - CFG -> WETH: https://hydration.subscan.io/extrinsic/0x1d486dce7206dfff932128078c25c7b056e3bfbd5e135c6bf6ea8786c482ea8e
- Check all validate swap
