### ISSUE TITLE
Review API to track TON tx history

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3698]

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/17UqeP0McZLXsG7je-6IqJ1kfQSl1hV4X/view?usp=drive_link

Please check issues:

- [ ] Transfer with wallet address version different v4
- [ ] Show incorrect balance
  - Check with address UQA0YtsSSNrDbGsvUoFPEE02b9SSUKqio9CGPedtkKHqf0n, EQAYqo4u7VF0fa4DPAebk4g9lBytj2VFny7pzXR0trjtXQaO, UQAj-peZGPH-cC25EAv4Q-h8cBXszTmkch6ba6wXC8BM40qt
- [ ] Re-check get balance to send

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1EEs3BlI2BDDEYAo3-LPgDIos-UmBOI9w/view?usp=sharing

Validation passed for case transfer with wallet address version different v4
- Check case transfer native token with v4: https://testnet.tonviewer.com/0QBpcvmd6Nu74WPYsdsVJ3xINgtZI-RG4GTf4fFKqKUAceFl
- Check case transfer local token with v4
- Check case transfer native token with v5: https://testnet.tonviewer.com/0QBIq1jLD_afIZTDs3hVe01xySrNWzhcfAnKoD-3UNJjWVkA
- Check case transfer local token with v5
- Check case transfer native token with v3r2: https://testnet.tonviewer.com/0QAJxWtWu2pWCg9SjqzlnpHEzIUCSjYsFyRuEgjHuxstR06Y
- Check case transfer local token with v3r2
- Check case transfer native token with v3r1: https://testnet.tonviewer.com/0QDROfQlIX4QRfEojc3RLltdZIVUmgoRjCbTY7OPDSmhkosP
- Check case transfer local token with v3r1
- Re-check validate (network, bounceable testnet)

Waiting RPC to check balance on some cases

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1tCRr4iA29PRv5CX1UOtTdU_0nGfhFl3K/view?usp=sharing

Validation passed in cases:
- Send TON (testnet) 
  - Notes: Check with all walletcontract version (v4, v5, v3r1, v3r2)
- Show balance for TON (testnet + mainnet)
  ![image](https://github.com/user-attachments/assets/16b36023-7bf8-456d-9378-57eb30cf5009)
