### ISSUE TITLE
Unified account - Improve derive account feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3704]
**Describe the task**
Improve derive account feature:

- [x] Auto increase index on default derivation path when detecting have account existed (Check with Polkadot account and upgrade version)
  ![Image](https://github.com/user-attachments/assets/4b808105-5ddf-41be-9acc-a57d22ed3b14)

**Comment by haiyenvu23** [comment]
Related to issue #3751
