### ISSUE TITLE
Unified account - Update UX when click on "dApp connection" icon

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3707]
**Describe the task**

- [x] Update UX when click on "dApp connection" icon
  - Actual : Show accounts of different types when not connected to it
    ![image](https://github.com/user-attachments/assets/cfd45c36-5a0a-46db-8495-c882a84a36ed)
  - Expect : Hide accounts of different types when not connected to it

- [x] UI bug when account name is long
  ![image](https://github.com/user-attachments/assets/26b54724-db37-458d-a11b-8fd3f999179d)

- [x] Re-check status connect and number of connected accounts/number of connectable accounts
- [x] The number of account on "All accounts" show is incorrect
  - Actual: Show all account
    ![Image](https://github.com/user-attachments/assets/b10cc054-1b2f-4df8-9c43-5e434ef934b8)

  - Expect: Only show total account that can connect to dApp

- [x] Re-check issue Connection unsuccessful
  ![Image](https://github.com/user-attachments/assets/33076dad-1031-49f9-ab2d-844c62a3bb5e)

- [x] The margin for the address is on the right
Actual : The address is centered
![image](https://github.com/user-attachments/assets/528a96c7-6178-4f9f-9de0-54779379637a)

- [x] Update padding for icon and account name
![image](https://github.com/user-attachments/assets/d4fd0270-be1d-46a2-b62e-ce02f00125bf)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1EEs3BlI2BDDEYAo3-LPgDIos-UmBOI9w/view?usp=sharing

- [ ] UI bug
![image](https://github.com/user-attachments/assets/bc3a4367-39f1-4634-a6e0-3afd64e75962)

- [ ] UI bug when check with account difference dapp type
Actual : 
![image](https://github.com/user-attachments/assets/e47cea28-490e-4755-aedc-c4e9ff4d3463)
Expect : 
![image](https://github.com/user-attachments/assets/e4736d0d-bb05-48c4-ad75-2811737854b2)

**Comment by haiyenvu23** [comment]
Version test : https://drive.google.com/file/d/1LiUAlQZS4VL3jxfUvjpt7018GHufQwNo/view?usp=sharing
Validation passed in case : 
- Install/Update version 
- Check UI on some screen 
![Image](https://github.com/user-attachments/assets/50229dce-95fb-44f1-bc07-c4ec1b3293da)

- Check when connect dApp, walletconnect and perform sign message, sign transaction with some account type : Unified account, solo account, QR account, Ledger account, watch only account
