### ISSUE TITLE
Review logic fetching transferable balance

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3711]
Users report not seeing transferable balance in transaction screens. We need to review this
https://github.com/Koniverse/SubWallet-Extension/issues/3653
https://github.com/Koniverse/SubWallet-Extension/issues/3695

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/RsfTnbrgsoabgFr
Validation passed in case : 
- Install/Update version 
- Show transferable balance when perform some features : send token, send NFT, stake , unstake, cancel unstake, withdraw, claim reward, swap
- Re-check issue : https://github.com/Koniverse/SubWallet-Extension/issues/2352
![Image](https://github.com/user-attachments/assets/a9abdb02-c006-4741-a719-a12043b92636)
-  Update icon loading when can't get balance on All account mode => Related to issue #2568 
![Image](https://github.com/user-attachments/assets/6f99a415-609d-4068-92cd-f1a970b3daa4)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/S3GGkPfndWcHBez

- [ ] Can't change rpc 
![Image](https://github.com/user-attachments/assets/6fc0c645-30b4-4c76-8af6-fec68962d4eb)

- [ ] Don't show loading when can't get balance 
![Image](https://github.com/user-attachments/assets/bd7a47a2-23dd-4d0f-84ac-152553d5183c)

Expect : Show loading
