### ISSUE TITLE
Fix bug validating recipient balance when sending Substrate token

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3713]
**Describe the task**
- [x] Any token that requires a native token to keep alive will be blocked from sending
  - Actual: It is always forbidden to deposit tokens into an account with native token balance = 0
  - Expect: Only block sending tokens to accounts that require native token balance > 0

- [x] Update compare logic
  - Actual: Comparing with Transferable balance
  - Expect: Comparing with Total balance

**Comment by nampc1** [comment]
https://github.com/Koniverse/SubWallet-Extension/issues/3473

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/Fdy8SA8cLcaHjTb

- [ ] Error when transfer native token
Actual: Show error

![Image](https://github.com/user-attachments/assets/a7008bdd-176c-4519-94f6-7aca555b9047)

Expect: Allow transfer

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Error when transfer MYTH(Polkadto asset hub)
  Actual: Show error
  
  ![Image](https://github.com/user-attachments/assets/c17365f6-072c-4267-8c10-7a765434a322)
  
  Expect: Allow transfer

- [ ] Lost tokens when transfer XCM MYTH -> MYTH(Polkadot asset hub) when input account without native tokens(DOT)
  Actual: Lost token
  Transaction: https://mythos.subscan.io/extrinsic/0xad7a86399f10b5ef49f64e4d9b45eb5b3f16d046de9298af8f6f2531892293e2

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/mf9MfkmETksn7NJ
Validation passed

Checklist for issues: https://www.notion.so/subwallet/Unified-account-Checklist-validating-recipient-address-8895b03e58524ca28cf2b613617d0b27?pvs=4
