### ISSUE TITLE
Unified account - Add infobox about Wallet version for TON token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3718]
**Describe the task**
Add infobox about Wallet version for TON token
- Content: https://www.notion.so/subwallet/SubWallet-Chu-n-ho-content-in-app-c-a-t-nh-n-ng-Switch-WalletContract-version-06b49b4889f74bca8936538dbe506686?pvs=4#501ea9a305114a4bb7e2fe93f9ff0fc5
- Component: https://www.figma.com/design/lsJoDNOy7hqT41tfiiAk1Z/SubWallet-UI-Base-1.0.1-(NEW)?node-id=744-8730&t=Ax7LpmzAgKIVYqQh-4
- Ticket: https://discord.com/channels/447263980252037141/1290519792561684551 

Add to:
- [x] Token token details screen
- [x] Token home for TON solo account

**Comment by ThaoNguyen998** [comment]
Version test: https://drive.google.com/file/d/1fWpqT-Ye74jdEGnkX_9cro1LPmHwYK78/view?usp=sharing

- [ ] Do not show info box on All account (have Solo account TON)
- [ ] Do not navigate in case click hyperlink (All account)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/Ctk7MbYj6iHgf6A

- [ ] Update modal Wallet address & version

   ![Image](https://github.com/user-attachments/assets/5b512b17-133a-48ee-a695-27ba52c3c53d)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/bri9wCHngCNqeYX
- [ ] Bug in case change version with watch only account TON
Actual: Show message error
Expect: Do not show infor box with watch only account TON

  ![Image](https://github.com/user-attachments/assets/5ea2e767-51fb-4c99-b618-5fcb1dd6d4e7)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/ERxrrn3NT3Nt9kc
Validation passed.

Checklist for issues: https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#d12db6d557fa41c7ab410c48c32d2ece
