### ISSUE TITLE
Support ERC1155

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3726]
We'd like to support ERC1155 for RARI chain. ERC1155 should show up on NFT tab just as ERC721. Some example collections:
https://mainnet.explorer.rarichain.org/address/0xd8936E602E38dfEe5d6466865068b94b1943DEBF?tab=tokens_nfts
https://mainnet.explorer.rarichain.org/token/0x1DE9ed3E7622171fb9af8bFfE45A6B75a4cD9B15
https://mainnet.explorer.rarichain.org/address/0x12c621C96Ad3F09487d2Bb91f22B2e6C43A1feAd
https://mainnet.explorer.rarichain.org/address/0x1DfCEE225aD4DD33DAa7f511853a125ec2a27cd8

We can use rarible API:
https://docs.rarible.org/reference/getitemsbyowner

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/kD2wGkdyWLqRFfY

- [ ] Re-check collection ID
Actual : 
![image](https://github.com/user-attachments/assets/64cb2d16-73a3-4406-97ed-43c4a2a78050)

- [ ] Error when perform send NFT
Actual : 
![image](https://github.com/user-attachments/assets/e995b6a3-291f-4acd-b9b3-28bf5ade064a)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/JpLXdJWjegbyGPe
Validation passed in case : 
- Install/Update version
- Show collection NFT on specific account/all account mode
- Check NFT details 
![Image](https://github.com/user-attachments/assets/cb02ca22-183a-4ea4-825e-b1926e91913a)
- Check show NFT when ON/OFF network
- Send NFT 
![Image](https://github.com/user-attachments/assets/ca38aed5-8957-4fde-b2ac-b1e8a0da6c0d)
![Image](https://github.com/user-attachments/assets/da2598ec-c14d-4cd9-9493-dce954d0db37)
