### ISSUE TITLE
Logging unknown response from koni-content

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#373]
**Describe the bug**
Display unknown response

**To Reproduce**
1. Have any action with subwallet from like connect to https://moonfit.xyz/whitelist/
2. Reload page

**Expected behavior**
Not show error

**Screenshots**
![image](https://user-images.githubusercontent.com/11567273/175201401-5f11db39-1ade-45a4-bfec-ed88fcede4fa.png)

**Comment by hieudd** [comment]
Fixed in #438
