### ISSUE TITLE
Unified account - UI bug on the Mission pool screen and Buy token

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3733]
**Describe the bug**

- [x] UI bug on the Mission pool
  Notes: Reproduce this behavior with Mac OS
  ![Image](https://github.com/user-attachments/assets/07a32375-2355-4523-b5fd-7a3176bc1c3b)

- [x] Need to disable button "Buy token" in case do not select account yet
  - Actual: Enable then redirect to service page but do not account
    ![image](https://github.com/user-attachments/assets/0a0d325c-9518-4539-a394-094cbcb183fb)

  - Expect: Disable button Buy token in case do not select account yet

**Comment by ThaoNguyen998** [comment]
- [ ] Re-check list token for Buy feature
  Actual: Show incorrect list token( check with token POL(Polygon))

  ![Image](https://github.com/user-attachments/assets/ba6a79ee-f886-4d1f-9241-c978c81056aa)

**Comment by Sokol142196** [comment]
Version test:
Validation passed in these cases:
![image](https://github.com/user-attachments/assets/2c858b74-8be0-4bc0-ae6c-7672b293d711)

![image](https://github.com/user-attachments/assets/9f8c41b8-c82e-491b-8a34-75789923853b)
