### ISSUE TITLE
Unified account - Error page in case search account on config dapp detail

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3736]
**Describe the bug**
Error page in case search account on config dapp detail

To reproduce the bug
Steps:
1. Go to on the config dapp detail
2. Enter multiple characters in the search box
3. Observe the displayed screen

Actual: Error page

  ![Image](https://github.com/user-attachments/assets/37f9b2b1-a92a-4ede-bbdb-ffdc90fa16f3)

Expect: Display accounts that meet the search criteria

**Comment by Sokol142196** [comment]
Will resolve in https://github.com/Koniverse/SubWallet-Extension/issues/3707
