### ISSUE TITLE
Extension - Re-check list token for Buy feature

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3738]
**Describe the bug**
Re-check list token for Buy feature

**To reproduce the bug**
  Actual:
- Some devices display the POL token

  ![Image](https://github.com/user-attachments/assets/ba6a79ee-f886-4d1f-9241-c978c81056aa)

- When navigating to the browser, an invalid address error message is displayed

  ![Image](https://github.com/user-attachments/assets/e250f5f7-fcea-415b-9ae3-b653197ebc24)

**Comment by haiyenvu23** [comment]
- [ ] Add supplier for token KAR on Karura 
Actual : 
![Image](https://github.com/user-attachments/assets/be9c7d1f-9bfc-4f46-adee-a0e9312c5014)
Expect : Add (new) banxa

- [ ] Remove BUSD on Ethereum

**Comment by ThaoNguyen998** [comment]
Version test: v1.3.1
Validation passed. 
- Re-check list token for Buy token feature
