### ISSUE TITLE
Unified account - Bug related to Earning feature

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3746]
**Describe the task**
Bug related to Earning feature
- [x] Re-check min stake  in case stake more
  Steps: Input Amount < Min stake  (Check with Vara network)
  Actual: Show error

   ![Image](https://github.com/user-attachments/assets/3025dbf3-e827-4dd7-8461-219d8190a73e)

- [x] Can't perform liquid staking for EVM Ledger account
Actual: Show message 

  ![Image](https://github.com/user-attachments/assets/c35cb5ff-00c1-4a41-910f-0a2811d094c7)

  Expect: Perform transaction
- [x] Re-check action in case perform a transaction earning with account QR signer account EVM (Dev mode)
  Actual: Show message

  ![Image](https://github.com/user-attachments/assets/8a36bc92-0424-42b1-be5c-5950849c399a)

  Expect: In dev mode, transactions are still allowed
  Note: Transfer with account QR signer EVM normal

**Comment by ThaoNguyen998** [comment]
Version test: https://drive.google.com/file/d/12-lZOfrAyeI_ixhbgG98h6p3BN9B-NLS/view?usp=sharing
Validation passed. 
- Stake more:

   ![Image](https://github.com/user-attachments/assets/d6450e2c-2ad4-47f4-97b7-4184abf57372)

- Withdraw liquid staking Ledger account

  ![Image](https://github.com/user-attachments/assets/740924af-bd5b-4927-b684-67510908f58a)

- Perform a transaction earning with account QR signer account EVM (Dev mode)

  ![Image](https://github.com/user-attachments/assets/395e386f-e4e9-4679-b7c2-7738228a821a)
