### ISSUE TITLE
Extension - Support export for Derived account

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3751]
**Describe the task**
- [x] In case export for Derived account (type = Unified account)
  - Actual:: Enable button Export 
  ![image](https://github.com/user-attachments/assets/1e974633-7bec-42b8-8dff-cdfbca41be85)
  ![image](https://github.com/user-attachments/assets/6700809d-46a0-4571-9d41-785671f41ac8)
  - Expect: Discuss more
- [x] Re-check case re-import Derived account ( with QR code ) 
**Re-production steps** : 
1. Perform derive Polkadot solo account 
2. Perform export QR code with the previously derived account
3. Remove previously derived account
4. Perform import previously exported QR code and perform derive on account F1
  - Actual: Show derive infor
  ![image](https://github.com/user-attachments/assets/f822ebeb-7de9-496a-a79e-89fffd0b9897)
  - Expect: 
    - If detect derivation info -> Show tab Derivation info
    - If not detect -> Hide derive info

- [x] Check case when can't get balance and UI with derive account imported from the export json file
**Re-production steps** : 
1. Perform derive solo account from unified account
2. Perform export JSON file with the previously derived account
3. Remove previously derived account
4. Perform import previously exported JSON file
- Actual:
  ![1122](https://github.com/user-attachments/assets/ad18fb34-8e5c-4abb-83df-437374666fd6)

- [x] https://github.com/Koniverse/SubWallet-Extension/issues/3704

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/KsEqfkCE6jSrdT2

- [ ] Hide Derivation infor tab when remove parent account
Actual : Show derivation infor
![Image](https://github.com/user-attachments/assets/db7d345c-a570-46bf-ae52-edf0327c8cbe)
Expect : Hide derivation infor

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/QCQjrP4RRopXXjz
Validation passed in case : 
- Install/Update version
- https://github.com/Koniverse/SubWallet-Extension/issues/3704
![Image](https://github.com/user-attachments/assets/c670486e-757b-4f48-b081-b370aafdc219)
![Image](https://github.com/user-attachments/assets/be9eb2e2-6dc5-44a6-a668-db38886315ef)

- Link checklist : https://www.notion.so/subwallet/4c5b588fb0f443ba9083fe2380584119?v=0e9338df67444767a59f69fe7bcaa421&p=cb94bfb37cd7434099a1364880c656d0&pm=s
- In case export for Derived account (type = Unified account)
![Image](https://github.com/user-attachments/assets/f8106afa-5c10-4f9a-a7aa-f69d2655c36d)
- Re-check case re-import Derived account ( with QR code )
- Check case when can't get balance and UI with derive account imported from the export json file
![Image](https://github.com/user-attachments/assets/da8cb41f-93dd-4680-8b80-8f33fd73a7be)
