### ISSUE TITLE
Extension - Improve UI related to Account selector screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3755]
**Describe the task**
- [x] Allows searching for accounts by any address of the account
![image](https://github.com/user-attachments/assets/32c6be69-de39-4830-9f24-f4bc57899498)
- [x] #3772
  - Actual: Still show All accounts
    ![Image](https://github.com/user-attachments/assets/5ea98fe6-868d-4cde-b266-c2a7746bfecd)
  - Expect: Automatically switch to remain account

- [x] Auto select when choose all account in case export all mode
![image](https://github.com/user-attachments/assets/972fa4df-38cf-4749-be76-4c647e5777bb)

- [x] Update show tooltip
  - Actual : Always display
  - Expect : Only show tooltip when user hover on button
    ![image](https://github.com/user-attachments/assets/3cf1863b-bcd1-4bf1-b742-ee946380e960)

- [x] Need ot improve issue Add auto focus on searchbox on Account selector screen
  - Actual: only auto focus on the first time
  - Expect: Always auto focus

- [x] Auto focus on search box choose From field on Send fund
  ![image](https://github.com/user-attachments/assets/0f01415a-9825-4ba8-83ce-e285a3c063e6)

**Comment by Quangdm-cdm** [comment]
About Allows searching for accounts by any address of the account: Need to discuss more, so i recommend create new issue for this bug

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/kHZw9WTxbsZDfJb

- [ ] Re-check case show tooltip when hover
Actual : The tooltip is still automatically displayed even though it is not hovered over ( on expand view, popup)

![Image](https://github.com/user-attachments/assets/90294896-b701-4b03-be93-2b574c6b8217)
![Image](https://github.com/user-attachments/assets/5837071c-cef3-4e2a-9730-12a2c73d5b4b)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/gtgw38qPnE75p8E
Validation passed in case : 
- Install/update version
- Allows searching for accounts by any address of the account : Search with 3 address type: Substrate, Ethereum, Ton
![Image](https://github.com/user-attachments/assets/3354bc0d-3c6d-4d7c-9523-249b445f2e9a)
![Image](https://github.com/user-attachments/assets/a439b8d9-97e8-4fc4-b8d7-3e1cb841681f)
- Auto focus on search box choose From field on Send fund. Re-check all popup select account
![Image](https://github.com/user-attachments/assets/4f7d3541-f331-4918-96e8-6027c6a2fcee)

- Auto select when choose all account in case export all mode
- Turn OFF auto show tooltip export all account
