### ISSUE TITLE
Extension - Improve UI related to Select token screen

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3756]
**Describe the task**
 Improve UI related to Select token screen
- [x] Improve UX
  Actual :  Reappear with TON solo account when getting TON, USDT token (mainnet)

  ![TON-getaress](https://github.com/user-attachments/assets/438c12f4-0b61-4917-9b21-c874176e7e08)

  Expect : 
    - If the token list has only 1 token, show the QR code screen, skip the token selection step

- [x] Show TON (mainnet) on top when search to get address
  ![image](https://github.com/user-attachments/assets/ba07115e-e3e8-45fb-adc8-f92f8426badc)

- [x] Allow search by Token name or Network name

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/iDepgkcGyKStNPo

- [ ] Don't show search box field when scroll on Select token 
![Image](https://github.com/user-attachments/assets/e4cc6fc0-7b11-453d-89f5-a252068ec3e5)
Expect : 
![Image](https://github.com/user-attachments/assets/64de6394-aa63-4c4a-8ba9-fd2f1dedebcf)

- [ ] Can't show result when input 1-2 characters
Actual 
![Image](https://github.com/user-attachments/assets/d1ff94e3-f485-4ba6-8a52-8d58b39b1e76)
Expect : Allow show result when input >= 2 characters

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/r6AZp6HZRQwnbmJ
Validation passed in case : 
- Install/Update version
- If the token list has only 1 token, show the QR code screen, skip the token selection step
![Image](https://github.com/user-attachments/assets/cd797435-6a5a-4047-abf6-5b1c137e6900)
- Show TON (mainnet) on top when search to get address
- Allow search network name and symbol token ( Allow show result when input >= 2 characters)
![Image](https://github.com/user-attachments/assets/a7b06a63-1f6d-4ad1-ae80-c0211b39170d)
- Re-check all popup select token and select network on all features

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/FwPGzjgYZFaiKXT

Validation passed for these cases
