### ISSUE TITLE
Extension - Retest unified account on Firefox browser

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3759]
**Describe the task**
Retest unified account on Firefox browser

Need to fix bug

- [x] Do not load extension

  ![Image](https://github.com/user-attachments/assets/442a0b81-b7c9-47f4-9192-ffdcb665c9b5)

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/92HA8jjTn2NjCEY

- [ ] UI bug on some features : send token, swap 
![Image](https://github.com/user-attachments/assets/d8e48b5b-f400-4b8b-b31d-46fd7002822c)
