### ISSUE TITLE
Extension - Error when send NFT on Ethereum network

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/SubWallet-Extension#3762]
**Describe the bug**
Error when send NFT on Ethereum network
![Image](https://github.com/user-attachments/assets/d29b1468-eb81-4444-8454-e7f94bf8c9a5)
Send from : 0xe2A83b15FC300D8457eB9E176f98d92a8FF40a49 
Send to : 0x00000000219ab540356cBB839Cbe05303d7705Fa
ERC-721 contract : 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D

Expect : Link content for message : https://www.notion.so/subwallet/Product-Chu-n-h-a-content-cho-message-l-i-khi-send-NFT-14dd010d863545048fba27425116a7b0?pvs=4#414f5c8658c7458cad155eaa4b717214

**Comment by PDTnhah** [comment]
> Version test : http://14.224.129.242:8900/s/nyS4Gn3KAHBfbYL
> 
> * [ ]  Re-check error don't show NFT on Kusama network
>   Account test : CmJjAAaoSQtd4jq1ZugQ84zpkma6EPKLwAi2tRVM5QAoozC
>   ![Image](https://github.com/user-attachments/assets/51879bb3-721b-4051-a41a-44ba52fa096b)

Cannot reproduce bug

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/iLDNfK7eYzDAwtn
Validation passed in case : 
- Install/Update version
- Send NFT to account : 0x00000000219ab540356cBB839Cbe05303d7705Fa
![Image](https://github.com/user-attachments/assets/8189b715-819a-4789-a503-fae6fc555398)

- Send NFT to other accounts
![Image](https://github.com/user-attachments/assets/fc9df76d-7132-47ee-9eb9-fc95b41e4cd1)

- Send NFT with other network
![Image](https://github.com/user-attachments/assets/d296cf4a-4599-45dd-857f-52d07d909ff0)
