### ISSUE TITLE
Extension - Recheck Kodadot NFT

### ISSUE THREAD

**Issue by tunghp2002** [Koniverse/SubWallet-Extension#3791]

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/qaDFLRYHcxY8jBs
Validation passed.
- Show image collection OG
  
  ![Image](https://github.com/user-attachments/assets/de24fe4c-e195-4174-8781-a7c9befe1955)

  ![Image](https://github.com/user-attachments/assets/ea9a39ff-3a79-43da-8ffb-bf46b6b389f9) 
- Re-check other collection, transfer NFT
- Install, Upgrade version
