### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3794]
- [x] Inactive `tinkernet`

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/icn8S9DPnTzqEpT
Validation passed.

- [ ] Update logo MATIC token
  
  ![Image](https://github.com/user-attachments/assets/3bbd588c-9d70-4169-afec-5a1077e57f9e)

- [ ] Inactive Tinkernet

  ![Image](https://github.com/user-attachments/assets/8c6daeb1-d661-4efc-8e8e-546d16283391)

- Install/ Upgrade version
