### ISSUE TITLE
Integrate off-ramp

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3801]
**Describe the task**
Integrate off-ramp
- Extension: Redirect to SubWallet Dashboard
- WebApp: Integrate off-ramp with Transak

BA doc: https://www.notion.so/subwallet/Integrate-off-ramp-feature-93f9ae1534ef419dbee9753d71feacfb?pvs=4
Link design: https://www.figma.com/design/aEnkI859zkZaIpyzPidYwh/SubWallet-Apps?node-id=3172-169938&t=GwkYnhWNt3uzO5XQ-4
Link content: https://www.notion.so/subwallet/Product-Chu-n-ho-t-nh-n-ng-Buy-Sell-ade47e8d18424a6fa0bc87d185bf9886?pvs=4

**Comment by haiyenvu23** [comment]
Version test : https://66683caf.subwallet-webapp.pages.dev/

- [ ] Don't show popup in case remove account in wallet while selling
![Image](https://github.com/user-attachments/assets/0b831be9-84a7-410a-a490-e35f29a9b81a)

Expect : Show popup when click confirm on transak web and navigate to subwallet webapp
Link content : https://www.notion.so/subwallet/Product-Chu-n-ho-t-nh-n-ng-Buy-Sell-ade47e8d18424a6fa0bc87d185bf9886?pvs=4#4da962e187f442818b8dd595a690cbd8


- [ ] Error when send ETH token ( on Send fund features)
![Image](https://github.com/user-attachments/assets/e0f1581b-74b0-41fe-8b79-3e0cb4d13bf4)
