### ISSUE TITLE
Improve block action online by environment

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3814]
**Describe the task**
Setup mechanism to block action online by environment:
- [x] App Config:
- environment: webapp, extension, mobile
- version
- [x] Browser Config:
- type
- version
- [x] OS Config:
- type
- version

**Comment by bluezdot** [comment]
To test:
- Create a set of config.
- Get an ID for config set at https://www.uuidgenerator.net/.
- Add config set into Static Content -> blocked-actions/preview/envConfig.json.
- Add a file of blocked action list with the file name is `{configID}.json`.
- Deploy and check

**Comment by bluezdot** [comment]
for version config. there're these format (with any space):
- `>=x.y.z` (can be `>=  x.y.z` also)
- `>x.y.z`
- `x.y.z`

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/LSKAGNPZdGwZFEJ

- [ ] Detect the wrong environment

  ![Image](https://github.com/user-attachments/assets/9ddbeeb6-1f4c-44e0-8804-093d2fbab8de)

- [ ] Show message error

 ![Image](https://github.com/user-attachments/assets/412df5f7-ef2f-4594-bd61-f81a60c73067)

**Comment by bluezdot** [comment]
@ThaoNguyen998 fix json format by add a comma at line 6

**Comment by ThaoNguyen998** [comment]
Checklist for issue: https://www.notion.so/subwallet/Checklist-block-actions-online-272383eca2f940bda3702a3aea2ea4a5?pvs=4#b665cc9e2bf4493499652419f729c085

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/rcEBPQwQF7iBbGY

- [ ] Still detect wrong environment
  Config: "sysConfig": {"type": "macOS"}
  Actual: Still block when type = Windows

  ![Image](https://github.com/user-attachments/assets/b90c338b-7239-4504-adc3-77648a3f1e77)
