### ISSUE TITLE
Miscalculation of unstaking time

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#382]
**Describe the bug**
Miscalculation of unstaking time

**To Reproduce**
Unstake KSM
Remaining time to withdrawal is incorrect

**Comment by NamPhamc99** [comment]
Bug: Error when unlocking data is null
Solution: Check for unlocking is null and redeemable exists

**Comment by sokol142** [comment]
Active stake value is incorrect
![image](https://user-images.githubusercontent.com/102292476/175759793-1a68cbf0-37cc-406a-a807-cdc8d2f316c1.png)

**Comment by NamPhamc99** [comment]
Bug: Showing staking balance incorrectly for HydraDX
![image](https://user-images.githubusercontent.com/44641118/175764556-ce4d2c33-cff5-4899-b6d0-f65007da798c.png)
