### ISSUE TITLE
Support Unified bridge on Polygon

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3826]
- [x] ETH: Ethereum -> Polygon zkEVM
- [x] ETH: Polygon zkEVM -> Ethereum

https://docs.polygon.technology/zkEVM/architecture/unified-LxLy/bridging/#l1-to-l2

Example transactions:
https://sepolia.etherscan.io/tx/0x5600c28da154774ebe608666e77aadb36a9c684f17417c4449b7a2abcc2dacba
https://sepolia.etherscan.io/tx/0xf96f443d1df5d07a2eb962755e05c8f5bc7791dbd3d4404535271a6751c27b63
https://etherscan.io/tx/0xddbff67ac10c27db39c8e49a36871eba319528286752188e1730fbfdcb184f1b
https://etherscan.io/tx/0x70f7f550cded85e21e0893b6ea5aae3dd2b998021ce449770fa78a967bc44f79

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/c8seYfpDy4w8sz6

- [ ] Re-check the popup Pay attention! when bridge
    Actual: Click button X but show loading -> unable to transfer 
    
    ![Image](https://github.com/user-attachments/assets/9b9401b9-4b31-41f5-b0ed-2b3e4b07d1d0)
    
    Expect: Click button X -> Close popup

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/dXZorXwKSJCoQns
Validation passed.

Checklist for issues: https://www.notion.so/subwallet/Checklist-Bridge-Polygon-bfeb455e61a34f52962741479cc9beb9?pvs=4
