### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3827]
**Describe the task**

- Update explorer for Tange network -> Move to https://github.com/Koniverse/SubWallet-Extension/issues/3828 
Actual: https://tangle.statescan.io/address/tgHN2u6WLhVXUKGuZnwtxyCgHd9hgncEuG21SDLQGsdjTng7W -> Show error account
Expect: https://tangle.statescan.io/#/accounts/tgHN2u6WLhVXUKGuZnwtxyCgHd9hgncEuG21SDLQGsdjTng7W

**Comment by nampc1** [comment]
https://github.com/Koniverse/SubWallet-Extension/issues/3828
