### ISSUE TITLE
Support Generic ledger app for Vara network

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3835]
polkadot-js PR: https://github.com/polkadot-js/common/pull/1958
slip-0044 registry PR: https://github.com/satoshilabs/slips/pull/1815

**Comment by nampc1** [comment]
Vara has not updated runtime

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/2zRE9tGr4MYPa6L
Validation passed in case : 
- Install/Update version
- Check when get address Vara on ledger generic account
- Check when send/receive
![Image](https://github.com/user-attachments/assets/98ee50e2-bd4c-4f44-90e5-05231a1c2796)

- Check when sign transaction with dApp ( polkadotjs, subwallet webapp)
![Image](https://github.com/user-attachments/assets/91076fa9-3a0a-49a5-b6d8-45aa1468df6c)

- Send NFT ( features not support send)
- Check when perform Earning : 
- Stake/stake more
![Image](https://github.com/user-attachments/assets/c4bfb88a-2bb6-419b-8caf-f22ac4338500)

- Unstake
![Image](https://github.com/user-attachments/assets/11fc8dc0-de1e-4f9e-ae62-aa0cf3f040e8)

- Claim reward ( proceed to the approval step)
- Withdraw ( unrealized )

- Check again with other tokens
