### ISSUE TITLE
Support swap TAO on SimpleSwap

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3855]
https://simpleswap.io/affiliate-program/en/help-desk/article/public-api-guide

https://api.simpleswap.io/

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Do not show swap quote
  Actual: Show error undefined
  
  ![Image](https://github.com/user-attachments/assets/df99c1c1-c794-4116-b9d5-b1d755f27d6f)
  
  Expect: Show swap quote
  
- [ ] Show message not support
  DOT -> TAO
  ETH -> TAO
  USDT -> TAO
  USDC -> TAO
  ![Image](https://github.com/user-attachments/assets/41948774-6ea8-4a6a-87d2-ba7f86cd6f65)

  Expect: Allow swap

**Comment by ThaoNguyen998** [comment]
- [ ] Error page when remove account
Actual: Error page after remove account

![Image](https://github.com/user-attachments/assets/2cfd46fe-90b5-4058-b599-9b31e2483ea8)

Expect: Perform action normal

![Image](https://github.com/user-attachments/assets/4cb0f970-cfd5-4aea-ad23-6965efeaf7ad)
![Image](https://github.com/user-attachments/assets/e34c5e96-65d5-433b-b0e0-6887318427cd)

**Comment by Sokol142196** [comment]
Please check issues:

- [ ] Re-check swap rate

- [ ] Update UI
  ![Image](https://github.com/user-attachments/assets/42dcb0c8-9f9f-4f37-8eb8-0515b5059e8b)

**Comment by Sokol142196** [comment]
Validation passed according checklist https://www.notion.so/subwallet/d4f4dc20fe4c46f0ba697d683c8add0f?v=af74dc10c213480bbffad3dc735cca2c&pvs=4

Need to improve in https://github.com/Koniverse/SubWallet-Extension/issues/3933
