### ISSUE TITLE
Support staking for more chains

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#386]
**Is your feature request related to a problem? Please describe.**

Please add the staking button for the following parachains

- [x] Moonbeam/Moonriver
- [x] Polkadex
- [x] Turing Network
- [x] Astar dApp staking
- [x] Bifrost

**Comment by NamPhamc99** [comment]
Acala, Bifrost, Phala, Khala have their own staking mechanisms

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.4.9-1657179143656.zip
Please check:
### Bugs

- [ ]  Still can not staking for Validator that have Minimum stake = 0
- Example: To reproduce with Turing Stage Network, observe in here: https://www.loom.com/share/4cf733ef96da467898559e8c056b1698

- [ ] An error occurred the user unstake SBY token when the transaction was incomplete (To reproduce the bug, observe in here: https://www.loom.com/share/220fd1a388904f77960700387599318e)

- [ ] Amount Unstaking is incorrect in case untake with 2 validator at least
- Actual: Total Stake = 10.5 SBY but when click on unstake all then Total Unstake = 15.5 SBY (Validator 1: 5.5 SBY, Validator 2: 10 SBY)
To reproduce the bug, observe in here: https://www.loom.com/share/6b69506a17ea40d8a7073322feca36a1

- [ ] Can not withdraw for EVM Chain
![image](https://user-images.githubusercontent.com/102292476/178188065-dbc87ef7-c74d-40cd-af5b-034dee8c1c6c.png)


### Improvements
- [ ] Disable button Cancel and Select box when extension is loading
![image](https://user-images.githubusercontent.com/102292476/178184579-418f99be-c621-4cea-a4a8-1b12f71026fb.png)

- [ ] Clear default value for the Amount field on the Unstake screen
![image](https://user-images.githubusercontent.com/102292476/178187496-98327b08-856f-4032-8a53-b9c3ee225c3b.png)

**Comment by sokol142** [comment]
- [ ] Showing message "Your balance is too low to cover fees" even though have enough balance to cover fees
Pre-condition: 
- Account A have balance < 0.2 WND
- Have stake record for the Account A
Steps:
1. Open the extension then switch to Account A
2. Go to the unstake screen
3. Input valid data for the all fields then click button Confirm
4. Observe result
Actual: Showing message "Your balance is too low to cover fees" but still unstake successfully (stake balance is decreasing,  & unstake balance is increasing): https://www.loom.com/share/890a8c2cfebf44e0802d18d87abbaec8

- [ ] Incorrect amount when user click on unstake all with small amount
![image](https://user-images.githubusercontent.com/102292476/178224499-5cc20782-a495-4543-a2af-f7a257435025.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.4.9-1657618719858.zip

Please check issues:
- [ ] Still can not withdraw for EVM Chain
![image](https://user-images.githubusercontent.com/102292476/178477406-46ecdcf3-c02e-49b8-a4a0-57be6d73f606.png)
- [ ] Incorrect value in case of unstake SBY (input unstake 2 SBY but stake value = 5 after submit successfully): https://www.loom.com/share/aa91ec41e8a94663bd95c10657f0b86c
- [ ] Showing incorrect tooltip when hover to Claim Reward button
![image](https://user-images.githubusercontent.com/102292476/178478477-7210d919-37f7-42f8-91dd-8ed468d63c67.png)
- [ ] The Next button is disabled in case Change DApp/Validator
![399_DisableNextbutton](https://user-images.githubusercontent.com/102292476/178478926-67def260-97f0-4935-afc0-13ad422d0697.gif)
- [ ] Bug happens when user claim reward 
- Case 1: Click on Claim Reward button
![image](https://user-images.githubusercontent.com/102292476/178481597-d2b00a5d-e3fa-45e8-87d3-eee23432ffe2.png)
- Case 2: Not showing selected DApp in case change DApp (Change form Algem to ADAO but still display Algem)
![399_ClaimReward](https://user-images.githubusercontent.com/102292476/178482271-1f9a7dc8-6e0c-4dd3-9758-8f885ef87bc5.gif)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.4.9-1657773379198.zip

Please check some issue with Astar dApp staking (Shibuya Testnet)
- [ ] An error occurred when the user unstakes after a few minutes of successful staking
Steps:
1. Open the extension
2. Staked for Shibuya Testnet successfully
3. Perform claim reward successfully
4. Then, click on Unstake fund action
Actual: An error occurred
![399_unstake_2](https://user-images.githubusercontent.com/102292476/179336196-f745bae1-4084-4f61-aa65-5333a67c886e.gif)

- [ ] Showing incorrect unstaking value
**Pre-condition: Previously unstake was successful**
- Example: Staked & unstake for dApp = ADAO successfully with 6 SBY
Steps:
1. Open the extension
2. Staked on Shibuya Testnet Network for dApp = Algem successfully with 5 SBY
3. Perform claim reward successfully
4. Then, click on Unstake fund action
5. Click on dApp dropdown then observe list dApp showing
6. Click on Unstake All then observe unstake amount
Actual: 
- Step 5: Not showing Algem dApp
- Step 6: Amount = 6 SBY while only 5 SBY
![399_unstake_3](https://user-images.githubusercontent.com/102292476/179336721-6b4d5845-9810-464b-bcc3-321abe49d784.gif)

- [ ] Claim Reward button displayed is disable when Active stake = 0
![399_ClaimReward_2](https://user-images.githubusercontent.com/102292476/179336260-edec6af2-919d-45d1-b319-0375344d99b1.gif)

**Comment by sokol142** [comment]
Staking feature over view
![Staking Feature_overview](https://user-images.githubusercontent.com/102292476/179502311-9bef130b-7931-401b-8de5-5af8653ac26f.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.4.9-1658137687379.zip

- [ ] Can not unstake for Relay Chain
![image](https://user-images.githubusercontent.com/102292476/179506278-31ee8e47-31e7-4037-9f05-192feddb260c.png)

- [ ] Re-check bug: Showing incorrect amount staking in the case of opening the unstake screen and there is only 1 validator

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.4.9-1658215640492.zip
Please check issue:
- [ ] Update UX when user enters decimal to set amount unstaking for relaychain
- [ ] Update tooltip when user hover over claim reward button 
- Change to "Make sure you claim all rewards regularly and before you unstake"

- [ ] Kindly check rounding function 
![image](https://user-images.githubusercontent.com/102292476/179728077-629138e7-19b7-41a8-a389-9b83e24e3df5.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.4.9-1658227070767.zip
- [ ] Incorrect withdrawable value display after successful withdrawal: https://www.loom.com/share/041ec9a66da14427a6374e35dea4e252
![image](https://user-images.githubusercontent.com/102292476/179742096-6f9b00d8-09c0-4de8-8d7e-3156bef1c303.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.4.9-1658400401295.zip

### Bugs

- [ ] Can not withdraw for Bifrost
![image](https://user-images.githubusercontent.com/102292476/180367678-aa81242e-2be9-4d2d-9642-01b976625ddd.png)

- [ ] Recheck the all function for the Shibuya Testnet network (include: stake, unstake, withdraw, claim reward, nominating mark)
![image](https://user-images.githubusercontent.com/102292476/180367878-d5455579-cc2b-46e4-abdd-fb76770c1be9.png)

![image](https://user-images.githubusercontent.com/102292476/180367710-343e53ea-5d90-4ddb-a119-64d054ad4d2c.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.5.2-1658474671802.zip

- [ ] Wrong withdraw information on parachain network (see file attachment)

https://user-images.githubusercontent.com/102292476/180435153-f2d19524-c699-49bf-bf7d-b6242f581a83.mp4

**Comment by sokol142** [comment]
Validation passed!

- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.5.2-1658821770095.zip

**Comment by sokol142** [comment]
Update commission for Turing Network

Validation passed!
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./399-merge-build-0.5.2-1658894075610.zip
