### ISSUE TITLE
Extension - Check for errors when making transactions on Tangle mainnet

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#3861]
**Describe the task**
Check for errors when making transactions on Tangle mainnet
Log bug: 

![Image](https://github.com/user-attachments/assets/f81cdd64-0b7e-4f65-b19e-43e1d9add1b5)

**Comment by ThugOG** [comment]
any update.

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/HQg9mdYFAJn4QAD

- [ ] Update link navigate to explorer

   Actual : Navigate to link: https://tangle.statescan.io/extrinsic/0x4e60042cbd79cb74c6b6e9fd0853bb42d2ad3c5aa2df1bef9a423d07494ab6b5

  ![Image](https://github.com/user-attachments/assets/b8733b12-5d42-4cff-8bb5-0fd621d57e06)

   Expect : Navigate to link : https://tangle.statescan.io/extrinsic/0x4e60042cbd79cb74c6b6e9fd0853bb42d2ad3c5aa2df1bef9a423d07494ab6b5#/extrinsics/0x4e60042cbd79cb74c6b6e9fd0853bb42d2ad3c5aa2df1bef9a423d07494ab6b5

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/fiFfz6Ac6jZMRRP
Validation passed in case : 
- Install/update version
- Perform send TNT token
Link explorer : https://tangle.statescan.io/extrinsic/0xc41839508e6c884bdf9d9af564fd75045fc53045cebd2dd4d037391ded1cad82#/extrinsics/0xc41839508e6c884bdf9d9af564fd75045fc53045cebd2dd4d037391ded1cad82?tab=calls&page=1

![Image](https://github.com/user-attachments/assets/b9b4aab5-91ce-4c02-98ac-93ef9186904f)

- Perform send some tokens
