### ISSUE TITLE
WalletConnect - Allow Polkadot namespace use EVM address

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3870]
Some substrate networks like `Moonbeam` or `Mythos` can connect via WalletConnect with `polkadot` namespace. But these networks require EVM address to connect.

--> Need support `polkadot` namespace can select EVM address to connect via WalletConnect

**Comment by haiyenvu23** [comment]
Version test : 
Validation passed in case : 
- Install/Update version
- Check connect with walletconnect 
- Check when sign message/sign transaction with walletconnect
- Re-check sign with dApp
![Image](https://github.com/user-attachments/assets/6ce06bc0-7379-4d0e-8120-0e02e7320241)
