### ISSUE TITLE
Extension - Re-check Transfer Max for EVM account when XCM transfer

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-Extension#3876]
**Describe the task**
Re-check Transfer Max for EVM account when XCM transfer

Solution: Disable button Max ETH: Ethereum <--> Polygon zkEVM

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/6PFkbA9Y54wzcpq
Validation passed.
Checklist for issues: https://www.notion.so/subwallet/Checklist-Bridge-Polygon-bfeb455e61a34f52962741479cc9beb9?pvs=4
