### ISSUE TITLE
Add auto-compounding for TUR (Turing Network) inside SubWallet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#388]
**Is your feature request related to a problem? Please describe.**

Add support for auto-compounding for TUR inside SubWallet.
Below are the docs:
- https://oak-network.notion.site/Time-Triggers-ddca8d57783749a88dded8d2f40abe34
- http://docs.oak.tech

**Comment by NamPhamc99** [comment]
To be resolved in  #520
