### ISSUE TITLE
[Chain abstraction] Update UI for chain abstraction explorer website

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3882]
Design:
https://www.figma.com/proto/MB4U2bIQGEcA3P3KYt5KIt/00.KoniStudio-Branding?page-id=325%3A1112&node-id=1723-3649&node-type=frame&t=N5N3tE0UePQFVWzC-0&scaling=min-zoom&content-scaling=fixed

We'll modify this codebase
https://github.com/Koniverse/DotInsights

**Comment by phamtrang2510** [comment]
Validation passed in case:
- Re-check padding in header
![padding_header](https://github.com/user-attachments/assets/f797263a-0a58-4546-97fa-b8c3eb798a4c)

- Update display category
![image](https://github.com/user-attachments/assets/3a97565e-be42-4b14-a80b-51b65efdc4dc)

- Update display Most loved projects
![image](https://github.com/user-attachments/assets/0a6022ba-56e1-40ab-b79e-833edb18c49f)

- Update padding responsive
![image](https://github.com/user-attachments/assets/11b38539-2aee-461a-beb8-fcdf1143e3f2)

- Update display when click button "Connect Wallet"
![connect](https://github.com/user-attachments/assets/84b9c3dd-074f-4a0c-aa77-6eae8a4ce2b6)

- Update display when click button "Votes"
![votes](https://github.com/user-attachments/assets/d89f6c04-e97c-4eff-a92d-9a70f01bf1f7)

- Update the color of the category in case of a new addition
![color](https://github.com/user-attachments/assets/4290e083-a5ad-4215-9ef2-5ad0f6470b6d)
