### ISSUE TITLE
Update version polkadot api

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#3888]
Upgrade version:
- `15.0.1`: @polkadot/api, @polkadot/api-augment, @polkadot/api-base, @polkadot/api-contract, @polkadot/api-derive, @polkadot/rpc-augment, @polkadot/rpc-core, @polkadot/rpc-provider, @polkadot/types, @polkadot/types-codec, @polkadot/types-known, @polkadot/types-support
- `13.2.3`: @polkadot/networks, @polkadot/util, @polkadot/util-crypto

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/ZSLf7bMZ3S2Qi3g

- [ ] Do not show swap quote in case swap HDX
  Actual: 

  ![Image](https://github.com/user-attachments/assets/f37e39dc-79ea-426c-98d9-3356d108326a)

  Expect: Show swap quote

**Comment by bluezdot** [comment]
- `5.1.0`: @galacticcouncil/sdk
- `5.1.6` : @types/bn.js

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/nTosrTeTcanJ8WD
Validation passed
Checklist for issue https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#ab0973e45f5246398d15ac8cf0f09789
