### ISSUE TITLE
Support bridge ETH <-> POS

### ISSUE THREAD

**Issue by tunghp2002** [Koniverse/SubWallet-Extension#3893]

**Comment by Hinted-tech** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[SubWallet Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by ThaoNguyen998** [comment]
Version test: 

- [ ] Handle case L2 -> L1: auto filter address and disable field address

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/3oW9aS7jB45mEKC

- [ ] Do not auto filter address on Receive account (L2 -> L1)
  Actual: Do not show address
  
  ![Image](https://github.com/user-attachments/assets/ea246af6-9144-4876-8828-359099527956)
  
  Expect: Auto filter address
- [ ] Do not reset account when change Destination chain 
  Actual: Auto select account 
  
  ![Image](https://github.com/user-attachments/assets/71cfe235-7946-4352-a441-93e9b5f9704f)
  
  Expect: Reset account when change Destination chain

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/6RiAKAeoQtKpL2X
Validation passed for checklist: https://www.notion.so/subwallet/Checklist-Bridge-Polygon-bfeb455e61a34f52962741479cc9beb9?pvs=4#1175f62b964b4d67a1f734a647d985be

**Comment by ThaoNguyen998** [comment]
- [ ] Implement UI receipient address in case bridge Polygon -> Ethereum
  Expect: 
  
  ![Image](https://github.com/user-attachments/assets/f1feaa98-fbb3-4d61-911d-b1ca34bb3391)

**Comment by ThaoNguyen998** [comment]
Version test: https://file.cdmteck.com/s/o9QJKmHaK6rEcLf
Validation passed.
Checklist for issue: https://www.notion.so/subwallet/Checklist-Bridge-Polygon-bfeb455e61a34f52962741479cc9beb9?pvs=4#1175f62b964b4d67a1f734a647d985be
