### ISSUE TITLE
Fix max transferable for Avail Bridge

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-Extension#3911]
- Describe problem: Users bridge AVAIL fail from Avail -> Ethereum (https://avail.subscan.io/extrinsic/0x0308a6cbf8ce78fec3016e5658ffd3380e758a1673e8913b46a4d080b7fe3cac)
- Check result: Almost all extrinsics fail in case users transfer max using wallet.
- Solution: Set `max_transferable = transferable balance - 1 AVAIL` (reference: https://bridge.availproject.org/)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/aRxrwkFSwQBHQHp

- [ ] Error when bridge avail(Ethereum sepolia -> avail turing)

  ![Image](https://github.com/user-attachments/assets/5c72801a-a343-4611-9f4a-9e3b48d42e3c)

  ![Image](https://github.com/user-attachments/assets/e766f19e-0fd8-4c9d-83f9-d9a611d3d896)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.129.242:8900/s/aRxrwkFSwQBHQHp
Validation passed.
Checklist for issue: https://www.notion.so/subwallet/Checklist-theo-issue-13c9e3215ec24762973dc680aec67198?pvs=4#01cc4594e10446368c76142264bcd604
