### ISSUE TITLE
Extension - Ledger - Support `Avail Recovery` app

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#3915]
Support `Avail Recovery` Ledger

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/CHTTikD9wC76oz3
Validation passed in case : 
- Install/Update version
- Check when perform send/receive with ledger account 

   ![Image](https://github.com/user-attachments/assets/d23d2032-1d24-4822-a804-76a31c0a9c1d)
   
   ![Image](https://github.com/user-attachments/assets/b5fd5fc6-75e8-46e4-9644-40b5ad07294c)

- Check when sign transaction ( token / stake ) with avail explorer
![Image](https://github.com/user-attachments/assets/fb1d8d50-5c7a-4fc6-a210-f613d11527f4)

- Re-check when perform send/receive with other account type
