### ISSUE TITLE
Fix UI bug for Cardano unified account

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-Extension#3927]
**Describe the task**
- [x] Fix “Unknown chain type” error when transferring Cardano tokens
  - Expect: Allow transfer when input valid data
 
  ![image](https://github.com/user-attachments/assets/3241130a-d71c-4744-bcc2-2160c0d8f477)

- [x] Cardano network, Cardano testnet not showing in transaction history screen in All Accounts mode
  - Expect: Show Cardano, Cardano testnet when viewing transaction history with Cardano Unified account/ Cardano solo account
  ![image](https://github.com/user-attachments/assets/79ada1aa-0a46-4456-bfe1-95f16ae3797e)

- [x] Update ecosystem logo, network logo, token logo
  ![image](https://github.com/user-attachments/assets/0624a1f1-2ebd-4a9b-b9d7-0826912a4209)

**Comment by Sokol142196** [comment]
Still reproduce the bugs

- [ ] Unknown chain type” error when transferring Cardano tokens in case select receive account from Suggestion 
  - Actual: Still show Substrate address 
  - Expect: Convert address on Suggestion popup to Cardano address when sending token in Cardano ecosystem
    <img width="352" alt="Image" src="https://github.com/user-attachments/assets/26bb1bdf-9ac0-4430-9476-a7576e38fbf7" />

**Comment by Sokol142196** [comment]
Version test: https://drive.google.com/file/d/1rudG13SxPgNcAjgWbrptOVutc053kIp_/view?usp=sharing

Validation for these case above
<img width="192" alt="Image" src="https://github.com/user-attachments/assets/e2685d0d-5c39-4d9b-ab1f-fff71bc87244" />

<img width="194" alt="Image" src="https://github.com/user-attachments/assets/3c149701-34f9-410d-979f-9f3700789e5c" />

<img width="193" alt="Image" src="https://github.com/user-attachments/assets/b02ba445-2c48-4390-89c6-17a1f865f31d" />

<img width="193" alt="Image" src="https://github.com/user-attachments/assets/3aeb9275-4f1d-4908-a72f-51241192892d" />
