### ISSUE TITLE
Improve the UX for contracts transaction with EVM provider

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#393]
**Is your feature request related to a problem? Please describe.**
Improve the UX for XCM transfers in Moonbeam Dapp: 
Detail: https://docs.google.com/document/d/1TqTva5PXuag8VhOcNMkF5Kq9F3T_NSD5Mtb0G5sAgFo/edit#

### Feature Request
- [x] Decode transaction data of EVM transaction request into friendly UI and more reliable
  - [x] ERC20
  - [x] ERC721
  - [x] XCM (More detail can be found [here](https://docs.google.com/document/d/1TqTva5PXuag8VhOcNMkF5Kq9F3T_NSD5Mtb0G5sAgFo/edit#))

**Comment by sokol142** [comment]
- [ ] showing incorrect amount
![image](https://user-images.githubusercontent.com/102292476/180162597-a135b5ec-0e36-44df-b901-3b860461f491.png)

**Comment by sokol142** [comment]
@hieudd please check the request 2nd on file: https://docs.google.com/document/d/1TqTva5PXuag8VhOcNMkF5Kq9F3T_NSD5Mtb0G5sAgFo/edit# is actual or expected?
![image](https://user-images.githubusercontent.com/102292476/180188981-61fb1045-3e1c-4f94-bb4d-e94e62e8436f.png)
