### ISSUE TITLE
Do not display popup connect wallet in case upgrade version

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#401]
**Description the bug**
- [x] Do not display popup connect wallet in case upgrade version on Moonbeam app
- [x] SubWallet is disable on Moonbeam app

**To reproduce:**
**Steps**:
1. Open the old version extension (ex: version extension = 0.4.5)
2. Connect to EVM DApps successfully (ex: https://apps.moonbeam.network/)
3. Upgrade the extension to the latest version
4. Re-open EVM Dapps
5. Select Connect button on popup confirm
6. Disconnect wallet on the DApps
7. Click on SubWallet to re-connect
**Actual**: Do not display popup connect wallet

![Image](https://user-images.githubusercontent.com/102292476/176670491-541acdb9-14d2-44d3-a3ac-79fd60c80b9a.png)

- [x] Do not display popup connect SubWallet (EVM) in case upgrade version on Astar app (upgrade from v0.4.5 to v0.4.9 in case astar dApp supported SubWallet EVM)
==> Solution: Auto create auth popup if DApps are in allow list and there are no accounts in allow list.

**To reproduce:**
**Steps**:
1. Open the old version extension (ex: version extension = 0.4.5)
2. Connect to Astar dApps (https://portal.astar.network/) successfully
3. Upgrade the extension to the latest version
4. Reload Astar dApp
5. Perform connect to SubWallet (EVM) then observe the screen displayed
**Actual**: Do not display popup connect to EVM Account

**Comment by sokol142** [comment]
Related: https://github.com/Koniverse/SubWallet-Extension/issues/444

**Comment by sokol142** [comment]
For Moonbeam app: Validation passed!

https://user-images.githubusercontent.com/102292476/179907494-427e1018-e52c-49c4-be21-800639adeb84.mp4

**Comment by sokol142** [comment]
> * [ ]  Please check bug: The allow list show incorrect account in case upgrade version
>   ![image](https://user-images.githubusercontent.com/102292476/180161064-5b1aa3a0-5de3-471d-b6e7-b6e530edb537.png)

Please check this bug!
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./461-merge-build-0.4.9-1658390392786.zip
- Actual: Still to reproduce this bug

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./461-merge-build-0.4.9-1658390392786.zip
- [ ] Please check recreate auth popup if dApp are in allow list is empty in case of reject connect

- Actual: Still showing popup connect 
- Expected: Do not showing popup connect

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./461-merge-build-0.5.2-1658569865567.zip

### Bugs

- [ ] Not show popup connect if user select reject connection in case below:

**Steps:**
1. Go to https://connect.subwallet.app
2. Click on Select Wallet button
3. Select SubWallet 
4. Select Reject button
5. Click on Select Wallet again
6. Select SubWallet EVM

**Actual:** Not show popup connect to SubWallet EVM
**Expected:** Show popup connect to SubWallet EVM
![401_connectSubWallet](https://user-images.githubusercontent.com/102292476/180766876-d384b655-5faf-4b7a-a624-a6b0fb0dd699.gif)

**Comment by saltict** [comment]
@sokol142, I have updated above problems please check this [build](https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./461-merge-build-0.5.2-1658805423250.zip)

**Comment by sokol142** [comment]
Version test:

Please check issue: still connect to Moonbeam app after blocked site 
https://user-images.githubusercontent.com/102292476/181447658-8820cf37-12c3-4cc6-953f-7280f068f124.mp4
