### ISSUE TITLE
Staking Button in SubWallet

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#42]
Some improvement for Staking Feature

**API:**
- [x] Get list of networks allow staking (not supporting custom network)
- [x] Get list of validators along with necessary information (total stake, number of nominators, commission, identity, minimum bonding amount)
- [x] Delegate to a validator

UI:
- [x] Choosing network screen
- [x] Choosing and filtering validator screen
- [x] Choose bonding amount screen
- [x] Sign and send screen
- [x] Confirmation screen

**Screen Design:**
- https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=2862%3A11482&scaling=min-zoom&page-id=4%3A14

**Comment by NamPhamc99** [comment]
API:
- [ ] Get list of networks allow staking (not supporting custom network)
- [ ] Get list of validators along with necessary information (total stake, number of nominators, commission, identity, minimum bonding amount)
- [ ] Delegate to a validator

UI:
- [ ] Choosing network screen
- [ ] Choosing and filtering validator screen
- [ ] Choose bonding amount screen
- [ ] Sign and send screen

**Comment by sokol142** [comment]
Pls check issues:

- [ ] Bug UI in expand mode: 
![image](https://user-images.githubusercontent.com/102292476/173735556-b7fa7e03-fa05-4c06-a426-c5ad9397c2b8.png)

- [ ] Disable buttons when extension is loading
Example:
![image](https://user-images.githubusercontent.com/102292476/173736346-cff8e482-76fb-4a59-bdcf-df308fabda8c.png)

- [ ] Do not back to the previous screen when user click on Cancel button on the Stacking Action screen
![image](https://user-images.githubusercontent.com/102292476/173735812-9e85d471-b1ae-42aa-b071-ba09ade975e7.png)

**Comment by sokol142** [comment]
- [ ] Can't load Network on the Select a Network screen in case user connect to HydraDX Network (pls check with another network)
![235_LoadingNetwork](https://user-images.githubusercontent.com/102292476/173768863-9b962bf8-ec3b-4960-9574-b2cc5a202002.gif)

**Comment by sokol142** [comment]
- [ ] Improve: Due to not supporting staking for Ledger/QR accounts, we should temporarily hide the Stake button for the above accounts.
