### ISSUE TITLE
HydraDX snakenet staking issue

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#423]
**Describe the bug**

The staking tab show infinity loading when HydraDX snakenet solochain is turned on. Please check it.
Here is the link that reproduce the bug: https://drive.google.com/file/d/1JWDUiB02gAgG-66YCcOU-YLLp-YdevH0/view?usp=sharing

**Comment by NamPhamc99** [comment]
Resolved in issue #386. Due to hydradx migrates to become a parachain
