### ISSUE TITLE
Add select acc screen when user in All Account mode to show address

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#425]
**Is your feature request related to a problem? Please describe.**
Add select acc screen when the user is in 'All Account' mode

**Describe:**

- Step 1: When the user uses All Account mode click on the receive button
- Step 2: Display the account selection screen: Design: https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=4051%3A13455&scaling=min-zoom&page-id=4%3A14
- Step 3: After the user has finished selecting the account, the network selection screen is displayed
- Step 4: After the user has selected the network, the screen of receiving will be displayed: QR code, Address: https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=158%3A1709&scaling=min-zoom&page-id=4%3A14

**Comment by sokol142** [comment]
- [ ] Update UI follow design:
![image](https://user-images.githubusercontent.com/102292476/179344985-4059a5ce-a73b-4039-a5ac-8ad9925bb916.png)

- [ ] Add tooltip when hover to ? icon
- [ ] Bug UI
![image](https://user-images.githubusercontent.com/102292476/179345365-8e0b4db0-f4b9-46bf-bcf2-70d43ea99449.png)
- Search box size is changed when entering search keywords (see file below)
![image](https://user-images.githubusercontent.com/102292476/179345425-7537651e-c636-4028-b409-5450a83e64f1.png)

**Comment by sokol142** [comment]
Improve UI:

- [ ] Add the x icon button to clear text for the search box (both Network Selection & Account Selection popup)

![Image](https://user-images.githubusercontent.com/102292476/179499441-64ddfe60-146e-407b-a26a-4d8bf956a3a0.png)


- [ ] Update height-weight for popup (both Network Selection & Account Selection popup)

![Image](https://user-images.githubusercontent.com/102292476/179499617-6104c33c-390c-4742-97d9-b7ba482de203.png)

**Comment by hieudd** [comment]
@S2kael Update UI
![Screen Shot 2022-07-19 at 8 21 33 AM](https://user-images.githubusercontent.com/2582652/179645183-ecccbdbc-9a66-4444-866f-d2b7a03e86bd.png)
![Screen Shot 2022-07-19 at 8 24 09 AM](https://user-images.githubusercontent.com/2582652/179645193-4cf204e7-2faf-4caa-8a5c-0fd8c39ff602.png)
![Screen Shot 2022-07-19 at 8 20 29 AM](https://user-images.githubusercontent.com/2582652/179645181-aff8647c-e743-4d5b-8ecd-36881c12db4e.png)

**Comment by hieudd** [comment]
![Screen Shot 2022-07-20 at 10 55 12 AM](https://user-images.githubusercontent.com/2582652/179895761-5a41049c-9884-4953-9163-fb88326ab5dd.png)
![Screen Shot 2022-07-20 at 10 55 47 AM](https://user-images.githubusercontent.com/2582652/179895776-dc55fb29-7c27-44fb-9d63-56be283f972b.png)

**Comment by sokol142** [comment]
Validation passed!
![425_validation](https://user-images.githubusercontent.com/102292476/179938841-73be6ec1-e1c8-4d19-8a66-3e2fbc08e990.gif)
