### ISSUE TITLE
Error logs from koni-content

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#438]
**Describe the bug**
Show error logs `page.js:4079 Unknown response: {"id":".1657957039834.1","response":false,"origin":"koni-content"}`

**To Reproduce**
1. Install SubWallet
2. Open any web page
3. Open console log with `F12`

**Expected behavior**
Show nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/11567273/179345391-eca2193d-4880-44e9-b0d8-4231e06807e7.png)

**Comment by sokol142** [comment]
Validation passed!

- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.4.9-1658369565951.zip

![438_validation](https://user-images.githubusercontent.com/102292476/180137865-7db2be44-b6a0-4c49-9089-9c55b173b350.gif)
