### ISSUE TITLE
Integrate Astar NFT

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#44]
Integrate Astar NFT

- [x] Logic API @minhle2994 
- [x] UI @NamPhamc99 

- [x] **Supported Astar NFT collections:**

- Astar Punks
- Kongz Of Astar (KONGz)

**Comment by hieudd** [comment]
@NamPhamc99 pls add more collections: https://tofunft.com/en/astar

![Screen Shot 2022-04-07 at 10 56 35 AM](https://user-images.githubusercontent.com/2582652/162117246-3ee3fcc3-b86d-40c5-84b3-8b589805a264.png)

**Comment by NamPhamc99** [comment]
Added support for NFT collections:

- AstarDegens
- Astarians
- AstarBots
- AstarGhost
- Astar Kevin
- Astar Punk X
- Astar Invisible Friends
- Astar MetaLion Kingdom
- Astar Karafuru

**Comment by NamPhamc99** [comment]
![image](https://user-images.githubusercontent.com/44641118/162161386-6400f8e2-8a74-46e9-be59-23d93e5d1ae3.png)
