### ISSUE TITLE
The issue with EVM Provider by late initialized

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#444]
**Describe the bug**
Some DApp gets problems because of the late initialization of the provider.

**To Reproduce**
1. Go to [Moonbase App](https://apps.moonbeam.network/moonbase-alpha)
2. Select disconnected if connected with wallet
3. Reload the browser
4. Select wallet
**This error can occur by repeating steps 3 and 4**
![image](https://user-images.githubusercontent.com/11567273/179667049-9442ee6c-4e94-4c7b-b46c-f5d87437cf04.png)

**Expected behavior**
There are no errors

**Comment by sokol142** [comment]
Validation passed! (Check for Moonbeam app)

https://user-images.githubusercontent.com/102292476/179908241-e1cbe2a6-a1dc-465e-874b-c711d932de11.mp4
