### ISSUE TITLE
Add support for DOT on Astar Native and on Astar EVM

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#450]
**Is your feature request related to a problem? Please describe.**
Astar Network has supported XCM transfer for DOT from Relay chain to Astar native and Astar EVM. Please add support for DOT on Astar Native and on Astar EVM.

**Comment by NamPhamc99** [comment]
- [ ] DOT on Astar
- [ ] DOT on Astar EVM

**Comment by sokol142** [comment]
Validation passed!
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./543-merge-build-0.5.5-1660623430987.zip

![image](https://user-images.githubusercontent.com/102292476/184859170-91c54c1a-cca2-4d78-ad83-7a334d052af4.png)
![image](https://user-images.githubusercontent.com/102292476/184859261-c14eb69c-5b51-4c57-b3da-7b92cdc35c09.png)
