### ISSUE TITLE
USDC does not show on Moonbeam

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#451]
**Describe the bug**
USDC doesn't show token and value on Moonbeam 

**To Reproduce**
See video: https://www.loom.com/share/7cd05166f7f14ce7bfa1bc92397a4074 

**Desktop (please complete the following information):**
 - Macbook pro 2016
 - Browser [Chromoe]
 - SubWallet Version [0.4.9]

**Comment by Sokol142196** [comment]
@NamPhamc99 you can reproduce this bug on the new version extension with the address: 0x61E088F8B70fcf569ee9E320C5114d295359E8b7


![Image](https://user-images.githubusercontent.com/130966515/233757049-bb75de0d-4296-4c5e-8db4-bb88a62eb520.png)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-1.0.2-1-2023-04-22T11-46-48UTC.zip
Validation passed!
- Check with address: 0x434FC3043a4a3b0EE43c50dFB86B16C4b3B759D6
![image](https://user-images.githubusercontent.com/130966515/233898400-ae847e06-bfcf-466f-8899-9aea7dfe91de.png)
