### ISSUE TITLE
MoonFit support

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#452]
**Is your feature request related to a problem? Please describe.**

-  #317
- #469
- #467
- #468
- https://github.com/Koniverse/SubConnect/issues/9

### Other Issues:

- https://github.com/Koniverse/SubWallet-Extension/issues/481
- https://github.com/Koniverse/SubWallet-Extension/issues/480
- https://github.com/Koniverse/SubWallet-Extension/issues/495
- https://github.com/Koniverse/SubWallet-Extension/issues/464

**Comment by sokol142** [comment]
@hieudd @daodinhhieu please verify this issue help me.
