### ISSUE TITLE
Add support for transaction history on Astar EVM

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#454]
**Is your feature request related to a problem? Please describe.**
Please add support for transaction history on Astar EVM. It is not supported atm. (Moonbeam/Moonriver is supported already)

<img width="455" alt="Screen Shot 2022-07-20 at 18 11 03" src="https://user-images.githubusercontent.com/102496727/179969538-0526eed7-b3f4-4e7f-be91-56f189d26abc.png">

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./544-merge-build-0.5.4-1660189619856.zip
Validation passed!
- Transaction history displayed
![image](https://user-images.githubusercontent.com/102292476/184108916-b7994818-7ba6-41eb-a7e9-3bd58eccf582.png)
