### ISSUE TITLE
EVM Account Identicon is not show

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#457]
**Describe the bug**
EVM Account Identicon is not show

**To Reproduce**
1. Go to [SubConnect](https://connect.subwallet.app/#/evm-wallet-info)
2. Select SubWallet(EVM)
3. Select any network
4. Make an example transaction
5. To Account Address is not displayed 
![image](https://user-images.githubusercontent.com/11567273/180039145-7f3deea0-d42f-4a24-a9aa-4353d5c5a86b.png)

**Expected behavior**
Display the right account address

**Comment by sokol142** [comment]
Validation passed!
![354_457_validation](https://user-images.githubusercontent.com/102292476/180125354-bdc739d4-72cc-4556-89b0-1a9a216b42fa.gif)
