### ISSUE TITLE
Improve UI for XCM transaction with EVM provider

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#462]
Related: https://github.com/Koniverse/SubWallet-Extension/issues/393
**Is your feature request related to a problem? Please describe.**

Improve the UX/UI for XCM transfers in Moonbeam Dapp (request 2nd on file: https://docs.google.com/document/d/1TqTva5PXuag8VhOcNMkF5Kq9F3T_NSD5Mtb0G5sAgFo/edit?usp=sharing)

**Comment by Sokol142196** [comment]
Applied new UI => Close this issue
