### ISSUE TITLE
Display connection information with DApps

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#469]
**Is your feature request related to a problem? Please describe.**
We need to show more information for users who connected DApp to SubWallet

**Describe the solution you'd like**
Show information about the connection of the active tab on the home screen by changing the features of the "Account Visibility" icon like MetaMask did.
![image](https://user-images.githubusercontent.com/11567273/180366398-3b543957-6fe2-47ec-b97b-057992be91e1.png)
![image](https://user-images.githubusercontent.com/11567273/180366441-9b76b713-5cb1-4018-b38b-f4e7cce34adb.png)

- [x] This icon needs to show connection information with the currently DApp in the active browser tab
  - Gray: Not connected
  - Green: Connected with current account
  - Red: Not connected with a current account
  - Red with blocked icon: DApp in the blacklist
- [x] Show these icons on all account
  - Gray: Not connected
  - Green: accepted accounts nums == max account num (Detect by auth type)
  - Yellow: 0 < accepted accounts nums < max account num (Detect by auth type)
  - Red: accepted accounts nums == 0
  - Red with blocked icon: DApp in the blacklist
- [x] Not connected popup
- [x] Blocked popup (DApp in black list)
- [x] Click this icon need to open a popup of Dapp access config: https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=4192%3A13226&scaling=min-zoom&page-id=4%3A14

**Comment by hieudd** [comment]
@S2kael pls check this issue: https://www.loom.com/share/c698ade20835442fad4e78695117ba8c

**Comment by hieudd** [comment]
@S2kael pls check issue when connect with substrate DApp
![Screen Shot 2022-07-27 at 3 00 46 PM](https://user-images.githubusercontent.com/2582652/181195309-181dde30-4fb9-4fae-9900-2ea42b848c12.png)

**Comment by sokol142** [comment]
Bugs:
- [ ] Still show connected icon when user click on Forget Site
**Steps:**
1. Open the extension
2. Open any dApp (example: https://apps.karura.network/)
3. Connected to dApp successfully
4. Go to Manage Website Access screen then open Karura dApp
5. Click on Forget Site then observe connection icon displayed
**Actual:** Still show connected icon
**Expected:** Show not connected icon
- [ ] Showing incorrect icon on Expand extension
**Expected**: Remove the connect icon from the expand screen
