### ISSUE TITLE
Show wrong account on the allow list by dApp type in case of upgrade version

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#473]
**Description the bug**
Show wrong account on the allow list in case of upgrade version

**To reproduce the bug**
Steps:
1. Install extension (v0.4.5)
2. Create account successfully (both Substrate & EVM Account)
3. Open the dApp (example: polkadot js app)
4. Connect to dApp successfully
5. Update extension to v0.4.9 or latest version (v0.5.1)
6. Reload Polkadot js app
7. Select connect on popup re-connect dApp
8. Go to Manager Website Access screen then observe allow list displayed

**Actual**: Still EVM Account on allow list of polkadot js app

![Image](https://user-images.githubusercontent.com/102292476/180402862-bd0c0b29-63d7-4ce3-9892-d0e8387412a5.png)

**Expected**: Showing correct allow list by dApp type

Version test: v0.5.1

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./546-merge-build-0.5.4-1660200361029.zip

Validation failed! Still reproduce the bug. Please double check!
![473_validation](https://user-images.githubusercontent.com/102292476/184469979-edace853-bb0e-4601-899c-6ca8ca032381.gif)

**Comment by S2kael** [comment]
Because before version 0.4.5, dApp can't connect with EVM account, so it is unnecessary to handle migrate from type `evm | both`. I only handle migrate from type `substrate`
