### ISSUE TITLE
Support token import for PSP-22 and PSP-34

### ISSUE THREAD

**Issue by RottenKiwi** [Koniverse/SubWallet-Extension#477]
**Is your feature request related to a problem? Please describe.**
I cannot add/import/see my PSP22/34/35 tokens on Aleph zero testnet or mainet, therefore it is related to a problem.

**Describe the solution you'd like**
A elegant solution would be to add add/import button, where user could paste the token contract address. 

**Describe alternatives you've considered**
The only possible way to show the user his PSP22 token balance amount is by using polkadot API.

**Additional context**
...

**Comment by NamPhamc99** [comment]
Hi there, can you give me some more clues into these tokens ?? I can't find any information about them.

**Comment by RyanDinh8** [comment]
**From the Panorama Swap team:** 

_"We actually have an idea, for starters, I've suggested this for Nova wallet as well, to implement PSP22 token tracker (Import PSP22 tokens to track balances)

I've done a research and discovered that projects from Aleph zero, Acala and Kusama using PSP22 token standard and PSP33/34 (NFT)"_

**Here is the documentation:** https://docs.openbrush.io/smart-contracts/PSP22/

Please work on it.

**Comment by NamPhamc99** [comment]
Related issues:
#635

**Comment by NamPhamc99** [comment]
- [ ] Experiment how to interact and integrate WASM tokens
- [ ] Refactor token import to support both EVM and WASM tokens
- [ ] Update UI for importing WASM tokens
- [ ] Update token validating logic and tokens storing logic
- [ ] Showing PSP-22 token balance and PSP-34 token as NFT
- [ ] Support sending PSP-22 and PSP-34 tokens

**Comment by NamPhamc99** [comment]
Sending PSP tokens will be resolved in issue #742

**Comment by sokol142** [comment]
version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./741-merge-build-0.6.7-1-1666239070377.zip

Please check issue:

- [ ] Do not import PSP token when stand on All Accounts or EVM Account
- [ ] Show incorrect chain list
- The following chains are missing: Shiden EVM, Pangolin EVM, Shibuya Testnet EVM

- [ ] Can't clear text on the "NFT collection name" field
- [ ] Do not show the warning message when the user selects chain again

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./741-merge-build-0.6.7-1-1666351021527.zip

Validation passed!
