### ISSUE TITLE
Wrong balance display due to data caching

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#481]
**Describe the bug**

- [x] Wrong balance display due to data caching
- [ ] Still loading when open NFT Tab

**To Reproduce**
Video: Video Detail: https://www.loom.com/share/c9a6a9f9b99d4ebd9d34a27d39e9da94

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Browser Chrome
 - Version 103.0.5060.134 (Official Build) (arm64)

**Comment by sokol142** [comment]
Version test: https://drive.google.com/file/d/1bBF9j7Qpfx6zlGS6td4sszldf776ElMY/view?usp=sharing
- validation passed! (Crowdloans)
![481_crowdloan_validation](https://user-images.githubusercontent.com/102292476/180957781-07bc47c0-1deb-4906-a6c4-aac31bdb2789.gif)
