### ISSUE TITLE
Integrate tokens for dapps on Moonbeam/Moonriver

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#485]
**Describe the solution you'd like**
Please add tokens (ERC-20 and ERC-721) for new layer2 dapps on the Moonbeam/Moonriver ecosystems:

- [x] Athos Finance:
- AthosNFT: 0xCF82ddCca84d0E419BCcD7a540E807c114250DeD
- $ATH: 
- Network: Moonbeam
- [x] Moonwell Artemis
- $WELL: 0x511ab53f793683763e5a8829738301368a2411e3
- Network: Moonbeam

**Comment by sokol142** [comment]
@S2kael Please check:
Bugs:

- [ ] Can not send WELL token

- Actual: When user select WELL then automatically close Send fund screen
![485_bug_sendAsset](https://user-images.githubusercontent.com/102292476/181230375-267d5eee-4daa-4567-8276-c9cf82ef0ac1.gif)

- Expected: Send WELL tokens successfully

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./491-merge-build-0.5.2-1658921521417.zip

Validation pass!

![Image](https://user-images.githubusercontent.com/102292476/181425651-cf49aec9-2b6b-47f2-b7bd-2c14ba1a3a55.gif)
