### ISSUE TITLE
Update response information of EVM Provider

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#489]
## Overview
Review overall EVM Provider and update response message in some cases:
- [x] Response error code for evm provider
- [x] `eth_chainId`, `net_version`, If there is no EVM network enabled should be null/undefined/0 instead of Chain Disconnected Error
- [x] Request permission should return 4001:User Rejected Error

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./506-merge-build-0.5.2-1659087721145.zip

Validation passed cases:
- Request permission/Connect
- Add/Switch network
- Send Transaction
- Sign Data
