### ISSUE TITLE
Bug adding default EVM token after deleting it

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#490]
### Describe the bug
After delete default EVM token, cannot re-add this token in extension

**Comment by sokol142** [comment]
Please re-check case re-add custom tokens after delete

- Version test: v0.5.2 (chrome store)

https://user-images.githubusercontent.com/102292476/181161821-a68752c2-8861-4e33-9d84-c8b4377d7f3e.mp4

**Comment by sokol142** [comment]
Validation passed!

- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./493-merge-build-0.5.2-1658906939044.zip
