### ISSUE TITLE
Bugs: Display connection information with DApps

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#498]
Bugs:
- [x] Still show connected icon when user click on Forget Site
**Steps:**
1. Open the extension
2. Open any dApp (example: https://apps.karura.network/)
3. Connected to dApp successfully
4. Go to Manage Website Access screen then open Karura dApp
5. Click on Forget Site then observe connection icon displayed
**Actual:** Still show connected icon
**Expected:** Show not connected icon
- [x] Showing incorrect icon on Expand extension
**Expected**: Remove the connect icon from the expand screen

- [x] Show not connected icon after attached external QR-signer account successfully #358

**Steps:**
1. Open the popup extension
2. Connected to the dApps successfully (example: connect.subwallet.app) & stand on this dApp
3. Perform attached external QR-signer account successfully
4. Switch to All account then click on connection icon
5. Observe List account displayed
6. Switch to attached account in Step 3 then check connection icon of this account

**Actual:** 
- Step 5: Not show account that attach external QR-signer on List account
- Step 6: Show not connected icon

**Expected:** Show disconnected icon & display account on List account to connect

https://user-images.githubusercontent.com/102292476/181407551-ce5cae04-e1ea-42a9-b557-a1703c9aa5da.mp4

_Originally posted by @sokol142 in https://github.com/Koniverse/SubWallet-Extension/issues/469#issuecomment-1196627611_

**Comment by sokol142** [comment]
Validation pass!
**Validation case 1+2:**
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./502-merge-build-0.5.2-1659066181673.zip
![498_Validation_case1_2](https://user-images.githubusercontent.com/102292476/181909163-6569483c-f325-4248-96df-727b2645c603.gif)

Validation case 3: 
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./503-merge-build-0.5.2-1659080072551.zip
![498_Validation_case3](https://user-images.githubusercontent.com/102292476/181909046-c30d8d53-549e-4ee9-a33a-a7fef88520a3.gif)
