### ISSUE TITLE
Token information is overwritten when importing another token with the same name

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#511]
Description the bug
Token information is overwritten when importing another token with the same name

To reproduce the bug
Pre-condition: already MFG token (pre-defined token), (contract address: 0xc2bFd8e028b342F0537aDC2bF310821c807c1312)
Steps:
1. Open the extension
2. Switch to any EVM account then go to the Token detail screen and check MFG balance displayed
3. Perform import another MFG token (contract address: 0xb161b2da48de283ec22bafbc36e5551c892629a2)
4. Go to Token detail screen then check balance displayed
5. Go to Manage EVM Token screen
6. Select MFG then delete token
7. Back to token detail screen then re-check balance displayed

Actual: Token information is overwritten
- In step 4: MFG balance is changed
- In step 7: MFG pre-defined token is deleted

https://user-images.githubusercontent.com/102292476/181897266-a4b11a07-8fd1-4b0d-b460-5216b9eb11cc.mp4

**Comment by NamPhamc99** [comment]
New architecture will fix this issue

**Comment by sokol142** [comment]
Consider the case when two custom tokens have the same symbols would look exactly the same on UI (due to no logo)

**Comment by sokol142** [comment]
Resolved it in the new UI version
