### ISSUE TITLE
Polkadot JS component Issues

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#514]
Polkadot JS component Issues:

### Input

1. xc Token balance cannot be obtained
2. Input can only round number up to 4 decimals

**Comment by NamPhamc99** [comment]
Related issue:
#471 

Description:
Polkadot.js input can only round number up to 4 decimals which causes a lot of problem with small balances

**Comment by NamPhamc99** [comment]
Add tooltips, guidance and notifications to inform users

**Comment by NamPhamc99** [comment]
Resolved in new UI design system
