### ISSUE TITLE
Support staking for cross-chain tokens inside parachains

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#515]
**Is your feature request related to a problem? Please describe.**
Please add support for built-in staking for cross-chain tokens inside parachains:

- [ ] Moonbeam/Moonriver: (via Lido Finance)
- xcDOT: https://docs.polkadot.lido.fi/ 
- xcKSM: https://docs.kusama.lido.fi/
- [ ] Updating...

**Comment by NamPhamc99** [comment]
This should be implemented under the smart contract interaction feature
