### ISSUE TITLE
Add Moonpets NFT

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#517]
**Is your feature request related to a problem? Please describe.**
Please add support for Moonpets NFT on SubWallet. This is their smart contract address: 0x2159762693c629c5a44fc9bafd484f8b96713467

**Comment by sokol142** [comment]
Validation passed!
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./519-merge-build-0.5.3-1659495033542.zip

![image](https://user-images.githubusercontent.com/102292476/182525135-2228b661-5bb5-4929-8d2d-acb882ad1b80.png)
