### ISSUE TITLE
Not trigger accountChanged when changed account list and submit authList of DApp

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#518]
**Describe the bug**

**To Reproduce**
1. Connect DApp with extension (Eg: SubConnect)
2. Select All account in the wallet
3. Change account from Auth List
  a. Case 1: Change account in account list then submit
  ![image](https://user-images.githubusercontent.com/11567273/182505172-0fb39976-fb90-4f27-a182-44382ea26b39.png)
  b. Case 2: Change toggle in account list in setting
  ![image](https://user-images.githubusercontent.com/11567273/182505508-2fbaa427-ff8c-44f0-8926-12f99c95a9f1.png)
4. Account changed event is not triggered (DApp not reload)

**Expected behavior**
Account changed event should be triggered (DApp reload)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./537-merge-build-0.5.4-1660205428063.zip

- [ ] Please check: Can not astar app when create new account

![image](https://user-images.githubusercontent.com/102292476/184113669-30606779-d52c-4c4f-9bfd-46fca64628b9.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./537-merge-build-0.5.5-1660701907314.zip

Validation passed for cases:
- Connect wallet
- Change account
- Add/Forget account
- Block site
- Change toggle connect in account list in setting
