### ISSUE TITLE
Change the logo of xcINTR, xciBTC, xckBTC, xcCSM, xcSDN, xcKMA, xcLIT, xcCRAB, xcTEER

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#524]
**Is your feature request related to a problem? Please describe.**

- [x] The logo of xcINTR, xciBTC, xckBTC, xcCSM, xcSDN, xcKMA, xcLIT, xcCRAB, xcTEER on SubWallet are not correct. Please change it.

Also, please change
-  "xcIBTC" to 'xciBTC"; and "xcKBTC" to "xckBTC (On Moonbeam and Moonriver)
- "IBTC" to "iBTC": and "KBTC" to "kBTC" on Interlay and Kintsugi

<img width="456" alt="Screen Shot 2022-08-05 at 14 15 05" src="https://user-images.githubusercontent.com/102496727/183023558-2fd0acb7-8035-494e-a139-809cda95cafc.png">
<img width="455" alt="Screen Shot 2022-08-05 at 14 15 22" src="https://user-images.githubusercontent.com/102496727/183023575-97dacf72-f568-4938-941e-8aea89aafe18.png">

- [x] Update $ Balance of INTR, xcINTR, xciBTC, xckBTC, xcCSM, xcSDN, xcKMA, xcLIT, xcCRAB, xcTEER
![image](https://user-images.githubusercontent.com/102292476/183553519-f5119750-e0bc-44e4-8b43-f7fe6d2972a0.png)

- [x] Update URL explorer for Bifrost-kusama chain
![image](https://user-images.githubusercontent.com/102292476/183338267-dc58b1e5-6c7b-41e0-9d42-7c1bc232284c.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./596-merge-build-0.5.6-1661752787114.zip
Please re-check issue 1 & 3

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./604-merge-build-0.5.6-1662358981100.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/188395154-e154f17a-fdee-423c-919e-363aa9de4d26.png)
![image](https://user-images.githubusercontent.com/102292476/188395344-6ff4fbb4-6d65-40c6-90e5-684976a014f4.png)
![image](https://user-images.githubusercontent.com/102292476/188395545-7081e23d-e3e1-4d5e-b6ab-973ddcb2c82a.png)
![image](https://user-images.githubusercontent.com/102292476/188395602-7be9de52-d9ab-4b54-9af9-c60bb7b0eb95.png)
