### ISSUE TITLE
Add documentation for EVM Provider

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#529]
Add documentation for EVM Provider:
- Overview of EvmProvider and SubWallet EVM Provider (https://github.com/Koniverse/SubWallet-Extension/issues/235)
- Getting Started (How to connect with `window.SubWallet`)
- Methods
- Events
- Connectors: 
  - web3-react-v6-connector
  - wagmi-connector

**Comment by montogeek** [comment]
Where is this documentation?

**Comment by NamPhamc99** [comment]
hi @montogeek, is this what you're looking for? https://github.com/Koniverse/SubConnect/wiki/Integrate-SubWallet-with-EVM-DApp
