### ISSUE TITLE
Non-Evm

### ISSUE THREAD

**Issue by usmanhashmis** [Koniverse/SubWallet-Extension#534]
Hi!
Sir many people need a non-Evm system. So kindly add this feature.
It means a single address and we'll receive multiple coins(trx,xrp,ada,dot, etc) through a single address

**Comment by NamPhamc99** [comment]
Thanks for the attention. Can you specify a bit more in detail what you need ? Sounds like you want us to integrate blockchains other than Polkadot ecosystem (Tron, Ripple, Cardano,..).

**Comment by usmanhashmis** [comment]
I mean to say :
Let c we receive multiple coins( trx , xrp , eth, btc, etc )
one Address for all chains coins receiving :
1 receiving address  = if send TRX then deposit this address and if send
SOL then deposit also this address.
And wallet show all coins

I think you understand

**Comment by NamPhamc99** [comment]
Okay, I get what your idea. We're working toward a solution where users can just use 1 address (or 1 account) for all parachains in Polkadot/Kusama ecosystem so be patient with us. But we don't have any plan to integrate blockchains that are not in the Polkadot/Kusama ecosystem (TRX, XRP, SOL,...). Hope this can clear things out for you.
