### ISSUE TITLE
Integration Ledger EVM account

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#538]
### Integration Ledger EVM account

Add Moonbeam, Moonriver, Ethereum,... to list ledger network support

=> Ledger information

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/4fe90660-019b-464a-96a5-1292b79e0cf6)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1504-build-1.0.8-2023-06-08T08-02-36UTC.zip

Improve:

- [ ] Disable Send button when choosing a token that is not supported with Ledger account
- [ ] Update network on the Select network to connect Ledger device

![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/d06aa424-af8b-4900-85b6-cb6e74c925a4)


![Image](https://github.com/Koniverse/SubWallet-Extension/assets/130966515/fd7d35c6-8d06-4509-83c2-589bb26a70a4)


Re-test later: XCM feature.

**Comment by Sokol142196** [comment]
- [ ] Error occurs when user connects Ledger device in case no network is enabled
   - Expect: Default list = All networks supported by Ledger
      - When user connect network successfully then auto-turn on selected network
         - Polkadot, Kusama, Acala -> turn on network and all token of the network
         - EVM networks -> enable Ethereum and networks with balance

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1504-build-1.0.9-0-2023-06-13T03-51-58UTC.zip

Validation passed for cases:
- Connect Ledger EVM account
- Show balance 
- Send token: pre-defined token (GLMR, DEV), custom token (MFG)
- Send NFT: pre-defined NFT, custom NFT (Moonbeast)
- Receive
- Buy
- Connect dApp and perform transactions from dApp

Notes: List token do not supported by Ledger EVM account:
- CKTON (Crab 2 Parachain)
- KTON (Darwinia2)
- CKTON (Pangolin)
