### ISSUE TITLE
Recovery account

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#549]
**Is your feature request related to a problem? Please describe.**
Recovery account feature follow Polkadot JS

![Screen Shot 2022-08-11 at 7 01 39 PM](https://user-images.githubusercontent.com/2582652/184129233-57fbb911-97e8-45d3-863c-7c9bbe970346.png)

**Comment by sokol142** [comment]
Same as https://github.com/Koniverse/SubWallet-Extension/issues/1210
