### ISSUE TITLE
Support xcm transfer on Kusama, Polkadot, Astar, Shiden chain for QR/Ledger Account

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#552]
### Support xcm transfer Kusama, Polkadot, Astar, Shiden for QR Account:
Details:

- [x] Polkadot -> Moonbeam/Astar/ Acala
- [x] Kusama -> Moonriver/Shiden/Karura
- [x] Astar -> Acala/Polkadot
- [x] Shiden -> Karura/ Kusama 

Follow issue: #411

### Support xcm transfer Kusama, Polkadot for Ledger Account:
- [ ] Polkadot -> Moonbeam/Astar/ Acala
- [ ] Kusama -> Moonriver/Shiden/Karura

_=> Dev comment: For Ledger Account, Polkadot and Kusama App not support XCM method_

**Comment by S2kael** [comment]
At this time, Polkadot and Kusama App not support XCM method
https://github.com/Zondax/ledger-polkadot
https://github.com/Zondax/ledger-kusama

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./560-merge-build-0.5.5-1660709939675.zip

Validation passed for:
- Polkadot -> Moonbeam/Astar/ Acala
- Kusama -> Moonriver/Shiden/Karura
- Shiden -> Karura/ Kusama

Testing later: Astar -> Acala/Polkadot (https://github.com/Koniverse/SubWallet-Extension/issues/571)

**Comment by sokol142** [comment]
@S2kael Please add support Bifrost chain (follow this issue: https://github.com/Koniverse/SubWallet-Extension/issues/333)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./560-merge-build-0.5.5-1660897098135.zip

Please check issue:
Incorrect transaction history when transfer:

- [ ] KAR token (from Bifrost to Karura) 

![image](https://user-images.githubusercontent.com/102292476/185832574-ce21447e-2f50-4266-8c69-1233c086fc8f.png)

- [ ] BNC (from Karura to Bifrost)

![image](https://user-images.githubusercontent.com/102292476/185833849-7b93db7f-8941-4535-bd68-b12290cdfb45.png)

- [ ] KSM (from Bifrost -> Kusama)
![image](https://user-images.githubusercontent.com/102292476/185834340-ab2f4993-4a4a-4421-aae4-cca44597ceb1.png)

**Comment by sokol142** [comment]
Validation Passed!
- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./560-merge-build-0.5.6-1661346290239.zip

Validation record:
[552_Validation.zip](https://github.com/Koniverse/SubWallet-Extension/files/9429355/552_Validation.zip)
