### ISSUE TITLE
Add Suspace testnets into SubWallet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#553]
**Is your feature request related to a problem? Please describe.**
Subspace is running a number of testnets, please add them into SubWallet:

- [x] Subspace Gemini 1b - gemini-1b.subspace.network
- [x] Subspace Farmnet - farm-rpc.subspace.network

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./559-merge-build-0.5.5-1660645525667.zip
![image](https://user-images.githubusercontent.com/102292476/184870568-ec495d96-d5d8-452d-90f7-65d80b3dda67.png)
