### ISSUE TITLE
Create PR for the ArthSwap team to integrate SubWallet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#554]
**Is your feature request related to a problem? Please describe.**
The ArthSwap team is lacking human resources to integrate SubWallet. Please create a PR for them to integrate SubWallet. Below is their Github:
- https://github.com/ArthSwap/arthswap-core

**Comment by NamPhamc99** [comment]
https://github.com/arth-s/arthswap-interface/pull/342
