### ISSUE TITLE
Bug showing balance on very small balance

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#556]
Cause: formatting string of float number

![image](https://user-images.githubusercontent.com/44641118/184602430-d75e765f-c7e6-4420-9966-5e8cb70e6e79.png)

**Comment by sokol142** [comment]
Validation passed!

- Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./543-merge-build-0.5.5-1660557685786.zip

![image](https://user-images.githubusercontent.com/102292476/184785370-ac0f2d0a-8466-416d-9253-dbc8e415f672.png)
