### ISSUE TITLE
Add new networks to SubWallet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#558]
**Is your feature request related to a problem? Please describe.**
Please add new networks to SubWallet:

**- Parachain winners**
- [x] Amplitude: https://parachains.info/details/amplitude
- [x] GM Parachain: https://parachains.info/details/gm_parachain (Token: FREN)
- [x] Integritee Polkadot: https://parachains.info/details/integritee_polkadot 
- [x] Integritee Kusama
- [x] Tanganika Network: https://twitter.com/DataHighway_DHX
- [x] Coinversation: https://twitter.com/Coinversation_

**- Others:**
- [x] Ternoa Network: A EMV compatible network built on Substrate, aiming to secure a parachain slot in the future.
- Website: https://www.ternoa.com/
- RPC: wss://mainnet.ternoa.network

**Comment by NamPhamc99** [comment]
Coinversation will be added later when more information is available

**Comment by sokol142** [comment]
Please recheck this issue when send fund CAPS (Ternoa EVM)https://media.discordapp.net/attachments/961837378580922368/1009405564876496967/unknown.png

**Comment by NamPhamc99** [comment]
Temporarily remove Ternoa EVM until more information is available

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./559-merge-build-0.5.5-1660815436234.zip

Integrated:
- Amplitude (Tokens: AMPE)
- GM Parachain (Token: FREN)
- Integritee Polkadot/ Integritee Kusama (Token: TEER)
- DataHighway Tanganika Network (Token: DHX)
- Ternoa Mainnet (Token: CAPS)

**Comment by RyanDinh8** [comment]
Please add new parachain winners:

- [ ] SNOW: https://parachains.info/details/snow 
- [ ] Aventus: https://parachains.info/details/aventus_network
