### ISSUE TITLE
Bug parsing Acala crowdloan data

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#568]
Cause:
Data format from the API is changed.

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.5.5-1661152078729.zip

Validation passed!
- IcAmount --> totalDOTLocked
![image](https://user-images.githubusercontent.com/102292476/186065045-157996ee-c4b5-4abe-b6bf-9fbfa6cf9f81.png)
