### ISSUE TITLE
Some issues related to connect to Astar Portal

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#570]
Description the issue:

- [x] Improve UX in case of don't have any EVM/Substrate Account

![Image](https://user-images.githubusercontent.com/102292476/185284606-d7ba4556-c0bb-482c-ae84-aa2eecf4911a.png)

Expected: Only show popup when user choose to connect to EVM

Other issues: 

- [x] Not detect SubWallet when user cancel connection: https://www.loom.com/share/f0d50431ae4a48d493a2fe2b59162ca0
- [x] Do not connect to previously connected accounts

**Comment by NamPhamc99** [comment]
To be resolved later. Requires support from Astar team

**Comment by NamPhamc99** [comment]
Resolved in this issue
https://github.com/AstarNetwork/astar-apps/issues/494
