### ISSUE TITLE
Re-check XCM transfer feature for Astar

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#571]
Description the bug:
When I perform XCM transfer from Astar to Acala then:

- [x] Send successfully but both Sender Account balance and Receiver Account balance are not updated
- [x] Transaction history show 0 aUSD

![Image](https://user-images.githubusercontent.com/102292476/185378368-23d2bb28-e48b-4058-b155-0832e9e93ad1.png)

Notes: Before, it sent successfully (validation in #472 )

**Comment by NamPhamc99** [comment]
XCM transfers to Acala is temporarily disabled to due to a technical issue on Acala
