### ISSUE TITLE
Improved decimal display UX

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#585]
**Is your feature request related to a problem? Please describe.**

- [x] Improved decimal display UX: Display decimal with Opacity: 0.6

### Display decimals according to the following rule => Improve later https://github.com/Koniverse/SubWallet-Extension/issues/599
- If the number is greater than 1, display only 2 decimals
- If the number is less than 1, display it according to the current decimal rule

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./587-merge-build-0.5.6-1661512003660.zip

Validation passed on views:
- Total balance
- Crypto tab
- Crowdloans tab
- Staking tab
- Transfer tab
- Send fund/xcm transfers/staking/unstake/withdraw/claim reward screen
- Authorize transaction screen

**Comment by sokol142** [comment]
@S2kael Rule for display decimals according apply to most screens, except for authorize screens of actions:
- Send fund
- XCM transfer
- Stake/ Unstake/ Withdraw/ Claim reward
Display it according to the current decimal rule

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./587-merge-build-0.5.6-1661767840664.zip

Validation passed for update opacity
