### ISSUE TITLE
Auto update metadata: Auto update metadata via API, not required update from polkadot-js/app

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#588]
**Description**
- [x] Auto update metadata: Auto update metadata via API, not required update from polkadot-js/app

Convert from issue https://github.com/Koniverse/SubWallet-Extension/issues/525

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1638-build-1.1.1-2023-07-12T05-10-32UTC.zip

Re-check for Rococo and kindly re-check all netwotk

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1638-build-1.1.2-2023-07-18T07-48-01UTC.zip

Validation passed.
Notes: Need to enable network to auto-update metadata
