### ISSUE TITLE
Bug inject provider not auto remove

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#591]
Inject script in unwanted page
![image](https://user-images.githubusercontent.com/11567273/187118116-acca74a1-6dcc-48c9-847e-964f271a8f4c.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./597-merge-build-0.5.6-1661763038915.zip

Validation pass
