### ISSUE TITLE
Integrate Gear testnet into SubWallet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#605]
**Is your feature request related to a problem? Please describe.**
Please add support for Gear testnet:
- Name: Gear Staging Testnet
- RPC: wss://rpc-node.gear-tech.io

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./606-merge-build-0.5.6-1662436354489.zip

Validation passed

![Image](https://user-images.githubusercontent.com/102292476/188554697-4a7a596d-2c23-4f2d-9d74-ae0149f3b23c.png)
