### ISSUE TITLE
Add new networks (new parachain winners)

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#608]
**Is your feature request related to a problem? Please describe.**
Please add new parachain winners:

- [x]  SNOW: https://parachains.info/details/snow
- [x] #646

Note:
Add Arctic Testnet first
Snow Parachain is not live yet
Aventus network will be resolved later in another issue

**Comment by NamPhamc99** [comment]
Adding Arctic Testnet first, Snow Parachain will be live soon
