### ISSUE TITLE
Improved handling for case the NFT's source failure

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#619]
Improve issue #611

Description:
- Actual: Hot fix by disable ipfs-gateway.cloud source
- Expected: @huukhai @NamPhamc99 please describe in detail

**Comment by NamPhamc99** [comment]
To be resolved after architecture update
=> Automatically and dynamically update IPFS gateway

**Comment by sokol142** [comment]
Resolve later in https://github.com/Koniverse/SubWallet-Extension/issues/1300
