### ISSUE TITLE
Integrate Bit.Country Token and XCM

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#621]
**Is your feature request related to a problem? Please describe.**
- Support BIT (tokens > MiningResource > 0)
- XCM - between Bit.Country Pioneer <> Karura (pipeline: Moonriver, Shiden Network)

**Comment by NamPhamc99** [comment]
- [ ] NEER: Pioneer -> Karura
- [ ] NEER: Karura -> Pioneer
- [ ] Display BIT token on Pioneer (transferring not supported)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./630-merge-build-0.5.9-1663042453066.zip

Validation passed for case:
- Integrated Pioneer Network (tokens: NEER, BIT)
- XCM transfer NEER (Pioneer <=> Karura)
_Validation record_
[621_Validation.zip](https://github.com/Koniverse/SubWallet-Extension/files/9553544/621_Validation.zip)

And, waiting for new logo for the BIT token
