### ISSUE TITLE
Support Bit.Country'NFT Trading and Land Portfolio

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#622]
**Is your feature request related to a problem? Please describe.**
- NFT Trading (Buy & sell) - Referral fee (batch call with remarkWithEvent)
- Land Portfolio (Buy & sell) - Referral fee

**Comment by NamPhamc99** [comment]
- [ ] Support showing Land/Estate from metaverses on Pioneer

**Comment by Sokol142196** [comment]
Resolve on https://github.com/Koniverse/SubWallet-Extension/issues/1335
