### ISSUE TITLE
Create a PR request to integrate SubWallet into Rainbowkit

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#624]
**Is your feature request related to a problem? Please describe.**
Please create a PR request to integrate SubWallet into Rainbowkit
- https://github.com/rainbow-me/rainbowkit

**Comment by S2kael** [comment]
PR: https://github.com/rainbow-me/rainbowkit/pull/1461

**Comment by Sokol142196** [comment]
The pull request has been merged => Closed issue
