### ISSUE TITLE
Update ArthSwap logo (ARSW token on Astar-EVM)

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#626]
Source: https://drive.google.com/drive/folders/1IAt_9XD4eEJ6fQThpwyalpaLZcJdQjmk

**Comment by sokol142** [comment]
Validation passed.
- Version test: 

![image](https://user-images.githubusercontent.com/102292476/189339012-4a5993eb-f3ae-4490-acc0-3c42198acb9a.png)
![image](https://user-images.githubusercontent.com/102292476/189339072-57efb966-a745-49d0-8cd3-ba06d460b194.png)
![image](https://user-images.githubusercontent.com/102292476/189340189-51957a55-4862-4301-8b81-85a12addafad.png)
