### ISSUE TITLE
Update existential deposit for XCM transfer feature & transaction history

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#631]
**Description**
- Not show a warning if your balance < existential deposit
- Show incorrect fee in the transaction history in case of user send fund/xcm transfer when balance < existential deposit

![Image](https://user-images.githubusercontent.com/102292476/189805214-2034b816-1753-4deb-894e-a677f1e94c98.png)

### To do
- [x] Update existential deposit for XCM transfer feature 
- [x] Update fee value on transaction history for this case

**Comment by NamPhamc99** [comment]
To be resolved after architecture update

**Comment by Sokol142196** [comment]
Add the validate when xcm transfer in the new UI version
