### ISSUE TITLE
Add staking for $CAPS and add support for Ternoa's testnet Alphanet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#636]
**Is your feature request related to a problem? Please describe.**

- [x] Add in-app staking for $CAPS 
- [x] Add support for Ternoa's testnet Alphanet: wss://alphanet.ternoa.com

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./678-merge-build-0.6.5-1664181745600.zip

Validation passed for cases:
- Stake/ stake more
- Unstake

Follow-up withdraw feature
