### ISSUE TITLE
Infinite loading when user stake DOT

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#641]
**Description the bug**
_(Feedback from user)
faleh27: Hi, I tried to stake some DOT but no luck. the screen is stuck like this.
Address: 15MsfqEFMdcELRki4eoUDfmL3JyLCrwts2vCVneTX5HHsYqv_

![Image](https://user-images.githubusercontent.com/102292476/190945206-24cebdde-31f8-42dd-a76e-608a7c8cc6f9.png)

**Comment by NamPhamc99** [comment]
Problem happened due to estimated fee being larger than number upper bound.
Refer to: https://github.com/paritytech/substrate/issues/4897
![image](https://user-images.githubusercontent.com/44641118/190962230-38a2b818-aee6-448e-80e7-98126731c657.png)

**Comment by NamPhamc99** [comment]
Temporarily fixed in #648
