### ISSUE TITLE
Integrate Aventus Network

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#646]
Integrate Aventus Network (a parachain winner on Polkadot)
Aventus requires specific use of their provider to maintain access control. Read more in their docs
https://parachains.info/details/aventus_network

**Comment by NamPhamc99** [comment]
To be resolved after architecture update

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1114-merge-build-0.8.3-1-1680250312584.zip

Validation passed for cases:
- Displayed
- Send token
![image](https://user-images.githubusercontent.com/102292476/229065956-d83eed39-6d28-4285-9a26-aacf0cb56d47.png)
