### ISSUE TITLE
Handle estimated fee error on NFT sending + staking

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#648]
**Describe the bug**
Problem happened due to estimated fee being larger than number upper bound.
This prevents the user from submitting transaction

**Expected behavior**
Catch error, set estimated fee to 0 if error happens.

**Comment by sokol142** [comment]
Version test:[ ](https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./659-merge-build-0.6.3-1663830162336.zip)

Validation passed.
