### ISSUE TITLE
Add support staking for Amplitude/Kilt

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#653]
**Is your feature request related to a problem? Please describe.**

- [x] Please add in-app staking for $AMPE (https://twitter.com/amplitude_chain)
- [x] Add staking for KILT

**Comment by NamPhamc99** [comment]
Amplitude has no staking mechanism.

**Comment by NamPhamc99** [comment]
Update: The staking pallet is live, Amplitude staking is being integrated

**Comment by NamPhamc99** [comment]
Amplitude and Kilt have the same staking pallet

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./807-merge-build-0.7.2-0-1668682361108.zip

Please check issue:

- [ ] Can't unstake a part
![image](https://user-images.githubusercontent.com/102292476/202601862-38c2df2e-aebc-4cf8-a5f8-21f81d927b22.png)

- [ ] Still allow user stake more when have already unstake all record

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.7.2-0-1668772901031.zip

Validation passed.
