### ISSUE TITLE
Integrate Polkaholic API for XCM transfer history

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#660]
**Is your feature request related to a problem? Please describe.**
Please integrate Polkaholic API for XCM transfer history. Here's the docs: https://docs.polkaholic.io/#xcm

**Comment by NamPhamc99** [comment]
Will be considered along with other 3rd-party data provider in the architecture update

**Comment by NamPhamc99** [comment]
Postponed until new notice
