### ISSUE TITLE
Improve extrinsic submitting flow and error handling

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#664]
- [x] Handle fee estimation error #648 
- [x] Use 1 flow and 1 UI for extrinsic submission (for all functionalities)
- [x] Design a system to handle error when submitting extrinsic

**Comment by sokol142** [comment]
Please check this bug below when staking on Ternoa Alphanet
![image](https://user-images.githubusercontent.com/102292476/192257384-1021bbc3-aa7a-4de9-b476-78c78907e3f8.png)

**Comment by NamPhamc99** [comment]
Done by new architecture
