### ISSUE TITLE
Support transfer BIT token on Pioneer Network

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#665]
Read more: https://github.com/bit-country/Metaverse-Network-Integration/blob/master/src/transfer-examples/bit-transfer.ts

**Comment by sokol142** [comment]
Version test:[ ](https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./666-merge-build-0.6.3-1663924909680.zip)

Validation passed
