### ISSUE TITLE
Temporarily disable XCM for Acala

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#667]
Due to an incident on Acala, XCM is temporarily disabled

Disable these paths:
- [x] Acala -> All other chains
- [x] Polkadot -> Acala
- [x] Moonbeam -> Acala
- [x] Astar -> Acala

Note: Karura's still functioning properly

**Comment by sokol142** [comment]
Version test:[ ](https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./668-merge-build-0.6.3-1663927566695.zip)

Validation passed
