### ISSUE TITLE
Update Zeitgeist endpoints

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#669]
Update Zeitgeist endpoints:

- [x] wss://zeitgeist.api.onfinality.io/public-ws
- [x] wss://zeitgeist-rpc.dwellir.com

**Comment by sokol142** [comment]
Version test:[ ](https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./670-merge-build-0.6.3-1663998224172.zip)

Validation passed
