### ISSUE TITLE
Documenting queries from SubSquid for update

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#674]
**Is your feature request related to a problem? Please describe.**
SubSquid is updating their APIs. They need to know all existing SubSquid queries in order to update the schemas accordingly

SubWallet is only using staking reward data provided by SubSquid. The query is:

```
query MyQuery {
  accountById(id: "${account}") {
    totalReward
    totalSlash
    totalBond
    rewards(limit: 1, orderBy: blockNumber_DESC) {
      amount
    }
  }
}
```

Overall, the API is great and the data is accurate but we would also like to add some comments and suggestions for the SubSquid team.

Suggestions: 
- [ ] Would be great if the API provides bonded amount per validator/collator
- [ ] Astar requires user to claim reward manually, would be great if SubSquid can provide claimable reward data and the total claimed reward.
- [ ] Support transaction history data for more chains: Aleph Zero, SubSpace,...
- [ ] API for transaction history for XCM

**Comment by belopash** [comment]
hi, this query should do the same as yours
```
query MyQuery {
  stakerById(id: "${account}") {
    totalReward
    totalSlash
    activeBond
    rewards(limit: 1, orderBy: blockNumber_DESC) {
      amount
    }
  }
}
```

**Comment by NamPhamc99** [comment]
Close for now. Any update will be in a different issue
