### ISSUE TITLE
Incorrect transaction history in case of user perform transaction from dApp

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#675]
**Description the bug**
Incorrect transaction history in case of user perform transaction from dApp

Steps:
1. Open the extension
2. Open the moonbeam app then go to staking action (https://apps.moonbeam.network/moonbase-alpha/staking)
3. On the moonbeam app, user perform staking successfully
4. Back to extension
5. Go to Transfer tab, observe transaction history displayed

Actual: Showing incorrect transaction history

![Image](https://user-images.githubusercontent.com/102292476/192199286-cd47994e-419b-4746-a12b-e30d992548f1.gif)

Notes: Some pages do not save transaction history (polkadot.js app) => Discussion more

**Comment by NamPhamc99** [comment]
Need to review and re-design the whole transaction history feature

**Comment by Sokol142196** [comment]
Resolve later in https://github.com/Koniverse/SubWallet-Extension/issues/1580
