### ISSUE TITLE
Add USDT on Polkadot

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#679]
**Is your feature request related to a problem? Please describe.**
$USDT is now available on Polkadot: https://tether.to/en/tether-tokens-usdt-live-on-polkadot

Please add USDT on parachains:

- [x] Statemint
- [x] Astar Native and Astar EVM (USDT is available on Astar from Sep 24, 2022)
- [x] Moonbeam

**Comment by NamPhamc99** [comment]
- [ ] Support token transfer on Statemint/Statemine
- [ ] Support XCM from/to Statemint/Statemine

**Comment by sokol142** [comment]
Update USDT token for more chains:
- Statemine
- Moonriver
- Shiden - EVM
