### ISSUE TITLE
Avatar All Account does not update when changing from collapse (popup)

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#68]
**Describe the bug**
Avatar All Account does not update when changing from collapse (popup)
Version test: V0.2.8 (18/03/2022)

**To Reproduce**

1. Open the wallet in both screens: Expand (Full Screen) and Collapse (popup)
2. Observe All Accoun's Avatar
3. Do Change Avatar from the popup and see the updated avatar: Avatar in Full Screen does not change, still displays the old Avatar => 2 forms with 2 different avatars

**Expected behavior**
Update Avatar after changing in any screen

**Screenshots**
![bug_avatar](https://user-images.githubusercontent.com/2582652/161203181-b5323ee1-f02b-4f9d-862b-aa2b37edca3e.gif)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Brave

**Comment by sokol142** [comment]
Other case.
**Describe the bug**
Avatar All Account does not update when changing from collapse (popup) in Firefox browser
Version test: V0.2.8 (18/03/2022)
Browser test: Firefox

**To Reproduce**
Steps to reproduce the behavior
1. Open the wallet in popup screen
2. Observe All Accoun's Avatar
3. Do Change Avatar from the popup and observe the updated avatar

**Actual**: Avatar does not change, still displays the old Avatar
**Suggestion**:
1. Disable button Change Avatar in popup screen (only aplies to Firefox browser) => I choose this option.
2. Open expand screen when click on Change Avatar button from popup screen.
![bug_avatar_firefox](https://user-images.githubusercontent.com/102292476/161512266-e42c7782-9559-4d0c-a747-c14a7e251429.gif)
