### ISSUE TITLE
Support transfer and XCM for Statemine/Statemint

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#684]
- [x] Transfer tokens (DOT, USDT) within Statemine/Statemint
- [x] USDT: Statemint -> Astar
- [x] USDT: Statemint -> Moonbeam
- [x] DOT: Polkadot <-> Statemint

Related issues: #679

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./693-merge-build-0.6.6-1664858514195.zip

Please check issues:

- [ ] Update price for DOT (Statemint) token
![image](https://user-images.githubusercontent.com/102292476/196336558-c14872c0-e8a9-45bf-8f0d-092118d193c9.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./693-merge-build-0.6.7-1-1666841881733.zip

Validation passed for cases:
- Send DOT, USDT token on Statemint
- XCM DOT: 
   - Statemint --> Polkadot
- XCM USDT: 
   - Statemint --> Moonbeam

Notes:  XCM DOT: Polkadot --> Statemint (Pending, test later)
Please check issue:

- [ ] XCM USDT: Statemint --> Astar/Astar EVM
- Actual: Do not receive USDT

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./693-merge-build-0.6.7-1666866557708.zip

Validation passed!
Validation record: 
[684_Validation.zip](https://github.com/Koniverse/SubWallet-Extension/files/9884706/684_Validation.zip)
