### ISSUE TITLE
Update Acala endpoints

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#685]
OnFinality nodes will apply rate limit => Update other endpoints

https://wiki.acala.network/integrate/acala/endpoints
https://wiki.acala.network/integrate/karura/endpoints

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./686-merge-build-0.6.5-1664508276650.zip

Validation passed!

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./686-merge-build-0.6.5-1664508276650.zip

Validation passed!
