### ISSUE TITLE
Update provider URL for some chain

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#697]
**Actual:** Some chains can't be connected (unable to connect):
- Bajun
- Bifrost Testnet
- Other chain: Acala Mandala TC7, Ares Odyssey, Dolphin Testnet, MangataX Public Testnet, Manta, OPAL by UNIQUE, SubGame, Subsocial

**Expected:** Update provider URL for the chain to connect successfully

**Comment by NamPhamc99** [comment]
- [ ] Update Bajun
- [ ] Update Bifrost testnet
- [ ] Update default provider of Acala Mandata TC7
- [ ] Remove Ares Odyssey
- [ ] Update Dolphin Testnet
- [ ] Update MangataX
- [ ] Remove Manta (duplicated)
- [ ] Update OPAL
- [ ] Remove SubGame
- [ ] Remove Subsocial (duplicated)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./701-merge-build-0.6.6-1665055395943.zip

Validation passed.
