### ISSUE TITLE
Looping reconnecting issue

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#702]
![image](https://user-images.githubusercontent.com/102292476/197102576-4e8e9a5d-294f-4131-919a-99fa2c54c6b0.png)
Context:
- When I inpsect background it show a lot of "Connecting to network [moonbeam] background:41" and doesn't stop.
- I guess the problems are because of reconnecting logic. Please check with the disconnecting case.
- When this occurs we can not work with DApp like Moonbeam, Stellaswap until change the network endpoint.
- After change the network endpoint background still continue show many reconnecting log

**Comment by NamPhamc99** [comment]
Done
