### ISSUE TITLE
Unable to load extension (extension mode) when the user reopens the browser after improperly shutting down

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#703]
**Description the bug**
Unable to load extension (extension mode) when the user reopens the browser after improperly shutting down

**To reproduce the bug**
**_Browser test: Brave_**
_Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.6.6-1664881262236.zip_
Steps:
1. Open the expand extension
2. Switch to the any account
3. Stand on Homepage screen
4. Shut-down device (=> improperly shut down the browser)
5. Turn on the device
6. Reopen the Brave browser then observe the SubWallet extension displayed

Actual: Unable to load extension

![Image](https://user-images.githubusercontent.com/102292476/194451066-689e1f73-435c-4d75-babd-2b8625b5d1b5.png)

Expected: Load extension successfully

**Comment by Sokol142196** [comment]
Do not reproduce this issue in the new UI version.
- When turn on browser -> extension is locked.
