### ISSUE TITLE
Convert extension to Manifest V3

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#707]
Need to change after converting to MV3
- [ ] Persist Confirmation
- [ ] Migrate features
  - [x] Use build-in fetch instead of 3rd lib to make requests
  - [ ] Can't access the DOM from Service Worker
  - [ ] Service worker will terminate when not in use around 5 minutes
  - [ ] Keep the Service-Worker alive by sending messages continuously
- [x] #782
- [ ] Store balances, crowdloans, nft, nft collect, staking, and transaction history data directly into Storage instead of memory to reduce runtime memory usage
- [ ] Subscribe data changes directly from Storage.

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./718-merge-build-0.6.7-0-1665484488010.zip

Please check issues in here: https://docs.google.com/document/d/1aiJLNMFEhxAHBTdsLSHOPIZcWPwIc-8uGe-NghauTTk/edit?usp=sharing

**Comment by saltict** [comment]
Continue in #2205
