### ISSUE TITLE
Support export account via QR

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#709]
Export account via QR and suitable to import to
- Polkadot-js App
- SubWallet Mobile

QR display string follow this structure: `secret:[privateKey]:[publicKey]:[accountName]`

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./733-merge-build-0.6.7-1-1665989733062.zip

- [ ] Improve UX UI for Attach QR-signer account feature

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./733-merge-build-0.6.7-1-1666068461837.zip

Validation passed for cases:
- Export account via QR
- Import account via QR
- Regression test main function with QR Account
![image](https://user-images.githubusercontent.com/102292476/196339078-ff5fbba0-87e5-496f-a6a5-f7ccc7ff7607.png)
