### ISSUE TITLE
An error occurs when a user deletes tokens in case the tokens to be deleted have the same address contract

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#714]
**Description the bug**
An error occurs when a user deletes tokens in case the tokens to be deleted have the same address contract

**To reproduce the bug**
Steps:
1. Open the extension
2. Go to the import token screen then imported token successfully (Ex: x03065E84748a9e4a1AEbef15AC89da1Cdf18B202 (Astar-EVM))
3. Go to the import NFT then import the token with the same contract address in step 2 successfully
4. Go to the Manage EVM tokens screen
5. Select both imported tokens above then click on Delete token button
6. Choose Confirm on popup confirmation
7. Observe the delete tokens result

**Actual:** Still show ERC-20 tokens although selected it to delete

![Image](https://user-images.githubusercontent.com/102292476/194822023-ef4d9f8a-1dda-41b1-be0f-07c0fd087065.gif)

**Expected:** delete the selected tokens is success

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./741-merge-build-0.6.7-1-1666351021527.zip

Validation passed!
![714_Validation](https://user-images.githubusercontent.com/102292476/197315009-8fe061a1-b634-440f-bb98-8563fea63807.gif)

**Comment by NamPhamc99** [comment]
Resolved in PR #741
