### ISSUE TITLE
Refactor Interface Sign Request 

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#735]
- [x] Background:
  - [x] Stake action:
    - [x] Stake
    - [x] UnStake
    - [x] Withdraw
    - [x] ClaimReward
    - [x] CreateCompound
    - [x] CancelCompound
  - [x] Send:
    - [x] Token
    - [x] Nft
    - [x] XCM  
- [x] UI:
  - [x] Stake action:
    - [x] Stake
    - [x] UnStake
    - [x] Withdraw
    - [x] ClaimReward
    - [x] CreateCompound
    - [x] CancelCompound
  - [x] Send:
    - [x] Token
    - [x] Nft
    - [x] XCM

**Comment by sokol142** [comment]
- [ ] Fix bug "There is no related account in the app" when claim reward on Shibuya Testnet/Astar...

![image](https://user-images.githubusercontent.com/102292476/200821688-cacebab0-1f93-4c44-a057-17d5e1422318.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./803-merge-build-0.6.9-1668070494914.zip

Please check: UI on the withdraw screen
![image](https://user-images.githubusercontent.com/102292476/201050918-7f6118c2-a5c0-4758-865c-6035323217be.png)

**Comment by sokol142** [comment]
version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.6.9-1668405983319.zip

Please check issue:

- [ ] Can't send fund with EVM account
![image](https://user-images.githubusercontent.com/102292476/201600861-3ac97059-3e5a-44a1-b434-b9d5229469a0.png)

- [ ] Can't stake/unstake/withdraw with EVM Account
![image](https://user-images.githubusercontent.com/102292476/201601407-058c4a53-430b-49a9-9e57-cf3c4aacd275.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./819-merge-build-0.6.9-1668414491809.zip

Validation passed for cases:
- Send fund (PSP22)
- XCM
- Send NFT (PSP34)
- Sign transaction
- Staking action: stake/stake more/unstake/withdraw/claim/claim reward/compound
