### ISSUE TITLE
Add checkbox "Remember password" for Authorize Transaction with EVM QR-signer account

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#737]
Description the issue:
_- Reproduce the bug in case: **Private key in extension**_
Add checkbox "Remember password" for Authorize Transaction when use **EVM QR-signer** account on cases:
- Send fund
- Send NFT
- Sign Transaction when connected the dApp

Follow this design:
![Image](https://user-images.githubusercontent.com/102292476/196420961-20f94708-1229-42d1-8448-21e67c6727ee.png)

**Comment by saltict** [comment]
Need to improve keyring before update this task because privateKey is not support to remember now

**Comment by sokol142** [comment]
Do not support this feature on the new UI version -> Not fix
