### ISSUE TITLE
Error when use stake action on Turing Staging/ Turing network with QR signer account

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#743]
**Description the bug**
Can't unstake, withdraw, stake, compound on Turing Staging/ Turing network when using a QR signer account

**Actual:** Unstake/ Withdraw/Stake/Compound failed

**Expected:** Unstake/ Withdraw/Stake/Compound  successfully

**Comment by S2kael** [comment]
- Add Turing Network and Turing Staging to list ignore QR-signer

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.6.9-1668405983319.zip

Validation passed for cases:
- Send fund
- Stake
- Unstake
- Withdraw
- Compound
