### ISSUE TITLE
Issue sending Bit.Country NFT and displaying BIT token

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#747]
1. Trying to transfer NFTs using SubWallet, the transaction seems to get stuck and not going through.  Happy to transfer some NFTs to any wallet you send for you to test.
2. Also, $BIT on alpha testnet is not listed/transferrable. As mentioned above, it's not a high priority as it's on testnet. 

![photo_2022-10-24_06-19-26](https://user-images.githubusercontent.com/2582652/197431813-3594747b-8780-45c5-a876-bfc3a6130bef.jpg)

**Comment by NamPhamc99** [comment]
Added BIT token on Alpha Net
Fix bug sending NFT

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./762-merge-build-0.6.7-1667191562050.zip

Validation passed for cases:
- Intergate BIT token
- Sending NFT
