### ISSUE TITLE
Support staking for KMA (Calamari parachain)

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#755]
**Is your feature request related to a problem? Please describe.**
Please support in-app staking for KMA (https://calamari.network/).

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./769-merge-build-0.6.8-1667358968847.zip

- [ ] Please check withdraw action

![image](https://user-images.githubusercontent.com/102292476/199470183-5b8aea2b-967e-4abf-9e28-6cbc6f9d670b.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./769-merge-build-0.6.8-1667451304545.zip

Validation passed for case:
- Stake
- Unstake

Keep track of withdrawal action
