### ISSUE TITLE
Support ReadOnly account

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-Extension#757]
Support ReadOnly Account

- [x] Design
- [x] Function

Metadata:
`{
  isExternal: true,
  isReadOnly: true
}`
Extend from Qr account

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./758-merge-build-0.6.9-1667811673805.zip

Please check issue:

- [ ] Do not display account address after scan successfully

https://user-images.githubusercontent.com/102292476/200985749-72d12b30-3097-48be-b22c-a3be69d384f6.mp4

- [ ] UI bugs
- 
![image](https://user-images.githubusercontent.com/102292476/200988094-594b4c53-c329-472f-a4e0-15d741ae1921.png)
![image](https://user-images.githubusercontent.com/102292476/200988926-f1275e48-6baa-4187-938e-3bcfba3fd949.png)
![image](https://user-images.githubusercontent.com/102292476/200989149-376be5dd-0e41-48ab-aab2-f3a46e41af51.png)
![image](https://user-images.githubusercontent.com/102292476/200990159-33c9e887-adf4-475d-b266-aadbe141d48b.png)
![image](https://user-images.githubusercontent.com/102292476/200990381-9c7c449c-37f1-42b6-bf4a-7c0e50343f6b.png)
![image](https://user-images.githubusercontent.com/102292476/200991295-6f9097fa-bef9-46c3-9a1b-90ac342ec39e.png)
![image](https://user-images.githubusercontent.com/102292476/200991635-8228757d-58fc-4c4e-ae90-4fcbbc01b392.png)

- [ ] Change warning message
- Change to "The account you are using is read-only, you cannot send assets with it"

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./758-merge-build-0.6.9-1668074268116.zip

- [ ] Enable "Attach Readonly Account" button as default
- [ ] The current network icon is overridden when the name is long
![image](https://user-images.githubusercontent.com/102292476/201254784-840e098f-c41e-4ad6-bbce-deec67480f3d.png)

- [ ] Bug happens after change avatar
![image](https://user-images.githubusercontent.com/102292476/201255669-f5b5be49-9054-4ad6-989b-08bc8fadb200.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.6.9-1668405983319.zip

Validation passed.
