### ISSUE TITLE
Resovle conflict and problems after merge newest koni-dev into koni-dev-wr

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#763]
- [x] Review error in token APIs
- [x] Plan to fix these problems in https://github.com/Koniverse/SubWallet-Mobile/issues/179

**Comment by lw-cdm** [comment]
- type:
  - Change:
    - ServiceInfo
    - NftItem
    - NetworkJson
    - TokenInfo
    - ConfirmationDefinitions
    - TransakNetwork
  - Add:
    - ContractType
    - CustomTokenType
  - Rename + change:
    - EvmNftTransactionRequest -> NftTransactionRequest
    - CustomEvmToken -> CustomToken
    - EvmTokenJson -> CustomTokenJson
    - DeleteEvmTokenParams -> DeleteCustomTokenParams
    - ValidateEvmTokenRequest -> ValidateCustomTokenRequest
    - ValidateEvmTokenResponse -> ValidateCustomTokenResponse
  - Remove:
    - SubstrateNftTransactionRequest
- message type:
  - Change:
    - pri(evmNft.getTransaction)
    - pri(substrateNft.getTransaction)
  - Rename + change:
    - pri(evmTokenState.validateEvmToken) -> pri(customTokenState.validateCustomToken)
    - pri(evmTokenState.deleteMany) -> pri(customTokenState.deleteMany)
    - pri(evmTokenState.upsertEvmTokenState) -> pri(customTokenState.upsertCustomTokenState)
    - pri(evmTokenState.getEvmTokenState) -> pri(customTokenState.getCustomTokenState)
    - pri(evmTokenState.getSubscription) -> pri(customTokenState.getSubscription)
  - Add:
    - pri(wasmNft.getTransaction)
- message function:
  - Change: 
    - evmNftGetTransaction
    - substrateNftGetTransaction
  - Rename + change:
    - subscribeEvmToken -> subscribeCustomToken
    - getEvmTokenState -> getCustomTokenState
    - upsertEvmToken -> upsertCustomToken
    - deleteEvmTokens -> deleteCustomTokens
    - validateEvmToken -> validateCustomToken
  - Add:
    - wasmNftGetTransaction
