### ISSUE TITLE
Support sending BIT token for Bit.Country Alpha Net

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#773]
Requested by Bit.Country team

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./774-merge-build-0.6.8-1667278814912.zip

Validation passed!
![773_Validation](https://user-images.githubusercontent.com/102292476/199216823-d97bac57-0a79-4578-b8ae-54e250f68357.gif)

**Comment by hieudd** [comment]
Update token logo 

![Image](https://user-images.githubusercontent.com/2582652/200100450-5969e0a2-b05f-4ec1-ae5d-d089b7769c6e.png)
