### ISSUE TITLE
Update parsing IPFS link for NFT

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#779]
Requested by BitPunkz team. The IPFS link format is /ipfs/QmRNAjTqfP4P5qk28mACsxCow1t4h5Sy2CJrENdWfUcNV7/251.json

**Comment by NamPhamc99** [comment]
Resolved in #795

**Comment by sokol142** [comment]
version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./795-merge-build-0.6.9-1667643361868.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/200300420-a3f7020a-cb0e-48c3-8e97-fea2a5426d78.png)
