### ISSUE TITLE
The wallet can't connect to StellaSwap when turning on both Moonbeam and Ethereum/Binance networks

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#781]
**Description the bug**

- [x] The wallet can't connect to StellaSwap when turning on both Moonbeam and Ethereum/Binance networks

Steps:
1. Open the extension
2. Go to the Network setting screen and turn on Moonbeam, Ethereum network
3. Go to the https://app.stellaswap.com
4. Connect to SubWallet

Actual: Can't connect

https://user-images.githubusercontent.com/102292476/199433170-ad341b0b-556f-49c1-bbc3-9b70ed2bae0a.mp4

Expected: The dApp should post a switch chain request

- [x] StellaSwap do not remember the connection with SubWallet
Pre-condition: Only turn on Moonbeam network

Steps:
1. Go to the https://app.stellaswap.com
2. Connect to SubWallet successfully
3. Reload page

Actual: No connection to SubWallet

https://user-images.githubusercontent.com/102292476/199433569-07e6c661-5307-4a97-9c26-2291d1fb630c.mp4

Expected: the dApp should automatically connect to SubWallet

**Comment by NamPhamc99** [comment]
Waiting response from StellaSwap

**Comment by sokol142** [comment]
Fixed the issue "The wallet can't connect to StellaSwap when turning on both Moonbeam and Ethereum/Binance networks" in the new UI version.
