### ISSUE TITLE
Update price for KBTC

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#785]
https://www.coingecko.com/en/coins/kintsugi-btc

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./786-merge-build-0.6.8-1667457750506.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/199664293-2c8aef73-1c39-4b8f-9b33-7490acf0bc0d.png)
