### ISSUE TITLE
Add support for the Octopus Network ecosystem

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#788]
**Is your feature request related to a problem? Please describe.**
The Octopus Network ecosystem is built on the Substrate framework. Please add support for Octopus Network ecosystem.

- https://oct.network/
- https://awesomenear.com/categories/octopus
- https://mainnet.oct.network/appchains (Running appchains)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./892-merge-build-0.7.3-1670295383560.zip
Integrated networks:
- Mainnet
  - Fusotao
  - Discovol
  - Atocha
  - Myriad
  - Debio 
- Testnet
  - Discovol (Testnet)
  - Barnacle
  - Barnacle EVM

Validation pass for cases:
- Show information
- Send fund with DISC (Discovol Testnet)
