### ISSUE TITLE
Bug automatically redirects to the Ethereum network when requesting permission

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#789]
**Description the bug**
Bug automatically redirects to the Ethereum network when requesting permission

**To reproduce the bug**
_Version test: v0.6.8_

- [x] Connect the dApp on the first time

Steps:
1. Open the SubWallet extension
2. Turn on Ethereum, Moonbeam, Moonbase,.. network
3. Go to the SubConnect-EVM page (https://connect.subwallet.app/#/evm-wallet-info)
4. Connect to wallet successfully
5. Observe Current network on the SubConnect
![789_bug](https://user-images.githubusercontent.com/102292476/202848739-c581ea24-58f2-46cb-8e24-111089811121.gif)

- [x] Request Permission again

Steps:
1. Open the SubWallet extension
2. Turn on Ethereum, Moonbeam, Moonbase,.. network
3. Go to the SubConnect-EVM page (https://connect.subwallet.app/#/evm-wallet-info)
4. Connect to wallet successfully
5. On the SubConnect, click on the switch to Moonbeam/Moonriver...
6. Click on the Request permission and approve request on the wallet
7. Observe Current network

Actual: automatically redirects to the Ethereum network => chain disconnected

![Image](https://user-images.githubusercontent.com/102292476/199877701-66645745-526e-4c7b-b89d-1d26439f05cf.gif)

Expected: Keep the previous connection

**Comment by saltict** [comment]
Error connect to DApp when open EVM ethereum:


![Image](https://user-images.githubusercontent.com/11567273/201824952-60e35bfe-23b3-4285-b38d-129a5083a436.png)


Expect: All chain with http provider should be connect anytime

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./844-merge-build-0.7.2-1669021828575.zip

Validation passed.
