### ISSUE TITLE
Integrate with WalletConnect

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#790]
**Is your feature request related to a problem? Please describe.**
Integrate with WalletConnect to support SubWallet connect with dapps using mobile versions

- https://walletconnect.com/
- https://www.youtube.com/watch?v=vy6NwQouHm4

**Comment by sokol142** [comment]
Same as https://github.com/Koniverse/SubWallet-Extension/issues/1497
