### ISSUE TITLE
Do not show sub-token of the Ethereum, Binance network on the Firefox browser in case update version extension

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#792]
**Description the bug**
Do not show sub-token of the Ethereum, Binance network on the **Firefox browser** in case update version extension

**To reproduce the bug**
Steps:
1. Install v0.6.8 on **Firefox browser**
2. Create/Import account successfully
3. Turn on Ethereum, Binance network
4. Upgrade version to v0.6.9 (koni-dev)
5. Reload extension then obverse list token on the Ethereum & Binance network

Actual: Do not show sub-token of the Ethereum, Binance network

![Image](https://user-images.githubusercontent.com/102292476/199945959-9fd35a0d-9cd2-47ee-bd7f-a1619c5d60dc.png)

![Image](https://user-images.githubusercontent.com/102292476/199946033-bd175691-d8ca-496b-881a-e9f37c300886.png)

**Comment by NamPhamc99** [comment]
Issue cannot be reproduced in v0.6.9
