### ISSUE TITLE
Bug parsing IPFS link

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#794]
**Describe the bug**
Bug parsing IPFS link starts with ipfs://

**Comment by sokol142** [comment]
version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./795-merge-build-0.6.9-1667643361868.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/200300420-a3f7020a-cb0e-48c3-8e97-fea2a5426d78.png)
