### ISSUE TITLE
Show nomination pool stake balance

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#796]
**Is your feature request related to a problem? Please describe.**
Show nomination pool stake balance:

1. Bonding and stake to Pool in https://staking.polkadot.network/#/pools
2. Show Bonded Funds in Staking Tab

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./797-merge-build-0.6.9-1667972256480.zip

Please check issue:

- [ ] Still display staking record on the Staking tab after withdraw all successfully

https://user-images.githubusercontent.com/102292476/200791091-f36c5e86-e89b-4eef-91d7-0feeadd07448.mp4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.6.9-1668082308815.zip

Validation passed
