### ISSUE TITLE
Update message when having no account to connect to dApp

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#798]
**Description the issue**
Update message when having no account to connect to dApp
![Image](https://user-images.githubusercontent.com/102292476/200231405-b33560dc-9ce4-4daa-a331-85b3cef5719b.png)

Expected: Change to message
- "This dApp requires a Substrate account. Please create, import, or restore a Substrate account and retry"
- "This dApp requires a EVM account. Please create, import, or restore a EVM account and retry"

**Comment by hieudd** [comment]
Need a link so that users can go to the Create new account screen

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.6.9-1668161717144.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/201327565-5674c4ef-049b-4c30-8709-3aaa668359cb.png)
![image](https://user-images.githubusercontent.com/102292476/201327622-54cf5665-fc35-4443-8b98-7e9ff853aed5.png)
