### ISSUE TITLE
Error withdrawing stake with slashing spans

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#809]
**Describe the bug**
An error occurred when user had slashing spans and tried to withdraw the staked amount.

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./810-merge-build-0.6.9-1668139216552.zip

Please check bug: Can't withdraw WND


![Image](https://user-images.githubusercontent.com/102292476/201288056-a5bcefe1-32e5-40bd-beab-3a3b75ab6ce6.png)
