### ISSUE TITLE
Add unclaimed reward info/Support reward withdrawing for nomination pool

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#812]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/44641118/201286219-b4c919bf-6299-40d7-a500-cc39ce7f7fdb.png)

- [x] Get unclaimed reward info
- [x] Support reward claiming

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.6.9-1668497789071.zip

Validation passed for cases:
- Show unclaimed balance
- Claimed balance
- Regression test for staking feature
