### ISSUE TITLE
Improve UI when users access phishing websites (listed on Polkadot JS Phishing list)

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#814]
**Is your feature request related to a problem? Please describe.**

When a user accesses a phishing website that is listed on the Polkadot JS Phishing list (https://polkadot.js.org/phishing/#), it automatically goes to the extension on a new window. This can be confusing for users. 

We should improve the UI to make it better for users to understand. See the example of MetaMask in the picture below

<img width="1257" alt="Screen Shot 2022-11-11 at 14 49 39" src="https://user-images.githubusercontent.com/102496727/201292176-85b9674c-e7b8-442c-9ef9-d9ced1b46c98.png">

**Comment by saltict** [comment]
Finish with new UI
