### ISSUE TITLE
Update BIT token logo

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#816]
Update token logo 

![Image](https://user-images.githubusercontent.com/2582652/200100450-5969e0a2-b05f-4ec1-ae5d-d089b7769c6e.png)

_Originally posted by @hieudd in https://github.com/Koniverse/SubWallet-Extension/issues/773#issuecomment-1304398887_

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./818-merge-build-0.6.9-1668412177390.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/201638859-62f9716e-e21e-49b9-8c49-a5fac4a61789.png)
