### ISSUE TITLE
Update history feature

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#820]
Replace transaction history sources with:
- https://squid.subsquid.io/multi-chain-tx/v/v1/graphql

**Comment by saltict** [comment]
Wait #868

**Comment by NamPhamc99** [comment]
**New SubSquid endpoints**

https://squid.subsquid.io/moonbeam-explorer/graphql
https://squid.subsquid.io/moonriver-explorer/graphql
https://squid.subsquid.io/astar-explorer/graphql
https://squid.subsquid.io/polkadot-explorer/graphql
https://squid.subsquid.io/kusama-explorer/graphql

To be updated...

**Comment by anhntk54** [comment]
+ With the above endpoints:
  - The data of polkadot and kusama have been taken
  - Astar no data yet
  - Moonbeam and moonriver  not enough data, some addresses found transactions
  - The returned data is missing the fee and eventIdx fields

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./923-merge-build-0.7.4-1670991709152.zip

Please check issues:

- [ ] Do not show the transaction's fee
![image](https://user-images.githubusercontent.com/102292476/207555144-2f09347f-30a0-4cc0-9387-4813e59c0adf.png)

- [ ] Show incorrect some transaction
![image](https://user-images.githubusercontent.com/102292476/207555169-54fe97d1-7388-4039-8337-4a0d4ac50a73.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./930-merge-build-0.7.5-1671274596162.zip

Validation passed for cases:
- Showing transaction for some chain: Polkadot, Kusama, Rococo)

Continuing follow-up.
