### ISSUE TITLE
Minor bugs on staking

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#824]
**Describe the bug**
- [x] Not showing staking for testnets (A0, westend,..)
- [x] Reduce the interval of fetching unclaimed reward for nomination pool

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./826-merge-build-0.7.2-0-1668575762981.zip

Validation passed.
