### ISSUE TITLE
Add new feature: Social Recovery 

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#832]
**Is your feature request related to a problem? Please describe.**
- Social recovery: https://www.parity.io/blog/social-recovery-on-substrate/
- Social recovery on Polkadot JS Plus: https://medium.com/@polkagate/social-recovery-by-polkadot-js-plus-ca422d871850

**Comment by hieudd** [comment]
https://github.com/Koniverse/SubWallet-Extension/issues/1210
