### ISSUE TITLE
Add support for $ZSTAKE on Aleph Zero

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#833]
**Is your feature request related to a problem? Please describe.**

ZStake is a reward platform with Staking as its primary feature and P2P and P2E casino games.
- Docs: https://zstake.gitbook.io/documentation/
- Website: https://zstake.finance/

ZStake has integrated SubWallet into their testnet dapp: https://zstake.finance/rewards/

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./836-merge-build-0.7.2-1669024072791.zip

- [ ] Show incorrect transaction history
- [ ] Insufficient amount received

**Comment by sokol142** [comment]
Temporary remove ZSTAKE
