### ISSUE TITLE
Bug withdrawing GLMR stake

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#837]
**Describe the bug**
https://discord.com/channels/925999372238483486/931014898857697310/1043070154545840229

**Possible reasons**
Invalid parameters have been passed into the function
Bug in the sign and send logic

**Screenshots**
![image](https://user-images.githubusercontent.com/44641118/202689685-edbd2c07-73df-40ca-8680-1101e32daec2.png)

**Comment by Sokol142196** [comment]
This problem on old version.
On the new version, there is no feedback on this and it is normal to re-test on Testnet
=> Follow-up on new version and closed this issue
