### ISSUE TITLE
Update the new Settings screen

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#85]
**Is your feature request related to a problem? Please describe.**
Update the new Settings screen
**Design:** 

- https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=2046%3A11030&scaling=min-zoom&page-id=4%3A14
- https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=2046%3A11849&scaling=min-zoom&page-id=4%3A14

**Icon:** 

- https://drive.google.com/drive/u/1/folders/1opTwOvq8VI5XmszlanVuKJ4KPNtM0FpW

**Comment by sokol142** [comment]
**Describe the bug**
Incorrect navigation when click on Back button in the Manage Website Access screen
Version test: v0.2.10 (31/03/2022)

**To Reproduce**
Steps:
1. Open wallet and Go to Settings screen
2. Click on "Manage Website Access" button
3. On Manage Website Access screen, click on Back button

**Actual**: Back to Homepage screen
**Expect**: Back to Settings screen
![bug_setting_navigation](https://user-images.githubusercontent.com/102292476/161477605-30005f67-2f5d-49b4-aa76-91cf61015e1b.gif)

**Comment by hieudd** [comment]
remove unused menus and add Allow QR Camera Access

![Screen Shot 2022-04-04 at 5 31 50 PM](https://user-images.githubusercontent.com/2582652/161526317-6fc54c48-d483-41dc-8163-beef43b28d64.png)
