### ISSUE TITLE
Integrate Watr Protocol and Token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-Extension#854]
**Is your feature request related to a problem? Please describe.**
Watr is a blockchain protocol and open dApp ecosystem for transparency in real-world assets (and a parachain on Polkadot)
They're launching the mainnet + token on January 2023.

- [x] Integrate Watr Testnet

Documents: https://docs.watr.org/
RCP and connection info: https://docs.watr.org/builders/ethereum-contracts/add-watr-to-metamask-wallet

- #888
Updating...

Please add support for this. Thank you <3

**Comment by sokol142** [comment]
Please add EVM contract for this protocol

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./881-merge-build-0.7.3-1670040129437.zip

Validation passed:

https://user-images.githubusercontent.com/102292476/205425282-dc994b12-b85b-46fe-b4f1-5d3b775a72be.mp4
