### ISSUE TITLE
Support claim staking reward for Amplitude

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#867]
**Description the task**
Support claim staking reward for Amplitude

**Comment by NamPhamc99** [comment]
- Fixed a bug withdrawing Amplitude stake
- Adjusted cron interval for Amplitude staking reward

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./876-merge-build-0.7.2-1669710822785.zip

Validation passed.
- Claim: 
![867_Validation](https://user-images.githubusercontent.com/102292476/204494953-265e3313-dded-4ba5-9f6f-fb73cf096efc.gif)
- Check more: Withdraw feature

https://user-images.githubusercontent.com/102292476/204495304-85a100f3-a1b6-44dd-860f-d0fd6f05405e.mp4
