### ISSUE TITLE
Summarize the list of data to get with Subsquid

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#868]

**Comment by NamPhamc99** [comment]
## Chains to be supported by SubSquid (sorted by priority descending)

1. Westend
2. Shiden
3. Pioneer
4. Acala/Karura
5. Statemint/Statemine
6. Moonriver
7. Bifrost
8. Aleph Zero
9. Khala
10. Parallel Finance
11. Zeitgeist
12. Clover
13. Calamari
14. Amplitude

## Data addition request for SubSquid

- XCM transfer history
- NFT owned by account (RMRK, Unique NFT, Statemine, ERC-721, PSP-34, Bit.Country)
- Support staking reward for nomination pool (total reward, latest reward,…)
- Claimable staking rewards for some chains (Astar, Kilt, Amplitude,…)
- NFT transfer history (RMRK, Unique NFT, Statemine, ERC-721, PSP-34, Bit.Country)
- Crowdloan status and contribution by account
- Account’s basic information: main token balance, nounce
