### ISSUE TITLE
Integrate xx.network - a L1 Substrate-based network

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#873]
**Is your feature request related to a problem? Please describe.**

Please add support for xx.network:
**- Website:** https://xx.network/
**- GitHub:** https://github.com/xx-labs?tab=repositories
**- Substrate pallet external security audit:** [https://github.com/xx-labs/xxchain/blob/master/doc/ChainSafe xxchain Code Review.pdf](https://github.com/xx-labs/xxchain/blob/master/doc/ChainSafe%20xxchain%20Code%20Review.pdf)
**- RPC:** 
1. wss://rpc.xx.network
2. wss://xxnetwork-rpc.dwellir.com

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./882-merge-build-0.7.3-1669979649848.zip

Validation passed.

https://user-images.githubusercontent.com/102292476/205419744-74f2690b-d2ce-4101-abc6-f4353ccb2578.mp4
