### ISSUE TITLE
Add Subspace Gemini 3 Testnet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#875]
**Is your feature request related to a problem? Please describe.**

**Gemini 3 Testnet:**

- wss://eu-0.gemini-3a.subspace.network
- wss://eu-1.gemini-3a.subspace.network
- wss://eu-2.gemini-3a.subspace.network

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./883-merge-build-0.7.3-1670040459697.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/205425813-d3b7f7b9-52af-4ed7-8bb7-d533ddb575aa.png)
![image](https://user-images.githubusercontent.com/102292476/205425873-6dcfd427-6e4d-460b-9811-110638d6f3fb.png)
