### ISSUE TITLE
Multiple click on toast show function cause race condition and it's flicker until all setTimeout cleared.

### ISSUE THREAD

**Issue by connect2amitu** [Koniverse/SubWallet-Extension#879]
**Describe the bug**
Toast flicker effect due to multiple clicks and show toast function calls

**To Reproduce**
1. Go to any section which show toast (eg. Copy Icons)
2. Click on the Icon multiple times
3. wait for some time and click on icon it will not show toast as per expectation. it start flicker 

**Expected behavior**
Toast setTimeout should be clear if any new toast function called, should be reset and show new toast with new timeout Id.

**Screenshots**
![TdQvbNLAin](https://user-images.githubusercontent.com/36689910/205114389-b4c50e6f-1519-4748-9c0a-7abf4904757f.gif)

**Desktop (please complete the following information):**
 - OS: Window, Ubuntu, Mac
 - Browser [e.g. chrome, Brave]

**Comment by NamPhamc99** [comment]
Hello @connect2amitu, we have verified this issue. 

Thank you for raising this, always nice to receive feedbacks from users, especially those with technical background.

Any suggestion or feedback is welcomed. Stay tuned for more exciting new
