### ISSUE TITLE
Update RMRK NFT endpoints

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#893]
Update RMRK NFT endpoints as requested by the RMRK team

https://singular.rmrk-api.xyz/api/account/{address}
https://singular.rmrk-api.xyz/api/account-rmrk1/{address}

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./900-merge-build-0.7.4-1670901052964.zip

Validation passed.
