### ISSUE TITLE
Update balance logic for Equilibrium

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#902]
Update new get Balance logic for Equilibrium:
- Balances in Equilibrium are now stored in the systems pallet in the data array of balances, where the balance is a tuple: [assetId; balance], balance is enum (Positive or Negative), there are now only master accounts in the system so all balances should be positive. Balances are always sorted by assetid. 
  ```javascript
  {
    nonce: 0
    consumers: 0
    providers: 2
    sufficients: 0
    data: [
      [
        25,969
        {
          Positive: 50,000,000,000
        }
      ]
    ]
  }
  ```
- AsssetID can get from `eqAssets.assets()`
  ```javascript
  [
    {
      id: 25,969
      lot: 1,000,000,000
      priceStep: 1,000
      makerFee: 500,000
      takerFee: 1,000,000
      assetXcmData: None
      debtWeight: 0
      lendingDebtWeight: 100.00%
      buyoutPriority: 18,446,744,073,709,551,614
      assetType: Native
      isDexEnabled: false
      collateralDiscount: 400,000,000
    }
  ]
  ```

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./962-merge-build-0.7.6-1672030034016.zip

Please check issues:

- [ ] Add the URL explorer for this chain
- [ ] Do not show Transferable on the Send fund screen
![image](https://user-images.githubusercontent.com/102292476/209541107-f0ce00ab-9444-4825-b43b-f39f6e760cdc.png)
- [ ] Re-test send fund feature

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./962-merge-build-0.7.6-1672055010498.zip

@Quangdm-cdm please check

- [ ] An error when send fund
![image](https://user-images.githubusercontent.com/102292476/209605862-16b3008c-f393-48b3-a626-0e1ae8dd4e4c.png)

- [ ] Do not update URL explorer in case upgrade version

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./962-merge-build-0.7.6-1672134950224.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/209649974-f152b814-1140-471a-a72a-8012b7c3261d.png)

Notes: Not support send fund
