### ISSUE TITLE
Custom Access screen improvements

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-Extension#91]
**Is your feature request related to a problem? Please describe.**
Custom Access screen improvements

https://www.figma.com/proto/4cYWHubrmdayui6VybR3BA/SubWallet-font-2?node-id=2046%3A10754&scaling=min-zoom&page-id=4%3A14

**Comment by hieudd** [comment]
Pls fix 2 problems:

- Don't public EVM acc for Substrate DApp
- Add cursor = pointer in grant access screen

**Comment by hieudd** [comment]
- Scroll bar should be used in this area
- Try to migrate the user's previous access data
![Screen Shot 2022-04-06 at 11 10 53 PM](https://user-images.githubusercontent.com/2582652/162020167-87c8bf09-8c68-40be-83d8-08f8e95223f8.png)

**Comment by saltict** [comment]
@Quangdm-cdm Please sure that you haved migrate all allow list from old version

**Comment by sokol142** [comment]
@Quangdm-cdm Other bugs:
1. Account List is empty even though Connect All in case the previous connect, user choose Cancel
2. Derivation Account not shown in the List Account in the Connect screen
3. Quantity of the account is incorrect when wallet have EVM account

![image](https://user-images.githubusercontent.com/102292476/162124146-47a05618-0975-4a18-85ce-73634e37fea0.png)
![91_issue](https://user-images.githubusercontent.com/102292476/162124371-2eb71299-c069-4356-9a89-f2d659ae99b3.gif)

**Comment by sokol142** [comment]
fix some bug:
1. Quatity of the account incorrect when Forget Account
![image](https://user-images.githubusercontent.com/102292476/162402127-63591daa-bf1d-4bbf-9c10-0ace4731f81d.png)

2. Can't connect All Account in case add account after connected the Dapp

**Comment by sokol142** [comment]
@Quangdm-cdm 
1. The language field in General Setting screen is not shows value in the first visit
To reproduce:
![issue_91](https://user-images.githubusercontent.com/102292476/162907826-a9bd5ef7-ebdb-458b-8493-281da80044fc.gif)
2. The popup confirm Forget Site should not show when no website request yet.
![image](https://user-images.githubusercontent.com/102292476/162909087-8d194b84-cd65-4eed-85a7-d750b75eb5bc.png)
