### ISSUE TITLE
Add support for Astar/Shiden Light Client

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-Extension#911]
**Is your feature request related to a problem? Please describe.**
Astar has recently supported Light Client. Please see their announcement here: https://medium.com/astar-network/decentralising-astar-with-light-clients-335bb9017546

**Describe the solution you'd like**
Please add support for Astar Light Client in the SubWallet extension.

Thank you <3

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./946-merge-build-0.7.6-1671547340148.zip

Validation passed in cases:
- Connect to light client
- Show the balance
- Send fund

Pending case xcm transfer, wait #945
