### ISSUE TITLE
Turn off background in case extension reloaded and popup never opened

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#912]
The sleep mechanism is missing some cases. This leads to extension background to run indefinitely without stopping

- [x] Turn off background in case browser starts and user does not turn on SubWallet popup
- [x] Turn off background in case extension reload (due to an update,..) and user does not turn on SubWallet popup

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./koni-dev-build-0.7.4-1670987553402.zip

Validation passed.
