### ISSUE TITLE
Add incrementDelegatorRewards call to Amplitude reward claiming

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#914]
The `incrementDelegatorRewards` needs to be called before `claimRewards`

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./915-merge-build-0.7.4-1670899300702.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/207283349-5926d478-c57f-4f50-8b72-ab56420ea00c.png)
