### ISSUE TITLE
Integrate PhalaWorld Shells Collection

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#918]
**Description the task**
Integrate PhalaWorld Shells Collection: https://phala.world/collections/1/1331

**Comment by NamPhamc99** [comment]
To get all existing collections: `api.query.rmrkCore.collections.entries`
To get all NFTs owned by an address in a collection: `api.query.uniques.account.entries(accountAddress, collectionId) `
To get metadata for NFT: `api.query.rmrkCore.nfts.entries(collectionId, nftId)`
To get custom properties for NFT: `api.query.rmrkCore.properties.entries(collectionId, nftId)`


Phala uses Arweave to store NFT metadata, use this gateway: https://arweave.net/

**Comment by Sokol142196** [comment]
Outdate => Closed issue
