### ISSUE TITLE
Support EVM Account for Astar Network

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#92]
## Overview 
Astar use 2 account types:
- H256 for Substrate world: ASTR balance, Staking....
- H160 for Ethereum world: NFTs...

To make manager account, assets clearly, we will separte Astar chain info Astar and Astar (EVM)
- Astar support H256 and show substrate assets.
- Astar (EVM) support NFTs and other EVM tokens.

### Change in code
- [x] Make a copy of Astar in `packages/extension-koni-base/src/api/endpoints.ts` with new name Astar (EVM) key 'astarEvm' and prop `isEthereum` = `true`.
- [x] Add `astar-evm` into `ethereumChains` in file `packages/extension-koni-base/src/api/dotsama/api-helper/index.ts`

### Test again these features
- [x] Get balance
- [x] Get staking
- [x] Get crowdloan
- [x] Get NFT
- [x] Show/hide network depend on address type
- [x] Disable show balance to Astar - EVM because it don't support show balance of EVM account.

**Comment by hieudd** [comment]
@saltict: Astar's EVM account balance is not displayed yet

![2022-04-07 08 38 17](https://user-images.githubusercontent.com/2582652/162103005-af6bb7cc-36a0-4009-a692-5255e298da90.jpg)

![photo_2022-04-07 08 38 34](https://user-images.githubusercontent.com/2582652/162103044-a55f592d-b326-49d9-80af-3bd37834b741.jpeg)
