### ISSUE TITLE
Migrate Custom Network feature

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#926]
- [x] Support network customizing only for pure EVM or Substrate networks (mixed networks are not supported)
- [x] Migrate logic into ChainService

**Comment by sokol142** [comment]
Add support:

- [ ] Fully custom chains
- [ ] Local substrate node (re-design)

**Comment by sokol142** [comment]
Please check cases:

- [ ] Add network: Substrate network/ EVM network/ support both Substrate & EVM
- [ ] Delete network
- [ ] Config network:
     - [ ] Install:
          - [ ] Change provider
          - [ ] Add provider
          - [ ] Edit Name
     - [ ] Upgrade version:
          - [ ] Custom network --> Custom network (_Expected: Keep the user's settings in the previous version)_
          - [ ] Pre-defined network --> Pre-defined network (Expected: 
          - [ ] Custom network --> Pre-defined network

**Comment by NamPhamc99** [comment]
- [ ] Check chain usage with a network running crowdloan but not yet live
