### ISSUE TITLE
Integrate $TFA token into SubWallet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#928]
**Is your feature request related to a problem? Please describe.**
TFA DAO has launched $TFA and they have plans to use $TFA with future games (https://twitter.com/TFAlphaDao/status/1602355633076015111)

Please add $TFA:
- Smart contract address: 0xE065ffaf3f7dED69BB5cf5FDd1Fd1dDA2EEe8493
- https://moonbeam.moonscan.io/token/0xe065ffaf3f7ded69bb5cf5fdd1fd1dda2eee8493#balances

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./930-merge-build-0.7.5-1671177607689.zip

Validation passed for case:
- Send tokens
- Show balance
Please update logo for TFA tokens: https://twitter.com/TFAlphaDao/photo

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./930-merge-build-0.7.5-1671274596162.zip

Validation passed!
