### ISSUE TITLE
Add support for $AZERO nomination pool staking (Aleph Zero)

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-Extension#933]
**Is your feature request related to a problem? Please describe.**
Aleph has now launched their mainnet and nomination pool staking for $AZERO. Please add support for it
- https://alephzero.org/blog/faq-aleph-zero-nomination-pools/

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./935-merge-build-0.7.5-1671192483202.zip

Validation passed!
![image](https://user-images.githubusercontent.com/102292476/208226292-56cc03d0-842d-4790-bdc5-72a77c04351e.png)
