### ISSUE TITLE
Bump deps

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#944]
Update extension dependencies version

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./954-merge-build-0.7.6-1671709669021.zip

Validation passed for cases:
- Show balance
- Send fund
- XCM
- Send NFT
- Staking: Stake, Unstake, Withdraw, Claim, Compound
- Connect dApp
- Import token
- Sign message/sign transaction
