### ISSUE TITLE
UI Bug when zoom in/ zoom out browser

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-Extension#947]
Description the bug
UI Bug when zooming150% in the browser

- All list screen
![Image](https://user-images.githubusercontent.com/117999489/208651636-2760254b-d8d1-4e7f-8634-dce85817cc5e.png)
- Buy (Network Selection, Service Selection )
- Export to devices
- [Receive assets
- Send NFT
- Staking
     - Select a network
     - Select a validator
     - Staked result
     - Unstake
     - Compound
     - Claim reward
     - Withdraw

**Comment by Sokol142196** [comment]
Resolve the issue on the v1.0.2
