### ISSUE TITLE
Upgrade UI - Update Redux

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#976]
- [ ] Setting
  - [ ] Theme
  - [ ] Language
  - [ ] Notification Type (Remove, default is popup)
- [ ] Confirmations (Merge all confirmations into one store)
- [ ] Account
  - [ ] accounts
  - [ ] currentAccount
  - [ ] currentNetwork
- [ ] Network
- [ ] Token
- [ ] NFT
- [ ] Crowdloan
- [ ] Staking
  - [ ] Validator List
  - [ ] Reward
  - [ ] Compound
  - [ ] Unlocking
- [ ] Transactions
  - [ ] History
  - [ ] PendingQueue

**Comment by NamPhamc99** [comment]
Done
