### ISSUE TITLE
Support Shiden base PSP-34 contract

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-Extension#985]
Requested by Astar team

Resources:
https://github.com/Maar-io/hashlips-ui-for-ink
https://github.com/swanky-dapps/nft

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./987-merge-build-0.7.8-1674875788329.zip
Validation passed with contract: b8QeEr72aJQKfaXcEDGwB5iwqGuF1b9oysHtj3nwMsdmgHa (Shiden)
![image](https://user-images.githubusercontent.com/102292476/215372768-b6a4557e-d2d1-4aa9-8401-15b8e9669702.png)

Re-check this issue with other contract: 
- 5HrE1aYXt4k1TvBZYkL6B1BBcFp9tCWyMdCZqp2cXDNub5zW- Praying Mantis Predators (Aleph Zero Testnet)
- 5DUcAgGbGhPxhv9fbCkEBrYRRNCttmLtBhc1asNNsy2Gc5Af - BitPunkz (Aleph Zero Testnet)
- 5HjeqQiddWpU8myfnThA617vGGY6z1DDPBmwvXotwsqhLb8P - Azero Punks (Aleph Zero Testnet)
