### ISSUE TITLE
Upgrade UI - Screen Welcome

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-Extension#994]
Design: https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=1172%3A85430&t=ENjVxCJpOxJvG5Co-4

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-build-0.8.1-1678525608021.zip
Please check:

- [ ] Add the link for "this instruction" on the Import by QR code screen
![image](https://user-images.githubusercontent.com/102292476/224679808-f9292ec4-f62f-4728-8244-2db0597b81a4.png)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./1087-merge-build-0.8.1-1678951713211.zip

Validation passed.
![image](https://user-images.githubusercontent.com/102292476/225556883-f2bb2129-c595-4918-9b41-81ab609a74e5.png)
