### ISSUE TITLE
Update the staking validator's expected return for relaychain

### ISSUE THREAD

**Issue by sokol142** [Koniverse/SubWallet-Extension#997]
**Description the task**
Update the staking validator's expected return for relaychain

**Actual**: Show incorrect expected return of the validator

![Image](https://user-images.githubusercontent.com/102292476/215934074-b0d59c38-7ac8-4acc-93e9-434960e82141.png)

**Expected**: Show correct expected return

**Comment by NamPhamc99** [comment]
![Screenshot 2023-02-01 122738](https://user-images.githubusercontent.com/44641118/215977707-72ffbcd1-2cb1-4a5c-98f7-3b3d294cac04.png)

Caused by a change in the formula (commit by A0 team)

**Comment by sokol142** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./998-merge-build-0.7.9-1675311244653.zip

Validation pass for chain:
- Aleph Zero
- Polkadot
- Kusame
- Ternoa
- Polkadex
![image](https://user-images.githubusercontent.com/102292476/216865376-82a653dd-4ca0-40d2-870e-20ade5207a2c.png)

![image](https://user-images.githubusercontent.com/102292476/216865459-fc7e7de1-6f47-4c9c-99b0-377ef2eda44c.png)

![image](https://user-images.githubusercontent.com/102292476/216865530-619cec78-b902-48ee-9272-e6693fca066a.png)

![image](https://user-images.githubusercontent.com/102292476/216864933-1ec59ec7-f3a8-452c-a397-64c8aa70ac36.png)
![image](https://user-images.githubusercontent.com/102292476/216865122-7f96732e-01e8-4337-9de9-e24bbcd3570f.png)
